### PR TITLE
fix(eslint-plugin): [no-unnecessary-condition] downgrade fix to suggestion

### LINKED ISSUE #4513: [no-unnecessary-condition] False error on uninitialized variable
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

[Playground](https://typescript-eslint.io/play#ts=5.3.2&fileType=.tsx&code=DYUwLgBAZg9jBcEDOYBOBLAdgcwNwCh8BjGTFZcAMTggF4IAKASkQDcZ0ATOgPggG98ECOiiNYMAPwA6UDjAALCAB4IARiYChw6DXoByCfoLCAvvlMEgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

```JSON
{
  "rules": {
      "@typescript-eslint/no-unnecessary-condition": [
      "error"
    ],
  }
}
```

```TS
let foo: string;

const setFoo = (): void => {
  if (foo?.length < 1) {
    foo = 'foo';
  }
};

```

tsconfig
```
{
  "compilerOptions": {
    "outDir": "./lib",
    "module": "commonjs",
    "target": "es2015",
    "lib": ["es6", "es7"],
    "sourceMap": true,
    "allowJs": false,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strict": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "noErrorTruncation": true,
    "pretty": true,
    "declaration": true
  },
  "include": [
    "src/**/*"
  ]
}
```

**Expected Result**

Existence check on a possibly uninitialized variable should not trigger no-unnecessary-condition

For sure, the type might be extended to `let foo = string | undefined;` as workaround, but that actually looks a bit uncommon for a let definition, where not initializing might be intended.

**Actual Result**
`Unnecessary optional chain on a non-nullish value  @typescript-eslint/no-unnecessary-condition`

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.10.0` |
| `@typescript-eslint/parser`        | `5.10.0` |
| `TypeScript`                       | `4.5.5` |
| `ESLint`                           | `8.7.0` |
| `ts-node`                             | `10.4.0` |

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #4513 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 1]
```diff
@@ -184,6 +185,7 @@ export default createRule<Options, MessageId>({
         'Unnecessary conditional, the types have no overlap.',
       noStrictNullCheck:
         'This rule requires the `strictNullChecks` compiler option to be turned on to function correctly.',
+      suggestRemoveOptionalChain: 'Replace `?.` with `.`',
```
Comment (ronami) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:188]: [Nit]: I think the message is not always accurate as the suggestion fixer can sometimes remove `?.` and not replace it with `.` ([deploy preview playground link](https://deploy-preview-11081--typescript-eslint.netlify.app/play/#ts=5.8.2&fileType=.tsx&code=CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoBKALngDcctgBuAKAYHpmksAPEYeLVDHPAAGiQqSENROAPwA6UoxZtEnbr36ChAbQCMAGngAmAwGYAuloAMZiboPH45uVbOMgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)):

```ts
declare function foo(): void;

// fixed into `foo()`
foo?.();

// fixed into `[1, 2, 3][0]`
[1, 2, 3]?.[0];
```

I couldn't think of a better alternative though (and I think the existing message explains the suggestion fixer pretty well).

**Review by ronami — DISMISSED** [review]
🎉

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts (hunk 1 above)
Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:188]: Yeah, this crossed my mind while working on it... I agree with you your suggestion!

```suggestion
      suggestRemoveOptionalChain: 'Remove unnecessary optional chain',
```

**Review by ronami — APPROVED** [review]

**Review by JoshuaKGoldberg — APPROVED** [review]
