### PR TITLE
fix(eslint-plugin): [no-unsafe-call] differentiate a types-error any from a true any

### LINKED ISSUE #9216: Bug: [no-unsafe-call] Differentiate a types-error any from a "true" any
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.ts&code=DYUwLgBAbghsCuIBcEByB7MBpAdug7jgNwBQJsCIAFAJRFA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolpk%2B8eOiiJo0DtEjgwAXxBKgA&tsconfig=&tokens=false

### Repro Code

```TypeScript
let value: NotKnown;

value();
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-unsafe-call": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

When the called value is of an "error" type, there should be some indication that it's not the same as an `any`. It's confusing for developers to see both "error" `any`s and "true" `any`s described with the same messaging.

### Actual Result

```plaintext
Unsafe call of an `any` typed value. 3:1 - 3:6
```

### Additional Info

Split out of #8304 <- #8231.

💖

### PR DESCRIPTION
**Pull request by Vinccool96**
## PR Checklist

- [X] Addresses an existing open issue: fixes #9216 
- [X] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [X] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unsafe-call.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export default createRule<[], MessageIds>({
   meta: {
     type: 'problem',
     docs: {
-      description: 'Disallow calling a value with type `any`',
+      description: 'Disallow calling a value with type {{type}}',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-unsafe-call.ts:23]: To maintain consistency with #8304 and https://github.com/typescript-eslint/typescript-eslint/pull/9291#discussion_r1632047535, let's go with:

```suggestion
      description: 'Disallow calling a value with an {{type}} value.',
```

...where the `type` is either <code>'\`error\` type'</code> or <code>'\`any\`'</code>.

File: packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts:1]: [Testing] As with #8304, please include the `data` in existing tests. If there's a bug in the new `isErrorType ? ... : ...` logic, the tests should be able to catch it.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Nice clean & readable code - a good start! Requesting changes to fit in a bit with the other PRs, and some testing please. Thanks! ✨

File: packages/eslint-plugin/src/rules/no-unsafe-call.ts [hunk 2]
```diff
@@ -64,9 +64,15 @@ export default createRule<[], MessageIds>({
...
           }
         }
+
+        const isErrorType = tsutils.isIntrinsicErrorType(type);
+
         context.report({
           node: reportingNode,
           messageId: messageId,
+          data: {
+            type: isErrorType ? '`error`' : '`any`',
```
Comment (StyleShit) [inline packages/eslint-plugin/src/rules/no-unsafe-call.ts:74]: not sure whether "`error`" is the best term in this case
a user might think it refers to the `Error` type in JS, no?

maybe it could be something like "disallow calling unresolved types"?
(probably not the best wording, but something along these lines)

WDYT?

File: packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts [hunk 3]
```diff
@@ -163,5 +233,22 @@ const methods = {
...
+value();
+      `,
+      errors: [
+        {
+          messageId: 'unsafeCall',
+          line: 3,
+          column: 1,
+          endColumn: 6,
+          data: {
+            type: '`error` type',
```
Comment (StyleShit) [inline packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts:248]: shouldn't be just "error"?

```suggestion
            type: '`error`',
```

Comment (Vinccool96) [reply packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts:248]: Looks like I forgot to change it.

File: packages/eslint-plugin/docs/rules/no-unsafe-call.mdx [hunk 4]
```diff
@@ -1,5 +1,5 @@
 ---
-description: 'Disallow calling a value with type `any`.'
+description: 'Disallow calling a value with type an {{type}} value.'
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/docs/rules/no-unsafe-call.mdx:2]: 🤔 find-and-replace mishap? 😄

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Other than reverting the `description` changes, this looks great - thanks for updating the tests! 🧹

File: packages/eslint-plugin/docs/rules/no-unsafe-call.mdx (hunk 4 above)
Comment (StyleShit) [reply packages/eslint-plugin/docs/rules/no-unsafe-call.mdx:2]: Sorry for hijacking, but what's your opinion about [this](https://github.com/typescript-eslint/typescript-eslint/pull/9304#discussion_r1632171888) BTW?

File: packages/eslint-plugin/src/rules/no-unsafe-call.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-unsafe-call.ts]: Good question. I'd say since #8304 and other PRs are landing in this area with the _"error typed"_ phrasing, let's treat that as a separate followup.

File: packages/eslint-plugin/docs/rules/no-unsafe-call.mdx (hunk 4 above)
Comment (Vinccool96) [reply packages/eslint-plugin/docs/rules/no-unsafe-call.mdx:2]: It makes the test fail when I revert it. Do I add the file to `rulesWithComplexOptionHeadings`?

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/docs/rules/no-unsafe-call.mdx:2]: No, I'm guessing you need to also update `no-unsafe-call.ts`? If that doesn't work, can you post the test error you're seeing? Hard to help without details. 🙂

Comment (Vinccool96) [reply packages/eslint-plugin/docs/rules/no-unsafe-call.mdx:2]:
```
Error: expect(received).toMatchObject(expected)

- Expected  - 1
+ Received  + 1

  Object {
    "depth": 2,
-   "text": "description: 'Disallow calling a value with type an {{type}} value.'",
+   "text": "description: 'Disallow calling a value with type an `any` value.'",
    "type": "heading",
  }
    at Object.toMatchObject (C:\Users\User\Documents\WebstormProjects\typescript-eslint\packages\eslint-plugin\tests\docs.test.ts:202:27)
```

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/docs/rules/no-unsafe-call.mdx:2]: Yup, looks to me like you need to keep both places in sync. Anywhere that has the _`Disallow calling a value with ...`"_ should be the proper rule description.

If it helps, https://typescript-eslint.io/developers/custom-rules has our docs (not specifically relevant to this thread), and also links to the core ESLint docs. https://eslint.org/docs/latest/extend/custom-rules in particular mentions what `docs.description` is.

File: packages/eslint-plugin/src/rules/no-unsafe-call.ts [hunk 5]
```diff
@@ -20,7 +20,7 @@ export default createRule<[], MessageIds>({
   meta: {
     type: 'problem',
     docs: {
-      description: 'Disallow calling a value with type `any`',
+      description: 'Disallow calling a value with type an {{type}} value',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-unsafe-call.ts:23]: ...in other words, you odn't need to update this string. `docs.description` is a description of the rule. It doesn't show up in error messages.

File: packages/eslint-plugin/src/rules/no-unsafe-call.ts [hunk 6]
```diff
@@ -20,12 +20,12 @@ export default createRule<[], MessageIds>({
   meta: {
     type: 'problem',
     docs: {
-      description: 'Disallow calling a value with type `any`',
+      description: 'Disallow calling a value with type an `any` value',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-unsafe-call.ts:23]: [Docs] Still this typo...

```suggestion
      description: 'Disallow calling a value with type `any`',
```

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]

**Review by JoshuaKGoldberg — APPROVED** [review]
🔥 swell, thank you!
