### PR TITLE
fix(typescript-estree): disallow `using` as the variable keyword for `for..in` loops

### LINKED ISSUE #7555: Bug: `for (using foo in {});` should be invalid
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

parser

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.0-beta&showAST=es&fileType=.tsx&code=GYewTgBAFArgzgSwHYHMKhBZEDeBfASgG4g&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
for (using foo in {});
```

- [TS Playground](https://www.typescriptlang.org/play?#code/GYewTgBAFArgzgSwHYHMKhBZEDeBfASgG4g)
- [Prettier Playground (babel)](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnABACgK4DOAllAOZboRYlbAC+AlANwgA0IEADjEdAcqACGGDBADuABWEJ+KQQBsxggJ792AIwyCwAazgwAyoIC2cADIk4yVAoJwNW3foOdtJUshgY89kHeNEnt6+xGTycACKeBDw1ra+AFYEAB4G7uFRMVZINvJ27ACO0fASopyyIIIEALRQcHAAJo1sIF6CRPLuAMIQxsaCyJXy8i2hpOEAgjBeROp4JXAYFnVxeb4AFjDG8gDq60TwBK5gcAYyB0QAbgfKg2AEaiCXPgCSUE2wBmAYRNwT7wYYMpwqt8iBOKI7DstJxBhC4HYMJcrOwSIiYKVBKR+qDfK4MIjBupBOo4CN2BCSDAdkQGjB1sgABwABnYGDgRSI7Mx2IGOXi7BgJJpdIZSAATOxCHAACok2S5MFwYykhpNBpmQRkPBYuAAMUw-Wm7kGgnmEBAdDoQA)

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

Error thrown.

### Actual Result

Successfuly parsed.

### Additional Info

_No response_

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/parser`            | `5.6.0` |

### PR DESCRIPTION
**Pull request by Solo-steven**
## PR Checklist

- [x] Addresses an existing open issue: fixes #7555 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

fix issue #7555  by check TypeScript `nodeflag`, one problem is I not sure I add test case in correct file, if there are some wrong, please tell me, thanks ~

### CODE REVIEW

**Comment by Solo-steven** [comment]
The reason that the CI job failed seems because OOM ( out of memory ), local linter result is pass, and since I only changed the `typescript-estree` package, and the CI log shows that this package is passing linter, I belive re-run the CI pipeline should be ok ~ 😄
Screenshot 2023-09-15 at 5 33 26 PM

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
The only thing forbidden is `for (using x in y)`, because in this case `x` is statically known to be non-disposable, so this is likely a mistake. For all other constructs, `x` can actually be a disposable, and the grammar allows `using`.

**Comment by JoshuaKGoldberg** [comment]
👋 Hey @Solo-steven! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging. Thanks!

**Comment by Solo-steven** [comment]
> 👋 Hey @Solo-steven! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging. Thanks!

Hi @JoshuaKGoldberg , sorry for the delay, I am missing this issue from my schedule, I change the test case and only disallow using when `using` is in for-of statement, and thanks @Josh-Cena 's check ~

**Comment by JoshuaKGoldberg** [comment]
Okie dokie, when you're ready for it to be re-reviewed you can [re-request a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#re-requesting-a-review).

File: packages/typescript-estree/src/convert.ts [hunk 1]
```diff
@@ -3458,4 +3459,20 @@ export class Converter {
...
   }
+  #checkForStatementDeclaration(initializer: ts.ForInitializer): void {
+    if (ts.isVariableDeclarationList(initializer)) {
+      if (
+        !(
+          initializer.flags & ts.NodeFlags.Const ||
+          initializer.flags & ts.NodeFlags.Let ||
+          initializer.flags === ts.NodeFlags.None
+        )
+      ) {
```
Comment (bradzacher) [inline packages/typescript-estree/src/convert.ts:3470]: instead of checking for it "not being one of the valid states", instead can we just check for the one state we want to error on - `(initializer.flags & ts.NodeFlags.Using) !== 0`

File: packages/typescript-estree/src/convert.ts [hunk 2]
```diff
@@ -3458,4 +3459,20 @@ export class Converter {
...
+        this.#throwError(
+          initializer,
+          " The left-hand side of a 'for...in' statement cannot be a 'using' declaration.",
```
Comment (bradzacher) [inline packages/typescript-estree/src/convert.ts:3473]: nit remove the space

```suggestion
          "The left-hand side of a 'for...in' statement cannot be a 'using' declaration.",
```

File: packages/typescript-estree/tests/lib/convert.test.ts [hunk 3]
```diff
@@ -361,4 +361,13 @@ describe('convert', () => {
...
   });
+  describe('using should be forbidden in for-related initializer ', () => {
+    it('using should be forbidden in for in statement ', () => {
+      const ast = convertCode('for(using foo in {});');
+
+      const instance = new Converter(ast);
+
+      expect(() => instance.convertProgram()).toThrow();
+    });
+  });
```
Comment (bradzacher) [inline packages/typescript-estree/tests/lib/convert.test.ts:372]: We don't put AST tests in this location - this is more for testing our infra.
Instead we place our AST tests in the `ast-spec` package alongside the AST declarations.

We haven't written proper docs for this yet (sorry!) but the steps for doing this is as follows:

1) within [this folder](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/ast-spec/src/statement/ForInStatement) create a folder called `fixtures`.
2) within `fixtures` create a `_error_` folder
3) within `_error_` create a folder with a name for your case - for example maybe `using-initializer`?
4) within that folder, create a file called `fixture.ts`
5) within that file add your test code (eg `for(using foo in {});`)
6) `cd packages/ast-spec && yarn test` to run the fixture tests and generate the necessary snapshots.

**Review by bradzacher — CHANGES_REQUESTED** [review]
thanks for your work on this! sorry for taking so long to get back to this.

**Comment by Josh-Cena** [comment]
Hi @Solo-steven, do you have time to take a look at the review?

**Comment by Solo-steven** [comment]
> Hi @Solo-steven, do you have time to take a look at the review?

Hi @Josh-Cena  Sorry about the late response, I am kind of busy this month, but I will fix this PR this weekend! thanks for your reminder ~

**Comment by JoshuaKGoldberg** [comment]
👋 checking in again @Solo-steven - by "this month" do you mean January?

No worries if you're busy, just checking in!

**Comment by Solo-steven** [comment]
I @JoshuaKGoldberg sorry about being so late, i pushed a new commit to fix the above problem, thanks for your patience and comment on this PR ~

**Comment by JoshuaKGoldberg** [comment]
Ok great, thanks!

Tip: if you ever want us to take another look, re-requesting review through the GitHub UI will auto-remove the `awaiting response` label. Nice little automation we set up 😄

**Review by bradzacher — DISMISSED** [review]
this LGTM - thanks for adding this in!
