### PR TITLE
fix(eslint-plugin): [no-unnecessary-condition] don't flag optional chaining for union types with an unconstrained type parameters

### LINKED ISSUE #10600: Bug: [no-unnecessary-condition] False positive on dynamic access of generic value
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.7.2&fileType=.tsx&code=KYDwDg9gTgLgBASwHY2FAZgQwMbDgMQQBtUoAZBAZxgElUBbSmpMAVxgB4AVAPjgG8AUHEQNKALjgBBKFEwBPbj2FxKwTFGwALSdSjIA5oIC%2BgwaEiw46VkmwwEEJNeKkK1OsEYAheQGlgeUolAAoVflEvSgAaVXVNLThjSUISNHdaMWY2Tl5olQBrQIlpWQUOIvkIdDg8wQBKSRk5RV4BFWwnajgiCAB3NABhTDUAZXjtOABeOI1tADoYCDJ%2BoZHgEPqzEShgGFYoZwQxefRXNBCQ46966eUREUrKecoIeg2Qytupvmv6AG1KgBdAD8iwgoxg%2BiQBk24JWAygwzUcOQ2CIrAAJsBKCFeojkcBxnMtPV6vkRFtjEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
export interface FilterListItemsInput<T> {
  items: Array<T>
  search: string
}

export function filterListItemsByKeys<T>(
  { items, search }: FilterListItemsInput<T>,
  keys: Array<keyof T>,
): Array<T> {
  const lowerCaseSearch = search.toLowerCase()

  return items.filter((item) =>
    keys.some((key) => item[key]?.toString().toLowerCase().includes(lowerCaseSearch)),
  )
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unnecessary-condition": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expect the code above not to error because `item[key]` **can** be nullish, but the ESLint rule says it can't.

### Actual Result

`ESLint: Unnecessary optional chain on a non-nullish value.(@typescript-eslint/ no-unnecessary-condition)`

### Additional Info

I found https://github.com/typescript-eslint/typescript-eslint/issues/9754 which seems similar, though I don't think it's quite the same.

### PR DESCRIPTION
**Pull request by ronami**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10600
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR resolves #10600 and removes some duplicated logic for checking special-case types in a union (`any`, `unknown`, or types with the `TypeVariable` type flag).

The current implementation seems to pick up unconstrained type parameters by checking the presence of the `TypeVariable` type flag. I think this is necessary (over `getConstraintInfo`) as the check needs to detect types such as the following:

```ts
function test<T>(arg: T, key: keyof T) {
  if (arg[key]) {
    //
  }
}
```

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 1]
```diff
@@ -370,18 +383,7 @@ export default createRule<Options, MessageId>({
...
-      if (
-        tsutils
-          .unionTypeParts(type)
-          .some(
-            part =>
-              isTypeAnyType(part) ||
-              isTypeUnknownType(part) ||
-              isTypeFlagSet(part, ts.TypeFlags.TypeVariable),
-          )
-      ) {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:384]: [Praise] Heh, yeah, this was getting a little hard to read inline even before...

**Review by JoshuaKGoldberg — APPROVED** [review]
Basketball players celebrating on the court. One in center calmly nods at the viewer
