### PR TITLE
fix(typescript-eslint): apply `ignores` to all extended configs passed to `config` helper function

### LINKED ISSUE #8511: Bug: config function from typescript-eslint doesn't use `ignores` when `extends` is provided.
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### Playground Link

_No response_

### Repro Code

I want to apply type-checked rules to most of my codebase with some exceptions. This is the config I have:

### ESLint Config

```TypeScript
tseslint.config({
    files: ['**/*.{ts,tsx}'],
    ignores: ['libs/legacy-lib/**'],
    extends: [
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
  })
```

### tsconfig

_No response_

### Expected Result

I expect the final config to have `ignores` applied to each of the configs I'm extending from.

### Actual Result

Only `files` are applied, not `ignores`.

### Additional Info

I can see from [the code](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-eslint/src/config-helper.ts#L94-L100) that `ignores` is not supported. This is somewhat surprising, given that `files` and `ignores` are two sides of the same coin - the ability to provide a list of files which to apply the rules to.

However, adding this functionality will likely be considered a breaking change.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript-eslint` | `7.0.1` |

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8511
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/typescript-eslint/src/config-helper.ts [hunk 1]
```diff
@@ -91,14 +91,17 @@ export function config(
...
-    if (config.files) {
-      const files = config.files;
-      return [
-        ...extendsArr.map(conf => ({ ...conf, files: [...files] })),
-        config,
-      ];
-    }
+    const extension = {
+      ...(config.files && { files: config.files }),
+      ...(config.ignores && { ignores: config.ignores }),
```
Comment (auvred) [inline packages/typescript-eslint/src/config-helper.ts:96]: `ignores` will overwrite `ignores` from the extended config. I'm not sure if this is the desired behavior, but so far I've made it to match the behavior of `files`. Any thoughts on this?

Comment (bradzacher) [reply packages/typescript-eslint/src/config-helper.ts:96]: I think overriding is correct.
Any local config should always override the extended config

**Review by bradzacher — APPROVED** [review]
