### PR TITLE
fix(eslint-plugin): correct rule schemas to pass ajv validation

### LINKED ISSUE #5525: Bug: Strange logging "can't resolve reference" after update to version 5.34.0
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Issue Description

Strange logging after update to version 5.34.0

```
can't resolve reference #/definitions/arrayOption from id #
can't resolve reference #/definitions/arrayOption from id #
can't resolve reference #/definitions/directiveConfigSchema from id #
can't resolve reference #/definitions/directiveConfigSchema from id #
can't resolve reference #/definitions/directiveConfigSchema from id #
can't resolve reference #/definitions/directiveConfigSchema from id #
can't resolve reference #/definitions/accessibilityLevel from id #
can't resolve reference #/definitions/accessibilityLevel from id #
can't resolve reference #/definitions/accessibilityLevel from id #
can't resolve reference #/definitions/accessibilityLevel from id #
can't resolve reference #/definitions/accessibilityLevel from id #
can't resolve reference #/definitions/accessibilityLevel from id #
can't resolve reference #/definitions/modifier from id #
```

### Reproduction Repository Link

na

### Repro Steps

1) clone the repo
2) `yarn install`
3) `yarn lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.35.0` |
| `@typescript-eslint/parser`            | `5.35.0` |
| `TypeScript`                           | `4.7.4` |
| `ESLint`                               | `8.22.0` |
| `node`                                 | `18.7.0` |

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5525
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Many rules use one or both of the following [JSON schema](https://json-schema.org) features:
* Using a tuple (fixed size array) of size two for their options schema. 
* Using [schema refs](https://json-schema.org/understanding-json-schema/structuring.html#ref) to repeat types. Those types get printed as individual interfaces or unions on https://typescript-eslint.io.

For example, `ban-ts-comment` options separate out a `directiveConfigSchema` ref representing a union of `false`, `"allow-with-description"`, or an object with `descriptionFormat?: string`. See https://typescript-eslint.io/rules/ban-ts-comment/#options.

Although what we use to auto-generate much of the rule docs on typescript-eslint.io works for rules that both use the array format and schema refs (#5386), the settings used by ESLint during runtime validation are apparently much more strict.

This PR switches from `schema: [ ... ]` to `schema: { ... }` using [JSON schema's native tuple validation](https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation) on just the rules causing complaints. It's a little bit uglier code but fixes the errors.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/array-type.ts [hunk 1]
```diff
@@ -102,27 +102,30 @@ export default util.createRule<Options, MessageIds>({
...
-          default: {
-            $ref: '#/definitions/arrayOption',
-            description: 'The array type expected for mutable cases...',
-          },
-          readonly: {
-            $ref: '#/definitions/arrayOption',
-            description:
-              'The array type expected for readonly cases. If omitted, the value for `default` will be used.',
+      },
+      prefixItems: [
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/array-type.ts:111]: This syntax is a little more heavyweight than `schema: [ ... ]`. It would be nice if someone could figure out a ray to use `$ref`s within the array. I couldn't.

cc @bchery 😁

File: packages/eslint-plugin/src/rules/array-type.ts [hunk 2]
```diff
@@ -102,27 +102,30 @@ export default util.createRule<Options, MessageIds>({
...
+        {
+          properties: {
+            default: {
+              $ref: '#/definitions/arrayOption',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/array-type.ts:115]: #5509 did not fix the issue for me.

File: packages/eslint-plugin/src/rules/ban-ts-comment.ts [hunk 3]
```diff
@@ -38,43 +38,45 @@ export default util.createRule<[Options], MessageIds>({
...
+      },
+      prefixItems: [
+        {
+          properties: {
+            'ts-expect-error': {
+              $ref: '#/definitions/directiveConfigSchema',
+            },
+            'ts-ignore': { $ref: '#/definitions/directiveConfigSchema' },
+            'ts-nocheck': { $ref: '#/definitions/directiveConfigSchema' },
+            'ts-check': { $ref: '#/definitions/directiveConfigSchema' },
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/ban-ts-comment.ts:69]: _Sigh_. Working on it.

Screenshot of ban-ts-comments with type Options = unknown

**Review by bradzacher — APPROVED** [review]

**Comment by JoshuaKGoldberg** [comment]
This is released in `@typescript-eslint/eslint-plugin@5.35.1`! ✨ Please update all packages under `@typescript-eslint/` in your `package.json`s to the latest version, same version.

If this exact issue is still happening for you, please go through https://github.com/typescript-eslint/typescript-eslint/issues/new/choose to file a new issue. Be sure to check all versions of your installed packages.

Thanks for your patience all - and apologies again for the disruption! ❤️

**Comment by WesleyMConner** [comment]
@typescript-eslint/eslint-plugin  5.34.0  →  5.35.1
@typescript-eslint/parser         5.34.0  →  5.35.1

No longer see the issue. :)
