### PR TITLE
fix(eslint-plugin): [use-unknown-in-catch-callback-variable] only flag function literals

### LINKED ISSUE #9057: Enhancement: [use-unknown-in-catch-callback-variable] Option to only check inline functions
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/use-unknown-in-catch-callback-variable/

### Description

I propose an option to only check on inline functions, i.e. `.catch((foo) => bar)` and not `.catch(baz)`. If `baz` accepts `any`, it's either from an external library or will be flagged by `--noImplicitAny`/`no-explicit-any`.

Use case: I have a few instances of `.catch(console.error)` in my codebase to log errors without throwing. `console.error` is typed as `(...data: any[]): void`, and as such this rule triggers an error.

### Fail

```TypeScript
Promise.resolve().catch((error) => error) // Preserve old behavior
```

### Pass

```TypeScript
Promise.resolve().catch((error: unknown) => error) // Preserve old behavior
Promise.resolve().catch(console.log) // Would previously error
Promise.resolve().catch(foo) // Would previously error

function foo(bar: any) { }
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9057 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Since we're no longer generally flagging expressions that have type `(e: any) => whatever`, I added in recursion to catch function literals not passed directly, but whose type is still inferred. So, `promise.catch(e => condition ? (e) => {} : (e) => {});` still can and does trigger the rule, since `e` is inferred as `any` in both locations. Plus, the rule reports them each individually and consequently offers a suggestion now.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/use-unknown-in-catch-callback-variable.ts [hunk 1]
```diff
@@ -100,10 +100,41 @@ export default createRule<[], MessageIds>({
...
+        case AST_NODE_TYPES.LogicalExpression:
+          return [
+            ...collectFlaggedNodes(node.left),
+            ...collectFlaggedNodes(node.right),
+          ];
+        case AST_NODE_TYPES.SequenceExpression:
+          return collectFlaggedNodes(
+            nullThrows(
+              node.expressions.at(-1),
+              'seuence expression must have multiple expressions',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/use-unknown-in-catch-callback-variable.ts:116]:
```suggestion
              'sequence expression must have multiple expressions',
```

**Review by JoshuaKGoldberg — DISMISSED** [review]
Wow this is so much more effort than I thought would happen - and it's a great improvement! 🔥 

Pitch Meetings guy on YouTube saying "Wow wow wow ... wow"
