### PR TITLE
fix(eslint-plugin): always ignore assignments in no-unnecessary-type-assertion

### LINKED ISSUE #3115: [strict-boolean-expressions] False positive with union types having only one falsey value
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```javascript
module.exports = {
    "root": true,
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "tsconfigRootDir": __dirname,
        "project": ["./tsconfig.json"]
    },
    "plugins": ["@typescript-eslint"],
    "rules": {
        "@typescript-eslint/strict-boolean-expressions": ["error"]
    }
}
```

```TS
function f(arg: "Option1" | "Option2" | null) {
    if (arg)
        console.log(`Input: ${arg}`);
    else
        console.log("Null was input");
}
```

tsconfig: the default as output by `tsc --init`

**Expected Result**

I expected there to be no error, as there is exactly one possible falsey value, no ambiguity.

**Actual Result**
```
  2:9  error  Unexpected nullable string value in conditional. Please handle the nullish/empty cases explicitly  @typescript-eslint/strict-boolean-expressions
```
**Additional Info**
This is similar to the likely non-bug #2894, but in that example there are multiple falsey values.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.15.2` |
| `@typescript-eslint/parser`        | `4.15.2` |
| `TypeScript`                       | `4.1.5` |
| `ESLint`                           | `7.20.0` |
| `node`                             | `10.24.0` |

### LINKED ISSUE #3187: [no-unnecessary-type-assertion] too restrictive with intended temporary narrowing
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Release 4.17.0 has changed the rule "no-unnecessary-type-assertion" (PR #3133) in a way that breaks existing code, as it seems it now forbids some legitimate use cases of the `!` operator:

```JSON
{
  "rules": {
    "@typescript-eslint/no-unnecessary-type-assertion": "error"
  }
}
```

```TS
class X {
    public doSomething(): void { }
}

const arr: X[] = [];

let x: X | undefined;
if (arr.length > 0) {
    x = arr.pop()!; // <== known that pop() returns something, needed to temp. narrow `x`
    x.doSomething();
}

if (x) {
    // ...
}
```

**Expected Result**
Inside the first `if`, the assignment to `x` intentionally narrows the result of `pop()` because it's sure that the array is not empty.

**Actual Result**
With v4.17 the narrowing will produce a warning.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.17.0` |
| `@typescript-eslint/parser`        | `4.17.0` |
| `TypeScript`                       | `4.2.3` |
| `ESLint`                           | `7.22.0` |
| `node`                             | `12.16.2` |

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #3187.

Since TypeScript is smart about inferring types for variable assignments, I think it's reasonable to always exclude the right-hand-side of assignment expressions.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts [hunk 1]
```diff
@@ -137,19 +137,20 @@ export default util.createRule<Options, MessageIds>({
...
+              messageId: 'contextuallyUnnecessary',
+              fix(fixer) {
+                return fixer.removeRange([
+                  node.expression.range[1],
+                  node.range[1],
+                ]);
+              },
+            });
+          }
           return;
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts:154]: could you please add a comment explaining why we don't check any other assignments?

```suggestion
          // for all other = assignments we ignore non-null checks
          // this is because non-null assertions can change the type-flow of the code
          // so whilst they might be unnecessary for the assignment - they are necessary
          // for following code
          return;
```

**Review by bradzacher — CHANGES_REQUESTED** [review]
Yeah the change didn't consider all of the cases and was ultimately a bad one.

Thanks! One comment

**Review by bradzacher — APPROVED** [review]
THANKS!
