### PR TITLE
fix(eslint-plugin): [no-extraneous-class] handle accessor keyword

### LINKED ISSUE #10676: Bug: [no-extraneous-class] false positive with accessor
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.7.2&fileType=.ts&code=MYGwhgzhAEDKAuZ4EtgGED2A7CivxgG8AoaaMYYAUygwCdoswBbKgLmlzuSwHMBuUp0Qpg0AGYYMACgCU0EmTJ0q8AK50sEsCAhUhAX2JGgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge3oA99oBDJog6xktMvH7JUGSImjQO0SODABfEGqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
class StaticConstants {
  accessor name: string;
  static foo() {
    return false
  }
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-extraneous-class": ["error"],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

no errors

### Actual Result

```ts
class StaticConstants { // Unexpected class with only static properties. 1:7 - 1:22
  accessor name: string;
  static foo() {
    return false
  }
}
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by mdm317**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10676
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-extraneous-class.ts [hunk 1]
```diff
@@ -123,7 +123,8 @@ export default createRule<Options, MessageIds>({
             onlyConstructor = false;
             if (
               ((prop.type === AST_NODE_TYPES.PropertyDefinition ||
-                prop.type === AST_NODE_TYPES.MethodDefinition) &&
+                prop.type === AST_NODE_TYPES.MethodDefinition ||
+                prop.type === AST_NODE_TYPES.AccessorProperty) &&
```
Comment (ronami) [inline packages/eslint-plugin/src/rules/no-extraneous-class.ts:127]: [Bug]: Seeing https://github.com/typescript-eslint/typescript-eslint/issues/9359, I think the rule should not report on the following:

```ts
// doesn't report correctly
abstract class R {
  abstract property: string;
}

// doesn't report correctly
abstract class S {
  abstract method(): string;
}

// reports but shouldn't
abstract class T {
  //           ~
  // Unexpected class with only static properties.
  abstract accessor prop: () => void;
}
```

**Review by ronami — CHANGES_REQUESTED** [review]
Looking good! Thanks for sending this in, just requesting a small adjustment around `abstract` `accessor` properties 💯

File: packages/eslint-plugin/src/rules/no-extraneous-class.ts (hunk 1 above)
Comment (mdm317) [reply packages/eslint-plugin/src/rules/no-extraneous-class.ts:127]: I missed the case of the abstract class. Thank you for letting me know.
I fixed it.

**Review by ronami — APPROVED** [review]
🚀  Nice! Thanks for sending this in!!

**Review by JoshuaKGoldberg — APPROVED** [review]
🧼
