### PR TITLE
fix(eslint-plugin): [switch-exhaustiveness-check] better support for intersections, infinite types, non-union values

### LINKED ISSUE #6682: Bug: [switch-exhaustiveness-check] invalid fix for union with infinite types
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play#ts=5.0.1-rc&sourceType=module&code=CYUwxgNghgTiAEYD2A7AzgF3lAXPARFPvAD4EBGxZKArgLbkgwDcAUK2gO4CWGYAFvAAUUAJTwA3q3iIoaBIXx5ycKAGs2MsHIWVlqjawC+rIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZAd0vzIAt6AHrwCGsZPkoA3RExTJafRGQDW6KImjQA9tEjgwAXxAGgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
declare const a: "a" | "b" | number;

switch (a) {
  case "a": break;
  case "b": break;
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/switch-exhaustiveness-check": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

No error, no suggestion fixer, or suggestion to add a default case

### Actual Result

Fixer produces `case number:`, which is invalid syntax.

### Additional Info

I'm not sure what the best fix for this issue is, so I hope to get more discussion first.

### LINKED ISSUE #8238: Bug: [switch-exhaustiveness-check] requireDefaultForNonUnion false positive on type with one value
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=C4TwDgpgBAsiAq5oF4oCIA2BLYEBOAhhlAM7B5YB2A5mlAPQBUUAPugPbAAW%2Bdj9AbgBQQiAA8w7PMCgBjdpTJQAZlFQAKMQC5YCJAEo1APigBvIVFIB3HLK5RNh85cuyCJaJhz4ipclVotCxdLPAhgAFc8SmEQpmDXd09OHjw0IJDQ8KiYhKh%2BYIBfIULhIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZAd0vzIAt6AHrwCGsZPkoA3RExTJafRGQDW6MAG1w2HB2HQmkADRbtWbdkjD48APYcAIogBmo%2BPgDCw5IgBiN6ACiQqLiUogAylw8vGou8N7G5hbQiACOsJQpji4I%2BH7QAHI2TACqTJTFavhwiCbYAL51ALpajfVAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
type MyType = "literal string" /* | "other" */;

export const f = (x: MyType) => {
  switch (x) {
    case "literal string":
      return;
    /*
    case "other":
      return;
    */
  }
};
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/switch-exhaustiveness-check": [
      "warn",
      {
        allowDefaultCaseForExhaustiveSwitch: false,
        requireDefaultForNonUnion: true,
      },
    ],
  },
};
```

### tsconfig

_No response_

### Expected Result

No warning. This switch exhaustively covers the 1 case.

### Actual Result

A warning.

### Additional Info

[Convenient link to the docs](https://typescript-eslint.io/rules/switch-exhaustiveness-check/). This option was added recently: https://github.com/typescript-eslint/typescript-eslint/pull/7880

The option works for unions of strings, but if the union only has one option (so it's just a literal), then the option thinks the switch needs a default.

You might wonder why we have a switch that only has one case. This is code that changes frequently for handling feature flags in our app, and right now, we only have one feature flag, but don't want to refactor out the switch just to add it back when we add a second flag again.

In the example, if you uncomment the second option, it will correctly know there doesn't need to be a default, and eslint will pass.

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8238, fixes #6682
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

I decided to fix both issues in one pr, because it was really hard to fix the first one without fixing the second.

This PR introduces better support for all combinations of unions, intersections, infinite types. It also fix suggestions more accurate.

In addition, this PR also includes several fixes for bugs that were present on `main` but wasn't mentioned in issues:

#### 1. Provide correct fixes for missing `unique symbols`

Before ([playground](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=MYewdgzgLgBAhjAvDAygTwLYCMQBsAUA5HIQJQBQoksWSqmOBhWZ5AJgKbC5wBOHMKtBgA3OLgCuHAFwwoaAA4cQAM3gwAPnMXK1tGOXIQA7gEsowABYx8YyR1IwA3uRiC4EAXFlZ%2BcANYA3OQAvkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZAd0vzIAt6AHrwCGsZPkoA3RExTJafRGQDW6MAG1w2HImjQA9tEhaIAXS0BfEBaA&tsconfig=&tokens=false)):
```diff
const a = Symbol('a')
const b = Symbol('b')
declare const value: typeof a | typeof b  

switch (value) {
  case a: break;
+ case unique symbol: { throw new Error('Not implemented yet: unique symbol case') }
}
```
After:
```diff
const a = Symbol('a')
const b = Symbol('b')
declare const value: typeof a | typeof b  

switch (value) {
  case a: break;
+ case b: { throw new Error('Not implemented yet: b case') }
}
```

#### 2. Support intersections that includes literals

Before ([playground](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=CYUwxgNghgTiAEYD2A7AzgF3gNyhAriAFzwAUA5FFOfAGTwDeURAjAL4CU8APvOQEb9yAKDQB3AJYYwACzK4CILg2HxEUNAkrUS-OFADWAblXrNfQeV37jwtkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZAd0vzIAt6AHrwCGsZPkoA3RExTJafRGQDW6MAG1w2HImjQA9tEgAaLdqzbsMRAEdYlaIgAiiAGaj4%2BAGKGAcvqYAVSZKALV8OEQzbABfaIBdLTiYoA&tsconfig=&tokens=false)):
```ts
declare const value: ('aa' & {a:1}) | 'bb'
switch (value) {
//      ^ Switch is not exhaustive. Cases not matched: "aa" & { a: 1; }
  case 'aa': break;
  case 'bb': break;
}
```
After (no false positive):
```ts
declare const value: ('aa' & {a:1}) | 'bb'
switch (value) {
  case 'aa': break;
  case 'bb': break;
}
```

#### 3. Consistently add a default branch both for bare infinite types and unions of infinite types

Before ([playground](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=CYUwxgNghgTiAEYD2A7AzgF3gNyhAriAFzwr4C2ARiDAFBoDuAlhmABbwAUuBIAlPADeteIihoEARhKU4UANYBuWgF9a60JFgJk6LD0LTSFajHgAfeJhhMUAc3rNWHbnkMDhosOKky5S1SA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZAd0vzIAt6AHrwCGsZPkoA3RExTJafRGQDW6MAG1w2HImjQA9tEgAaLdqzbsMRAEdYlaIgAiiAGaj4%2BAGKGAcvqYAVSZKALV8OEQzbABfaIBdLTiYoA&tsconfig=&tokens=false)):
```diff
declare const value: number
switch (value) {
  case 1: break;
+ default: { throw new Error('default case') }
}


declare const value: number | string
switch (value) {
  case 1: break;
+ case string: { throw new Error('Not implemented yet: string case') }
+ case number: { throw new Error('Not implemented yet: number case') }
}
```
After:
```diff

declare const value: number
switch (value) {
  case 1: break;
+ default: { throw new Error('default case') }
}


declare const value: number | string
switch (value) {
  case 1: break;
+ default: { throw new Error('default case') }
}
```

---

I've removed `isUnion` from `SwitchMetadata` to avoid confusion: we shouldn't treat unions and non-unions differently. We should only care whether a type contains non-literal types or not

### CODE REVIEW

File: packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts [hunk 1]
```diff
@@ -134,54 +123,47 @@ export default createRule<Options, MessageIds>({
...
-      const unionTypes = tsutils.unionTypeParts(discriminantType);
-      const missingBranchTypes = unionTypes.filter(
-        unionType => !caseTypes.has(unionType),
-      );
+      const missingLiteralBranchTypes: ts.Type[] = [];
+
+      for (const unionPart of tsutils.unionTypeParts(discriminantType)) {
+        for (const intersectionPart of tsutils.intersectionTypeParts(
+          unionPart,
+        )) {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts:131]: [Non-Actionable] This feels like something we'd want a shared utility for... and, ha, I filed an issue for this back in August! https://github.com/typescript-eslint/typescript-eslint/pull/7466#discussion_r1295028416 -> https://github.com/JoshuaKGoldberg/ts-api-utils/issues/258

Not requesting changes here. I'll go ahead and send that PR to `ts-api-utils` and then follow up in this repo.

**Review by JoshuaKGoldberg — APPROVED** [review]
What a lovely, thoroughly tested PR! Thanks for sending this in! 👏

File: packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts:131]: https://github.com/JoshuaKGoldberg/ts-api-utils/pull/374
