### PR TITLE
fix(typescript-estree): fix filename handling for vue JSX + markdown

### LINKED ISSUE #1123: [2.5.0] Markdown parsing failed
**What code were you trying to parse?**

Markdown text:

``````md
There are `primary` button, `default` button, `dashed` button, `danger` button and `link` button in antd.

```jsx
import { Button } from 'antd';

ReactDOM.render(
  <div>
    <Button type="primary">Primary</Button>
    <Button>Default</Button>
    <Button type="dashed">Dashed</Button>
    <Button type="danger">Danger</Button>
    <Button type="link">Link</Button>
  </div>,
  mountNode,
);
```

``````

**What did you expect to happen?**

Works eslint normal as `2.4.0`

**What actually happened?**

> error  Parsing error: '>' expected

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.5.0` |
| `TypeScript`                | `3.6.4` |
| `ESLint`                    | `6.5.1` |
| `node`                      | `10.16.3` |
| `npm`                       | `6.9.0` |

### LINKED ISSUE #1124: JSX cannot be resolved in  Vue and Ts
**What code were you trying to parse?**

```ts
<script lang="tsx">
import Vue from 'vue'
import { mapMutations } from 'vuex'
import { Component } from 'vue-property-decorator'

@Component({
    created () {
        this.toggleHeader(false)
    },
    methods: {
        ...mapMutations(process.env.APP_SCOPE_NAME as string, ['toggleHeader'])
    }
})
export default class Error extends Vue {
    render (): JSX.Element {
        return (
            // An error occurred in the next line: "Parsing error: '>' expected.eslint"
            <div class="mg-notFound">
                <div class="fixed-center text-center">
                    <p>
                        <img
                            src={require('@/assets/sad.svg')}
                            style="width:30vw;max-width:150px;"
                        />
                    </p>
                    <p class="text-faded">Sorry, nothing here...<strong>(404)</strong></p>
                    <q-btn
                        color="secondary"
                        style="width:200px;"
                        onClick={() => this.$router.replace('/')}
                    >Go back</q-btn>
                </div>
            </div>
        )
    }
}
</script>
```
and my eslintrc.js

```ts
module.exports = {
    plugins: ['vue', '@typescript-eslint'],
    parserOptions: {
        parser: '@typescript-eslint/parser',
        ecmaVersion: 2018,
        sourceType: 'module',
        ecmaFeatures: {
            experimentalObjectRestSpread: true,
            jsx: true,
            globalReturn: true
        },
        extraFileExtensions: ['.vue']
    },
    root: true,
    env: {
        node: true
    },
    extends: [
        'plugin:vue/base',
        "plugin:@typescript-eslint/eslint-recommended",
        'plugin:@typescript-eslint/recommended',
        'plugin:vue/essential',
        '@vue/standard',
        '@vue/typescript'
    ],
    rules: {
        // eslint rules
        'one-var': 0,
        'arrow-parens': 0,
        'generator-star-spacing': 0,
        'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
        'no-console': 0,
        'semi': [2, 'never'],
        "quotes": [2, "single"],
        'no-extra-semi': 2,
        'space-before-function-paren': 0,
        'eqeqeq': 2,
        'spaced-comment': 0,
        'no-useless-escape': 0,
        'no-tabs': 0,
        'no-mixed-spaces-and-tabs': 0,
        'new-cap': 0,
        'camelcase': 0,
        'no-new': 0,
        'indent': [2, 4],
        'no-multiple-empty-lines': [2, { 'max': 1, 'maxEOF': 2 }],
        'space-before-function-paren': [2, "always"],
        'comma-spacing': [2, { 'before': false, 'after': true }],
        'no-redeclare': [2, { builtinGlobals: true }],
        'curly': [2, 'multi-line'],
        'prefer-const': 0,
        'keyword-spacing': 0,
        // typescript-eslint rules
        '@typescript-eslint/indent': ['error', 4],
        '@typescript-eslint/explicit-function-return-type': 0,
        '@typescript-eslint/no-triple-slash-reference': 0,
        '@typescript-eslint/no-explicit-any': 'off',
        '@typescript-eslint/no-angle-bracket-type-assertion': 0,
        '@typescript-eslint/triple-slash-reference': 0,
        '@typescript-eslint/consistent-type-assertions': 0,
        '@typescript-eslint/member-delimiter-style': 0
    }
}
```
my tsconfig.json
```ts
{
    "compilerOptions": {
        "target": "esnext",
        "module": "esnext",
        "strict": true,
        "jsx": "preserve",
        "importHelpers": true,
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "experimentalDecorators": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "sourceMap": true,
        "noImplicitAny": false,
        "allowJs": true,
        "baseUrl": "./",
        "outDir": "./dist",
        "rootDir": "./src",
        "paths": {
            "assets/*": [
                "src/assets/*"
            ],
            "http/*": [
                "src/api/http/*"
            ],
            "components/*": [
                "src/components/*"
            ],
            "*": [
                "types/*"
            ],
            "@/*": [
                "src/*"
            ]
        },
        "lib": [
            "esnext",
            "dom",
            "dom.iterable",
            "scripthost"
        ]
    },
    "include": [
        "src/*.vue",
        "src/**/*.ts",
        "src/**/*.tsx",
        "src/**/*.vue",
        "tests/**/*.ts",
        "tests/**/*.tsx"
    ],
    "exclude": [
        "lib/*",
        "node_modules",
        "./dist"
    ]
}
```

**What did you expect to happen?**
I think it will pass by eslint
**What actually happened?**
Parsing error: '>' expected. eslint
**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.5.0` |
| `TypeScript`                | `3.6.4` |
| `ESLint`                    | `5.16.0` |

### PR DESCRIPTION
**Pull request by bradzacher**
Integrations I never knew existed:
- JSX in vue files
- Parsing of markdown snippets via `eslint-plugin-markdown`

Fixes #1123
Fixes #1124

### CODE REVIEW

**Comment by JounQin** [comment]
Can we add a test case for `.mdx` with `eslint-plugin-mdx` which is definitely different from `eslint-plugin-markdown`?

**Comment by bradzacher** [comment]
feel free to raise a PR with an integration test case for your tool if you want.
I don't know what MDX is, or how it works, so it would be better if you, as a maintainer of that project, adds an integration test.

The Vue stuff that we've added has been cobbled together by copy+pasting from issues that have been raised, and then those who know vue have PR'd modifications to the config appropriately.

**Comment by JounQin** [comment]
Thx for your explanation, it will raise another PR ASAP.

File: packages/typescript-estree/src/create-program/shared.ts [hunk 1]
```diff
@@ -38,11 +38,41 @@ function canonicalDirname(p: CanonicalPath): CanonicalPath {
...
+  // jsx setting, but that could create weird situations where we throw parse errors when TSC doesn't
+  switch (extension.toLowerCase()) {
+    case 'ts':
+      return ts.ScriptKind.TS;
+
+    case 'tsx':
+      return ts.ScriptKind.TSX;
+
+    case 'js':
+      return ts.ScriptKind.JS;
```
Comment (JounQin) [inline packages/typescript-estree/src/create-program/shared.ts]: It is very common to use JSX in plain `.js` files as far as I know.

Comment (bradzacher) [reply packages/typescript-estree/src/create-program/shared.ts]: Typescript does not ban JSX within plain JS files - you can provide JSX in both `.js` and `.jsx` files.

It does ofc enforce it for TS files - you can only provide JSX in `.tsx` files.

image

Comment (JounQin) [reply packages/typescript-estree/src/create-program/shared.ts]: Cool, I'm so familiar with `ts.ScriptKind` then. Thx for your great job.

File: packages/parser/README.md [hunk 2]
```diff
@@ -42,9 +42,17 @@ The following additional configuration options are available by specifying them
...
+  typescript compiler has its own internal handling for known file extensions. The exact behaviour is as follows:
+
+  - if `parserOptions.project` is provided:
+    - `.js`, `.jsx`, `.tsx` files are parsed as if this is true.
+    - `.ts` files are parsed as if this is false.
+    - unknown extensions (`.md`, `.vue`) will respect this setting.
+  - if `parserOptions.project` is _not_ provided:
+    - `.js`, `.jsx`, `.tsx` files are parsed as if this is true.
+    - `.ts` files are parsed as if this is false.
+    - "unknown" extensions (`.md`, `.vue`) **are parsed as if this is false**.
```
[the remark this answers is not in the document]
Comment (JounQin) [reply packages/parser/README.md]: And `.vue` can be used with `jsx` syntax also.

[the remark this answers is not in the document]
Comment (bradzacher) [reply packages/parser/README.md]: oops, I got the headings the wrong way around.

if you have a project, it will not respect the setting.
if you do not have a project, it will respect the setting.
