### PR TITLE
fix(eslint-plugin): [consistent-type-definitions] correct fix for `export default`

### LINKED ISSUE #3894: [consistent-type-definitions] Add option to use interface with methods
It is possible to add the possibility of not validating this rule when the interface has functions ([default Interface style used in languages like Java](https://www.w3schools.com/java/java_interface.asp))?

E.G.:

```ts
"@typescript-eslint/consistent-type-definitions": ["error", { "type", => "allowInterfaceWithFunctions" <= }]
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

- Create one interface with methods (Java and C# style)

```ts
interface Test {
   bar(): string;
   foo(): number;
}
```

- Linter will inform you to use `Type`

- Run `eslint` with `--fix`

- Code will be updated to:

```ts
type Test = {
   bar(): string;
   foo(): number;
}
```

- Eslint will report error: `',' expected`

**Rule**

```JSON
{
  "rules": {
    "@typescript-eslint/consistent-type-definitions": ["error", "type"],
  }
}
```

### Before
Captura de Tela 2021-09-16 às 22 37 59

### After auto fix
Captura de Tela 2021-09-16 às 22 37 37

**Expected Result**

Don't suggest `Type` for `Interfaces` that contain functions (like Java and C# Interface styles)

**Actual Result**

Suggests change, performs auto-fix, but displays error after it.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.31.1` |
| `@typescript-eslint/parser`        | `4.31.1` |
| `TypeScript`                       | `4.4.3` |
| `ESLint`                           | `7.32.0` |
| `node`                             | `12.18.3` |

### PR DESCRIPTION
**Pull request by rafaelss95**
Fixes #3894.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/consistent-type-definitions.ts [hunk 1]
```diff
@@ -122,6 +122,19 @@ export default util.createRule({
                     });
                   }
 
+                  if (
```
Comment (rafaelss95) [inline packages/eslint-plugin/src/rules/consistent-type-definitions.ts:125]: While working on this fix, I noticed that the option is checked **after** having already found a certain node (and in some other files as well), for example:

https://github.com/typescript-eslint/typescript-eslint/blob/1e7e6d8cec0bae3736ae2c8a84509b7dddc2525f/packages/eslint-plugin/src/rules/consistent-type-definitions.ts#L50-L54

<details>
<summary>Other cases <sub><i>(click to expand)</i></sub></summary>

https://github.com/typescript-eslint/typescript-eslint/blob/b1d44497ddf8ef4615c727fe4241e54f7f1aba65/packages/eslint-plugin/src/rules/method-signature-style.ts#L120-L123

https://github.com/typescript-eslint/typescript-eslint/blob/1c1b572c3000d72cfe665b7afbada0ec415e7855/packages/eslint-plugin/src/rules/restrict-plus-operands.ts#L136-L137

https://github.com/typescript-eslint/typescript-eslint/blob/25ea953cc60b118bd385c71e0a9b61c286c26fcf/packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts#L242-L244

https://github.com/typescript-eslint/typescript-eslint/blob/1c1b572c3000d72cfe665b7afbada0ec415e7855/packages/eslint-plugin/src/rules/typedef.ts#L180-L183

https://github.com/typescript-eslint/typescript-eslint/blob/1c1b572c3000d72cfe665b7afbada0ec415e7855/packages/eslint-plugin/src/rules/explicit-function-return-type.ts#L71-L76

</details>

But, IMHO this could be improved by moving the conditional up then wrapping the `return {`, and so avoiding looking for nodes which doesn't corresponds unnecessarily. Does it makes sense for you? If so, I can send a PR `refactor` for that.

Comment (bradzacher) [reply packages/eslint-plugin/src/rules/consistent-type-definitions.ts:125]: happy to accept a PR if you want!

**Review by bradzacher — APPROVED** [review]
thanks for fixing this!
