### PR TITLE
fix(eslint-plugin): [no-unnecessary-type-assertion] provide valid fixes for assertions with extra tokens before `as` keyword

### LINKED ISSUE #8325: Bug: [no-unnecessary-type-assertion] fixer produces syntax error when there are some extra tokens before `as` keyword
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.2&fileType=.tsx&code=BQRgBA1GBMYJRgIYGcwDsCuBbARgUwCcAocKaAegCokxLylVNdCg&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
(1 + 2 ) as number
1 + 2/* a */ as number
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-unnecessary-type-assertion": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

It should be fixed to

```ts
(1 + 2 )
1 + 2/* a */
```

### Actual Result

It's fixed to

```ts
(1 + 2 
1 + 2/
```

### Additional Info

UPD: it also doesn't provide (but it should) fixes when type annotation of angle bracket assertion contains some extra tokens: [playground](https://typescript-eslint.io/play/#ts=5.3.2&fileType=.ts&code=DwCgdgrgtgRgpgJwAQEoB8ICMSDUSBMKQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

```ts
<(number )>(1 + 2)
```

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8325
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

I think the test cases and comments are a nice overview :)

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts [hunk 1]
```diff
@@ -263,23 +263,38 @@ export default createRule<Options, MessageIds>({
...
-                      node.range[0],
-                      closingAngleBracket.range[1],
-                    ])
-                  : null;
+                  token =>
+                    token.type === AST_TOKEN_TYPES.Punctuator &&
+                    token.value === '>',
+                )!;
+                // < ( number ) > ( 3 + 5 )
+                // ^---remove---^
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts:279]: [Non-Actionable] Somehow my brain immediately parsed this as an emoticon smiley... amused.

```plaintext
// < ( number ) >
// ^---remove---^
```

**Review by JoshuaKGoldberg — APPROVED** [review]
Very nice and thorough, awesome!

Animaniacs Pinky and the Brain: Pinky is saying "I love it. No notes!"
