### PR TITLE
fix(eslint-plugin): [no-shadow] report correctly on parameters of functions declared with the `declare` keyword

### LINKED ISSUE #10539: Bug: [no-shadow] inconsistent reports on function parameter names inside ambient declarations clashing with real variable declarations
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.6.3&fileType=.tsx&code=CYUwxgNghgTiAEkoGdnwMoHsC2IDC0qAjPAN4CwAUPIpgHbIAuMArmI5jABRj1OvtOABVhRsALnhQ6ATwCUAbio1kOEAFkQjABaZgXXDr0iYYydPlLq8Vbk1HgAdQCWOgKIAPAA4RnYVwBKWiwwdAAqMl4gBlq6wCZiAPrmsnKS-M50AOZWNAD0efAAUixMUvAAZiAA7vDYnAiMIEzIAHTtyjZq9nEAgmBgIF6MmVl4UBAQAEZQYADWPBPTs3OSMQ4JElKp8AC8AHzblp22IEIwmFEwjDJrsBfVAGIsdOzO9Jsp8nuHAG6YzmAVgAvlQKi83vRaAxmGwODBNlw5GR4KDKODXiMoYY4ojkaRUWCIVi6HVYsZRNhEkiUWiMZDSfdME9ie86HjaVQqAV4O1WhgxAhtFAvFE6KN4NVXNp4DoEGIps4QHRGJVWVDQEhTCTxFzKJroHA1Zi2V1cM8TfQuPSSZ8jml4P9AVYbabXR9KTSCcCrNzCnz4FMWKq6JhVVKdLLtPLsIrlarfrBnFAphAEAbRCT4FxEzA8mnGHleDD4CAPGIfM00nqM0bc2aQAA1JMptNrMBLGbzO0WZEHR0AoFEy2kjuTLtzDnehTwHm9CCqeCh0swC4wNDOCqO2D5rRFviq5xoUogYDwTJMEBQM-RuA18CGhAFhvNmDJ1MgAAyWnbnZWm2-Rgvj7P5BxddVRz-btKUAr1UV9fUH1gBBizKU5X3fNM8APX9x3-SlsJhYCfgHZ1hwZRAoMnAiDzgn09R5AA5TAVzXDctzlGxhWAZlTyXQVzzQAADXMhN1SgqFrFDCDQLBcAIFBkAAJjITpUNhQRuHUgR4U2JTgNyBsej0dZcUpfT7RBKh620uFhHMqx6xxClTGwJSEKk40KNOC0GWtCC9IdJ0h0oet3XZByGP9dp4E4eAhILMT7y1aTFIwNQFNQABmVTrFszSeAPHT7NcrKDJObpyX0Zz4kpMrLKoNFn3y3S6qsZ8as2LKPKQo1wobXySX8kcuqCsDrNgLzbTaqLeRiuKhPUpKJMQlLEBk9L5JkgAWXKaBazhCphYqEUpbbyusU5jOqqrNnOhrKDRdToX4OzTtc3bdmzEDaSsZ7OrOvZvpI6dksfKbTR8iDhoZO6xrI0LJvCu6rCAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1uQAsBDACYcA7uiiJo0DtEjgwAXxDygA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

The minimal reproduction is as follows:

```TypeScript

declare class SomeClass {
  someMethod(methodParam: any); // ❌ `'methodParam' is already declared in the upper scope`
}
function methodParam() { }
```

If, however, `function methodParam` is instead a `var`, `let` or `const` declaration, the ESLint error is not triggered.

Quite a few more examples of this strange behavior are in the playground link.

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-shadow": "error"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

The error should always be reported or not reported no matter with what type of declaration the name of the parameter inside an ambient declaration clashes.

I personally can't tell whether it's technically shadowing or not. Perhaps having an option to treat clashes between real and ambient declarations' names as shadowing issues could be the solution.

### Actual Result

The current behavior seems inconsistent to me.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by ronami**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10539
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR addresses #10539 and adjusts the rule to include the following ways of defining functions (and their parameters) behind the `ignoreFunctionTypeParameterNameValueShadow` flag: 

```ts
const arg1 = 0;
declare function test1(arg1: string): typeof arg1;

const arg2 = 0;
declare class Test3 {
  p2(arg2: string): typeof arg2;
}
```

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-shadow.ts [hunk 1]
```diff
@@ -564,6 +575,11 @@ export default createRule<Options, MessageIds>({
           continue;
         }
 
+        // ignore variables of function declarations or function/method overloads
+        if (isParameterOfTypeOnlyFunctionDeclaration(variable)) {
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-shadow.ts:579]: i'm wondering if these added checks should be part of `isFunctionTypeParameterNameValueShadow`, so that they're affected by the `ignoreFunctionTypeParameterNameValueShadow` option? I was playing with this playground link, and the inconsistencies are the same but inverted compared to the issue report: https://deploy-preview-10543--typescript-eslint.netlify.app/play/#ts=5.7.2&fileType=.ts&code=CYUwxgNghgTiAEkoGdnwMoHsC2IDC0qAjPAN4BQ8imAdsgC4wCuY9mMAFGLQ86%2BwAVYUbAC54UGgE8AlAG5K8ZDhABZEPQAWmYB1xadQmCPGTZCqstzqDwAOoBLLQFEAHgAcIDsE4BKGphgaABUpdxA9DW1gIxEAfVNpGXFeBxoAcwt4AHps%2BAApJgYJeAAzEAB3eGx2BHoQBmQAOhbFKzUonQBBMDAQd3o09LwoCAgAIygwAGsuUYmp6fFI21ixCST4AF4APg3zNpUBGExwmHopZdgTioAxJhpWB1o1xNltvYA3TAdgBQBfcilB5PWjUOiMFhsGBrDgyMjwQHAx6DMH6aKw%2BGkRFAkGomjVToxYTYOJwhFIvHPAnXTB3KkvEnk7GA8i5eAtJoYEQITRQdzhGhDeAVJyaeBaBAicYOEA0ehlBkE0BIYz40Tkcgq6BwRUo6lKFT3fW0DjI0E0V77ZLwb6-BTm-F6i2YikKNl5TnwcZMBU0TAK0VaCWaKXYGVyhWfWAOKDjCAIbXCJ0caMwbIJ%2BjZbgQ%2BAgVwiTwNZKapO6tOG3AANRjcYTyzA80mMytZnhu1tPz%2BuJNBMbY2b01dLLkOTyXQgyng-rzMBOMDQDlKttgGY02Z4CocaCKIGA8DSDBAUH3obgpfAOoQmcrIBrMFj8ZAABkNA2m4s1q-6G9218uw6SqIB%2BLYkt%2BzKIu6ZYIDmxTtPej4Jngm7vgOn4kshEK-h8nb2j2FrAWhoHGNgmEMBB-zuuyABymCzvOi7LpKSh8sAdJ7tOPIHmgAAGaY8RqWqXrAMGEGgWC4AQKDIAATGQiiwZC-CcIpfDQmsMm-lk7Q2NEKwYiSmnWgC5AVqpUKCIZCgVuihhWReqoII6BrtMaFpmkqGk2na3YVs5jIkTJVGei08DsPAPGZgJDlXogYkYCoUmoAAzPJVDmcpXCbmplkkclWmHNYRL6XZeUFYCN4ZepJLJQoN62cSeVQcJur%2BQSrlKh5vZrMl3kAaZsDOviPXBRyoXhTxinRUJjlxdJCWSWJAAsaXgrwFkqdlG1rEtBWWCouk6CVjUiLtxnkICilrUp1UkStWzwOSHYjuQV0NTt2yPX%2BboxSJQ0uUanVtTtfV4X5nkkktChAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaZACwEMATfAd3SnwDMHIAacbSAAQBcBPABxQBjaAEt%2B3Qinijc3APQFi5KrQwBtdtiiJo0fNFZbsWbR1EBzAtEQAxWLiHdR%2BXABUBiAAploZALaI3LoAcgGIAGpk8LCIAMoqNHQM0ciIxhAAvsYAuuzZmUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

Comment (ronami) [reply packages/eslint-plugin/src/rules/no-shadow.ts]: Oh, I've completely missed the mark on this 🙈 

I initially considered it a false positive and thought the parameter's value could never be referenced directly. Looking some more into it, and especially after reading https://github.com/typescript-eslint/typescript-eslint/issues/2447#issuecomment-684021953, I see it is possible, and a lot like other checks behind the `isFunctionTypeParameterNameValueShadow` option.

I've updated the PR to match this, thanks for catching this 👍

**Review by kirkwaiblinger — DISMISSED** [review]
Looks good! 🎉🎄

File: packages/eslint-plugin/src/rules/no-shadow.ts [hunk 2]
```diff
@@ -22,6 +22,8 @@ const allowedFunctionVariableDefTypes = new Set([
   AST_NODE_TYPES.TSCallSignatureDeclaration,
   AST_NODE_TYPES.TSFunctionType,
   AST_NODE_TYPES.TSMethodSignature,
+  AST_NODE_TYPES.TSEmptyBodyFunctionExpression,
+  AST_NODE_TYPES.TSDeclareFunction,
```
Comment (yeonjuan) [inline packages/eslint-plugin/src/rules/no-shadow.ts:26]: Hi @ronami IMO, `TSConstructSignatureDeclaration` should also be added, what do you think?

- [playground](https://deploy-preview-10543--typescript-eslint.netlify.app/play/#ts=5.7.2&fileType=.tsx&code=MYewdgzgLgBAhgJwOYwLwwAwG4BQOAmApsADaKEyiSwBiIIAXDAN44wwBm9TAFIkkzABXALYAjQggCUaAHwwAbiACW%2BXOzCEA7n2SDRE6UyWqsMAPTmYAcn7WYyiPBIJCcfAE8YRUuXwOwGCgACwohAAdwyRgIUCiYcBgSZU0YACZKEBJRQIB2ADocAF8sIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1uQAsBDACYcA7ujABtSImjQO0SAF1wYAL4gVQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)
```ts
// "ignoreFunctionTypeParameterNameValueShadow": true
const arg = 0;

declare const Foo: {
  foo: (arg: number) => void;
  new(arg: number): void; // 'arg' is already declared in the upper scope on line 2 column 7.
};
```

Comment (ronami) [reply packages/eslint-plugin/src/rules/no-shadow.ts:26]: Thank you @yeonjuan for catching this 👍

Comment (yeonjuan) [reply packages/eslint-plugin/src/rules/no-shadow.ts:26]: @ronami I edited the previous comment :) . I think we should add `TSConstructorType` also

Comment (ronami) [reply packages/eslint-plugin/src/rules/no-shadow.ts:26]: Oh, I just went over the list of nodes to make sure I didn't miss anything 🙈 

Thanks!

Comment (yeonjuan) [reply packages/eslint-plugin/src/rules/no-shadow.ts:26]: LGTM! Thanks! 👍

Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/no-shadow.ts:26]: Thanks @yeonjuan for the catch!

**Review by kirkwaiblinger — APPROVED** [review]

**Review by JoshuaKGoldberg — APPROVED** [review]
🆒
