### PR TITLE
fix(eslint-plugin): [no-unused-expressions] handle ternary and short-circuit options

### LINKED ISSUE #1764: [no-unused-expressions] no-unused-expressions works not as expected with optional chaining and condition
**Repro**

```JSON
{
  "rules": {
    "no-unused-expressions": 0,
    "@typescript-eslint/no-unused-expressions": [2, {
      "allowShortCircuit": true
    }]
  }
}
```

```TS
const expr: any = false;
const v: { [key: string]: any } = {};
v.somestaff?.callMe(); // Works fine 👍
expr && v.somestaff?.callMe(); // Problem 😭
```

**Expected Result**
No error for line

**Actual Result**
image

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.23.0` |
| `@typescript-eslint/parser`        | `2.23.0` |
| `TypeScript`                       | `3.7.5` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `11.15.0` |
| `npm`                              | `6.7.0` |

### PR DESCRIPTION
**Pull request by yeonjuan**
Fixes #1764 😁

### CODE REVIEW

File: packages/eslint-plugin/typings/eslint-rules.d.ts [hunk 1]
```diff
@@ -411,15 +411,13 @@ declare module 'eslint/lib/rules/no-unused-expressions' {
...
-          allowTaggedTemplates?: boolean;
-        }
-    )[],
+    [
+      {
+        allowShortCircuit?: boolean;
+        allowTernary?: boolean;
+        allowTaggedTemplates?: boolean;
+      }?,
+    ],
```
Comment (yeonjuan) [inline packages/eslint-plugin/typings/eslint-rules.d.ts:420]: I think it was wrong typed since there is no option "all", "local" in [eslint no-unused-expression](https://eslint.org/docs/rules/no-unused-expressions#options)

File: packages/eslint-plugin/src/rules/no-unused-expressions.ts [hunk 2]
```diff
@@ -18,17 +21,37 @@ export default util.createRule<Options, MessageIds>({
...
+      }
+      if (allowTernary && node.type === AST_NODE_TYPES.ConditionalExpression) {
+        return (
+          isValidExpression(node.alternate) &&
+          isValidExpression(node.consequent)
+        );
+      }
+      return (
+        node.type === AST_NODE_TYPES.OptionalCallExpression ||
+        node.type === AST_NODE_TYPES.ImportExpression
```
Comment (yeonjuan) [inline packages/eslint-plugin/src/rules/no-unused-expressions.ts:48]: ESLint support `ImportExpression` since v7.2.0.
But typescript-eslint seems support `"eslint": "^5.0.0 || ^6.0.0 || ^7.0.0". so I didn't remove it.
