### PR TITLE
fix(scope-manager): handle typeParameters of TSInstantiationExpression

### LINKED ISSUE #5317: Bug: [no-unused-vars] Generic passed to class reference during class property assignment not picked up as being used.
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.4&sourceType=module&code=MYGwhgzhAEBiD28A8AVAfNA3gKGtAbmCAK4CmAXNCtgL7baiQwBCYATqhjngGaLQBeOIk616AO1IB3aKzYAKAJTYgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tidmUQAmtAG4BDaKgwBtSImjQO0SAF1wYAL4h1QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
class Foo<T> {
  value: T
}

class Bar<T> {
  foo = Foo<T>
}

new Bar()
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-unused-vars": ["error"]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

To pick up that T in `foo = Foo<T>` is being used.

### Actual Result

`'T' is defined but never used. 5:11 - 5:12`

### Additional Info

The ability to modify function references with generics is a new feature in TS 4.7, so this is probably the reason the rule hasn't updated yet to support it.

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.30.5` |
| `@typescript-eslint/parser` | `5.30.5` |
| `TypeScript` | `4.7.4` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

### PR DESCRIPTION
**Pull request by Zzzen**
## PR Checklist

-   [x] Addresses an existing open issue: fixes #5317
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

ref: https://github.com/typescript-eslint/typescript-eslint/blob/3d552895af436ef0a983a34a9b708030c9b5ebc7/packages/scope-manager/src/referencer/Referencer.ts#L383-L386

### CODE REVIEW

File: packages/scope-manager/src/referencer/Referencer.ts [hunk 1]
```diff
@@ -692,6 +692,13 @@ class Referencer extends Visitor {
     this.close(node);
   }
 
+  protected TSInstantiationExpression(
+    node: TSESTree.TSInstantiationExpression,
+  ): void {
+    this.visitChildren(node, ['typeParameters']);
+    this.visitType(node.typeParameters);
```
Comment (armano2) [inline packages/scope-manager/src/referencer/Referencer.ts:699]: can you add test case for scope manger

File: packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts [hunk 2]
```diff
@@ -921,6 +921,17 @@ export declare namespace Foo {
     }
   }
 }
+    `,
+    `
+class Foo<T> {
```
Comment (armano2) [inline packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts:926]: this syntax is not supported by prettier yet, can you use `noFormat`?

Comment (Josh-Cena) [reply packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts:926]: @armano2 Upgrading Prettier to 2.7 should work.

**Review by armano2 — APPROVED** [review]
