### PR TITLE
fix(eslint-plugin): [no-misused-spread] correct and elaborate string spread report message

### LINKED ISSUE #10745: Bug: [no-misused-spread] report for string spread harmfully conflates Unicode code points with UTF-16 code units
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.6.3&fileType=.tsx&code=MYewdgzgLgBBMF4YCJBd4Ycw3Bvu4Gx1kG4AoA0SEAGwFMA6MkAcwAoApAZQHkA5K6AJwEswdPgDMAngwDaVaRAC6ASnmEA9MpgBhEDx4VgUAFwwJaZABpkWM8lyyCqmACEArrDAgAtAFs%2BEJxAoAJu4QAA46AIYBMKCeIWThAvBQABYUOqYw4WBRvnR0FNAQ%2BkQkEOTUtIysnNxQ-IIi4hDccXxQDMjIikp2agCSYKDaugZGJuYAOk4BABwAbADsVlMBAcJzVjYEQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oFtLlZkiACa1kxaIgCGQ9FETRoHaJHBgAviDVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const s = "螺𩷶屬";

console.log(JSON.stringify([...s]));
// Correct: ["螺","𩷶","屬"]
// But no-misused-spread complains there, and suggests:

console.log(JSON.stringify(s.split("")));
// Incorrect: ["螺","\ud867","\uddf6","屬"]
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-misused-spread": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

In JavaScript, string spreading is the correct way to split a string into Unicode code points. It should not be an error.

### Actual Result

``error  Using the spread operator on a string can cause unexpected behavior. Prefer `.split('')` instead.  @typescript-eslint-no-misused-spread``

But `.split('')` splits a string into UTF-16 code units, not Unicode code points. For characters outside the basic multilingual plane, this produces invalid unpaired surrogates.

### Additional Info

This rule was introduced with a justification linking to the blog post “[Strings Shouldn’t Be Iterable By Default](https://www.xanthir.com/b4wJ1)”. But this post is about how to design better languages in the future, not how to use the languages we already have.

In the JavaScript language we have, `[...s]` *is the correct way* to split a string into Unicode code points, and `.split('')` does not do that correctly. The suggestion is harmful and will result in the introduction of subtle internationalization bugs triggered with less common languages (and emoji).

There isn’t another good way to correctly split a string into Unicode code points, so this rule should just be disabled for strings.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10745
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Updates the report message for a string spread to bemoan _both_ `...` and `.split("")`.

💖

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-misused-spread.ts [hunk 1]
```diff
@@ -57,8 +57,13 @@ export default createRule<Options, MessageIds>({
...
       noPromiseSpreadInObject:
         'Using the spread operator on Promise in an object can cause unexpected behavior. Did you forget to await the promise?',
-      noStringSpread:
-        "Using the spread operator on a string can cause unexpected behavior. Prefer `.split('')` instead.",
+      noStringSpread: [
+        'Using the spread operator on a string can mishandle special characters, as can `split("")`.',
+        '- `...` produces Unicode code points, which will decompose complex emojis into individual emojis',
+        '- .split("") produces UTF-16 code units, which breaks rich characters in many languages',
+        "If this string does not need to preserve emojis or other non-English characters, disable this lint rule on this line or configure the 'allow' rule option.",
+        'Otherwise, consider using `Intl.Segmenter`.',
```
Comment (ArnaudBarre) [inline packages/eslint-plugin/src/rules/no-misused-spread.ts:65]: Nice,
I would prefer these last two lines to be flipped, saying ~
Consider using Intl.Segmenter to split on graphemes
Otherwise, if this string does not need ....

File: packages/eslint-plugin/src/rules/no-misused-spread.ts [hunk 2]
```diff
@@ -57,8 +57,13 @@ export default createRule<Options, MessageIds>({
...
+      ].join('\n'),
```
[the remark this answers is not in the document]
Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/no-misused-spread.ts:66]: +1. I think it makes sense to say "consider using Intl.Segmenter for robust, locale-aware string decomposition." first, and then "Otherwise, if you don't need to preserve emojis or other non-Ascii characters, disable, etc..."

File: packages/eslint-plugin/src/rules/no-misused-spread.ts [hunk 3]
```diff
@@ -57,8 +57,13 @@ export default createRule<Options, MessageIds>({
         'Using the spread operator on a Map in an object will result in an empty object. Did you mean to use `Object.fromEntries(map)` instead?',
       noPromiseSpreadInObject:
         'Using the spread operator on Promise in an object can cause unexpected behavior. Did you forget to await the promise?',
-      noStringSpread:
-        "Using the spread operator on a string can cause unexpected behavior. Prefer `.split('')` instead.",
+      noStringSpread: [
+        'Using the spread operator on a string can mishandle special characters, as can `split("")`.',
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-misused-spread.ts:61]:
```suggestion
        'Using the spread operator on a string can mishandle special characters, as can `.split("")`.',
```

**Comment by JoshuaKGoldberg** [comment]
🤦

**Review by kirkwaiblinger — APPROVED** [review]

**Review by kirkwaiblinger — APPROVED** [review]

**Review by ArnaudBarre — COMMENTED** [review]
🚀

**Comment by JoshuaKGoldberg** [comment]
I'd normally prefer to leave this open for a couple more days to get a full week (https://typescript-eslint.io/maintenance/pull-requests#approvals). But this is kind of a hot topic. Merging a couple days early.
