### PR TITLE
fix(typescript-estree): correct issues in AST definition

### LINKED ISSUE #2912: incorrect type - TryStatement's finalizer property can't be null
> Please don't ignore this template.

There doesn't seem to be a template for "@typescript-eslint/types".

**Checks**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Problem**

The `finalizer` property on the `TryStatement` node type can be `null` but the type says it can't be.

**Expected Type**

```ts
interface TryStatement extends BaseNode {
  // ...
  finalizer: BlockStatement | null;
}
```

**Actual Type**

```ts
interface TryStatement extends BaseNode {
  // ...
  finalizer: BlockStatement;
}
```

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/type`              | `4.11.1` |
| `TypeScript`                           | `4.1.3` |
| `node`                                 | `14.15.3` |

### PR DESCRIPTION
**Pull request by armano2**
Those changes has been extracted from #3078

fixes #2912

### `ProgramStatement` and `Statement` nodes can contain same set of nodes
```ts
if (x) export {x}
if (x) import test from 'x'
// -----
for (x in foo) {
  export {x}
}
// -----
function test (x: string) {
  export {x}
}
```

### `LeftHandSideExpression` can be a `AwaitExpression`
```ts
const a = ++(await x)
```

### `TryStatement` finalizer can be `null`
```ts
try {} catch {}
```

### `RegExpLiteral` value can be `null` if regexp is invalid or unsupported by env
good example in this case can be any proposal that has not been accepted yet 
eg. https://github.com/tc39/proposal-regexp-match-indices
```tsx
const x = /a+(?<Z>z)?/d
```

### `JSXOpeningElement` attributes can be a `JSXSpreadAttribute`
```ts
const foo = <x {...spread}></x>
```

### `TSModuleDeclaration` body can be `TSModuleDeclaration`
```ts
// TSModuleDeclaration without body
module "x";
// TSModuleDeclaration -> TSModuleBlock
module x {
}
// TSModuleDeclaration -> TSModuleDeclaration **
module x.x {
}
```

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unused-vars.ts [hunk 1]
```diff
@@ -408,10 +408,12 @@ export default util.createRule<Options, MessageIds>({
         return cached;
       }
 
-      for (const statement of node.body?.body ?? []) {
-        if (statement.type === AST_NODE_TYPES.TSExportAssignment) {
-          MODULE_DECL_CACHE.set(node, true);
-          return true;
+      if (node.body && node.body.type !== AST_NODE_TYPES.TSModuleDeclaration) {
```
Comment (armano2) [inline packages/eslint-plugin/src/rules/no-unused-vars.ts:411]: in this context body will never be a `TSModuleDeclaration` because path selector excludes it

File: packages/types/src/ts-estree.ts [hunk 2]
```diff
@@ -464,20 +462,8 @@ export type PrimaryExpression =
...
-  | ImportDeclaration
-  | Statement
-  | TSDeclareFunction
-  | TSEnumDeclaration
-  | TSExportAssignment
-  | TSImportEqualsDeclaration
-  | TSInterfaceDeclaration
-  | TSNamespaceExportDeclaration
-  | TSTypeAliasDeclaration;
+/** @deprecated TODO: delete this in next major release */
```
Comment (bradzacher) [inline packages/types/src/ts-estree.ts:465]: in the next major we should be seeking to re-align this with EStree spec, not deleting this type.

Comment (armano2) [reply packages/types/src/ts-estree.ts:465]: updated

File: packages/types/src/ts-estree.ts [hunk 3]
```diff
@@ -1496,13 +1493,13 @@ export interface TSMethodSignatureNonComputedName
...
   type: AST_NODE_TYPES.TSModuleBlock;
-  body: ProgramStatement[];
+  body: Statement[];
 }
 
 export interface TSModuleDeclaration extends BaseNode {
   type: AST_NODE_TYPES.TSModuleDeclaration;
   id: Identifier | Literal;
-  body?: TSModuleBlock;
+  body?: TSModuleBlock | TSModuleDeclaration;
```
Comment (bradzacher) [inline packages/types/src/ts-estree.ts:1502]: we really need to fix this - https://github.com/typescript-eslint/typescript-eslint/issues/2573

**Review by bradzacher — APPROVED** [review]

File: packages/types/src/ts-estree.ts (hunk 3 above)
Comment (armano2) [reply packages/types/src/ts-estree.ts:1502]: yes we should, but we should do that in separate PR

Comment (armano2) [reply packages/types/src/ts-estree.ts:1502]: if you look into no-unused-vars i had to add type guard against `TSModuleDeclaration`
