### PR TITLE
fix: use parser options from context.languageOptions

### LINKED ISSUE #11952: Enhancement: support eslint v10
### Before You File a Proposal Please Confirm You Have Done The Following...

- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [x] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

all tseslint packages.

### My proposal is suitable for this project

- [x] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

As of now, it supports eslint `^8.57.0 || ^9.0.0`.
ESLint v10 will be released in the coming weeks (currently in RC), so it seems like the right time to start considering support for it.

### Additional Info

related: 
* https://github.com/typescript-eslint/typescript-eslint/issues/11762
* https://eslint.org/docs/next/use/migrate-to-10.0.0

### PR DESCRIPTION
**Pull request by DMartens**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11952
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
Use `context.languageOptions.parserOptions` instead of `context.parserOptions` as the property was [moved](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context-properties%3A-parseroptions-and-parserpath-being-removed) and removed in ESLint v10.
This plugin allows the lowest version 8.57.0 which should already have `context.languageOptions.parserOptions`.
The issue does not yet have the label "accepting PRs" but the blocking PR mentioned in the [comment](https://github.com/typescript-eslint/typescript-eslint/issues/11952#issuecomment-3735510311) was already merged, so I hope this PR is okay.

### CODE REVIEW

**Comment by michaelfaith** [comment]
Looks like the properties just need sorting, and this should be green 🚀 

screenshot of build errors

**Comment by JoshuaKGoldberg** [comment]
```plaintext
Download action repository 'pnpm/action-setup@v4' (SHA:41ff72655975bd51cab0327fa583b6e92b6d3061)
Warning: Failed to download action 'https://api.github.com/repos/pnpm/action-setup/zipball/41ff72655975bd51cab0327fa583b6e92b6d3061'. Error: Response status code does not indicate success: 429 (Too Many Requests). 1C00:5E8CC:B36FCF:2F9AAFF:698A39B1
Warning: Back off 10.404 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/pnpm/action-setup/zipball/41ff72655975bd51cab0327fa583b6e92b6d3061'. Error: Response status code does not indicate success: 429 (Too Many Requests). 1C00:5E8CC:B3B935:2FAE503:698A39BB
Warning: Back off 16.231 seconds before retry.
Error: Response status code does not indicate success: 429 (Too Many Requests).
```

...huh. Those don't look related.

**Comment by michaelfaith** [comment]
I think this happened to run when GH was mid-incident yesterday

File: packages/utils/src/ts-eslint/Rule.ts
Comment (JoshuaKGoldberg) [inline packages/utils/src/ts-eslint/Rule.ts:1]: [Feature] We'll also need to mark `parserOptions` and `parserPath` as `@deprecated`. I'll go ahead and do that now.

**Comment by JoshuaKGoldberg** [comment]
😩 GitHub...

GitHub Actions CI status preview on this PR showing 10 in-progress, with all started 43 or 46 minutes ago

File: packages/rule-tester/src/RuleTester.ts [hunk 1]
```diff
@@ -432,6 +432,7 @@ export class RuleTester extends TestFramework {
       create(context): RuleListener {
         freezeDeeply(context.options);
         freezeDeeply(context.settings);
+        // eslint-disable-next-line @typescript-eslint/no-deprecated -- For compatibility with ESLint 8
```
Comment (robertIsaac) [inline packages/rule-tester/src/RuleTester.ts:435]: I'd suggest to drop support for eslint 8
keeping two major version support should be fine

Comment (robertIsaac) [reply packages/rule-tester/src/RuleTester.ts:435]: and eslint 8 has already reached eof

File: packages/utils/src/ts-eslint/Rule.ts [hunk 2]
```diff
@@ -274,18 +274,22 @@ export interface RuleContext<
   /**
    * The language options configured for this run
    */
-  languageOptions: FlatConfig.LanguageOptions;
+  languageOptions: FlatConfig.LanguageOptions & {
```
Comment (jnoordsij) [inline packages/utils/src/ts-eslint/Rule.ts:277]: I've not had the time to dive in to this too deeply, but I wonder if

A. ESLint v8 is indeed fully compatible (as https://eslint.org/docs/v8.x/extend/custom-rules#the-context-object seems to imply) in always providing this, then should this be tweaked to also include more of the properties that should never be `undefined` here? (can also be done later of course for the purpose of quick merging). 

B. ESLint v8 does not fully support this, should this just be left as is for now and a fix like https://github.com/eslint/eslint/issues/16559#issuecomment-2173748454 be tried?

File: packages/eslint-plugin/src/rules/consistent-generic-constructors.ts [hunk 3]
```diff
@@ -152,7 +152,8 @@ export default createRule<Options, MessageIds>({
           return;
         }
 
-        const isolatedDeclarations = context.parserOptions.isolatedDeclarations;
+        const isolatedDeclarations =
+          context.languageOptions.parserOptions.isolatedDeclarations;
```
Comment (jnoordsij) [inline packages/eslint-plugin/src/rules/consistent-generic-constructors.ts:156]: Nitpick: maybe it would be neater to stylistically match the other usage of this.
```suggestion
        const { isolatedDeclarations } = context.languageOptions.parserOptions;
```

File: packages/rule-tester/src/RuleTester.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/rule-tester/src/RuleTester.ts:435]: That'd be a breaking change that requires a new major version of typescript-eslint, which we're not prepared to do soon.

File: packages/utils/src/ts-eslint/Rule.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply packages/utils/src/ts-eslint/Rule.ts:277]: Yeah, the types story is kind of weird and tricky. Supporting _three_ major versions of ESLint means there's no way one type "snapshot" like this will be correct. I think long-term it'd be nice to really try to make a more intelligent / tailored-to-the-resolved-ESLint-version types setup.

File: packages/rule-tester/src/RuleTester.ts (hunk 1 above)
Comment (robertIsaac) [reply packages/rule-tester/src/RuleTester.ts:435]: is there a  roadmap for what's coming next in typescript-eslint?

Comment (bradzacher) [reply packages/rule-tester/src/RuleTester.ts:435]: we're also not going to drop support for ESLint v8 when a large percentage of the userbase still uses v8.

| Major | Weekly DL # | User % |
| ----- | ----------- | ------ |
| 8 | 32,553,840 | 38.97% |
| 9 | 41,958,296 | 50.23% |
| 10 | 1,144,768 | 1.37% |

Whether or not it's EOL'd -- a huge proportion of people are still using it.

Comment (robertIsaac) [reply packages/rule-tester/src/RuleTester.ts:435]: they can still use the older version of typescript-eslint
