### PR TITLE
fix(eslint-plugin): [return-await] sync the behavior with await-thenable

### LINKED ISSUE #9903: Bug: [return-await] Gives false positive with unknown values
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

[link](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=IYZwngdgxgBAZgV2gFwJYHsI2QUxMgCiQGsJ0B3CABWACdgBbALhhLMoEoYBvAKBmy0wPfgJi0cyBLSzBywVMlYRSFanUYBuUQF94qCMAA2R4XzEwomEOiM4AdEfQBzAgHIAkljgHjpmABGTlDEbhy6vDpAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6aRfWaJ2gQwDufSvnRRE0aAHtokcGAC%2BIBUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

### Repro Code

```TypeScript
async function test(unknownParam: unknown) {
  try {
    return await unknownParam;
  } finally {
    console.log('In finally block')
  }
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/return-await": "error",
  },
};
```

### Expected Result

Since `unknownParam` could be a Promise (we don't know), the correct code is `return await unknownParam`, so that the `finally` block will execute after the promise completes, not before.

### Actual Result

The rule does not allow that, and forces you to write incorrect code.

### PR DESCRIPTION
**Pull request by mdm317**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9903
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

sync the behavior with await-thenable.
If the type is any or unknown, we don't determine whether to add await or not.

I moved the below error test case to a valid test case.
```ts
const fn = (): unknown => null;
async function test() {
  return await fn();
}
const fn = (): any => null;
async function test() {
  return await fn();
}
```
And add valid test case 
```ts
async function test(unknownParam: unknown) {
  try {
    return await unknownParam;
  } finally {
    console.log('In finally block');
  }
}
```

### CODE REVIEW

File: packages/eslint-plugin/src/rules/return-await.ts [hunk 1]
```diff
@@ -307,13 +307,14 @@ export default createRule({
...
+            return;
+          }
           context.report({
             messageId: 'nonPromiseAwait',
             node,
-            ...fixOrSuggest(useAutoFix, {
+            ...fixOrSuggest(true, {
               messageId: 'nonPromiseAwait',
               fix: fixer => removeAwait(fixer, node),
             }),
```
Comment (auvred) [inline packages/eslint-plugin/src/rules/return-await.ts:320]: [Refactor] Since we don't report suggestions anymore, we don't need to use `fixOrSuggest` here. How about replacing the whole `...fixOrSuggest(...)` call with just `fix: fixer => removeAwait(fixer, node),`?

**Review by auvred — CHANGES_REQUESTED** [review]

File: packages/eslint-plugin/src/rules/return-await.ts (hunk 1 above)
Comment (mdm317) [reply packages/eslint-plugin/src/rules/return-await.ts]: Thanks for reviewing it, and i fixed this code the way you showed me.

File: packages/eslint-plugin/src/rules/return-await.ts [hunk 2]
```diff
@@ -307,16 +307,14 @@ export default createRule({
 
       if (!isThenable) {
         if (isAwait) {
-          // any/unknown could be thenable; do not auto-fix
-          const useAutoFix = !(isTypeAnyType(type) || isTypeUnknownType(type));
-
+          // sync behavior with return-await
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/return-await.ts:310]:
```suggestion
          // any/unknown could be thenable; do not enforce whether they are `await`ed.
```

**Comment by kirkwaiblinger** [comment]
Looking at this closer, I'm wondering whether we should enforce that `any` and `unknown` _must_ be awaited in an error-handling context, instead of ignoring them 🤔 Can't make up my mind.

**Review by kirkwaiblinger — APPROVED** [review]
Looks good to me!

**Review by JoshuaKGoldberg — APPROVED** [review]
🆒
