### PR TITLE
fix(eslint-plugin): check optional chaining for floating promises

### LINKED ISSUE #4095: [no-floating-promises] optionally called function that return a promise is not flagged
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-floating-promises": ["error"]
  }
}
```

```TS
const doSomething = async (callback?: () => Promise<void>): Promise<void> => {
  callback?.();
};

doSomething();
```

```JSON
{
  "compilerOptions": {
    "target": "ES2021",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "lib": ["ES2021"],
    "rootDir": "./",
    "allowJs": true,
    "checkJs": true,
    "noEmit": true,
    "strict": true,
    "resolveJsonModule": true,
    "useDefineForClassFields": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noEmitOnError": true,
    "removeComments": false,
    "esModuleInterop": true
  },
  "exclude": ["coverage", "node_modules", "lib"],
  "files": [".eslintrc.js"],
  "include": ["**/*.js", "**/*.ts"]
}
```

**Expected Result**

That both lines 2 and 5 are flagged.

**Actual Result**

Only line 5 is flagged.

**Additional Info**

This looks to be the opposite of how `@typescript-eslint/await-thenable` behaves, which lets me `await` line 2 even though the type is `Promise<void> | undefined`.

~I'm happy to attempt a PR for this.~ I'm implemented a fix for this :)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.3.0` |
| `@typescript-eslint/parser`        | `5.3.0` |
| `TypeScript`                       | `4.4.4` |
| `ESLint`                           | `7.32.0` |
| `node`                             | `16.0.0` |

### PR DESCRIPTION
**Pull request by G-Rath**
## PR Checklist

-   [x] Addresses an existing issue: fixes #4095
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/master/CONTRIBUTING.md) were taken

## Overview

Changes `no-floating-promises` to "expand" optional chain so that it's expression is checked.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-floating-promises.ts [hunk 1]
```diff
@@ -65,7 +65,13 @@ export default util.createRule<Options, MessageId>({
           return;
         }
 
-        if (isUnhandledPromise(checker, node.expression)) {
+        let expression = node.expression;
+
+        if (expression.type === AST_NODE_TYPES.ChainExpression) {
+          expression = expression.expression;
+        }
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-floating-promises.ts:72]: Nit: this is similar to `skipChainExpression` from `padding-line-between-statements`. You might consider making a util for it? I imagine this situation is one that will keep coming up.

Not a blocker, just a thought!

**Review by JoshuaKGoldberg — APPROVED** [review]
🔥
