### PR TITLE
fix(eslint-plugin): [prefer-nullish-coalescing] fix parenthesization bug in suggestion

### LINKED ISSUE #11097: Bug: @typescript-eslint/prefer-nullish-coalescing mal-fixes nested condition
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.7.2&showAST=types&fileType=.tsx&code=DYUwLgBAhgXBDOYBOBLAdgcwgHwgVzQBMQAzdEQgKFEgCM4BvCAWxHnigxDkVUwgC%2BOfEVLkqAYwD2aRBEgBeCAAowPZOgwBKCAoB88ypWmzIJKVN3RKEW3YD81u3bi0bzhxFoA6Vu04g7h4QcGDKAEQYwFK0UMDeIEhIUkjeBADWaFIA7mjhWpRAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WlqYSNkAC1pkA9gEMkyMswDm6KL2jjokcGAC%2BILUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
let a: string | undefined
let b: { message: string } | undefined
const t = (t: string) => t

const foo = a
      ? a
      : b
        ? b.message
        : t("global.error.unknown")

```

The error happens when running the `Fix` on this rule: It breaks the code.

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/prefer-nullish-coalescing": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

```ts
let a: string | undefined
let b: { message: string } | undefined
const t = (t: string) => t

const foo = a ?? (b
        ? b.message
        : t("global.error.unknown"))

```

### Actual Result

```ts
let a: string | undefined
let b: { message: string } | undefined
const t = (t: string) => t

const foo = a ?? b
        ? b.message
        : t("global.error.unknown")
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by mdm317**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11097
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
When running the `Fix`, add parentheses to conditional expressions that are missing them

### CODE REVIEW

**Comment by OlivierZal** [comment]
Looks good!

File: packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts [hunk 1]
```diff
@@ -932,3 +934,17 @@ function formatComments(
     )
     .join('');
 }
+
+function getTextWithEnsuredParentheses(
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts:938]: I wonder if we can leverage existing infrastructure around parenthesization/wrapping rather than hard-code a special case for `a ? b : c`... is there a specific reason to do that? I worry we might miss parens on other expressions that might need it?

FWIW I had success passing all the test cases with the following...

```ts
          context.report({
            node,
            messageId: 'preferNullishOverTernary',
            // TODO: also account for = in the ternary clause
            data: { equals: '' },
            suggest: [
              {
                messageId: 'suggestNullish',
                data: { equals: '' },
                fix(fixer: TSESLint.RuleFixer): TSESLint.RuleFix {
                  return fixer.replaceText(
                    node,
                    `${getTextWithParentheses(
                      context.sourceCode,
                      nullishCoalescingParams.nullishCoalescingLeftNode,
                    )} ?? ${(() => {
                      const branch = getBranchNodes(
                        node,
                        operator,
                      ).nullishBranch;
                      if (isParenthesized(branch, context.sourceCode)) {
                        return getTextWithParentheses(
                          context.sourceCode,
                          branch,
                        );
                      }
                      return getWrappedCode(
                        getTextWithParentheses(context.sourceCode, branch),
                        getOperatorPrecedenceForNode(
                          getBranchNodes(node, operator).nullishBranch,
                        ),
                        OperatorPrecedence.Coalesce,
                      );
                    })()}`,
                  );
                },
              },
            ],
          });
```

Curious what you think!

**Review by kirkwaiblinger — COMMENTED** [review]
Looks like it will solve the specific bug case but just have a question about being generic and/or reusing code. Thanks for sending!

**Review by kirkwaiblinger — APPROVED** [review]
Thanks for sending this in!

**Review by JoshuaKGoldberg — APPROVED** [review]
Super!

Great review suggestion too Kirk :)
