### PR TITLE
fix(eslint-plugin): properly coerce all types to string in `getStaticMemberAccessValue`

### LINKED ISSUE #9999: Bug: [prefer-promise-reject-errors (and other rules too)] Cannot convert Symbol to string (8.6.0 regression)
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=KYDwDg9gTgLgBAYwDYEMDOa4FkVgErADmAlmjFAJ4A8A0gDRwAqAfHAN4BQccYArgEZJiCOMRjAAtpgC8cAHbAA7tly0GLABQBKANxceAoSIDaAZQoT%2BEJADoxwKChjQAutvb7uUYDF5Q5cDAAFqR24lJmFla29o7OUG66%2BgC%2BHKlAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0Wlo4D2AW0rJEtTgCtEZOr2gDoqDJHmLI4MAF8QWoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
export class MapRegistry<K, T> {
  public items = new Map<K, T>();
  public [Symbol.iterator]() {
    return this.items[Symbol.iterator]();
  }
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/prefer-promise-reject-errors": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

lint should pass

### Actual Result

`TypeError: Cannot convert a Symbol value to a string`

### Additional Info

8.5.0 works fine

### PR DESCRIPTION
**Pull request by abrahamguo**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9999 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

#9836 had some bugs with how various data types are coerced to strings when used in a computed `MemberAccess`; this PR fixes those bugs.

### CODE REVIEW

File: packages/eslint-plugin/src/util/misc.ts [hunk 1]
```diff
@@ -242,20 +242,18 @@ type NodeWithKey =
...
   if (!node.computed) {
     return key.type === AST_NODE_TYPES.Literal
       ? `${key.value}`
       : (key as TSESTree.Identifier | TSESTree.PrivateIdentifier).name;
   }
-  const value = getStaticValue(key, sourceCode.getScope(node))?.value as
-    | string
-    | number
-    | null
-    | undefined;
```
Comment (abrahamguo) [inline packages/eslint-plugin/src/util/misc.ts:257]: this type assertion was not correct. `getStaticValue` can return _anything_ — `symbol`, `bigint`, `array`, `Date`, etc.

File: packages/eslint-plugin/tests/rules/prefer-promise-reject-errors.test.ts [hunk 2]
```diff
@@ -266,6 +266,7 @@ ruleTester.run('prefer-promise-reject-errors', rule, {
       declare const foo: PromiseConstructor;
       foo.reject(new Error());
     `,
+    'console[Symbol.iterator]();',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/prefer-promise-reject-errors.test.ts:269]: [Testing] This is just a bit different from the `public [Symbol.iterator]() { ... }` from #9999. Could you include that too, please?

File: packages/eslint-plugin/src/util/misc.ts [hunk 3]
```diff
@@ -242,20 +242,19 @@ type NodeWithKey =
...
-): string | undefined {
+): string | null {
   const key =
     node.type === AST_NODE_TYPES.MemberExpression ? node.property : node.key;
   if (!node.computed) {
     return key.type === AST_NODE_TYPES.Literal
       ? `${key.value}`
       : (key as TSESTree.Identifier | TSESTree.PrivateIdentifier).name;
   }
-  const value = getStaticValue(key, sourceCode.getScope(node))?.value as
```
Comment (abrahamguo) [inline packages/eslint-plugin/src/util/misc.ts:253]: using optional chaining was not correct. we need to distinguish between a return value of `null`, which means "no static value", versus a return value of `{ value: null }`, which means "access the property called `'null'`.

**Review by JoshuaKGoldberg — DISMISSED** [review]
> [abrahamguo](https://github.com/abrahamguo) commented [5 hours ago](https://github.com/typescript-eslint/typescript-eslint/issues/9999#issuecomment-2353986652):
>
> ... I will plan on opening a PR with the fix in the next 12 hours  ...

You work fast! 😄

...and, thanks for this! We can ship a quick patch release to get this to users.

File: packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts [hunk 4]
```diff
@@ -416,7 +417,7 @@ export class Test {
       `,
       options: [
         {
-          allowedNames: ['prop', 'method', 'foo'],
+          allowedNames: ['prop', 'method', 'null', 'foo'],
```
Comment (abrahamguo) [inline packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts:420]: note that adding `'Symbol(a)'` to `allowedNames` allows both
`'Symbol(a)'() {}`
and
`[Symbol('a')]() {}`

Not sure if this is a feature or a bug, or if it's worth documenting? 🤷‍♂️

File: packages/eslint-plugin/tests/rules/prefer-promise-reject-errors.test.ts (hunk 2 above)
Comment (abrahamguo) [reply packages/eslint-plugin/tests/rules/prefer-promise-reject-errors.test.ts:269]: > You work fast! 😄

Under promise, over deliver, etc etc 😉 

Additional test added!

File: packages/eslint-plugin/src/util/misc.ts [hunk 5]
```diff
@@ -242,20 +242,19 @@ type NodeWithKey =
...
-    | string
-    | number
-    | null
-    | undefined;
-  return value == null ? undefined : `${value}`;
```
Comment (abrahamguo) [inline packages/eslint-plugin/src/util/misc.ts:258]: seems to be
- a strange inconsistency of JavaScript that `` `${Symbol('a')}` `` throws while `String(Symbol('a'))` and `Symbol('a').toString()` work fine
- a minor type hole in TypeScript that `tsc` _does_ warn for interpolating a `Symbol`, but does _not_ warn for interpolating an `unknown`

**Comment by abrahamguo** [comment]
Lint failed due to CI flake.

File: packages/eslint-plugin/src/util/misc.ts [hunk 6]
```diff
@@ -242,20 +242,19 @@ type NodeWithKey =
...
+  const result = getStaticValue(key, sourceCode.getScope(node));
+  /* If a value is returned, coerce it to a string, because that's what JavaScript does with any data type in a
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/util/misc.ts:254]: Well, JS doesn't do this with symbols, though (which is kind of the whole point of symbols). Symbols are keys unto themselves. So, I wouldn't think it would make sense to stringify symbols ever (their string representation is only a debugging tool). Shouldn't we just return the symbol itself?

Comment (abrahamguo) [reply packages/eslint-plugin/src/util/misc.ts:254]: Yes, I agree that is more correct. The only downside is that Symbol-based methods will not be able to be allow-listed using things like `explicit-module-boundary-types` => `allowedNames` or `class-methods-use-this` => `exceptMethods`.

File: packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts (hunk 4 above)
Comment (abrahamguo) [reply packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts:420]: This is no longer true with the latest change requested by @kirkwaiblinger.

File: packages/eslint-plugin/src/util/misc.ts [hunk 7]
```diff
@@ -242,20 +242,25 @@ type NodeWithKey =
...
   node: NodeWithKey,
   { sourceCode }: RuleContext<string, unknown[]>,
-): string | undefined {
+): string | symbol | undefined {
   const key =
     node.type === AST_NODE_TYPES.MemberExpression ? node.property : node.key;
   if (!node.computed) {
     return key.type === AST_NODE_TYPES.Literal
       ? `${key.value}`
       : (key as TSESTree.Identifier | TSESTree.PrivateIdentifier).name;
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/util/misc.ts:251]: This type assertion isn't necessary if the `key` is checked within the condition, i.e.
```suggestion
  if (!node.computed) {
    const key =
      node.type === AST_NODE_TYPES.MemberExpression ? node.property : node.key;
    return key.type === AST_NODE_TYPES.Literal
      ? `${key.value}`
      : key.name;
```

Taking this suggestion literally will incur duplication, though, since `key` is used in the else branch too. Is there a way to make this nice?

Granted another type assertion in this very function was part of what burned us on this bug, it would be nice to avoid this one too.

File: packages/eslint-plugin/src/util/misc.ts [hunk 8]
```diff
@@ -242,20 +242,25 @@ type NodeWithKey =
 function getStaticMemberAccessValue(
   node: NodeWithKey,
   { sourceCode }: RuleContext<string, unknown[]>,
-): string | undefined {
+): string | symbol | undefined {
   const key =
     node.type === AST_NODE_TYPES.MemberExpression ? node.property : node.key;
   if (!node.computed) {
     return key.type === AST_NODE_TYPES.Literal
       ? `${key.value}`
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/util/misc.ts:250]:
```suggestion
      ? String(key.value)
```

File: packages/eslint-plugin/src/util/isArrayMethodCallWithPredicate.ts [hunk 9]
```diff
@@ -30,7 +30,10 @@ export function isArrayMethodCallWithPredicate(
 
   const staticAccessValue = getStaticMemberAccessValue(node.callee, context);
 
-  if (!staticAccessValue || !ARRAY_PREDICATE_FUNCTIONS.has(staticAccessValue)) {
+  if (
+    typeof staticAccessValue !== 'string' ||
+    !ARRAY_PREDICATE_FUNCTIONS.has(staticAccessValue)
+  ) {
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/util/isArrayMethodCallWithPredicate.ts:36]: (nit) I think applying DeMorgan on these makes the intention much more clear, but up to you! 🙂 
```suggestion
  if (
    !(typeof staticAccessValue === 'string' &&
       ARRAY_PREDICATE_FUNCTIONS.has(staticAccessValue)
    )
  ) {
```

File: packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts (hunk 4 above)
Comment (kirkwaiblinger) [reply packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts:420]: Since `Symbol('a')` is always a unique value, I don't think that it would make sense for the `allowedNames` to be able to specify it in this way.

Whether `Symbol.for('a')` should have a way of specifying it.... 🤷‍♂️. That could be sorted out in a feature request. In any case, I think it would belong in the rule logic and/or specifier logic to stringify the symbol, rather than in the static member access utility.

**Review by kirkwaiblinger — CHANGES_REQUESTED** [review]
Some syntax changes requested, but I think the logic is good

File: packages/eslint-plugin/src/util/isArrayMethodCallWithPredicate.ts (hunk 9 above)
Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/util/isArrayMethodCallWithPredicate.ts:36]: (side note) - I _really_ wish that `Set#has` were typed to allow `unknown` rather than the type of the set . Having to narrow the type to the set is often counterproductive. 

I personally actually really wouldn't mind doing
```suggestion
  if (
    ARRAY_PREDICATE_FUNCTIONS.has(staticAccessValue as any)
  ) {
```
but i have a feeling that might not be so popular

File: packages/eslint-plugin/src/util/misc.ts [hunk 10]
```diff
@@ -242,20 +242,25 @@ type NodeWithKey =
...
+  if (!result) {
+    return;
+  }
+  const { value } = result;
+  return typeof value === 'symbol'
+    ? value
+    : /* intentional interpolation of an `unknown` value, because any non-Symbol value is coerced to a string by
+         JavaScript when in a `MemberAccess`. */
+      // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
+      `${value}`;
```
[the remark this answers is not in the document]
Comment (abrahamguo) [reply packages/eslint-plugin/src/util/misc.ts:269]: We should really be checking `String(...)` with `restrict-template-expressions`, meaning that this will come back 😛

File: packages/eslint-plugin/src/util/isArrayMethodCallWithPredicate.ts (hunk 9 above)
Comment (abrahamguo) [reply packages/eslint-plugin/src/util/isArrayMethodCallWithPredicate.ts:36]: I 200% agree with you about the type of `Set#has` (and `Array#includes`) haha...
https://github.com/mattpocock/ts-reset

File: packages/eslint-plugin/src/util/misc.ts [hunk 11]
```diff
@@ -239,36 +239,42 @@ type NodeWithKey =
   | TSESTree.PropertyDefinition
   | TSESTree.TSAbstractMethodDefinition
   | TSESTree.TSAbstractPropertyDefinition;
+
+/**
+ * Gets the key being accessed or declared, such as `value` in
+ * `x.value`, `x['value']`,
+ * or even `const v = 'value'; x[v]` (or optional variants thereof).
+ */
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/util/misc.ts:247]:
```suggestion
/**
 * Gets a member being accessed or declared if its value can be statically, and
 * resolves it to the string or symbol value that will be used as the actual member
 * access key at runtime. Otherwise, returns `undefined`.
 *
 * ```ts
 * x.member // returns 'member'
 * ^^^^^^^^
 * 
 * x?.member // returns 'member' (optional chaining is treated the same)
 * ^^^^^^^^^
 *
 * x['value'] // returns 'value'
 * ^^^^^^^^^^
 *
 * x[Math.random()] // returns undefined (not a static value)
 * ^^^^^^^^^^^^^^^^
 *
 * arr[0] // returns '0' (NOT 0)
 * ^^^^^^
 *
 * arr[0n] // returns '0' (NOT 0n)
 * ^^^^^^^
 *
 * const s = Symbol.for('symbolName')
 * x[s] // returns `Symbol.for('symbolName')` (since it's a static/global symbol)
 * ^^^^
 *
 * const us = Symbol.('symbolName')
 * x[us] // returns undefined (since it's a unique symbol, so not statically analyzable)
 * ^^^^^
 *
 * var object = {
 *     1234: '4567', // returns '1234' (NOT 1234)
 *     ^^^^^^^^^^^^
 *     method() { } // returns 'method'
 *     ^^^^^^^^^^^^
 * }
 *
 * class WithMembers {
 *     foo: string // returns 'foo'
 *     ^^^^^^^^^^^
 * }
 * ```
 */
```

File: packages/eslint-plugin/src/util/misc.ts (hunk 7 above)
Comment (abrahamguo) [reply packages/eslint-plugin/src/util/misc.ts]: Totally agree! Refactored ✅

File: packages/eslint-plugin/src/util/misc.ts [hunk 12]
```diff
@@ -241,20 +241,66 @@ type NodeWithKey =
...
   { sourceCode }: RuleContext<string, unknown[]>,
 ): string | symbol | undefined {
   const key =
     node.type === AST_NODE_TYPES.MemberExpression ? node.property : node.key;
-  if (!node.computed) {
-    return key.type === AST_NODE_TYPES.Literal
-      ? String(key.value)
-      : (key as TSESTree.Identifier | TSESTree.PrivateIdentifier).name;
+  const { type } = key;
+  if (type === AST_NODE_TYPES.Literal) {
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/util/misc.ts:295]: (question, no specific action/resolution implied) is this conditional necessary? Or will it just be caught by the `getStaticValue`?

**Review by kirkwaiblinger — APPROVED** [review]
I think this looks good! Thanks!

File: packages/eslint-plugin/src/util/misc.ts (hunk 12 above)
Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/util/misc.ts:295]: checked locally and all the tests pass if I comment it out 🤷

Comment (abrahamguo) [reply packages/eslint-plugin/src/util/misc.ts]: good catch, removed!

**Review by kirkwaiblinger — APPROVED** [review]

**Review by Josh-Cena — APPROVED** [review]
