### PR TITLE
fix(eslint-plugin): do not use .at(), Node 14 does not support it

### LINKED ISSUE #6396: Bug: [key-spacing] Crashes on Node 14
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

This is a ~~critical~~ issue with the 5.50.0 release, which is _not entirely compatible_ with node v14.x.

```TypeError: node.parameters.at is not a function```

`Array.at()` usage has been introduced here:
https://github.com/typescript-eslint/typescript-eslint/blob/99c091e0e3cf38a28aa5e1d1d2b03b602d51aa0a/packages/eslint-plugin/src/rules/key-spacing.ts#L105
This does not exist on node v14, and no polyfill has been provided in the released package.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.50.0` |
| `ESlint`                                 | `8.33.0` |
| `node`                                 | `14.21.2` |

### PR DESCRIPTION
**Pull request by coyotte508**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6396
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/eslint-plugin/src/rules/key-spacing.ts [hunk 1]
```diff
@@ -14,6 +14,16 @@ const baseSchema = Array.isArray(baseRule.meta.schema)
   ? baseRule.meta.schema[0]
   : baseRule.meta.schema;
 
+/**
+ * To replace with native .at() once Node 14 stops being supported
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/key-spacing.ts:18]: Nit: we generally use actual `TODO` comments to help with searchability.

```suggestion
 * TODO: replace with native .at() once Node 14 stops being supported
```

File: packages/eslint-plugin/src/rules/key-spacing.ts [hunk 2]
```diff
@@ -41,7 +51,8 @@ export default util.createRule<Options, MessageIds>({
     function adjustedColumn(position: TSESTree.Position): number {
       const line = position.line - 1; // position.line is 1-indexed
       return util.getStringLength(
-        sourceCode.lines[line].slice(0, position.column),
+        // use at() just for codecov, so it has a positive position case
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/key-spacing.ts:54]: Codecov just reports our `jest --coverage` results. I think this is fine without a comment.

```suggestion
```

**Review by JoshuaKGoldberg — APPROVED** [review]
Thanks!

**Review by JoshuaKGoldberg — APPROVED** [review]
