### PR TITLE
fix(eslint-plugin): [unbound-method] false positives for unary expressions

### LINKED ISSUE #1934: [unbound-method] False positive for Uncalled Function Checks
**Repro**

```JSON
{
  "extends": [
      "airbnb-typescript/base",
      "plugin:@typescript-eslint/eslint-recommended",
      "plugin:@typescript-eslint/recommended",
      "plugin:@typescript-eslint/recommended-requiring-type-checking"
  ],
  "rules": {
  }
}
```

```TS
// https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#uncalled-function-checks
// this check is disallowed, but it's a reasonable function safety check aka uncalled-function-checks
// Avoid referencing unbound methods which may cause unintentional scoping of `this`. eslint@typescript-eslint/unbound-method
if (!!obj.doThing) {
  // safe function call, but linting error
  obj.doThing()
}
```

**Expected Result**

TypeScript advicates the `!!` syntax on functions
See: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#uncalled-function-checks
> If you intended to test the function without calling it, you can correct the definition of it to include undefined/null, or use !! to write something like if (!!user.isAdministrator) to indicate that the coercion is intentional.

I'd expect the linting rules to match :)

**Actual Result**

eslint@typescript-eslint/unbound-method complains
> Avoid referencing unbound methods which may cause unintentional scoping of `this`. 

**Additional Info**

There is also an issue with the eslint rule `no-extra-boolean-cast` as it doesn't have type info. So it doesn't know that it's a function. Perhaps this exception can also dealt with?

> Redundant double negation. eslint(no-extra-boolean-cast)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.29.0` |
| `@typescript-eslint/parser`        | `2.29.0` |
| `TypeScript`                       | `3.8.3` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `13.12.0` |
| `npm`                              | `X.Y.Z` |
| `yarn`                              | `1.22.0` |

### PR DESCRIPTION
**Pull request by auhsoja**
Fixes #1934. 

Added an extra check to `isSafeUse` to deal with the case when an unbound method is made truthy/falsy (and therefore safe to reference) through the use of the `!` operator.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/unbound-method.ts [hunk 1]
```diff
@@ -241,7 +241,10 @@ function isSafeUse(node: TSESTree.Node): boolean {
       return parent.tag === node;
 
     case AST_NODE_TYPES.UnaryExpression:
-      return parent.operator === 'typeof';
+      // the first case is safe for obvious
+      // reasons. The second one is also fine
+      // since we're returning something falsy
+      return ['typeof', '!'].includes(parent.operator);
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/unbound-method.ts:247]: while we're at it, could we also whitelist both `void` and `delete`?
They're both equally safe for obvious reasons

Comment (auhsoja) [reply packages/eslint-plugin/src/rules/unbound-method.ts:247]: Yeah sure. One moment.

Comment (auhsoja) [reply packages/eslint-plugin/src/rules/unbound-method.ts]: Oops. Guess I forgot to mention this yesterday, but the extra whitelisted operators were added in the most recent commit. So should be good to go pending any further recommendations.
