### PR TITLE
fix(eslint-plugin): [switch-exhaustiveness-check] add support for covering a missing property with `undefined`

### LINKED ISSUE #10228: Bug: [switch-exhaustiveness-check] False positive with noUncheckedIndexedAccess
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.tsx&code=GYVwdgxgLglg9mABMOcAUAPAXIgzlAJxjAHMBtAXQEpEBvAKESbwHcYoIALRTMgBmp1GzJhACGuAKaIARJxgyswkUwBGBSWIDWAbmXNxUxOAAmk4MUkmlKxGeBiQAGyg3biKJwJwWiMJN8AUQJvAjQAAwBVfwwAB0loK0QANzEnEEkcABJaDH4KAF9wqj0RAvoCoA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQECJFwEipCtTqMWiAO5kcxABY0AHuth9EOMgDdkDIoiobkxANbDIqeAHs0PAL4g3QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDArugDTg2RGwAqkWgALdNADW6ACYBJIjPQAPWQEFo0dCTKUO6XgF8QhoA&tokens=false

### Repro Code

```TypeScript
function foo(x: string[]) {
    switch (x[0]) {
      case "hi":
        break;
      case undefined:
      default:
        throw new Error(`Unexpected value: ${x[0]}`);
    }
}
```

### ESLint Config

```javascript
module.exports = {
  "parser": "@typescript-eslint/parser",
  "rules": {
    "@typescript-eslint/switch-exhaustiveness-check": "error"
  }
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strict": true,
    "noUncheckedIndexedAccess": true
  }
}
```

### Expected Result

No error

### Actual Result

"Switch is not exhaustive. Cases not matched: undefined" — even though `case undefined:` is present

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by ronami**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10228
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR resolves #10228. Apparently, TypeScript has a different type [when a property could be missing](https://github.com/microsoft/TypeScript/blob/cb44488fcec4348a448434afbf2ebcbf2b423c61/src/compiler/checker.ts/#L2059) rather than the standard `undefined` type. Both types have the same object flags but different `debugIntrinsicName`, making them not match for the current equality check (along with a different `id` key). 

This issue isn't related to the recent fix in https://github.com/typescript-eslint/typescript-eslint/pull/10223 and can be tracked a while back. I didn't bother checking that the type is actually the missing type (it would require checking the currently untyped `debugIntrinsicName`) and just comparing for the standard undefined object flags (which match both the standard and the missing undefined types).

### CODE REVIEW

File: packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts [hunk 1]
```diff
@@ -155,6 +155,15 @@ export default createRule<Options, MessageIds>({
...
 
+          // `undefined` should cover the "missing" undefined type
+          // https://github.com/microsoft/TypeScript/blob/cb44488fcec4348a448434afbf2ebcbf2b423c61/src/compiler/checker.ts/#L2059
+          if (
+            caseTypes.has(checker.getUndefinedType()) &&
+            tsutils.isIntrinsicUndefinedType(intersectionPart)
+          ) {
+            continue;
+          }
+
```
Comment (auvred) [inline packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts:166]:
```suggestion
          // "missing", "optional" and "undefined" types are different runtime objects,
          // but all of them have TypeFlags.Undefined type flag
          if (
            Array.from(caseTypes).some(tsutils.isIntrinsicUndefinedType) &&
            tsutils.isIntrinsicUndefinedType(intersectionPart)
          ) {
            continue;
          }

```

[Bug] If we cannot rely `intersectionPart` being equal to `checker.getUndefinedType()`, we cannot rely on `caseTypes` to contain only `undefinedType` objects. `caseType` may also contain `missingType`:

```ts
function foo(x: string[], y: string | undefined) {
  const a = x[0];
  if (typeof a === 'string') {
    return
  }
  switch (y) {
    case 'hi':
      break;
    case a:
      break;
  }
}
```

[playground link](https://deploy-preview-10232--typescript-eslint.netlify.app/play/#ts=5.6.2&fileType=.tsx&code=GYVwdgxgLglg9mABMOcAUAPAXIgzlAJxjAHMBtAXQBpEBPHfI0xAH0XABMBTYYrjgJSIA3gChEiCAnyIAhogC8iDGQAMFANzjEMYIjRRaABy5w98hZcQByRsRLWhYiRIJcoIAmG0BfbbgB3GCgIAAt9WidtCQhZXC4bUJhrLGiXACM3WQBrLRdJOITZVPyJTK4cvMQ-PyA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQECJFwEipCtTqMWiAO5kcxABY0AHuth9EOMgDdkDIoiobkxANbDIqeAHs0PAL4g3QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUhFYAVSLQ%2Bg9ABMAkkVXoAHmoCC0aOhLCwo9FIC%2BIK0A&tokens=false)

**Review by auvred — CHANGES_REQUESTED** [review]

File: packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts (hunk 1 above)
Comment (ronami) [reply packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts:166]: Oh, nice catch, thanks!

**Comment by notaphplover** [comment]
Hey @ronami, I'm having issues with this rule when facing switch code flows with a `default` case:

```ts
enum NumberEnum {
  one = 1,
  zero = 0,
}

function getNumber(): NumberEnum {
  return 0;
}

function isZeroGenerated(): boolean {
  const foo: NumberEnum = getNumber();

  // Switch is not exhaustive. Cases not matched: NumberEnum.one
  switch (foo) {
    case NumberEnum.zero:
      return true;
    default:
      return false;
  }
}
```

Does this PR solve this case as well?

**Comment by kirkwaiblinger** [comment]
@notaphplover Unrelated; see https://github.com/typescript-eslint/typescript-eslint/issues/10228#issuecomment-2447944780. Please avoid spamming by tagging multiple people in multiple places with the same question.

For future reference, see the [contributing guide on getting help](https://typescript-eslint.io/contributing/issues#questions-and-support-requests). We're much chattier in the discord! 🙂

**Review by auvred — APPROVED** [review]
:100:

**Review by JoshuaKGoldberg — APPROVED** [review]
yay!

**Comment by jtbandes** [comment]
Thanks for the quick turnaround :)
