### PR TITLE
fix(eslint-plugin): [ban-ts-comment] support block comments

### LINKED ISSUE #2617: [ban-ts-comment] multiline @ts-ignore and @ts-expect-error not supported
The [regex we use](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/ban-ts-comment.ts#L101) for detecting TypeScript directives was originally adapted [from tslint](https://github.com/palantir/tslint/blob/master/src/rules/banTsIgnoreRule.ts#L48).  Since then (I think??) TypeScript has added multiline comment support for directives.

You can see TypeScript's own regexs [here](https://github.com/microsoft/TypeScript/blob/master/src/compiler/scanner.ts#L281-L289) (they have one for single line and another for multiline) as well as some useful test cases [here](https://github.com/microsoft/TypeScript/blob/master/tests/cases/conformance/directives/multiline.tsx).

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/ban-ts-comment": "error"
  }
}
```

```TS

if (false) {
  // @ts-expect-error
  console.log('this errors (appropriately) because a description is missing');
}

if (false) {
  // @ts-expect-error explanation: ziltoid is omniscient
  console.log('this does not error (appropriately) because a description is present');
}

if (false) {
  /* @ts-expect-error */
  console.log('this one does not error, although it should');
}
```

**Expected Result**

```ts
if (false) {
  /* @ts-expect-error */
  console.log('this one does not error, although it should');
}
```

should return an error.

**Actual Result**

no error is returned.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.1.1` |
| `@typescript-eslint/parser`        | `4.1.1` |
| `TypeScript`                       | `4.0.2` |
| `ESLint`                           | `7.10.0` |
| `node`                             | `12.6.0` |

### PR DESCRIPTION
**Pull request by dopecodez**
Fixes #2617 

### Overview
The support for `ban-ts-comment` was restricted to only single line comments.

This PR looks to expand the support for `ban-ts-comment` for block comments also.

### Approach
The approach revolved around changing the regex for recognizing the valid cases of @ts-<directive> commands and also changing how we handled comparing this regex and our comment.

### Checklist
- [x] Add UTs corresponding to change
- [x] Change rule documentation corresponding to change

### CODE REVIEW

File: packages/eslint-plugin/src/rules/ban-ts-comment.ts [hunk 1]
```diff
@@ -98,20 +98,21 @@ export default util.createRule<[Options], MessageIds>({
     },
   ],
   create(context, [options]) {
-    const tsCommentRegExp = /^\/*\s*@ts-(expect-error|ignore|check|nocheck)(.*)/;
+    const commentDirectiveRegExSingleLine = /^\/*\s*@ts-(expect-error|ignore|check|nocheck)(.*)/;
+    const commentDirectiveRegExMultiLine = /^\s*(?:\/|\*)*\s*@ts-(expect-error|ignore|check|nocheck)(.*)/;
```
Comment (dimitropoulos) [inline packages/eslint-plugin/src/rules/ban-ts-comment.ts:102]: It would be great to link back to the typescript source code as reference here, should these ever need to change (as they did recently when expect error was introduced)

Comment (dopecodez) [reply packages/eslint-plugin/src/rules/ban-ts-comment.ts:106]: Added the reference to the typescript docs here.

**Comment by dopecodez** [comment]
@bradzacher , I can see `codecov` not returning a status for my newest commit, and also can see the same happening to another PR. 
Looks like this is a known [problem](https://community.codecov.io/t/codecov-status-stuck-at-waiting-for-status-to-be-reported-on-github/341/12). 
The only way around it is to make a commit right now, since i can't retrigger the codecov report for this project. Could be something to take a look at in the future.

**Comment by bradzacher** [comment]
codecov is average yeah. sometimes it doesn't work. sometimes it's kinda flaky. it's also just slow sometimes.
it looks like it's reported the status now.

File: packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts [hunk 2]
```diff
@@ -146,6 +177,19 @@ ruleTester.run('ts-ignore', rule, {
         '// @ts-ignore I think that I am exempted from any need to follow the rules!',
       options: [{ 'ts-ignore': 'allow-with-description' }],
     },
+    {
+      code: `
+/*
+// @ts-ignore running with long description in a block
```
Comment (dimitropoulos) [inline packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts:183]: it would be great to have some tests that are not a combination of single line and multi-line comments.  If this works, it's not clear to me from the tests that it works because it's a multiline or because it's also a single line comment.

File: packages/eslint-plugin/src/rules/ban-ts-comment.ts (hunk 1 above)
Comment (dimitropoulos) [reply packages/eslint-plugin/src/rules/ban-ts-comment.ts:106]: thanks

File: packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts (hunk 2 above)
Comment (dopecodez) [reply packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts]: Yea I was using the tests that were already present within our code just like that. Changed all multiline tests to multiline only.

File: packages/eslint-plugin/docs/rules/ban-ts-comment.md [hunk 3]
```diff
@@ -41,13 +41,19 @@ const defaultOptions: Options = {
...
 
 ```ts
 if (false) {
   // @ts-ignore: Unreachable code error
   console.log('hello');
 }
+if (false) {
+  /*
+  @ts-ignore: Unreachable code error
+  */
```
Comment (bradzacher) [inline packages/eslint-plugin/docs/rules/ban-ts-comment.md:54]: the `@ts-ignore` must be on the line before the error, even in a multiline comment

```suggestion
  @ts-ignore: Unreachable code error */
```

File: packages/eslint-plugin/docs/rules/ban-ts-comment.md [hunk 4]
```diff
@@ -63,22 +69,32 @@ if (false) {
...
 
 ```ts
 if (false) {
   // @ts-expect-error: Unreachable code error
   console.log('hello');
 }
+if (false) {
+  /*
+  @ts-expect-error: Unreachable code error
+  */
```
Comment (bradzacher) [inline packages/eslint-plugin/docs/rules/ban-ts-comment.md:95]:
```suggestion
  @ts-expect-error: Unreachable code error */
```

**Review by bradzacher — APPROVED** [review]
lgtm - thanks for your contribution!
