### PR TITLE
fix(eslint-plugin): [no-restricted-imports] allow type import as long as there's one matching pattern

### LINKED ISSUE #4895: [no-restricted-imports] 2 pattern rules with different globs and `allowTypeImports` break validation
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/<rule>": ["error", {
	    "patterns": [
	      {
	        "group": [
	          "import1/private/*"
	        ],
	        "message": "usage of import1 private modules not allowed.",
	        "allowTypeImports": true
	      },
	      {
	        "group": [
	          "import2/private/*"
	        ],
	        "message": "usage of import2 private modules not allowed.",
	        "allowTypeImports": true
	      }
	    ]
	  }]
  }
}
```

```TS
import type {foo} from 'import1/private/bar'; 
import type {foo} from 'import2/private/bar';
```

**Expected Result**

Both type imports should be valid.

**Actual Result**

Both imports fail lint.

**Additional Info**

If only one `allowTypeImports` pattern rule exists, it works. Once I enable two rules, both break.

A failing test case for [no-restricted-imports.test.ts](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/tests/rules/no-restricted-imports.test.ts):

```ts
    {
      code: `
        import type {foo} from 'import1/private/foo';
        import type {bar} from 'import2/private/bar';
      `,
      options: [
        {
          patterns: [
            {
              group: ['import1/private/*'],
              message: 'usage of import1 private modules not allowed.',
              allowTypeImports: true,
            },
            {
              group: ['import2/private/*'],
              message: 'usage of import2 private modules not allowed.',
              allowTypeImports: true,
            },
          ],
        },
      ],
    },
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.22.0` |
| `@typescript-eslint/parser`        | `5.22.0` |
| `TypeScript`                       | `X.Y.Z` |
| `ESLint`                           | `X.Y.Z` |
| `node`                             | `X.Y.Z` |

### PR DESCRIPTION
**Pull request by Josh-Cena**
## PR Checklist

-   [x] Addresses an existing open issue: fixes #4895 
-   [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
    - No... but it clearly is a bug, so I'm pre-emptively sending the PR :D
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

The problem with our current logic is that we require _every_ allowed import pattern to match a given path, but in practice, they can well be disjoint! With this change, we will be more permissive and allow type import as long as _one_ matcher matches.

This may lead to some false-negatives? For example, there are two matchers that both match a file, one with `allowTypeImports`, another without. Previously, we report an error; now we don't. To be fair, both seem like valid behaviors to me. We don't have existing test-cases covering that anyways, and it doesn't seem like we have this behavior specced in the docs, so I assume either is fine.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-restricted-imports.ts [hunk 1]
```diff
@@ -158,9 +158,8 @@ export default createRule<Options, MessageIds>({
     function isAllowedTypeImportPattern(importSource: string): boolean {
       return (
         allowedImportTypeMatchers.length > 0 &&
-        allowedImportTypeMatchers.every(matcher => {
-          return matcher.ignores(importSource);
-        })
+        // As long as there's one matching pattern that allows type import
+        allowedImportTypeMatchers.some(matcher => matcher.ignores(importSource))
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-restricted-imports.ts:162]: Nit:

```ts
// As long as there's one matching pattern that allows type import
allowedImportTypeMatchers.some(matcher => matcher.ignores(importSource))
```

**Review by bradzacher — APPROVED** [review]
thanks for fixing this!
