### PR TITLE
fix(typescript-estree): forbid `abstract` modifier in object methods

### LINKED ISSUE #11655: Enhancement: Forbid `abstract` modifier in object methods
### Before You File a Proposal Please Confirm You Have Done The Following...

- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [x] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### My proposal is suitable for this project

- [x] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

```ts
({
  abstract method() {
    return 1;
  }
})
```

[Playground](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=BQbwsAUABFCGBGBnALgJ1gY2VAtgU2QAsB7AE2AEopxoYpUCBXVAOygEYBuSGAX0l4UgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

```
TypeScript
1042: 'abstract' modifier cannot be used here. 2:3 - 2:11
1244: Abstract methods can only appear within an abstract class. 2:3 - 2:11
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by fisker**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11655
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/typescript-estree/src/convert.ts [hunk 1]
```diff
@@ -398,6 +398,18 @@ export class Converter {
           );
         }
       }
+
+      // TODO: There are more cases in `checkGrammarObjectLiteralExpression` in typescript
```
Comment (JoshuaKGoldberg) [inline packages/typescript-estree/src/convert.ts]: [Docs] I don't follow the intent of this comment. Do you plan to file issues / send PRs for more of them?

Comment (fisker) [reply packages/typescript-estree/src/convert.ts]: > I don't follow the intent of this comment.

My idea is to leave a reference to track where it come from like other conditions. But this part from `checkGrammarObjectLiteralExpression` is not full covered.

> Do you plan to file issues / send PRs for more of them?

Maybe, but I don't know how to produce other cases yet.
