### PR TITLE
fix(eslint-plugin): [unbound-method] allow `super` expressions in `this` assignments

### LINKED ISSUE #1866: [unbound-method] Support super.foo in constructor
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/unbound-method": [
            "error",
            {
                "ignoreStatic": true
            }
        ]
  }
}
```

```TS
class BaseClass {
    x: number = 42;
    logThis() { console.log(`x is ${this?.x}`); }
}

class OtherClass extends BaseClass {
    superLogThis: any;
    constructor() {
        super();
        this.superLogThis = super.logThis;  // X - Incorrect eslint error
    }
}

const oc = new OtherClass();
oc.superLogThis();  // Works despite eslint error in constructor

```

**Expected Result**
No `unbound-method` error. In the test case above, `oc.superLogThis()` correctly prints `x is 42`.

**Actual Result**
`unbound-method` error about `super.logThis` in `OtherClass`'s constructor.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.17.0` |
| `@typescript-eslint/parser`        | `2.17.0` |
| `TypeScript`                       | `3.7.5` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `10.19.0` |
| `npm`                              | `6.13.4` |

### PR DESCRIPTION
**Pull request by armano2**
This is rebased version of PR, #1925 with fixes.

fixes #1866

### CODE REVIEW

**Review by bradzacher — APPROVED** [review]
thanks!

File: packages/eslint-plugin/src/rules/unbound-method.ts [hunk 1]
```diff
@@ -305,7 +305,12 @@ function isSafeUse(node: TSESTree.Node): boolean {
       return ['instanceof', '==', '!=', '===', '!=='].includes(parent.operator);
 
     case AST_NODE_TYPES.AssignmentExpression:
-      return parent.operator === '=' && node === parent.left;
+      return (
+        parent.operator === '=' &&
+        (node === parent.left ||
+          (node.type === AST_NODE_TYPES.MemberExpression &&
+            node.object.type === AST_NODE_TYPES.Super))
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/unbound-method.ts:312]: Actually - I think we need to do a little more with this check.

This check will allow:
```ts
let x;
x = super.foo;
```

Which is obviously not correct.
We need to ensure that the left is a `this` member expression and that the right is a `super` member expression

**Review by bradzacher — CHANGES_REQUESTED** [review]

**Review by bradzacher — APPROVED** [review]
LGTM! Thanks!

File: packages/eslint-plugin/src/rules/unbound-method.ts [hunk 2]
```diff
@@ -305,7 +305,14 @@ function isSafeUse(node: TSESTree.Node): boolean {
       return ['instanceof', '==', '!=', '===', '!=='].includes(parent.operator);
 
     case AST_NODE_TYPES.AssignmentExpression:
-      return parent.operator === '=' && node === parent.left;
+      return (
+        parent.operator === '=' &&
+        (node === parent.left ||
+          (node.type === AST_NODE_TYPES.MemberExpression &&
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/unbound-method.ts:311]: technically this won't handle `this.foo.bar` and `super.foo.bar`, but we can ignore those cases until someone complains.
