### PR TITLE
fix(eslint-plugin): [unified-signatures] crash: cannot read property 'name' of null

### LINKED ISSUE #1078: [unified-signatures] Crash: Cannot read property 'name' of null
**Repro**

```JSON
{
  "root": true,

  "parser": "@typescript-eslint/parser",

  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "impliedStrict": true
    }
  },

  "plugins": ["@typescript-eslint/eslint-plugin"],

  "rules": {
    "@typescript-eslint/unified-signatures": "error"
  }
}
```

```TS
declare module 'core-js-compat/get-modules-list-for-target-version' {
  export default function(a: string): string[];
}
```

**Expected Result**

It should finish with some linting results.

**Actual Result**

It crashes with:
```
TypeError: Cannot read property 'name' of null
Occurred while linting core-js-compat.d.ts:2
    at TSDeclareFunction (node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:330:43)
    at node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (node_modules/eslint/lib/linter/node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (node_modules/eslint/lib/linter/node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/linter/node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:646:23)
    at node_modules/eslint/lib/linter/linter.js:935:32
    at Array.forEach (<anonymous>)
```

**Additional Info**

```
  eslint:cli CLI args: [ 'packages/ts-env-sumo-transformer/plugins/core-js/core-js-compat.d.ts', '--debug' ] +0ms
  eslint:cli Running on files +4ms
  eslint:ignored-paths baseDir = "repo" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = ".*"
  eslint:ignored-paths   cooked   = ".*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "!../"
  eslint:ignored-paths   cooked   = "!../" +1ms
  eslint:ignored-paths Looking for ignore file in repo +0ms
  eslint:ignored-paths Loaded ignore file repo/.eslintignore +0ms
  eslint:ignored-paths Adding repo/.eslintignore +0ms
  eslint:ignored-paths baseDir = "repo" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +0ms
  eslint:ignored-paths Looking for ignore file in repo +0ms
  eslint:ignored-paths Loaded ignore file repo/.eslintignore +0ms
  eslint:ignored-paths Adding repo/.eslintignore +0ms
  eslint:file-enumerator Start to iterate files: [ 'packages/ts-env-sumo-transformer/plugins/core-js/core-js-compat.d.ts' ] +0ms
  eslint:file-enumerator File: repo/packages/ts-env-sumo-transformer/plugins/core-js/core-js-compat.d.ts +0ms
  eslint:cascading-config-array-factory Load config files for repo/packages/ts-env-sumo-transformer/plugins/core-js. +0ms
  eslint:cascading-config-array-factory No cache found: repo/packages/ts-env-sumo-transformer/plugins/core-js. +0ms
  eslint:config-array-factory Config file not found on repo/packages/ts-env-sumo-transformer/plugins/core-js +0ms
  eslint:cascading-config-array-factory No cache found: repo/packages/ts-env-sumo-transformer/plugins. +0ms
  eslint:config-array-factory Config file not found on repo/packages/ts-env-sumo-transformer/plugins +1ms
  eslint:cascading-config-array-factory No cache found: repo/packages/ts-env-sumo-transformer. +1ms
  eslint:config-array-factory Loading package.json config file: repo/packages/ts-env-sumo-transformer/package.json +0ms
  eslint:config-array-factory Loading JSON config file: repo/packages/ts-env-sumo-transformer/package.json +0ms
  eslint:config-array-factory Error reading package.json file: repo/packages/ts-env-sumo-transformer/package.json +1ms
  eslint:config-array-factory Config file not found on repo/packages/ts-env-sumo-transformer +0ms
  eslint:cascading-config-array-factory No cache found: repo/packages. +1ms
  eslint:config-array-factory Config file not found on repo/packages +0ms
  eslint:cascading-config-array-factory No cache found: repo. +0ms
  eslint:config-array-factory Loading JS config file: repo/.eslintrc.js +0ms
  eslint:config-array-factory Config file found: repo/.eslintrc.js +1ms
  eslint:config-array-factory Loading parser "@typescript-eslint/parser" from repo/.eslintrc.js +9ms
  eslint:config-array-factory Loaded: @typescript-eslint/parser@2.3.3 (repo/node_modules/@typescript-eslint/parser/dist/parser.js) +0ms
  eslint:config-array-factory Loading plugin "@typescript-eslint/eslint-plugin" from repo/.eslintrc.js +120ms
  eslint:config-array-factory Loaded: @typescript-eslint/eslint-plugin@2.3.3 (repo/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +1ms
  eslint:cascading-config-array-factory Stop traversing because of 'root:true'. +174ms
  eslint:cascading-config-array-factory Configuration was determined: ConfigArray [ { name: '.eslintrc.js', filePath: 'repo/.eslintrc.js', criteria: null, env: undefined, globals: undefined, noInlineConfig: undefined, parser: { error: null, filePath: 'repo/node_modules/@typescript-eslint/parser/dist/parser.js', id: '@typescript-eslint/parser', importerName: '.eslintrc.js', importerPath: 'repo/.eslintrc.js' }, parserOptions: { sourceType: 'module', ecmaFeatures: [Object] }, plugins: { '@typescript-eslint': [Object] }, processor: undefined, reportUnusedDisableDirectives: undefined, root: true, rules: { '@typescript-eslint/unified-signatures': 'error' }, settings: undefined } ] on repo/packages/ts-env-sumo-transformer/plugins/core-js +2ms
  eslint:ignored-paths contains: +180ms
  eslint:ignored-paths   target   = "repo/packages/ts-env-sumo-transformer/plugins/core-js/core-js-compat.d.ts" +0ms
  eslint:ignored-paths   base     = "repo" +0ms
  eslint:ignored-paths   relative = "packages/ts-env-sumo-transformer/plugins/core-js/core-js-compat.d.ts" +0ms
  eslint:ignored-paths   result   = false +0ms
  eslint:cli-engine Lint repo/packages/ts-env-sumo-transformer/plugins/core-js/core-js-compat.d.ts +0ms
  eslint:linter Linting code for repo/packages/ts-env-sumo-transformer/plugins/core-js/core-js-compat.d.ts (pass 1) +0ms
  eslint:linter Verify +1ms
  eslint:linter With ConfigArray: repo/packages/ts-env-sumo-transformer/plugins/core-js/core-js-compat.d.ts +0ms
  eslint:linter An error occurred while traversing +23ms
  eslint:linter Filename: repo/packages/ts-env-sumo-transformer/plugins/core-js/core-js-compat.d.ts +0ms
  eslint:linter Line: 2 +0ms
  eslint:linter Parser Options: {
  sourceType: 'module',
  ecmaFeatures: { impliedStrict: true, globalReturn: false },
  ecmaVersion: undefined
} +0ms
  eslint:linter Parser Path: repo/node_modules/@typescript-eslint/parser/dist/parser.js +0ms
  eslint:linter Settings: {} +0ms
TypeError: Cannot read property 'name' of null
Occurred while linting repo/packages/ts-env-sumo-transformer/plugins/core-js/core-js-compat.d.ts:2
    at TSDeclareFunction (repo/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:330:43)
    at repo/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (repo/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (repo/node_modules/eslint/lib/linter/node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (repo/node_modules/eslint/lib/linter/node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (repo/node_modules/eslint/lib/linter/node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (repo/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:646:23)
    at repo/node_modules/eslint/lib/linter/linter.js:935:32
    at Array.forEach (<anonymous>)
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.3.3` |
| `@typescript-eslint/parser`        | `2.3.3` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `6.5.1` |
| `node`                             | `12.12.0` |
| `npm`                              | ~~`6.11.3`~~ (not used) |
| `npm`                              | `1.19.1` |

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #1078

### CODE REVIEW

File: packages/eslint-plugin/src/rules/unified-signatures.ts [hunk 1]
```diff
@@ -535,7 +535,16 @@ export default util.createRule({
...
+        const exportingNode = getExportingNode(node);
+
+        const key =
+          exportingNode &&
+          exportingNode.type === AST_NODE_TYPES.ExportDefaultDeclaration &&
+          node.id === null
+            ? `${exportingNode.type}_${node.type}`
+            : node.id.name;
+
+        addOverload(node, key, exportingNode);
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/unified-signatures.ts]: After changing the types, this code can probably just simplify to:
```ts
addOverload(node, node?.id.name ?? `${exportingNode.type}_${node.type}`, getExportingNode(node));
```

**Comment by a-tarasyuk** [comment]
@bradzacher Sure
