### PR TITLE
fix(type-utils): also check declared modules for package names in TypeOrValueSpecifier

### LINKED ISSUE #6861: Enhancement: Detect declared modules for TypeOrValueSpecifier
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

type-utils

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

The `PackageSpecifier` check currently checks the declaration file path for the string `node_modules` and the name of the package: 

https://github.com/typescript-eslint/typescript-eslint/blob/v6/packages/type-utils/src/TypeOrValueSpecifier.ts#L173-L179

I propose to use TypeScript's `sourceFileToPackageName` map defined [here](https://github.com/microsoft/TypeScript/blob/85f20246a4a2b424f7d92b463c20886ddf7488f9/src/compiler/types.ts#L4796).

Only problem is that it is currently marked as internal - but maybe we could get TS maintainers to open it up?

### Fail

```typescript
-
```

### Pass

```typescript
-
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6861
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Adds a manual check to `TypeOrValueSpecifier` checks for declaration nodes inside a `declare module '...' {` matching on `packageName`.

The tests in `no-floating-promises` check for this in two ways:
* `'abc'` and `'node:test'`: when declared in the tested file
* `'node:test'`: sourced from `@types/node`

I found the `TypeOrValueSpecifier.ts` to be getting a bit tall, so I split up its main helper functions into their own files.

💖 

Co-authored-by: @RebeccaStevens

### CODE REVIEW

File: packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackage.ts [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    case ts.SyntaxKind.ModuleDeclaration:
+      return node as ts.ModuleDeclaration;
+    case ts.SyntaxKind.SourceFile:
+      return undefined;
+    default:
+      return findParentModuleDeclaration(node.parent);
+  }
+}
+
+function typeDeclaredInDeclareModule(
```
Comment (JoshuaKGoldberg) [inline packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackage.ts:16]: This is the main added logic in this PR.

cc @marekdedic @RebeccaStevens as previous authors around the TypeOrValueSpecifier tooling. Sorry it took me so long to follow up on this point!

File: packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackage.ts [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+  packageName: string,
+  declarations: ts.Node[],
+): boolean {
+  return declarations.some(
+    declaration =>
+      findParentModuleDeclaration(declaration)?.name.text === packageName,
+  );
+}
+
+function typeDeclaredInDeclarationFile(
```
Comment (RebeccaStevens) [inline packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackage.ts:26]: Might want to make this function's name a bit more clear that it is for package declaration files.

e.g. `typeDeclaredInPackageDeclarationFile`

File: packages/eslint-plugin/tests/rules/no-floating-promises.test.ts [hunk 3]
```diff
@@ -754,6 +754,53 @@ promise().then(() => {});
...
+        it('...', () => {});
+      `,
+      options: [
+        {
+          allowForKnownSafeCalls: [
+            { from: 'package', name: 'it', package: 'node:test' },
+          ],
+        },
+      ],
+    },
```
Comment (RebeccaStevens) [inline packages/eslint-plugin/tests/rules/no-floating-promises.test.ts:803]: Add test for local modules.

e.g. `declare module './foo'`. It should pass with `{ from: 'file', name: '...' }` but fail with `{ from: 'package', package: './foo' }`.

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/tests/rules/no-floating-promises.test.ts:803]: D'oh, I also just realized we already have a dedicated test file for this: `packages/type-utils/tests/TypeOrValueSpecifier.test.ts`. I'll move non-cursory tests there.

**Review by RebeccaStevens — APPROVED** [review]
LGTM

I've made this same change to [ts-declaration-location](https://www.npmjs.com/package/ts-declaration-location?activeTab=readme)

**Comment by abrahamguo** [comment]
@JoshuaKGoldberg I was investigating your work in this PR because I'm hoping to use it in #8556.

Here's a question I had:
In the `main` branch, it is impossible to match the built-in type `URL` if `@types/node` is installed ([explanation](https://github.com/typescript-eslint/typescript-eslint/pull/8556#issuecomment-2165608615)).

In this PR, I see that it is now possible to match the built-in type `URL` when `@types/node` is installed.
For example, the specifier `{ from: 'package', name: 'URL', package: 'global' }` matches against `type Test = URL;`.

This is because `findParentModuleDeclaration(declaration)?.name.text` returns `'global'`.

Is this expected? I'm not 100% sure where `global` is coming from — I believe it's a `declare global` somewhere.

File: packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackageDeclarationFile.ts [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+  }
+}
+
+function typeDeclaredInDeclareModule(
+  packageName: string,
+  declarations: ts.Node[],
+): boolean {
+  return declarations.some(
+    declaration =>
+      findParentModuleDeclaration(declaration)?.name.text === packageName,
```
Comment (abrahamguo) [inline packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackageDeclarationFile.ts:22]: @JoshuaKGoldberg I was investigating your work in this PR because I'm hoping to use it in #8556.

Here's a question I had:
In the `main` branch, it is impossible to match the built-in type `URL` if `@types/node` is installed ([explanation](https://github.com/typescript-eslint/typescript-eslint/pull/8556#issuecomment-2165608615)).

In this PR, I see that it is now possible to match the built-in type `URL` when `@types/node` is installed.
For example, the specifier `{ from: 'package', name: 'URL', package: 'global' }` matches against `type Test = URL;`.

This is because `findParentModuleDeclaration(declaration)?.name.text` returns `'global'`.

Is this expected? I'm not 100% sure where `global` is coming from — I believe it's a `declare global` somewhere.

Comment (JoshuaKGoldberg) [reply packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackageDeclarationFile.ts:22]: Huh, that's ... a really interesting bug! Thanks for pointing it out. `findParentModuleDeclaration` should be filtering out `declare global` but isn't. Nice find!

**Review by bradzacher — APPROVED** [review]

File: packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackageDeclarationFile.ts (hunk 4 above)
Comment (JoshuaKGoldberg) [reply packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackageDeclarationFile.ts:24]: (I fixed that in this PR)
