### PR TITLE
fix(typescript-estree): error on unexpected jsdoc nodes

### LINKED ISSUE #1301: Exception when parsing JSDocFunctionType
**What code were you trying to parse?**

```ts
var a: function(b): c;
```

**What actually happened?**

`Cannot set property 'typeAnnotation' of null`

I haven't debugged this at all, but I assume it's because the variable's type declaration is of kind `JSDocFunctionType`, which we do not have any handling for.

https://astexplorer.net/#/gist/a1a5bcad94191c0d730eb920ced2e24b/f10df5321aaf8ceef561d14ce57a0ab59eee0ac5

### PR DESCRIPTION
**Pull request by armano2**
fixes #1301

### CODE REVIEW

File: packages/typescript-estree/src/convert.ts [hunk 1]
```diff
@@ -379,14 +379,27 @@ export class Converter {
...
+    if (
+      node.kind >= SyntaxKind.FirstJSDocNode &&
+      node.kind <= SyntaxKind.LastJSDocNode
+    ) {
+      throw createError(
+        this.ast,
+        node.pos,
+        'JSDoc types can only be used inside documentation comments.',
+      );
+    }
```
Comment (bradzacher) [inline packages/typescript-estree/src/convert.ts]: don't we have a mechanism to bubble up compiler errors?
It seems weird that we have to duplicate the ts error logic here instead of just adding an error code.

Comment (armano2) [reply packages/typescript-estree/src/convert.ts]: "bubble up compiler errors" is hidden behind flag, and its not enabled by default

**Comment by thorn0** [comment]
Sorry for being late on this PR. In Prettier, we thought printing `?NullableTypes` as is was a good idea, useful for people who migrate from Flow to TS (see https://github.com/prettier/prettier/pull/7020). Otherwise, formatting wouldn't work for them until they eliminate this syntax in the entire file. Can we probably somehow still allow this specific type (`TSJSDocNullableType`) of node in the AST?

**Comment by armano2** [comment]
hmm, thats good point, main reason for this PR was fixing syntax `var a: function(b): c;`, `JSDocFunctionType`, 

i'm in conflict now, i don't want to produce that broken ast, but i want to support it at same time.

i think we could support it, but we will have to prepare some tests (as to not crash because of it anymore)

**Comment by thorn0** [comment]
I'm asking specifically about `TSJSDocNullableType` only. It didn't cause any crashes, did it? TypeScript ESLint could even introduce a rule that would autofix it into `... | null | undefined`.

The rest of the JSDoc types are of no interest. At least for now. We might meet them again though if one day Prettier decides to format JSDoc, but this is a completely different story.

**Comment by armano2** [comment]
that's good idea, i will take a look, and prepare POC latter today,
thanks for your feedback

**Comment by armano2** [comment]
from my research typescript is checking all cases from this file, https://github.com/microsoft/TypeScript/blob/master/tests/baselines/reference/jsdocDisallowedInTypescript.js

`TSJSDocAllType` = '*'
`TSJSDocUnknownType` = '?'
`TSJSDocNonNullableType` = '!xxxx' | 'xxxx!'
`TSJSDocNullableType` = '?xxxx' | 'xxxx?'

additionally before this change syntax was crashing.
```
const x: function(new: number, string);
const x: function(this: number, string);
var g: function(number, number): number;
```

**Comment by bradzacher** [comment]
Based on @thorn0's suggestion of "people who migrate from Flow to TS"
I think we only need to support:
- `JSDocAllType`
    - [The (deprecated) flow existential type](https://github.com/facebook/flow/blob/56e444f406a1ac391c9381ecbabba10b1791a5f6/website/en/docs/types/utilities.md#existential-type--)
- `JSDocNullableType`
    - [Flow maybe type](https://flow.org/en/docs/types/maybe/)
    - we could go a step further and only allow `JSDocNullableType` with a leading question mark (`?foo`, not `foo?`).

**Comment by armano2** [comment]
both syntaxes leading and trailing are generating currently same token (position is no preserved),

i started writing rule for this, i will push this soon (and ofc i revert this commit and fixed issue)

my only question is what node type we should use for them?

should we just keep those auto-generated names?

**Comment by bradzacher** [comment]
Yeah they can fall into the "unknown node bucket" which just prepends `TS`.
I wouldn't revert this commit - just submit a new one that excludes those two from the range.
