### PR TITLE
fix(eslint-plugin): [no-useless-template-literals] detect TemplateLiteral

### LINKED ISSUE #8545: Bug: [no-useless-template-literals] doesn't detect constant template literals in interpolations
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=MYewdgziA2CmB00QHMAUADArhWASA3unBBOgL7oCUQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tmUSWWS18iALbF4AQ2G1Gw6BPioMkRNGgdokcGAC%2BIHUA&tsconfig=&tokens=false

### Repro Code

```TypeScript
console.log(`use${`less`}`)
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-useless-template-literals": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

Should flag on useless template interpolation of constant template string.

### Actual Result

There was no error

### Additional Info

Related: https://github.com/typescript-eslint/typescript-eslint/issues/8544

### LINKED ISSUE #8584: Bug: [no-useless-template-literals] Nested template literals contain useless one
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=MYewdgzgLgBGCuBbGBeGBGA3AKAAYEMASAb1wCMSFEBfXa4XTIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tmUSWWS18iALbF4AQ2G1Gw6BPioMkRNGgdokcGAC%2BIHUA&tsconfig=&tokens=false

### Repro Code

```TypeScript
const num = 1;
`a${`b${num}`}c`;
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-useless-template-literals": "error"
  }
}
```

### tsconfig

_No response_

### Expected Result

Delete the useless template literal:

\`ab${num}c\`

### Actual Result

\`a${\`b${num}\`}c\`

### Additional Info

See https://github.com/typescript-eslint/typescript-eslint/pull/8575#discussion_r1507616393.
This [valid case](https://github.com/typescript-eslint/typescript-eslint/pull/8575/files#diff-e1397d81c6335b2044a2b15a62abf713bd821075d1a7b1d1f37521f031b1acefR66) in this PR needs to be adjusted if that is merged.

### PR DESCRIPTION
**Pull request by waynzh**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8545 fixes #8584
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Add detect for TemplateLiteral

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-useless-template-literals.ts [hunk 1]
```diff
@@ -54,7 +54,10 @@ export default createRule<[], MessageId>({
     }
 
     function isLiteral(expression: TSESTree.Expression): boolean {
-      return expression.type === AST_NODE_TYPES.Literal;
+      return (
+        expression.type === AST_NODE_TYPES.Literal ||
+        expression.type === AST_NODE_TYPES.TemplateLiteral
```
Comment (yeonjuan) [inline packages/eslint-plugin/src/rules/no-useless-template-literals.ts:59]:
```suggestion
     return (
        expression.type === AST_NODE_TYPES.Literal ||
        (expression.type === AST_NODE_TYPES.TemplateLiteral &&
          expression.expressions.length === 0 &&
          expression.quasis.length === 1)
```

I think we should also check for the existence of expressions in the template literal.
maybe, 


Because the auto-fixed result will cause a parsing error if an expression is present

- [playground preview](https://deploy-preview-8575--typescript-eslint.netlify.app/play/#ts=5.3.3&fileType=.tsx&code=MYewdgzgLgBGCuBbGBeGBGA3AKAAYDMQQASAb1wCMBDAJzIUQF9dHqAvXTIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tmUSWWS18iALbF4AQ2G1Gw6BPioMkRNGgdokcGAC%2BIHUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

- srouce
```ts
const num = 1;
`foo${`bar${num}`}baz`;
```
- after fixed
```ts
const num = 1;
`foo`bar${num}`baz`; // Parsing Error
```

Comment (waynzh) [reply packages/eslint-plugin/src/rules/no-useless-template-literals.ts:59]: Thanks for pointing out. I'll update and add this test case.

Comment (yeonjuan) [reply packages/eslint-plugin/src/rules/no-useless-template-literals.ts:59]: And there seems to be one more thing to think about when an expression exists.

```ts
const variable = '...';

`foo${`bar${variable}bar}foo`;
```
This code contains useless template literal also it can be reported and fixed to below.

```ts
const variable = '...';
`foobar${variable}barfoo`;
```

but I'm not sure this case should be handled in this PR, I'd love to hear from maintainers.

Comment (waynzh) [reply packages/eslint-plugin/src/rules/no-useless-template-literals.ts]: Added a [valid case](https://github.com/typescript-eslint/typescript-eslint/pull/8575/files#diff-e1397d81c6335b2044a2b15a62abf713bd821075d1a7b1d1f37521f031b1acefR66) about this situation, which can be fixed later if planned.

Comment (auvred) [reply packages/eslint-plugin/src/rules/no-useless-template-literals.ts]: IMO, it's better to just file a follow-up issue rather than adding a possibly invalid (in future) test as a valid test. So we can clarify if this is intended behavior or not (personally I'm +1 on having this). Are you up for filing this as a new issue?

**Review by auvred — DISMISSED** [review]
LGTM! :rocket: Thanks for working on this!

Crowd applauds

File: packages/eslint-plugin/src/rules/no-useless-template-literals.ts (hunk 1 above)
Comment (waynzh) [reply packages/eslint-plugin/src/rules/no-useless-template-literals.ts]: > it's better to just file a follow-up issue rather than adding a possibly invalid (in future) test as a valid test

Yes, that makes sense to me. I'll open a new issue to keep track of this.

**Comment by kirkwaiblinger** [comment]
@waynzh Nice work on this!
Unfortunately, I didn't notice this PR until just now, and I worked on a fix myself over the weekend 🤦.

I did one or two things slightly differently, though, so I thought I'd mention them here. Here is the commit for reference: https://github.com/kirkwaiblinger/typescript-eslint/commit/8bdddbd394bb12a8c02070add2e88f028ceec89f.

1. I think that this code _should_ flag on nested template literals with a nonzero number of substitution expressions. The fixer code change is straightforward (feel free to copy it): 
   ```typescript
              } else if (expression.type === AST_NODE_TYPES.TemplateLiteral) {
                // Note that some template literals get handled in the previous branch too.
                // Remove the beginning and trailing backtick characters.
                fixes.push(
                  fixer.removeRange([
                    expression.range[0],
                    expression.range[0] + 1,
                  ]),
                  fixer.removeRange([
                    expression.range[1] - 1,
                    expression.range[1],
                  ]),
                );
   ```
   and the test cases pass.
1. (testing only, not a bug) I think this should have a test case to make sure we _don't_ flag on _tagged_ template literals.
   ```typescript
   `
      \`not a useless \${String.raw\`nested interpolation \${a}\`}\`;
   `,
   ````

File: packages/eslint-plugin/src/rules/no-useless-template-literals.ts [hunk 2]
```diff
@@ -110,7 +115,12 @@ export default createRule<[], MessageId>({
         }
 
         const fixableExpressions = node.expressions.filter(
-          (expression): expression is TSESTree.Literal | TSESTree.Identifier =>
+          (
+            expression,
+          ): expression is
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-useless-template-literals.ts:120]: consider just returning boolean/omitting the return type since the type guard isn't needed for any subsequent code.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Yup, what @kirkwaiblinger said!

Looks great otherwise ✨ very clean. Thanks!

**Comment by waynzh** [comment]
Sorry for the late reply. I'll refactor the code soon.
Thanks for the review and reference! @kirkwaiblinger @JoshuaKGoldberg

File: packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts [hunk 3]
```diff
@@ -358,14 +362,92 @@ ruleTester.run('no-useless-template-literals', rule, {
...
+        {
+          messageId: 'noUselessTemplateLiteral',
+        },
+      ],
+    },
+
+    {
+      code: noFormat`
+\`u\${
+  // hopefully this comment is not needed.
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts:405]: [Non-Actionable] Oh, right, this reminds me I'd wanted to file a low-priority followup bug about the comments being removed. Thanks 😄 #8609

**Review by JoshuaKGoldberg — APPROVED** [review]
🙌

**Review by kirkwaiblinger — APPROVED** [review]

**Comment by kirkwaiblinger** [comment]
🚀
