### PR TITLE
fix(typescript-estree): fix persisted parse for relative paths

### LINKED ISSUE #1303: Newly created Vue SFC File: Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser
**What code were you trying to parse?**
I run into the infamous error of not finding the parser (similar to https://github.com/typescript-eslint/typescript-eslint/issues/1159 and https://github.com/typescript-eslint/typescript-eslint/issues/883) for *new Vue files* I create in my project.  **NOTE: a restart of VS and my live compiler eliminates the problem until the next time I create a new `.vue` file.**

I am using Quasar, and [vue-class-component](https://github.com/vuejs/vue-class-component) for my SFC Vue files.

Error details:
```
 error  in ./src/components/signup/CLSignupStepperHeader.vue

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/eyedean/dev/xxxxx/src/components/signup/CLSignupStepperHeader.vue
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/components/signup/CLSignupStepperHeader.vue.
The file must be included in at least one of the projects provided

✖ 1 problem (1 error, 0 warnings)


 @ ./node_modules/ts-loader??ref--10-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/signup/CLSignupStepVitals.vue?vue&type=script&lang=ts& 10:0-81 143:12-33
```

Per the request at https://github.com/typescript-eslint/typescript-eslint/issues/1159#issuecomment-558427959 I am creating this new ticket.

**What did you expect to happen?**
The new Vue file should be picked up normally.  Again, a restart of live tsc and VS code fixes it, but it kinda takes 1 minute for my project.

**What actually happened?**
It used to work flawlessly until I upgraded typescript-eslint, after a few months, recently.  Looking at https://github.com/typescript-eslint/typescript-eslint/pull/1083/commits/e3f344874368a952c607ac7167d4324287a70061 which was the fix for a similar problem, the symptom I am seeing is very related to `parsedFilesSeen` not picking up the newly created file `.vue` on-the-fly.

**Additional Notes**
Per https://eslint.vuejs.org/user-guide/#how-to-use-custom-parser for parsing Vue files, I have the following in my `.eslintrc`:
```
	parser: "vue-eslint-parser",
	
	// Must use parserOptions instead of "parser" to allow vue-eslint-parser to keep working
	// See https://eslint.vuejs.org/user-guide/#how-to-use-custom-parser
	// `parser: "vue-eslint-parser"` is already included with any "plugin:vue/**" config and should be omitted
	parserOptions: {
		project: "./tsconfig.eslint.json",
		parser: "@typescript-eslint/parser",
		sourceType: "module",
		extraFileExtensions: [".vue"]
	},
```

And then it is in my `tsconfig.eslint.json` that I am mentioning all the Vue files should be picked:
```
{
	"extends": "./tsconfig.json",
	"include": [
	  "**/*.ts",
	  "**/*.js",
	  "**/*.vue",
	  "**/*.json",
	],
	"compilerOptions": {
	  "allowJs": true,
	  "checkJs": true
	}
}
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.10.0` (was the same on `2.8.0`) | 
| `TypeScript`                | `3.3.3` |
| `ESLint`                    | `5.16.0` (It's on purpose to be on 5, rather than 6) |
| `node`                      | `12.3.1` |
| `npm`                       | `6.13.0` |

### PR DESCRIPTION
**Pull request by armano2**
Issue #1303 seams to be related to resolution of relative paths in watch part of persisted parse.

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src\bar.ts.
The file must be included in at least one of the projects provided.
```

its possible that this is different unrelated issue

### Tasks:
- [x] Create test case
- [x] Fix issue
- [x] ~find if its related to #1303~: its not
- [x] Apply fix for vscode (no way to test it from unit tests)

fixes #1303

### CODE REVIEW

File: packages/typescript-estree/tests/lib/persistentParse.ts [hunk 1]
```diff
@@ -161,6 +175,28 @@ function baseTests(
     expect(() => parseFile('foo', PROJECT_DIR)).not.toThrow();
     expect(() => parseFile('bar', PROJECT_DIR)).not.toThrow();
   });
+
+  it('should work with relative paths', () => {
+    const PROJECT_DIR = setup(tsConfigIncludeAll, false);
+    console.log(process.cwd());
```
Comment (armano2) [inline packages/typescript-estree/tests/lib/persistentParse.ts]:
```suggestion
```

File: packages/typescript-estree/src/parser.ts [hunk 2]
```diff
@@ -11,6 +11,7 @@ import { createSourceFile } from './create-program/createSourceFile';
 import { Extra, TSESTreeOptions, ParserServices } from './parser-options';
 import { getFirstSemanticOrSyntacticError } from './semantic-or-syntactic-errors';
 import { TSESTree } from './ts-estree';
+import { ensureAbsolutePath } from './create-program/shared';
```
Comment (armano2) [inline packages/typescript-estree/src/parser.ts]: i don't like this, maybe i should move it somewhere else

File: packages/typescript-estree/src/create-program/createWatchProgram.ts [hunk 3]
```diff
@@ -395,11 +395,12 @@ function maybeInvalidateProgram(
...
     if (folderWatchCallbacks) {
       folderWatchCallbacks.forEach(cb => {
-        cb(currentDir, ts.FileWatcherEventKind.Changed);
+        if (currentDir !== current) {
+          cb(currentDir, ts.FileWatcherEventKind.Changed);
+        }
         cb(current!, ts.FileWatcherEventKind.Changed);
       });
       hasCallback = true;
-      break;
```
Comment (armano2) [inline packages/typescript-estree/src/create-program/createWatchProgram.ts]: removal of his line fixes issue with vscode, but i'm unable to test this
