### PR TITLE
fix(eslint-plugin): [return-await] support explicit resource management

### LINKED ISSUE #7889: Bug: [return-await] "in-try-catch" not respected with explicit resource management
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.tsx&code=IYZwngdgxgBAZgV2gFwJYHsI1JKAxCACgEoYBvAKBmwHdhVkYIBTGmABQCd0BbVEZgB4AbulQATAHyFCnZiHQAbYc1IBeSTAHIAKqh7N0CZLPlKVAGhgBGAAy3ixANxUYUTAsXMAdIvQBzQgByHGgCGHFMZiDnVzlkBE4sIIUDZAALVAh-IJcAXwoKUNhEFAwseMSIAEE6BhJyVwQQLP8YAH0YNUbqagBtAGUwHgAjJW9xfgAHdAEAXQAuGAaNHt7qdwhPHz9AoMmQGYEYl3WC6gK45gSk2npGYoISfMLgOsZKpNr758LmAA8ZpxGGQYHkXEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6aRfWaJ2gQwDufSvnRRE0aAHtokcGAC%2BIBUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
async function asyncFn() {
  await new Promise<void>((resolve) => setTimeout(resolve, 50));
  return 'something';
}

async function returnAwait() {
  using _ = {
    [Symbol.dispose]: () => {
      console.log('dispose');
    }
  }

  return await asyncFn();
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/return-await": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "lib": ["esnext.disposable"]
  }
}
```

### Expected Result

I expect that the line `return await asyncFn();` does not trigger a linting error, since the `using` statement is effectively a `try/catch/finally` around the scope of the function.

### Actual Result

`return await asyncFn();` triggers a linting error for an unnecessary `await`, and it gets autofixed to `return asyncFn();`. This makes it so that the disposers run before the returned promise settles, when previously they would run after the returned promise settles.

### Additional Info

Demonstrates difference in behavior after running `eslint --fix`: https://stackblitz.com/edit/node-fsxhhx?file=src%2Fwith-await.ts

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
~~Blocked by https://github.com/typescript-eslint/typescript-eslint/pull/9031~~

## PR Checklist

- [x] Addresses an existing open issue: fixes #7889
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Use scope analysis to check for previously declared `using`/`await using` declarations in scope.

### CODE REVIEW

**Comment by kirkwaiblinger** [comment]
No longer blocked! Will rebase and open for review within a few days

File: packages/eslint-plugin/src/rules/return-await.ts [hunk 1]
```diff
@@ -73,6 +73,53 @@ export default createRule({
...
+
+        if (scope.upper == null) {
+          // we've hit the top level of the program.
+          // This shouldn't happen, since the rule should only be checking
+          // contexts in which `return` statements are legal, which should always
+          // be inside a function.
+          break;
+        }
+
+        scope = scope.upper;
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/return-await.ts:117]: [Style] Since no tests fail with the `break;` removed:

```suggestion
        // This should always exist, since the rule should only be checking
        // contexts in which `return` statements are legal, which should always
        // be inside a function.
        scope = scope.upper!;
```

**Review by JoshuaKGoldberg — APPROVED** [review]
🌠 Stellar! And great tests too, even if the variable names are a little _bleh_.

Just one nit on a bit more succinct source code.

File: packages/eslint-plugin/src/rules/return-await.ts (hunk 1 above)
Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/return-await.ts]: Added a few tests to ensure that it doesn't crash or anything with this change 👍

**Review by JoshuaKGoldberg — APPROVED** [review]
Ilana from Broad City joyously saying "even better!"
