### PR TITLE
fix(eslint-plugin): [no-useless-template-literals] report Infinity & NaN

### LINKED ISSUE #8294: Bug: [no-useless-template-literals] Missing report for `Infinity` and `NaN`
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&showAST=es&fileType=.ts&code=AYEg3gkgdgZgllOAXAngX2AbgFCjAOQEN8NMg&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tmUSWWS18iALbF4AQ2G1Gw6BPioMkRNGgdokcGAC%2BIHUA&tsconfig=&tokens=false

### Repro Code

```TypeScript
`${Infinity}`;
`${NaN}`;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-useless-template-literals": ["error"],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

Report on the nodes and suggest a fix

### Actual Result

There is no report

### Additional Info

Inspired by #8284 that made me curious 😅

### PR DESCRIPTION
**Pull request by StyleShit**
Closes #8294

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-useless-template-literals.ts [hunk 1]
```diff
@@ -53,6 +53,24 @@ export default createRule<[], MessageId>({
...
+        expression.name === 'Infinity'
+      );
+    }
+
+    function isNaNIdentifier(expression: TSESTree.Expression): boolean {
+      return (
+        expression.type === AST_NODE_TYPES.Identifier &&
+        expression.name === 'NaN'
+      );
+    }
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-useless-template-literals.ts:72]: [Style] Nit: both of these functions check `expression.type === AST_NODE_TYPES.Identifier`. I think it'd be just a bit cleaner code to avoid the duplicate check and instead have a single function for both. WDYT?

This is a super nitpicky nit and definitely not a blocker 😄. 

A good potential followup might be to look into writing a general catch-all function for this. Searching `expression.type === AST_NODE_TYPES.Identifier` shows a few dozen results. Maybe half or more of them or so are similar calls.

File: packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts [hunk 2]
```diff
@@ -280,6 +280,52 @@ ruleTester.run('no-useless-template-literals', rule, {
...
+
+    {
+      code: noFormat`\`\${    Infinity    }\`;`,
+      output: '`Infinity`;',
+      errors: [
+        {
+          messageId: 'noUselessTemplateLiteral',
+        },
+      ],
+    },
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts:304]: [Question] Is there a reason to add the `noFormat` tests for both of these? 
Like, is there any logic specific to formatting that's relevant for `Infinity` and/or `NaN`? I'd have thought it sufficiently covered by existing tests.

If not:

```suggestion
```

**Review by JoshuaKGoldberg — DISMISSED** [review]
LGTM, thanks for the quick + straightforward fix! 🧹 ✨ 

A couple of small thoughts, nothing blocking. Adding `1 approval` and setting a reminder to get to this before our next release.

File: packages/eslint-plugin/src/rules/no-useless-template-literals.ts (hunk 1 above)
Comment (StyleShit) [reply packages/eslint-plugin/src/rules/no-useless-template-literals.ts:72]: Yeah, so I basically took inspiration from this:
https://github.com/typescript-eslint/typescript-eslint/blob/8622286207b3e04ddd260eaa8ac71927d47edd7d/packages/eslint-plugin/src/rules/no-inferrable-types.ts#L73-L80

And thought about extracting it to a util, WDYT?

File: packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts (hunk 2 above)
Comment (StyleShit) [reply packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts:304]: Yeah, those are probably unnecessary. I just copy-pasted them from the previous one. removed :)

File: packages/eslint-plugin/src/rules/no-useless-template-literals.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-useless-template-literals.ts:72]: Probably useful to have that as a util yeah. I'm not super picky here to be honest.

**Review by JoshuaKGoldberg — APPROVED** [review]
:shipit:
