### PR TITLE
fix(eslint-plugin): [prefer-nullish-coalescing] treat `any`/`unknown` as eligible for nullish coalescing

### LINKED ISSUE #10694: Enhancement: [prefer-nullish-coalescing] revisit considering `any`/`unknown` possibly-nullish
### Before You File a Proposal Please Confirm You Have Done The Following...

- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [x] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [x] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/prefer-nullish-coalescing/

### Description

In #8262, a bug was fixed around prefer-nullish-coalescing's use of `isNullableType()`. However, it was mentioned during the PR (and I agree) that we probably _should_ use the behavior in `isNullableType()` and just adapt the rule implementation details to not crash on it, see https://github.com/typescript-eslint/typescript-eslint/pull/8262#issuecomment-1895982325. 

### Fail

```TypeScript
// ignorePrimitives: /* all set to false */
declare const u: unknown;
const foo = u || 'bar'
```

### Pass

```TypeScript
// ignorePrimitives: /* all set to false */
declare const u: unknown;
const foo = u ?? 'bar'

// ignorePrimitives: /* any set to true */
declare const u: unknown;
const foo = u || 'bar'
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10694 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Rather than creating a separate "ignorePrimitives"-like option for `any`/`unknown`, I interpreted it that `any`/`unknown` will only be eligible for conversion if _all_ "ignorePrimitive" options are false, since that matches the assignability.

Also, I
- moved the `isPossiblyNullish` utility back to no-unnecessary-condition since it differs from `isNullableType`, and `isNullableType` is more reliable.
- Fixed some examples on the docs page that this change exposed

cc @OlivierZal

### CODE REVIEW

File: packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts [hunk 1]
```diff
@@ -208,14 +208,23 @@ export default createRule<Options, MessageIds>({
...
-          tsutils
-            .intersectionTypeParts(t)
-            .some(t => tsutils.isTypeFlagSet(t, ignorableFlags)),
-        )
+        // if the type is any, undefined, or void, we can't make any assumptions
+        // about the value, so it could be any primitive, even though the flags
+        // won't be set.
+        (tsutils.isTypeFlagSet(
+          type,
+          ts.TypeFlags.Any | ts.TypeFlags.Undefined | ts.TypeFlags.Void,
```
Comment (ronami) [inline packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts:218]: [Bug]: To my understanding, an `unknown` type with any of the `ignorePrimitives` options set to `true` shouldn't be reported ([deploy preview playground link](https://deploy-preview-10865--typescript-eslint.netlify.app/play/#ts=5.7.2&fileType=.tsx&code=PTAEEsHMDsHsCcCmAFe4C24Au4BuiBnALlGACpQBDaAT1AMS1C1mfgFdFQzgAoXkKAAOlAgwKgAxgiSSsAGzoB3bAAtQAA2o0NvACaJJ8ykimxoBJuwCMJbQG5e0i0wBmsWNdABeUDdAAPgGgAOQARiYh-IIEqrDs8nrCohIqWOoa7NAA1nBK0BoA-PqGxqbOln4ATCRZubD5jhVuHlU%2B1YHB4ZG8QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WlqYSNkAC1pkA9gEMkyMswDm6MAG1w2HL2jjokADRr1ELIfWRK8ptsQAFKgFtK%2BSgDcUS4ydMAjc83xL8OER9T0NIL3FxJEkmJS5pZGCDUKgBOy9eOISklOxIZECFLPhE5JMAXzLsSpMAXTVK8qA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)):

```ts
// ignorePrimitives: /* any set to true */

// passes correctly with `any`
declare const u1: any;
const foo1 = u1 || 'bar'

// should pass with `unknown`?
declare const u2: unknown;
const foo2 = u2 || 'bar'
```

**Review by ronami — CHANGES_REQUESTED** [review]
👍👍 Looking good! Requesting minor changes, mostly around testing.

File: packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts:218]: Touche - `undefined` was a typo and should have been `unknown` 😅 . That resolves https://github.com/typescript-eslint/typescript-eslint/pull/10865#discussion_r1976506315. `void` is a TS error. removed!

File: packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts [hunk 2]
```diff
@@ -208,14 +208,23 @@ export default createRule<Options, MessageIds>({
...
+        ) &&
+          ignorableFlags !== 0) ||
+        tsutils
+          .typeParts(type)
+          .some(t =>
+            tsutils
+              .intersectionTypeParts(t)
```
[the remark this answers is not in the document]
Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts:225]: Maybe... I think I'd like to leave that line as is since technically it wasn't touched in this PR though. (The change that I had to make was because the type assertion `type as ts.UnionOrIntersectionType` was no longer valid). It's generally a bit of a smell I think if we treated unions and intersections the same shallowly, but not recursively 🤔 But I don't have a test case in mind

File: packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts (hunk 1 above)
Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts]: good catch! should be fixed now 👍

**Review by ronami — DISMISSED** [review]
👍👍

**Comment by OlivierZal** [comment]
FWIW it also looks good to me 😊

**Comment by kirkwaiblinger** [comment]
had to fix up a nasty merge conflict, but should be good to again! 👍

File: packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts [hunk 3]
```diff
@@ -1373,7 +1311,53 @@ if (c || (!a ? b : a)) {
...
+            number: true,
+          },
+        },
+      ],
+    },
+
+    {
+      code: `
+declare const u2: unknown;
+const foo2 = u2 || 'bar';
```
Comment (ronami) [inline packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts:1346]:
```suggestion
declare const a: unknown;
const b = a || 'bar';
```

**Review by ronami — APPROVED** [review]
