### PR TITLE
fix(utils): add missing entries to the RuleListener selectors list

### LINKED ISSUE #9988: Bug: PrivateIdentifier node is never
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Repro Code

```ts
export const newRule = createRule({
  create(context) {
    return {
      PrivateIdentifier(node) {},
    };
  },
});
```

The inferred type of `node` is never, implying that we have forgotten to add the type for the node.

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9988
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

I added some tests, and it turns out there were 10 selectors missing!

### CODE REVIEW

File: packages/utils/src/ts-eslint/Rule.ts [hunk 1]
```diff
@@ -423,7 +423,6 @@ interface RuleListenerBaseSelectors {
   AssignmentExpression?: RuleFunction<TSESTree.AssignmentExpression>;
   AssignmentPattern?: RuleFunction<TSESTree.AssignmentPattern>;
   AwaitExpression?: RuleFunction<TSESTree.AwaitExpression>;
-  BigIntLiteral?: RuleFunction<TSESTree.BigIntLiteral>;
```
Comment (auvred) [inline packages/utils/src/ts-eslint/Rule.ts:426]: There is no such node as `BigIntLiteral`, it is just an extension of `LiteralBase` which have `type: AST_NODE_TYPES.Literal`.

**Review by bradzacher — APPROVED** [review]
Thanks!

File: packages/utils/tests/ts-eslint/Rule.type-test.ts
Comment (JoshuaKGoldberg) [inline packages/utils/tests/ts-eslint/Rule.type-test.ts:1]: Cool, let's try this out 😄

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM!
