### PR TITLE
fix(eslint-plugin): [no-implied-eval] ignore locally declared functions

### LINKED ISSUE #3727: [no-implied-eval] False positive when using setTimeout from timers/promises
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-implied-eval": 2
  }
}
```

```TS
import { setTimeout } from 'timers/promises';
// or 
import { setTimeout } from 'node:timers/promises';

// Errors with: Implied eval. Consider passing a function.
setTimeout(1000);
```

**Expected Result**

I expected there to be no errors.

**Actual Result**

The no-implied-eval rule falsely triggers on the setTimeout function

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.29.1` |
| `@typescript-eslint/parser`        | `4.29.1` |
| `TypeScript`                       | `4.3.5` |
| `ESLint`                           | `7.32.0` |
| `node`                             | `16.6.1` |

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

-   [x] Addresses an existing issue: fixes #3727
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/master/CONTRIBUTING.md) were taken

## Overview

Skips giving a warning for an `EVAL_LIKE_METHODS` hit variable if it's redeclared as per the scope manager.

I've never used the scope analyzer before, is this the right way to do it? (is there no O(1) lookup for variables by name?)

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-implied-eval.ts [hunk 1]
```diff
@@ -156,7 +156,11 @@ export default util.createRule({
       }
 
       const [handler] = node.arguments;
-      if (EVAL_LIKE_METHODS.has(calleeName) && !isFunction(handler)) {
+      if (
+        EVAL_LIKE_METHODS.has(calleeName) &&
+        !isFunction(handler) &&
+        !context.getScope().variables.some(v => v.name === calleeName)
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-implied-eval.ts:162]: this isn't *quite* correct!

You'll find that this won't work for cases like this:
```ts
function setTimeout() {}

{
  setTimeout();
}
```
because the declaration for `setTimeout` is in the parent scope.

Additionally - a variable can and will be created from the "globals" config - so if you're parsing in "script" mode, then `setTimeout` will  be in the global scope and it'll break.
We parse our tests in "module" mode though - it's rare that you actually want script mode now-a-days.

We need to:
1) get the definition
2) ensure the definition IS an "implicit global variable"

**Review by bradzacher — CHANGES_REQUESTED** [review]

File: packages/eslint-plugin/src/rules/no-implied-eval.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-implied-eval.ts:162]: Interesting @bradzacher, do you have a test case that fails? https://github.com/typescript-eslint/typescript-eslint/pull/4049/commits/52a2b3193c07fb635551ec40afca1bc4e010df3e has a working one.

Comment (bradzacher) [reply packages/eslint-plugin/src/rules/no-implied-eval.ts:162]: sorry - I was being lazy cos mobile.
`setTimeout()` is ignored by the rule because it has no arguments.
The correct test case would be
```ts
function setTimeout() {}

{
  setTimeout(100);
}
```

Scope analysis is actually kind of an ugly API in this regard unfortunately.
What you end up with is a scope tree that looks like this:
```
+ Scope#1 - Global Scope
+---> Variables = [Variable#1 (setTimeout (implicit global))]
+---> References = []
|
+--+ Scope#2 - Module Scope
   +---> Variables = [Variable#2 (setTimeout (local declaration)]
   +---> References = []
   |
   +--+ Scope#3 - Block Scope
      +---> Variables = []
      +---> References = [Reference#1 (Variable#2)]
```

So when you do `context.getScope()` you get back `Scope#3`. Then you inspect the variables and you find no variables at all (so your `.some` returns `false`).

So there are two ways you can do this:
1) crawl up the scope tree until you find a scope with a variable declared with the name, then check if it's a "global" variable.
2) follow the reference from the current scope to its variable and check if it's a "global" variable.

```
function isReferenceToGlobalFunction(calleeName: string): boolean {
  const ref = context.getScope()
    .references.find(ref => ref.identifier.name === calleeName);
  if (ref == null || ref.resolved == null) {
    return true;
  }
  
  const variable = ref.resolved;
  // ensure it's the "global" version
  return variable.defs.length === 0;
}
```

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-implied-eval.ts]: Fascinating, thanks for the explanation!

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for this!
