### PR TITLE
fix(eslint-plugin): [no-floating-promises] allowForKnownSafeCalls now supports function names (fixes #11423)

### LINKED ISSUE #11423: Bug: [no-floating-promises] allowForSafeCalls doesn't work with string TypeOrValueSpecifiers
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.8.2&fileType=.tsx&code=MYewdgzgLgBATgQzAExAWwIIQJ5mAMQFc8oBLcGAXhgRzxgAoBKKgPhgG8AoGeAUyiE4YGAAU46UhD4A6OHwggANgDc%2BDKHEJ8mXAL5cuiFOiy4CxYGXDMuQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTowAbXDYciaBOiQANMpVYV2SP3h8A7gDEO0ANKdTTAMr9uiAMLH4qDEoMGY-JgATKQBBZEImMnNYSKEOJkhdAwBdJIgAXyTUjJB0oA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const randomAsyncFunction = async () => {
  return Promise.resolve(true)
}

randomAsyncFunction()
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-floating-promises": [
      "error",
      {
        "allowForKnownSafeCalls": [
          "randomAsyncFunction"
        ]
      }
    ]
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

According to the [docs](https://typescript-eslint.io/rules/no-floating-promises/), there should be no lint issue with calling this function since it's listed in the allow list.

### Actual Result

The lint rules still say it must be dealt with.

Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator. 5:1 - 5:22
> Add void operator to ignore.
> Add await operator.

### Additional Info

I believe this has to do with `isKnownSafePromiseReturn`, it never calls `valueMatchesSomeSpecifier`.

### PR DESCRIPTION
**Pull request by 976520**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11423
- [x] That issue was marked as accepting prs
- [x] Steps in Contributing were taken

## Overview

The allowForKnownSafeCalls option was only checking type-based matching using typeMatchesSomeSpecifier and completely ignoring value-based (function name) matching. This caused configurations like `["randomAsyncFunction"]` to be ignored, even though the documentation indicated they should work 💖

- f4d5daeb5ac92f90f293b4b43f1f800e66ac4f71
  - Added specific test cases for string-based function name matching 

- 8c1cc909dca363df8c467d6a5893707c30075c82
  - First check value-based matching using valueMatchesSomeSpecifier for function names
  - Fall back to type-based matching using typeMatchesSomeSpecifier for type specifications
  - Added the missing import for valueMatchesSomeSpecifier

- af92aeac3fc0816d6cc1e34b6c2b7bafee933f87
  - Updated documentation and test snapshots
  - Removed unnecessary skipValidation from example

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-floating-promises.ts [hunk 1]
```diff
@@ -242,6 +243,17 @@ export default createRule<Options, MessageId>({
 
       const type = services.getTypeAtLocation(node.callee);
 
+      if (
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-floating-promises.ts:246]: [Naming] This doesn't _quite_ match the intent of the function: _"is known safe Promise **return**"_. The new logic is checking the _callee name_, not the _return_. Let's rename the function:

```diff
- function isKnownSafePromiseReturn(node: TSESTree.Node): boolean {
+ function isKnownSafePromiseCall(node: TSESTree.Node): boolean {
```

**Review by JoshuaKGoldberg — DISMISSED** [review]
LGTM! Just one suggestion for a naming update, nothing in core logic or tests. Happy to just apply this change before our next release. Cheers! ❤️

File: packages/eslint-plugin/src/rules/no-floating-promises.ts (hunk 1 above)
Comment (zaewc) [reply packages/eslint-plugin/src/rules/no-floating-promises.ts:246]: [ff2e5cd](https://github.com/typescript-eslint/typescript-eslint/pull/11430/commits/ff2e5cdc6f508f18ab8aef8cc3580368c7f1e7e0) 

Good point!! I’ve renamed it as suggested
