### PR TITLE
fix(eslint-plugin): support arbitrary extensions in definition files

### LINKED ISSUE #10911: Bug: `isDefinitionFile` utility doesn't consider arbitrary extensions
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

eslint-plugin

### Playground Link

_No response_

### Repro Code

```TypeScript
// not applicable
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {},
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "allowArbitraryExtensions": true,
  }
}
```

### Expected Result

I expected [`isDefinitionFile`](https://github.com/typescript-eslint/typescript-eslint/blob/89f0c613e99b2419b329c1cb6277f1a286f1c98d/packages/eslint-plugin/src/util/misc.ts#L18-L29) to return `true` for file names like `.d.css.ts` (or the more general form of `{file basename}.d.{extension}.ts`) when [`allowArbitraryExtensions`](https://www.typescriptlang.org/tsconfig/#allowArbitraryExtensions) is enabled.

### Actual Result

The utility function doesn't seem to consider [`allowArbitraryExtensions`](https://www.typescriptlang.org/tsconfig/#allowArbitraryExtensions).

### Additional Info

This is a follow-up to the discussion in https://github.com/typescript-eslint/typescript-eslint/pull/10714#discussion_r1958813613.

TypeScript v5.0 added [support for `allowArbitraryExtensions`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#allowarbitraryextensions). This seems to affect several rules that use the [`isDefinitionFile`](https://github.com/typescript-eslint/typescript-eslint/blob/89f0c613e99b2419b329c1cb6277f1a286f1c98d/packages/eslint-plugin/src/util/misc.ts#L18-L29) utility:
- `no-empty-interface`
- `no-namespace`
- `no-shadow`
- `no-unused-vars`
- `no-useless-empty-export`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.24.1` |
| `@typescript-eslint/parser`            | `8.24.1` |
| `@typescript-eslint/rule-tester`       | `8.24.1` |
| `@typescript-eslint/scope-manager`     | `8.24.1` |
| `@typescript-eslint/typescript-estree` | `8.24.1` |
| `@typescript-eslint/type-utils`        | `8.24.1` |
| `@typescript-eslint/utils`             | `8.24.1` |
| `TypeScript`                           | `5.7.3` |
| `ESLint`                               | `9.21.0` |
| `node`                                 | `22.14.0` |

### PR DESCRIPTION
**Pull request by dbarabashh**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10911 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR #10911 adds support for TypeScript's `allowArbitraryExtensions` feature in the `isDefinitionFile` utility.

### CODE REVIEW

File: packages/eslint-plugin/src/util/misc.ts [hunk 1]
```diff
@@ -25,6 +25,11 @@ export function isDefinitionFile(fileName: string): boolean {
       return true;
     }
   }
+
+  if (lowerFileName.includes('.d.') && lowerFileName.endsWith('.ts')) {
+    return true;
+  }
+
   return false;
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/util/misc.ts:33]: [Bug] This isn't quite the same logic as the original TypeScript source: https://github.com/microsoft/DefinitelyTyped-tools/blob/1f6e243b03e6d557bf43e6312b0b8f2d47819e52/packages/utils/src/miscellany.ts#L97. Let's go with the same thing they use to play it safe:

```suggestion
  return /\.d\.(ts|cts|mts|.*\.ts)$/.test(lowerFileName);
```

File: packages/eslint-plugin/tests/util/misc.test.ts [hunk 2]
```diff
@@ -1,5 +1,26 @@
 import * as misc from '../../src/util/misc';
 
+describe('isDefinitionFile', () => {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/util/misc.test.ts:3]: [Praise] Thanks for adding unit tests when they didn't already exist! 🚀

File: packages/eslint-plugin/tests/util/misc.test.ts [hunk 3]
```diff
@@ -1,5 +1,26 @@
...
+  it('returns true for standard definition files', () => {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/util/misc.test.ts:4]: [Testing] These tests each have multiple cases in them. Which is generally not a great testing thing: if an earlier assertion fails, then subsequent ones won't get run. That makes for not-very-informative test failures.

Could you please change these to be one assertion per test?

FWIW I've personally enjoyed using `it.each` to make tables of tests when there are a lot of very similar cases.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Seems reasonable, thanks for hopping on this issue! Left a couple of comments. 🚀

File: packages/eslint-plugin/tests/util/misc.test.ts (hunk 3 above)
Comment (dbarabashh) [reply packages/eslint-plugin/tests/util/misc.test.ts:4]: Hello @JoshuaKGoldberg 
Can you confirm that I got your approach in the right way?

```ts
  it.each([
    ['index.d.ts'],
    ['module.d.cts'],
    ['package.d.mts'],
  ])('returns true for standard definition file: %s', filename => {
    expect(misc.isDefinitionFile(filename)).toBe(true);
  });

  it.each([
    ['styles.d.css.ts'],
    ['component.d.vue.ts'],
    ['env.d.node.ts'],
  ])('returns true for arbitrary extension definition file: %s', filename => {
    expect(misc.isDefinitionFile(filename)).toBe(true);
  });

  it.each([
    ['index.ts'],
    ['app.tsx'],
    ['styles.css.ts'],
    ['vite.config.ts'],
  ])('returns false for non definition file: %s', filename => {
    expect(misc.isDefinitionFile(filename)).toBe(false);
  });
```

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/tests/util/misc.test.ts:4]: Yup that works!
