### PR TITLE
fix(typescript-estree): use `TSEmptyBodyFunctionExpression` for body-less nodes

### LINKED ISSUE #734: When can body be undefined or null in vanilla espree?
I'm working on converting `eslint-plugin-jest` to typescript, and have come across a type definition that I can't reproduce at runtime.

While converting [`no-test-callbacks`](https://github.com/jest-community/eslint-plugin-jest/pull/321), I found out that it's apparently possible for the `body` of a [`FunctionDeclaration` to be `null`](https://github.com/typescript-eslint/typescript-eslint/blob/807bc2d4f5dbd62aebfcbd01012d41c37066480f/packages/typescript-estree/src/ts-estree/ts-estree.ts#L485).

This has required me to [add a null check](https://github.com/jest-community/eslint-plugin-jest/pull/321/files#diff-4ef22a3863ce94155654b7576ef9793fR40) in order to please typescript.

This in turn upsets our coverage b/c that branch is never tested, leading me here as I've not been able to write any code that reproduces the defined type.

Hence: how can I have a `FunctionDeclaration` w/ a `body` of `null` at runtime?

I suspect this heavily relates to #420, but theres too many moving parts for me to properly track :)

### PR DESCRIPTION
**Pull request by G-Rath**
BREAKING CHANGE:

Fixes #734

### CODE REVIEW

File: packages/typescript-estree/src/convert.ts [hunk 1]
```diff
@@ -993,6 +997,10 @@ export class Converter {
         if (parent.kind === SyntaxKind.ObjectLiteralExpression) {
           method.params = node.parameters.map(el => this.convertChild(el));
 
+          if (method.type === AST_NODE_TYPES.TSEmptyBodyFunctionExpression) {
```
Comment (G-Rath) [inline packages/typescript-estree/src/convert.ts]: This is required b/c `Property#value` cannot be of type `TSEmptyBodyFunctionExpression`, so we can't pass `method` [here](https://github.com/typescript-eslint/typescript-eslint/pull/1289/files#diff-68b2b0b0d2d0ff1846b1114472008332R1007) if it's `TSEmptyBodyFunctionExpression`.

This is a bit of a strawman - The tests pass, and going over it in my head if I'm understanding everything correctly it should never throw, so I don't think `Property` needs its type changed.

However, I'm not sure what the best way to represent the relationship for TS to be happy, aside from either asserting like this, or adding it to the if condition - both are "ok" in my books, but open to suggestions if there's a better or more prefered way :)

**Comment by bradzacher** [comment]
This overall LGTM, but it is technically a breaking change for direct consumers of `ts-estree` (like prettier cc @thorn0).

I'm thinking we should probably look to doing a 3.0.0 release v soon, as the number of things is starting to reach a decent sized pile (see the milestone) cc @JamesHenry

File: packages/typescript-estree/src/convert.ts (hunk 1 above)
Comment (thorn0) [reply packages/typescript-estree/src/convert.ts]: I'm not sure exactly why this code is parsed without errors
```
a={ get() }
```
but looks like it might cause these exception.

Comment (G-Rath) [reply packages/typescript-estree/src/convert.ts]: A winner is you!

~I've not run it in the tests, but looking at the AST in AST ~

You bet me to it 😄

Comment (bradzacher) [reply packages/typescript-estree/src/convert.ts]: That's weird, I would have thought that typescript would hard error for us in this case: [ts playground](https://www.typescriptlang.org/play/#code/MYewdgzgLgBAhjAvDA3jAZiEAKAlDAXyA)

Comment (G-Rath) [reply packages/typescript-estree/src/convert.ts]: Yeah, TypeScript just [parses it as a method body](https://astexplorer.net/#/gist/d8840821b2458e2a105061634e9c0334/78b5846bc3a6048d13b9b570a9db16c27fd459a8) apparently.

Comment (thorn0) [reply packages/typescript-estree/src/convert.ts]: With `--allowJs`, TS [successfully parses](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=1&pc=27&useJavaScript=true#code/MYewdgzgLgBAhjAvDA3jAZiEAKAlAbgBoYAjOAJxgF98g) even this so to say JavaScript code:
```ts
const a = { foo();, bar };
```
It's full of surprises.

Comment (bradzacher) [reply packages/typescript-estree/src/convert.ts]: For the second crash, I've raised #1301 to track it.
It's some weird syntax that we'd never encountered/considered before.

**Comment by G-Rath** [comment]
@bradleyayers not entirely sure what I can do about the diff coverage, as it doesn't seem to like the fact that I force pushed, and removed so many lines from `parser`.

I can't find a nice chunk where I'm missing coverage that I can hit easily :/

**Comment by bradzacher** [comment]
@G-Rath
https://codecov.io/gh/typescript-eslint/typescript-eslint/compare/b5a52a3aae85fce3bc45b39a2107a00d2655f5f9...732668047bfd2658fb3ad884a4732896974a973b/diff#D5-1140

Just one branch codecov doesn't think you've tested.

Also please be careful with your @ tagging. My username isn't the first "brad" username alphabetically, and github isn't smart enough to be contextually aware. (I've emailed them about it, but they are yet to fix it..)

**Comment by G-Rath** [comment]
@bradzacher Turns out that wasn't actually needed - Let me know if there's any other changes you'd like made for this 😄 

Also cheers for pointing out the wrong tagging 😬
