### PR TITLE
fix(eslint-plugin): [prefer-regexp-exec] factor in union types

### LINKED ISSUE #3319: [prefer-regexp-exec] False positive for union types
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/prefer-regexp-exec": "warn",
  }
}
```

```TS
// your repro code case
const docsExlusion = ['package-lock.json', /regexp/];

const file = '';
docsExclusions.some((ex) => !!file.match(ex)); // Use the `RegExp#exec()` method instead.
```

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": false,
    "jsx": "preserve",
    "lib": [
      "dom",
      "DOM.Iterable",
      "esnext"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitReturns": true,
    "pretty": true,
    "strict": true,
    "target": "es2018",
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "useDefineForClassFields": false,
    "allowJs": false,
    "skipLibCheck": true,
    "composite": true,
    "declarationMap": true
  }
}
```

**Expected Result**

No warning/error for this case when union type is present and autofix not applied.

**Actual Result**

Type of the variable is `string | RegExp` and rule reports warning to use RegExp method.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.22.0` |
| `@typescript-eslint/parser`        | `4.22.0` |
| `TypeScript`                       | `4.2.4` |
| `ESLint`                           | `7.24.0` |
| `node`                             | `15.11.0` |

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #3319.

Edit 5/31: the tests were previously asserting on non-`string` (e.g. `number`) values getting a rule complaint... but that seems off? TypeScript should let us know anyway that `/abc/.match(null)` isn't allowed. Updated the logic to not report on them.

Co-authored-by: @IllusionMH

### CODE REVIEW

File: packages/eslint-plugin/src/rules/prefer-regexp-exec.ts [hunk 1]
```diff
@@ -97,38 +128,46 @@ export default createRule({
...
+        const argumentTypes = collectArgumentTypes(
+          tsutils.unionTypeParts(argumentType),
+        );
+        switch (argumentTypes) {
+          case ArgumentType.Both:
+          case ArgumentType.Other:
+            return context.report({
+              node: memberNode.property,
+              messageId: 'regExpExecOverStringMatch',
+            });
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/prefer-regexp-exec.ts:143]: Are we sure we want to report if there is both string and regex?
It might be a bit weird for a user as they would have to create forked code in order to satisfy the rule.

If we do want to report - might be worth putting it behind a flag maybe?

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/prefer-regexp-exec.ts]: I think I'd just gotten confused originally 😄  agreed. This no longer reports if the type isn't purely a regexp or string.

File: packages/eslint-plugin/src/rules/prefer-regexp-exec.ts [hunk 2]
```diff
@@ -37,25 +46,41 @@ export default createRule({
...
+            result = ArgumentType.RegExp;
+          } else if (result === ArgumentType.String) {
+            result = ArgumentType.Both;
+          }
+        } else if (isStringType(type)) {
+          if (result === ArgumentType.Other) {
+            result = ArgumentType.String;
+          } else if (result === ArgumentType.RegExp) {
+            result = ArgumentType.Both;
+          }
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/prefer-regexp-exec.ts:79]: > Added line #L78 was not covered by tests

Well, both of these are covered in test cases:

```
const matchers = ['package-lock.json', /regexp/];
const matchers = [/regexp/, 'package-lock.json'];
```

...so I think this is a coincidental implementation detail in how TypeScript happens to sort union types.

File: packages/eslint-plugin/src/rules/prefer-regexp-exec.ts [hunk 3]
```diff
@@ -37,25 +46,41 @@ export default createRule({
...
+        }
+      }
+
+      return result;
     }
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/prefer-regexp-exec.ts:84]: you could simplify this code by using a "flag" enum:
```ts
enum ArgumentType {
  Other  = 0,
  String = 1 << 0,
  RegExp = 1 << 1,
  Both   = String | RegExp,
}

function collectArgumentTypes(types: ts.Type[]): ArgumentType {
  let result = ArgumentType.Other;

  for (const type of types) {
    if (isRegExpType(type)) {
      result |= ArgumentType.RegExp;
    } else if (isStringType(type)) {
      result |= ArgumentType.String;
    }
  }

  return result;
}
```

**Review by bradzacher — APPROVED** [review]
LGTM - thanks!
