### PR TITLE
fix(eslint-plugin): [method-signature-style] ignore methods that return `this`

### LINKED ISSUE #1991: [method-signature-style] Shouldn't affect methods that use `this`
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/method-signature-style": ["error"]
  }
}
```

```ts
interface Foo {
	cloneThis(): this; // ❌ reported
	cloneThis: () => this; //  🤔 fixed to this
}
```

**Expected Result**

Methods should not be affected, this should not be autofixed:

```ts
interface Foo {
	cloneThis(): this;
}
```

**Actual Result**

That type is changed to an arrow function, which doesn't have `this`

```ts
interface Foo {
	cloneThis: () => this; //  Fixed to this, broken
}
```

**Additional Info**

It causes errors elsewhere in the code

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.27.0` |
| `@typescript-eslint/parser`        | `2.27.0` |
| `TypeScript`                       | `3.8.3` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `13.8.0` |
| `npm`                              | `6.13.6` |

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1991
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Adds a utility method to recurse through the AST similar to `ts.forEachChild`.

💖

### CODE REVIEW

File: packages/eslint-plugin/src/rules/method-signature-style.ts [hunk 1]
```diff
@@ -156,39 +158,41 @@ export default createRule<Options, MessageIds>({
...
-                    if (lastToken) {
-                      const nextToken =
-                        context.sourceCode.getTokenAfter(lastToken);
-                      if (nextToken) {
-                        yield fixer.remove(node);
-                        yield fixer.replaceTextRange(
-                          [lastToken.range[1], nextToken.range[0]],
-                          '',
-                        );
+                fix: skipFix
```
Comment (ronami) [inline packages/eslint-plugin/src/rules/method-signature-style.ts:161]: Missing code coverage on this line can be achieved with the following test (or equivalent):

```ts
interface Foo {
  foo(): this;
  foo(): Promise<this>;
}
```

File: packages/eslint-plugin/src/rules/method-signature-style.ts [hunk 2]
```diff
@@ -131,6 +132,7 @@ export default createRule<Options, MessageIds>({
             return;
           }
 
+          const skipFix = returnTypeReferencesThisType(methodNode.returnType);
```
Comment (ronami) [inline packages/eslint-plugin/src/rules/method-signature-style.ts]: Non-actionable: I think this is too much of an edge case, but technically `this` can be used as generic type constraint/default ([deploy preview playground link](https://deploy-preview-11813--typescript-eslint.netlify.app/play/#ts=5.9.2&fileType=.tsx&code=JYOwLgpgTgZghgYwgAgCoEZkG8BQzkwCuICAPKshAB6QgAmAzsmABbAMB8AFAJQBcaANw4AvjiA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AW0XwAsB7AE1rJKAcyYBDfLGiIhRJOjABtcNhyJo0XtEgAaVWsjEtpaEUgGwAXVUBfELaA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)):

```ts
interface T1 {
  func<T extends this>(): T;
}
```

**Review by ronami — APPROVED** [review]
🚀🚀 Looking good, small comment from me regarding code coverage.
