### PR TITLE
fix(eslint-plugin): [no-useless-default-assignment] report unnecessary defaults in ternary expressions

### LINKED ISSUE #11980: Bug: [no-useless-default-assignment] should report unnecessary default when field is present in both sides of ternary
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.9.3&fileType=.tsx&code=MYewdgzgLgBA3jAhjAvDA5AI0QL3TAX1RgFlEoALAOgCdEwATEAWwAoBKGAHhgAYqArDAD88JAC4MAMxAh8RSQkSSsiGvIDcQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tmUSWWS0AJogBmAQwR1xAygHMmAW0Qt0UAO7joTSODABfEPqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDAruuGAL4g9A&tokens=false

### Repro Code

```TypeScript
const { a = 'baz' } = Math.random() < 0.5 ? { a: 'foo' } : { a: 'bar' };
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-useless-default-assignment": "warn"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strict": true
  }
}
```

### Expected Result

I expect the default on `a` to be reported, since it is provably unnecessary

### Actual Result

No linter report

### Additional Info

This was ostensibly introduced in https://github.com/typescript-eslint/typescript-eslint/pull/11908

cc @ulrichstark

### PR DESCRIPTION
**Pull request by SungHyun627**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11980
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
This PR fixes a bug in the no-useless-default-assignment rule where unnecessary default values were not reported for ternary expressions with the same property in all branches.

### CODE REVIEW

**Comment by mdm317** [comment]
Hello 👋

I think these cases should also be reported.
```
const b = { a1: 'a' }
const { a1 = 'b' } = Math.random() < 0.5 ? { ...b } : { a1: 'b' };

const { a2 = 'b' } = Math.random() < 0.5 ? { [`a2`]: 'a' } : { a2: 'b' }

const aKey = 'a3'
const { a3 = 'b' } = Math.random() < 0.5 ? { [aKey]: 'a' } : { a3: 'b' }
```
If my suggestion is off, please feel free to ignore it.

**Comment by SungHyun627** [comment]
> Hello 👋
> I think these cases should also be reported.

Thanks for the examples! I've implemented support for ternary branches, including static backticks (template literals).
However, I've decided to exclude spread elements and variable-based computed keys from this fix. Handling those cases reliably would require complex data-flow analysis, so I've kept this PR focused on the core ternary logic to ensure stability.

File: packages/eslint-plugin/src/rules/no-useless-default-assignment.ts [hunk 1]
```diff
@@ -322,6 +335,23 @@ export default createRule<[], MessageId>({
       return fixer.removeRange([start, end]);
     }
 
+    function hasPropertyInAllBranches(
+      expr: TSESTree.Expression,
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-useless-default-assignment.ts]: [Stye] Nit: I know every AI agent does it this way, but abbreviations make code harder to read for at least me and I believe some other folks too:

```suggestion
      expression: TSESTree.Expression,
```

**Comment by JoshuaKGoldberg** [comment]
CI is all clogged up but `pnpm build`, `pnpm lint`, and `pnpm test` all work locally.
