### PR TITLE
feat(rule-tester): support multipass fixes

### LINKED ISSUE #8554: [rule-tester] support multipass fixes
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

utils

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

https://github.com/eslint/eslint/issues/18007 was rejected as a breaking change enhancement.

Given this impacts us directly (eg https://github.com/typescript-eslint/typescript-eslint/issues/8251) we should build this into our fork.

I propose the following changes:
1) if the test case has `output` and the `output` value is a string and the test case requires more than 1 pass to fix then the test case fails with a message like "test requires multiple fixes to resolve due to overlapping fix ranges - please use the array form of `output` to declare all of the expected fix passes".
2) accept an array for `output` which declares the expected fix passes for a test case.
    - An array of size 0 is disallowed.
    - An array of size 1 is equivalent to the string form.
    - An array of size `n` asserts that there are exactly `n` fix passes
    - The rule tester asserts that after each  fix pass the output matches the `n`th element of the array.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8554
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/rule-tester/src/RuleTester.ts [hunk 1]
```diff
@@ -986,20 +997,43 @@ export class RuleTester extends TestFramework {
...
-      assert.strictEqual(
-        result.output,
-        item.code,
-        "The rule fixed the code. Please add 'output' property.",
-      );
+      if (result.outputs.length) {
+        assert.strictEqual(
+          result.outputs[0],
+          item.code,
+          "The rule fixed the code. Please add 'output' property.",
```
Comment (JoshuaKGoldberg) [inline packages/rule-tester/src/RuleTester.ts:1034]:
```suggestion
          "The rule fixed the code. Please add 'output' or 'outputs' property.",
```

File: packages/rule-tester/src/RuleTester.ts
Comment (JoshuaKGoldberg) [inline packages/rule-tester/src/RuleTester.ts:1]: [Docs] https://typescript-eslint.io/packages/rule-tester will need to have a mention of the difference. It's nice that the `raw-loader` usage already pulls in the interface. But I think calling out explicitly that we add the allowance of an array will help people who get confused when ESLint core doesn't have it. WDYT?

**Review by JoshuaKGoldberg — APPROVED** [review]
Looks lovely to me - and great test cases too! 

I think @bradzacher will want to take a look too if he has time, given that he wrote a bunch on the feature requests.

Big Boss from Metal Gear nodding goofily at a computer, then turning to the camera and giving a thumbs up

File: packages/rule-tester/src/RuleTester.ts (hunk 1 above)
Comment (auvred) [reply packages/rule-tester/src/RuleTester.ts:1034]: There is only a publicly visible property `output?: string | string[] | null` :smile: so we can't suggest adding `outputs` property. I think the main confusion here is that `runRuleForItem` now returns an array of `outputs` rather than just the string `output`

File: packages/rule-tester/src/RuleTester.ts
Comment (auvred) [reply packages/rule-tester/src/RuleTester.ts:1]: Ohh, nice catch! I always forget to update the docs!

File: packages/rule-tester/src/RuleTester.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/rule-tester/src/RuleTester.ts:1034]: Oh right sorry 🤦 I meant to delete this comment. Ignore me!

**Review by JoshuaKGoldberg — APPROVED** [review]
Just one small suggestion, looks great to me! 🔥

File: packages/eslint-plugin/tests/util/getWrappingFixer.test.ts [hunk 2]
```diff
@@ -36,7 +36,7 @@ const voidEverythingRule = createRule({
         fix: getWrappingFixer({
           sourceCode: context.sourceCode,
           node,
-          wrap: code => `void ${code}`,
+          wrap: code => `void ${code.replaceAll('wrap', 'wrapped')}`,
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/tests/util/getWrappingFixer.test.ts:39]: not necessarily a problem, but how is this change related? Seems to just add noise to this PR?

File: packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts [hunk 3]
```diff
@@ -409,11 +409,16 @@ declare const nested: string, interpolation: string;
   \`le\${  \`ss\`  }\`
 }\`;
       `,
-      output: `
+      output: [
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts:412]: yeah, as the author of this test case it really bugged me that I had to write this with the first pass only. Very excited to see this feature land!

File: packages/rule-tester/src/RuleTester.ts [hunk 4]
```diff
@@ -573,29 +572,43 @@ export class RuleTester extends TestFramework {
...
+
+      const fatalErrorMessage = messages.find(m => m.fatal);
+      assert(
+        !fatalErrorMessage,
+        `A fatal parsing error occurred: ${fatalErrorMessage?.message}`,
+      );
+
+      fixedResult = SourceCodeFixer.applyFixes(code, messages);
+      if (!messages.length || fixedResult.output === code) {
+        continue;
```
Comment (kirkwaiblinger) [inline packages/rule-tester/src/RuleTester.ts:605]: Question - i'm confused why this line would be a `continue` rather than a `break`. Could you clarify?

File: packages/rule-tester/src/RuleTester.ts [hunk 5]
```diff
@@ -573,29 +572,43 @@ export class RuleTester extends TestFramework {
...
+      }
+      outputs.push((code = fixedResult.output));
```
Comment (kirkwaiblinger) [inline packages/rule-tester/src/RuleTester.ts:607]: (Style preference, optional) 
```suggestion
      code = fixedResult.output;
      outputs.push(code);
```

**Review by kirkwaiblinger — APPROVED** [review]
I _LOVE_ this feature! ❤️ 

Approved pending resolution of comments, which may not require any changes at all. If you do make changes, I think they're simple enough that you have carte blanche from me to merge without an explicit reapproval from me.

File: packages/eslint-plugin/tests/util/getWrappingFixer.test.ts (hunk 2 above)
Comment (auvred) [reply packages/eslint-plugin/tests/util/getWrappingFixer.test.ts:39]: Without this replacement, this rule produces infinite fixers :smile:, because the rule listeners, such as `Identifier[name="wrapMe"]`, still match the `wrap*` node.

File: packages/rule-tester/src/RuleTester.ts (hunk 4 above)
Comment (auvred) [reply packages/rule-tester/src/RuleTester.ts:605]: The while loop will break because `fixedResult.fixed` will be `false` on the next iteration. But yes, I agree, using `break` shows a clearer intent. Thx!

Comment (kirkwaiblinger) [reply packages/rule-tester/src/RuleTester.ts]: TIL that the `continue` in a `do...while` still checks the condition 😆 I thought that 
```ts
do {
    continue;
} while(false);
``` 
would be an infinite loop lol

**Review by kirkwaiblinger — APPROVED** [review]
