### PR TITLE
chore(website): fix playground

### LINKED ISSUE #5572: Website: Playground failing to load
image

The playground is failing to load with the above errors.
Tested in a few browsers and it's consistently failing - so maybe a bundling issue?

We should probably add some smoke tests for this?

### PR DESCRIPTION
**Pull request by bradzacher**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5572
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

There's a lot of unrelated changes in here - it took me a while to really nail down exactly what the problem was. I spent a chunk of time just figuring out how everything worked.

I still don't know *why* it occurred, but for some reason when we upgraded to TS4.8 the website-eslint build started including a dependency that required `os` and `stream` (nodejs modules). Because rollup can't bundle nodejs modules - it assumed they'd be provided later, which they weren't - leading to unresolved imports that (I think) monaco attempted to resolve by loading a script from the server.

Result of testing with this PR locally:
image

### CODE REVIEW

File: packages/website-eslint/rollupConfig.ts [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+          /typescript-estree\/dist\/create-program\/createWatchProgram\.js/,
+          /typescript-estree\/dist\/create-program\/createProjectProgram\.js/,
+          /typescript-estree\/dist\/create-program\/createIsolatedProgram\.js/,
+          /utils\/dist\/ts-eslint\/ESLint\.js/,
+          // 'eslint/lib/shared/ajv.js',
+          // 'eslint/lib/shared/runtime-info.js',
+          /ajv\/lib\/definition_schema\.js/,
+          /stream/,
+          /os/,
+          /fs/,
```
Comment (bradzacher) [inline packages/website-eslint/rollupConfig.ts:38]: fix number 1 - stub out all of these modules.

File: packages/website-eslint/rollupConfig.ts [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+        target: './src/mock/util.js',
+      },
+      {
+        match: /^globby$/u,
+        target: './src/mock/globby.js',
+      },
+      {
+        match: /^is-glob$/u,
+        target: './src/mock/is-glob.js',
+      },
```
Comment (bradzacher) [inline packages/website-eslint/rollupConfig.ts:75]: fix number 2 - stub out globs

`globby`'s dependency tree was the culprit for the native module usage.
we don't actually use globs in the playground config, so it's unnecessary for us to bundle them at all. The mocks just return constant values (see the relevant mock files)

**Review by JoshuaKGoldberg — APPROVED** [review]
Just use Rollup, they said. It won't require configuration, they said!
