### PR TITLE
fix(utils): add defaultOptions to meta in rule

### LINKED ISSUE #10338: Bug: [no-unused-expressions, no-empty-functions, possibly others...] extension rules crash with eslint v9.15.0
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

eslint crashes when using the latest version of node 22 and the latest version of typescript-eslint.

```
Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting /home/ext4cats/Projects/tseslint-8.14.0-bug/index.js
    at Object.create (/home/ext4cats/Projects/tseslint-8.14.0-bug/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/rules/no-unused-expressions.js:75:13)
    at create (/home/ext4cats/Projects/tseslint-8.14.0-bug/node_modules/.pnpm/@typescript-eslint+eslint-plugin@8.14.0_@typescript-eslint+parser@8.14.0_eslint@9.15.0_typesc_u2crwq53uno6k5fweinf7nowby/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-expressions.js:28:32)
    at Object.create (/home/ext4cats/Projects/tseslint-8.14.0-bug/node_modules/.pnpm/@typescript-eslint+utils@8.14.0_eslint@9.15.0_typescript@5.6.3/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:31:20)
    at createRuleListeners (/home/ext4cats/Projects/tseslint-8.14.0-bug/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:944:21)
    at /home/ext4cats/Projects/tseslint-8.14.0-bug/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1082:84
    at Array.forEach (<anonymous>)
    at runRules (/home/ext4cats/Projects/tseslint-8.14.0-bug/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1013:34)
    at #flatVerifyWithoutProcessors (/home/ext4cats/Projects/tseslint-8.14.0-bug/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/home/ext4cats/Projects/tseslint-8.14.0-bug/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1993:49)
    at Linter._verifyWithFlatConfigArray (/home/ext4cats/Projects/tseslint-8.14.0-bug/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:2082:21)
```

### Reproduction Repository Link

https://github.com/ext4cats/tseslint-8.14.0-bug

### Repro Steps

1) clone the repo
2) follow steps in readme

### Versions

| package                                |  version  |
| -------------------------------------- | --------- |
| `typescript-eslint`                    | `8.14.0`  |
| `TypeScript`                           | `5.6.3`   |
| `ESLint`                               | `9.15.0`  |
| `node`                                 | `22.11.0` |

### PR DESCRIPTION
**Pull request by LuisUrrutia**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10338
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

ESLint v9.15.0 introduces default options using the `meta.defaultOptions` property. This PR updates the rules to add `defaultOptions` property to `meta` object, and retains the previous `defaultOptions` placement to ensure backward compatibility.

### CODE REVIEW

File: packages/utils/src/ts-eslint/Rule.ts [hunk 1]
```diff
@@ -65,12 +69,15 @@ export interface RuleMetaData<MessageIds extends string, PluginDocs = unknown> {
    * - `"layout"` means the rule cares primarily about whitespace, semicolons, commas, and parentheses, all the parts of the program that determine how the code looks rather than how it executes. These rules work on parts of the code that aren’t specified in the AST.
    */
   type: 'layout' | 'problem' | 'suggestion';
+
+  defaultOptions?: Options;
```
Comment (bradzacher) [inline packages/utils/src/ts-eslint/Rule.ts:73]: All properties need JSDoc!

```suggestion
  /**
   * Specifies default options for the rule. If present, any user-provided options in their config will be merged on top of them recursively.
   * This merging will be applied directly to `context.options`.
   * If you want backwards-compatible support for earlier ESLint version; consider using the top-level `defaultOptions` instead.
   *
   * @since ESLint 9.15.0
   */
  defaultOptions?: Options;
```

File: packages/utils/src/eslint-utils/RuleCreator.ts [hunk 2]
```diff
@@ -61,15 +62,18 @@ export function RuleCreator<PluginDocs = unknown>(
...
     name,
     ...rule
   }: Readonly<
     RuleWithMetaAndName<Options, MessageIds, PluginDocs>
   >): RuleModule<MessageIds, Options, PluginDocs> {
     return createRule<Options, MessageIds, PluginDocs>({
+      defaultOptions,
       meta: {
         ...meta,
+        defaultOptions,
```
Comment (bradzacher) [inline packages/utils/src/eslint-utils/RuleCreator.ts:76]: It's worth noting that adding this to this function will fix the bug with base rule extensions because our codebase uses the `RuleCreator` function -- but it might leave the broader ecosystem in a weird state.
This will cause all rules to have a different `context.options` value when run under ESLint v9.15.0 -- which could cause breakages in the ecosystem.

For reference -- currently we do not modify the `context.options` value -- meaning it exactly mirrors the value that a user sets in their config file and we instead pass the "merged options" in via a second argument -- `create(context, mergedOptions)`.
So if you pass `meta.defaultOptions` automatically then the first part of this behaviour no longer holds true and instead `context.options` will represent the "merged options".

For now we should leave this function as-is, and instead update our extension rule implementation to pass `defaultOptions` both in the top-level location (for our current rule logic) and in the `meta.defaultOptions` location (for ESLint base rule logic).

File: packages/utils/src/eslint-utils/RuleCreator.ts [hunk 3]
```diff
@@ -13,10 +13,11 @@ export type NamedCreateRuleMetaDocs = Omit<RuleMetaDataDocs, 'url'>;
 
 export type NamedCreateRuleMeta<
   MessageIds extends string,
+  Options extends readonly unknown[],
```
Comment (bradzacher) [inline packages/utils/src/eslint-utils/RuleCreator.ts:16]: Adding this new generic in this location is a breaking change.
It changes the meaning of existing code and could introduce type errors.
Instead it must be added after all type parameters AND it must be given a default value of `[]`

**Review by bradzacher — CHANGES_REQUESTED** [review]
thanks for doing this!
a few comments but it's looking good so far!

**Comment by bradzacher** [comment]
Sorry about the  commit spam.
I tested your PR against 9.15 and found that it introduced some unexpected breakages.
You had applied the `defaultOptions` refactoring to every extension rule.
But this broke certain rules (eg `prefer-destructuring`) due to their more complex schemas!

I just reverted some of the changes you made to limit them to exactly the rules touched in #17656

**Review by bradzacher — APPROVED** [review]
thanks for doing this!
I have tested this against 9.15 and this looks good!

**Comment by pavelkornev** [comment]
When do you plan to release this fix?

**Comment by bradzacher** [comment]
Please see the issue linked in the OP
