### PR TITLE
fix(eslint-plugin): [prefer-regexp-exec] fix heuristic to check whether regex may contain global flag

### LINKED ISSUE #8614: Bug: [prefer-regexp-exec] False positive when regex is an object property
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=MYewdgzgLgBFCmAPWBeGByCIC28oAsBLMAc3QG4AoUSWEAIwCsAuGAbxgngEMAnYfKwBK8EgFFEABxgBfKgmQA6bNygCAFA0aKufAQEpyQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0Wls4DmiAB7F6wxGXRRe0APbRI4MAF8QKoA&tsconfig=&tokens=false

### Repro Code

```TypeScript
const text = 'something';
const obj: { search: RegExp };
text.match(obj.search);
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/prefer-regexp-exec": "error"
  }
}
```

### tsconfig

_No response_

### Expected Result

I expected no error to be reported since the regular expression's flags are unknown, and changing this to `String#match` may change runtime behavior.

### Actual Result

An error was reported
> Use the `RegExp#exec()` method instead. 3:6 - 3:11

### Additional Info

Related to https://github.com/typescript-eslint/typescript-eslint/issues/3477#issuecomment-922385173

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8614 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Changes the heuristic to say "if we don't know what it is, it could have the global flag". Note that it could also be tricked into falsely flagging on factory functions that return a regexp, since the heuristic inspects the second argument without checking what function it's inspecting. That has been made more strict.

See [examples in the playground](https://typescript-eslint.io/play/#ts=5.4.2&fileType=.tsx&code=CYUwxgNghgTiAEYD2A7AzgF3hkAPDAXPJjAJYoDmA3AFA0D09xGArgGZvYAWCMLECYEhBp4ZCl0J0c%2BAHQBbKBjBcAFPTRck-YPDbQKAGngokWChCQAjKBHoBKWjIwKlK9Zu0RgKAORZ9KCN4UlELa1t6CkdpPBdFZTUAJRAKAFFcAAdVX08dPQNjU3NLGwhfY19fe3saZ1dE1RT0rJy87xQAHX8CoONQ%2BHCyivhfCmramlBIWARkdCx2nwwAMQMAQQA1WFIoKwEiZozMpziG9yWUVY3tsj2BScZuAYGAdx44bgQ2FhR4K1S5DQBDo02gn3mmDEIEOqWOtCeABUeIgoGhvjAkPIviE0GgWCA6mcEu4AN7ELQ6K5rIJET4AX1kl2uQRiU3A4O%2BvzAGFIqGhrBg6GaeFUuCIKBY8gBMGMAE8iCRyNFYS0TnQnpceoEKPAALRifiCYRoPxYADWple8CgKDlGC4yptVm0WAd3wMaFkRLkJLUcEFwtSooALAAmSoTBFMLUBAz6m0oXTuw0CG1gMCkUBXWwQOWDEAYUQOgbiSQAQngACFwFAWOiQlghCIzQwmHBbKQAF4IUgYXImMzwSxIc1OpQ4uAUPCZRCoEgsHlIGA%2B%2BJuf2FlhCtAi3CqcOVcY1WhAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0Wls4DmiAB7F6wxGXRRe0APbRI4MAF8QKoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

### CODE REVIEW

File: packages/eslint-plugin/src/rules/prefer-regexp-exec.ts [hunk 1]
```diff
@@ -72,22 +72,24 @@ export default createRule({
       return result;
     }
 
-    function isLikelyToContainGlobalFlag(
+    function provablyDoesNotContainGlobalFlag(
```
Comment (Josh-Cena) [inline packages/eslint-plugin/src/rules/prefer-regexp-exec.ts:75]: I read this as "probably" on first sight, and was like "okay so it's still guesswork?" 😅

Maybe "definitely" is better, or not have the adverb at all? IDK

Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/prefer-regexp-exec.ts]: Reasonable. Changed it up a bit, hopefully that is a little more clear at a glance 👍

**Review by auvred — APPROVED** [review]
LGTM! :fire:
