### PR TITLE
fix(typescript-estree): specific error for parserOptions.project not including a file

### LINKED ISSUE #9096: Bug: [v8.0.0-alpha.10] incorrect error message `Parsing error: "parserOptions.programs"`
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

_Bug discussed and confirmed by @JoshuaKGoldberg and @bradzacher._

Config working with `typescript-eslint` v7.9.0 does not work with v8.0.0-alpha.10, raising:
```
/Users/<...>/eslint.config.js
  0:0  error  Parsing error: "parserOptions.programs" has been provided for @typescript-eslint/parser.
The file was not found in any of the provided program instance(s): eslint.config.js
```
although I don't use any home-made program.

Potential culprit: https://github.com/typescript-eslint/typescript-eslint/pull/8834/files

### Reproduction Repository Link

https://github.com/OlivierZal/melcloud-api/blob/e118342a2ce16c49e41e145844bc318e344cfe52/eslint.config.js

### Repro Steps

1) `git clone https://github.com/OlivierZal/melcloud-api`
2) `git co e118342a2ce16c49e41e145844bc318e344cfe52`
3) `eslint .`
4) `npm i typescript-eslint@8.0.0-alpha.10 --force`
5) `eslint .`
6) compare the 2 outputs (see attached screenshots: v7.9.0 vs v8.0.0-alpha)

v7
v8

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.0.0-alpha.10` |
| `TypeScript`                           | `5.4.5` |
| `ESLint`                               | `9.2.0` |
| `node`                                 | `22.1.0` |

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9096
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

When `parseSettings.projects` is populated, `useProvidedPrograms` nows refer to `parserOptions.project` and `project(s)` instead of `parserOptions.programs` and `program(s)`.

Also applies a mild refactor to reduce nesting in the function.

I think after this I'd like to holistically revamp the error messages around invalid 

💖

### CODE REVIEW

File: packages/typescript-estree/src/create-program/useProvidedPrograms.ts [hunk 1]
```diff
@@ -5,45 +5,49 @@ import * as ts from 'typescript';
...
-
-    throw new Error(errorLines.join('\n'));
+  if (astAndProgram) {
+    astAndProgram.program.getTypeChecker(); // ensure parent pointers are set in source files
+    return astAndProgram;
   }
 
-  astAndProgram.program.getTypeChecker(); // ensure parent pointers are set in source files
+  const relativeFilePath = path.relative(
+    parseSettings.tsconfigRootDir,
```
Comment (JoshuaKGoldberg) [inline packages/typescript-estree/src/create-program/useProvidedPrograms.ts:36]: This used to be `tsconfigRootDir || process.cwd()`, but I'm pretty sure that's unnecessary. `createParseSettings` already defaults `tsconfigRootDir` to `process.cwd()`.

File: packages/website/src/hooks/useClipboard.ts [hunk 2]
```diff
@@ -9,7 +9,7 @@ export function useClipboard(code: () => string): useClipboardResult {
 
   const copy = useCallback(
     () =>
-      void navigator.clipboard.writeText(code()).then(() => {
+      navigator.clipboard.writeText(code()).then(() => {
```
Comment (JoshuaKGoldberg) [inline packages/website/src/hooks/useClipboard.ts:12]: This is also in the `v8` branch. GitHub just isn't updating...

**Review by bradzacher — APPROVED** [review]
