### PR TITLE
fix(eslint-plugin): [no-unnecessary-condition] handle comparison of any, unknown and loose comparisons with nullish values

### LINKED ISSUE #2113: [no-unnecessary-condition] `== null` against optional method param no longer allowed
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-unnecessary-condition": "error",
    "eqeqeq": ["error", "smart"],
  }
}
```

```TS
function foo(bar?: string) {
  if (bar != null) {
    // ^ "unnecessary condition"
  }
}
```

**Expected Result**
`== null` should be permitted against a `T?` value, especially when `eqeqeq` is set to `smart`.

**Actual Result**
A value that may be `undefined` cannot be `== null`.

**Rationale**
`== undefined` violates `eqeqeq=smart`. `===` against either one is less convenient and less safe at runtime where the distinction between them is rarely meaningful anyway. `== null` is the shortest to read/write and the most familiar idiom from other programming languages.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.0.1` |
| `@typescript-eslint/parser`        | `3.0.1` |
| `TypeScript`                       | `3.9.3` |
| `ESLint`                           | `7.1.0` |
| `node`                             | `13.14.0` |
| `yarn`                              | `1.22.4` |

### PR DESCRIPTION
**Pull request by umidbekkarimov**
, unknown and nullish values (closes #2113)

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 1]
```diff
@@ -14,6 +13,7 @@ import {
   isStrictCompilerOptionEnabled,
 } from 'tsutils';
 import {
+  isTypeFlagSet,
```
Comment (umidbekkarimov) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:16]: I needed that to have access to `isReceiver` option.

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 2]
```diff
@@ -267,13 +264,20 @@ export default createRule<Options, MessageId>({
...
+
+        const NULLISH =
+          node.operator === '==' || node.operator === '!='
+            ? NULL | UNDEFINED
+            : NULL;
+
         if (
           (leftType.flags === UNDEFINED &&
-            !typeContainsFlag(rightType, UNDEFINED)) ||
+            !isTypeFlagSet(rightType, UNDEFINED, true)) ||
```
Comment (Retsam) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:275]: It's niche, but we might want similar "NULLISH" handling for the `== undefined` case, otherwise the error will false positive on code like:

```ts
function foo(x: string | null) {
    if(x == undefined) {}
}
```
