### PR TITLE
fix(eslint-plugin): [no-duplicate-type-constituents] shouldn't report on error types

### LINKED ISSUE #9576: Bug: [no-duplicate-type-constituents] Shouldn't report on error types
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.2&fileType=.ts&code=C4TwDgpgBAKlC8UCCUA%2ByDcAoIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oBNZjGyAQ3yJaRUrTIcmyfJXyxELVBkiJo0DtEjgwAXxB6gA&tsconfig=&tokens=false

### Repro Code

```TypeScript
type T = A | A;
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-duplicate-type-constituents": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

When types are _error_ types, they shouldn't be factored into rules that check type equality.

### Actual Result

We still get an error even though the types are errors.

### Additional Info

Previously mentioned by @bradzacher in https://github.com/typescript-eslint/typescript-eslint/issues/9344#issuecomment-2164770946.

💖

### PR DESCRIPTION
**Pull request by y-hsgw**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9576 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

- Fixed to not report errors.
- Minor refactor.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts [hunk 1]
```diff
@@ -50,18 +51,13 @@ const isSameAstNode = (actualNode: unknown, expectedNode: unknown): boolean => {
...
-      return false;
-    }
-    return true;
+    return !actualNodeKeys.some(
+      actualNodeKey =>
+        !isSameAstNode(
+          actualNode[actualNodeKey as keyof typeof actualNode],
+          expectedNode[actualNodeKey as keyof typeof expectedNode],
+        ),
+    );
```
Comment (auvred) [inline packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts:60]: These changes don't seem to be related to the issue this PR solves?

File: packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts [hunk 2]
```diff
@@ -111,6 +107,13 @@ export default createRule<Options, MessageIds>({
       const cachedTypeMap = new Map<Type, TSESTree.TypeNode>();
       node.types.reduce<TSESTree.TypeNode[]>(
         (uniqueConstituents, constituentNode) => {
+          const constituentNodeType = checker.getTypeAtLocation(
+            parserServices.esTreeNodeToTSNodeMap.get(constituentNode),
+          );
```
Comment (auvred) [inline packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts:112]:
```suggestion
          const constituentNodeType = parserServices.getTypeAtLocation(constituentNode);
```

`ParserServices` has a nice utility function to do this :)

File: packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts [hunk 3]
```diff
@@ -111,6 +107,13 @@ export default createRule<Options, MessageIds>({
...
+          if (tsutils.isIntrinsicErrorType(constituentNodeType)) {
+            return [];
+          }
```
Comment (auvred) [inline packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts:115]:
```suggestion
          if (tsutils.isIntrinsicErrorType(constituentNodeType)) {
            return uniqueConstituents;
          }
```

As I understand this logic, `uniqueConstituents` is a kind of cache for finding duplicates using only AST (since it's faster than calling a checker to make type-level comparisons). See this comment https://github.com/typescript-eslint/typescript-eslint/pull/5728#discussion_r1083520606

If we return an empty array, we discard all previously found unique constituents and fallback to type-level checks, this may result in some performance penalty.

File: packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts [hunk 4]
```diff
@@ -275,19 +278,6 @@ type ActuallyDuplicated = IsArray<number>  ;
...
-      errors: [
-        {
-          messageId: 'duplicate',
-          data: {
-            type: 'Union',
-            previous: 'Class<string>',
-          },
-        },
-      ],
-    },
```
Comment (auvred) [inline packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts:290]: [Testing] If this case is no longer reported as an error, let's just move it to the `valid` section instead of deleting it?

File: packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts
Comment (auvred) [inline packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts:1]: [Testing] It would be great if we had some test cases (both valid and invalid) that mix error types with normal types

**Review by auvred — CHANGES_REQUESTED** [review]

File: packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts (hunk 1 above)
Comment (y-hsgw) [reply packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts]: I thought it was minor, so I went ahead and fixed it.
However, as you mentioned, it's unrelated to this PR, so I reverted it.
[1560c83](https://github.com/typescript-eslint/typescript-eslint/pull/9600/commits/1560c83b826f50daace5593acda28bbb307cae77)

File: packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts (hunk 2 above)
Comment (y-hsgw) [reply packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts]: Nice! Thank you :) Fixed in [fc5d5d8](https://github.com/typescript-eslint/typescript-eslint/pull/9600/commits/fc5d5d827c435cb07259f2f3b707174d6d1daa71).

File: packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts (hunk 3 above)
Comment (y-hsgw) [reply packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts]: Thank you for the guidance. Fixed in 6683e36.

File: packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts (hunk 4 above)
Comment (y-hsgw) [reply packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts:290]: Indeed, that's correct. I moved the tests in [3cf71ad](https://github.com/typescript-eslint/typescript-eslint/pull/9600/commits/3cf71add098ede30ecd2ace0b4c857737ca65ded).

File: packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts
Comment (y-hsgw) [reply packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts:1]: I added the tests in 3cf71ad.

**Review by auvred — APPROVED** [review]
:fire:

**Review by JoshuaKGoldberg — APPROVED** [review]
Woop, thanks!
