### PR TITLE
fix(eslint-plugin): [no-deprecated] report on deprecated properties with function-like types

### LINKED ISSUE #9970: Bug: [no-deprecated] fails on declared instances
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&showAST=es&fileType=.tsx&code=PTAEFpK6du4LAChnAFRtAAQCYFMAHAJzwGMBDAFzx1DWGQDMBXAO1MoEsB7V0AZ24BbPADE2HHqwAUASlABvAL7JBI8ey685AblAhQAdW5EA1vwA0ocv1B4AHgTLUcAOmSow8bz-gek%2BKQANuQkoJys1ESM5KR4oADKwngAkpF40bHxCsig%2BhjY%2BMRkVDR0DEh5SSIAsniUABbcOABcoHKgALwAfKAAbtycODrIKigBZCFhpLz8lALJaVExcW3VqemZcSPjahvLWa7rdY3NuvpgouRB-PGseADmVJx9eACEyEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oBNFjpEZAIb5E3dFETRoHaJHBgAviGVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

See the playground link above.

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9970
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

```ts
declare interface SomeInterface {
  /** @deprecated */
  property: () => void;

  /** @deprecated */
  method(): void;
}

declare const someInterface: SomeInterface;
someInterface.property(); // ❌ missing error
someInterface.method(); // ✅ errors
```

Both `property` and `method` identifiers have call signatures, but:
- `method` has `"deprecated"` jsdoc tag on its **signature**
- `property` has `"deprecated"` jsdoc tag on its **symbol**

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-deprecated.ts [hunk 1]
```diff
@@ -174,15 +174,32 @@ export default createRule({
...
           return signatureDeprecation;
         }
+
+        // Properties with function-like types have "deprecated" jsdoc
+        // on their symbols, not on their signatures:
+        //
+        // interface Props {
+        //   /** @deprecated */
+        //   property: () => 'foo'
+        //   ^symbol^  ^signature^
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-deprecated.ts:190]: (praise) Immensely helpful comment 🫶

**Review by JoshuaKGoldberg — APPROVED** [review]
+1, this is good nuance to note!

**Review by kirkwaiblinger — APPROVED** [review]
