### PR TITLE
fix(eslint-plugin): [no-extra-parens] keep parens around call expression arguments when type arguments contain parens

### LINKED ISSUE #7030: Bug: [no-extra-parens] False positive when calling generic function with type tuple parameter containing parenthesis
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.0.4&sourceType=module&code=CYUwxgNghgTiAEYD2A7AzgF3hkmBc8A3gFDzwhRgAWBJZZAPAIIwDma5AHjisBwK4oA1iiQB3FAG0AugD4AFLBgEW7GQEoC8jAEsMEEAUwwdKVgBp4AMxRaAdA9jsVbNOvgBeWfABuSHcDuXr7+wKTwAL7EUcQ4mHYU1AySTgCMWij8ALYARiAw8AA+8MamrOoylk4ATASZufly8pLhkpKp0pbVna2SAOTVfZ3wAMzSxNLq8n26+iB9lopsqVVs1UHedPDR6sRAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge3oA99oBDWsX7RETVBkiJo0DtEjgwAXxBKgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
declare const test: {
  each: {
    <Args extends unknown[]>(arr: Args[]): (title: string, fn: (...args: Args) => void) => void
  }
}

test.each<[arg1: (number | string)[], arg2: number]>([
  [[1], 2],
  [['2'], 3]
])('title', (arg1, arg2) => {
  
})
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-extra-parens": "error"
  }
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

No error

### Actual Result

Unnecessary parentheses around expression. 7:53 - 7:54

### Additional Info

Similar to #5488, but more sophisticated issue found while writing tests with jest.

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #7030
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This issue has a long story

After a little investigation I restored the chronology of changes:

1) This PR introduced fix for this issue https://github.com/typescript-eslint/typescript-eslint/pull/2319. Everything worked fine, and there was even a test case for such a situation
  https://github.com/typescript-eslint/typescript-eslint/pull/2319/files#diff-fbb45da7466e6a089a93155bac8bc3e3e16758e9ec33d941286852ed7d64f48bR31

2) In this PR (https://github.com/typescript-eslint/typescript-eslint/pull/3340) the `TSParenthesizedType` was removed 
  https://github.com/typescript-eslint/typescript-eslint/pull/3340/files#diff-a916a57c423a9435766d31cbea70b6434185d7f227eaff16df942efaab05b08bR86-R88
  The corresponding test case was also changed (I think this is a kind of regression)
  https://github.com/typescript-eslint/typescript-eslint/pull/3340/files#diff-fbb45da7466e6a089a93155bac8bc3e3e16758e9ec33d941286852ed7d64f48bR30-R32

3) There was added check for `TSArrayType` https://github.com/typescript-eslint/typescript-eslint/pull/5550. But as far as I understand it was just the edge case, because the same code without an array `[]` turns into a broken one

---

I couldn't find any other way to fix this problem other than checking if there any opening parenthesis between `node.callee` and first argument (`node.arguments[0]`). Otherwise `eslint/no-extra-parens` [treats it](https://github.com/eslint-community/eslint-utils/blob/0c552db0239a75bdbf4cae03dfd18214d43697b8/src/is-parenthesized.mjs#L14-L22) as an opening parenthesis for the arguments list 

_Many thanks to this explanation https://github.com/typescript-eslint/typescript-eslint/issues/2314#issue-662875833_

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-extra-parens.ts [hunk 1]
```diff
@@ -27,6 +27,8 @@ export default util.createRule<Options, MessageIds>({
   },
   defaultOptions: ['all'],
   create(context) {
+    const sourceCode = context.getSourceCode();
+
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-extra-parens.ts:31]: [Nitpick] No real need for this blank line...

```suggestion
```

**Review by JoshuaKGoldberg — DISMISSED** [review]
What a great PR description - thanks both for the fix and excellent writeup @auvred! 

Ryan Gosling happily clapping

**Review by JoshuaKGoldberg — APPROVED** [review]
