### PR TITLE
fix(eslint-plugin): [unified-signatures] no parameters function

### LINKED ISSUE #6882: Bug: [unified-signatures] Crash in rule implementation
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&showAST=es&code=KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAFWDTgG8BYAKDkVXS3gFtgYALCAEwAoAzfAHMAXHHQBXYAEoxAOwkskwKAG5a9ZGgzY4bTj16y42gJZyh6mgF9aQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6WJygM0sQBNaySgHMmAQ3yxoKdGADakRNGgB7aJAA0mKCKZrEAEW5cliFvEIA5MQFt+ABTHRbifEtQZ8cRGAC+AXXA-EF8gA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
export abstract class Test {
    abstract method(flag: true): number;
    abstract method(): string;
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/unified-signatures": ["error", { ignoreDifferentlyNamedParameters: true }],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strict": true
  }
}
```

### Expected Result

Linter should pass.

### Actual Result

```
Oops! Something went wrong! :(

ESLint: 8.38.0

TypeError: Cannot read properties of undefined (reading 'type')
Occurred while linting test.ts:13
Rule: "@typescript-eslint/unified-signatures"
    at signaturesCanBeUnified (./node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:146:58)
    at compareSignatures (./node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:133:18)
    at ./node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:124:35
    at forEachPair (./node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:311:21)
    at checkOverloads (./node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:120:17)
    at checkScope (./node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:328:30)
    at ruleErrorHandler (./node_modules/eslint/lib/linter/linter.js:1077:28)
    at ./node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (./node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

### Additional Info

Happens only with option "ignoreDifferentlyNamedParameters".

### PR DESCRIPTION
**Pull request by oxyu8**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6882 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Add guard clause because b.params[i].type is not accessible when comparing to a function with no parameters

### CODE REVIEW

File: packages/eslint-plugin/src/rules/unified-signatures.ts [hunk 1]
```diff
@@ -213,6 +213,9 @@ export default util.createRule<Options, MessageIds>({
         b.typeParameters !== undefined ? b.typeParameters.params : undefined;
 
       if (ignoreDifferentlyNamedParameters) {
+        if (b.params.length === 0) {
+          return false;
+        }
```
Comment (Josh-Cena) [inline packages/eslint-plugin/src/rules/unified-signatures.ts:218]: You need to check that _every_ `b.params[i]` is defined. [Test case](https://deploy-preview-6940--typescript-eslint.netlify.app/play/#ts=5.0.4&sourceType=module&code=GYVwdgxgLglg9mABMAFANwFyIEZzgGwFMBDMAGkWK1wJLAEoswQBbbQgJwG4AoUSWAmTpqeIqUaIAzlA4wwAc15A&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6WJygM0sQBNaySgHMmAQ3yxoKdGADa4bDkTRoAe2iQANIqVYl2SCKYbEAEW5cViFvEIA5MQFt+ABTHRnifCtQZ8cIi62AC+wQC6imEhQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

Comment (oxyu8) [reply packages/eslint-plugin/src/rules/unified-signatures.ts]: @Josh-Cena 
I fixed it in 47286f7

File: packages/eslint-plugin/src/rules/unified-signatures.ts [hunk 2]
```diff
@@ -215,6 +215,7 @@ export default util.createRule<Options, MessageIds>({
       if (ignoreDifferentlyNamedParameters) {
         for (let i = 0; i < a.params.length; i += 1) {
           if (
+            b.params[i] &&
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/unified-signatures.ts:218]: [Refactor] Asking for an element out of bounds of an array is a little confusing. It looks like this code is asking whether `b.params[i]` is a falsy element - even though the type of `b.params` indicates that not to be doable. I'm also under the impression accessing elements out of an array's bounds can cause a performance deoptimization (though this code almost certainly wouldn't suffer meaningfully).

I think a more proper fix would be capping the `i` to `Math.min(a.params.length, b.params.length)`.

**Review by JoshuaKGoldberg — DISMISSED** [review]
LGTM, thanks for the fix!

I'll just apply a quick lil refactor myself - the code & tests look great. Cheers!

File: packages/eslint-plugin/src/rules/unified-signatures.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/unified-signatures.ts]: Just applied - normally I'd let you have the pleasure, but I feel bad taking up your time on such a small change 😄

**Comment by JoshuaKGoldberg** [comment]
(sorry for jumping in @Josh-Cena - really want this merged in time for our Monday release)
