### PR TITLE
fix(eslint-plugin): [explicit-function-return-type] make error location smaller

### LINKED ISSUE #882: [@typescript-eslint/explicit-function-return-type] Error too big
I'm not entirely sure if this is an issue with this plugin, or with VS Code, but I assume it is with the plugin as I'm guessing VS Code just underlines what it's told to.

The issue is that `@typescript-eslint/explicit-function-return-type` will make VS Code highlight _everything_ in the _whole_ function. This makes it hard/impossible to see _other_ issues with the function, and it also adds a lot of noise when hovering over stuff to for example see the type of a variable or such. As seen in example below, it's very noisy. The issue with "implicit any" for the `response` parameter is hard to see, and when hovering over response further down, instead of just seeing the type, you also get a big ugly error which belongs to the function, and not the value being hovered over.

image

Is it possible to change the reporting of this rule so that it's less noisy in editors? Maybe it could just highlight the function name? Or the signature, which should work for unnamed arrow functions as well? Or something? 🤔

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #882

### CODE REVIEW

File: packages/eslint-plugin/src/rules/explicit-function-return-type.ts [hunk 1]
```diff
@@ -57,6 +58,53 @@ export default util.createRule<Options, MessageIds>({
...
+      /* highlight `=>` */
+      if (node.type === AST_NODE_TYPES.ArrowFunctionExpression) {
+        return sourceCode.getTokenBefore(
+          node.body,
+          token =>
+            token.type === AST_TOKEN_TYPES.Punctuator && token.value === '=>',
+        )!.loc.end;
+      }
+
+      return sourceCode.getTokenBefore(node.body!)!.loc.start;
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/explicit-function-return-type.ts]: Your logic for non-arrow functions is 1 character off:
image

This will fix the end position so it aligns with the closing paren.
Don't forget to update the test's `endColumn` to match!

```suggestion
      return sourceCode.getTokenBefore(node.body!)!.loc.end;
```

File: packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts [hunk 2]
```diff
@@ -328,29 +328,31 @@ const func = (value: number) => x as const;
...
-    return;
+  return;
 }
       `,
       errors: [
         {
           messageId: 'missingReturnType',
           line: 2,
           column: 1,
+          endColumn: 15,
```
Comment (bradzacher) [inline packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts]: I know it'll be annoyingly verbose, but for sanity checking, could you please also add `endLine` to these tests.

I just wanna be 100% sure that nobody accidentally does something weird to break it in future :)

Comment (a-tarasyuk) [reply packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts]: @bradzacher Sure :+1:
