### PR TITLE
fix(eslint-plugin): [no-deprecated] ignore deprecated `export import`s

### LINKED ISSUE #11586: Bug: [no-deprecated] `export import` marked as deprecated at definition
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.8.2&fileType=.tsx&code=HYQwtgpgzgDiDGEAEAxA9mpBvAvgWAChCB6AKlMKVKQAEATCGAJwnhABcI7LTjCIAHjDRN2SAJZhhopACEQTJAF5UGANxA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oBNFjpEZAIb5E3dFETRoHaJHBgAviEVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
namespace Foo {}

/**
 * @deprecated
 */
export import Bar = Foo;
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-deprecated": "error"
  }
}
```

### tsconfig

```jsonc
{}
```

### Expected Result

No error, this is the definition site at which `Bar` is marked deprecated.

### Actual Result

Got the error "`Bar` is deprecated." despite this being the definition.

### Additional Info

This regressed between 8.42.0 and 8.43.0. If I had to guess it broke in #11359. There did seem to be a number of good updates that caught other no-deprecated violations but the re-export isn't of a deprecated symbol so it doesn't seem like this case should be a violation.

### PR DESCRIPTION
**Pull request by mainframev**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11586
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

PR enhances the `no-deprecated` ESLint rule to better handle `TSImportEqualsDeclaration`, specifically cases like `export import Bar = Foo;`

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-deprecated.ts [hunk 1]
```diff
@@ -157,6 +157,10 @@ export default createRule<Options, MessageIds>({
         case AST_NODE_TYPES.TSTypeParameter:
           return true;
 
+        // treat `export import Bar = Foo;` (and `import Foo = require('...')`) as declarations
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-deprecated.ts:160]: drive-by comment: Could you also add a test case for the `import x = require(...)` case? 🙏 Thanks!

Comment (mainframev) [reply packages/eslint-plugin/src/rules/no-deprecated.ts:160]: updated ;)

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 thanks!
