### PR TITLE
fix(ast-spec): cleanup `TSLiteralType`

### LINKED ISSUE #11587: Enhancement(AST): Cleanup `TSLiteralType`
### Before You File a Proposal Please Confirm You Have Done The Following...

- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [x] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### My proposal is suitable for this project

- [x] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Currently `TSLiteralType` is typed to accept `Literal | TemplateLiteral | UnaryExpression | UpdateExpression`
https://github.com/typescript-eslint/typescript-eslint/blob/ef9173c56fa488737bff9ab463338ea65cb83373/packages/ast-spec/src/type/TSLiteralType/spec.ts#L7-L10

However this is unnecessarily permissive ([playground](https://typescript-eslint.io/play/#ts=5.3.3&showAST=es&fileType=.tsx&code=C4TwDgpgBAaghgGwJYBMAqBlAMk4EBOia40AvFANoCwAUFFAORwMA0t9ABnB23VAIy96-AHQAGIVAC0g9gIB2kmYrnB8AVwiSAZogDOW2gF0A3LVoB6C1ADywABYEoOPIQR7aoSFEwA5dQgIANIQIADuAPb4KFDk8gEIZjRWUF7QAApw%2BAb4AKL4%2BFGxUBZwFklpPhhoEAC2YAhweC4ERCTFXAAkAN4MAEYMAL4cSZbWAKryWSC5AB5g%2BBB6ekgR8p7tmMSQAIqa%2BCDFaRHaUACycGAV7Rh1cPLASADG%2BYX4-MUAhPxJKZWZ2QIryK5AA1Px5L9rP8sjlgfhiuDxFDUu0AXCCiCoOCUTDAXlMQjyAA3CKoAS4tGwoGE4ooCAICB4CljVHedE0t7FAB%2BP3MyQmYBQTQgcwWSxWa1ZeIxXLBOOlVPx8OKUhkoxoQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)):
- You cannot have `null` literals -- that is instead a `TSNullKeyword`
- You cannot have Regex literals -- they are currently a hard TS parser error
- You cannot have any `UnaryExpression` -- the only allowable operator is `-` for negative numbers -- `type T = -1` / `type U = -1n`
- You cannot have any `UpdateExpression`s -- `++` and `--` are both hard TS parser errors

Proposal:
- Remove `UpdateExpression` from the type
- Refine the `Literal` union to just the valid literals
- Refine the `UnaryExpression` to just the valid operators

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by abrahamguo**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11587
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

From @bradzacher's proposal in #11587:

- Remove `UpdateExpression` from the type
- Refine the `Literal` union to just the valid literals
- Refine the `UnaryExpression` to just the valid operators

### CODE REVIEW

File: packages/ast-spec/src/type/TSLiteralType/spec.ts [hunk 1]
```diff
@@ -1,10 +1,13 @@
...
 import type { UnaryExpression } from '../../expression/UnaryExpression/spec';
-import type { UpdateExpression } from '../../expression/UpdateExpression/spec';
 import type { LiteralExpression } from '../../unions/LiteralExpression';
 
 export interface TSLiteralType extends BaseNode {
   type: AST_NODE_TYPES.TSLiteralType;
-  literal: LiteralExpression | UnaryExpression | UpdateExpression;
+  literal:
+    | Exclude<LiteralExpression, NullLiteral | RegExpLiteral>
+    | (UnaryExpression & { operator: '+' | '-' });
```
Comment (JoshuaKGoldberg) [inline packages/ast-spec/src/type/TSLiteralType/spec.ts]: Thinking: maybe this should be its own type? `UnaryLiteralExpression` or some name like that?

I'm not sure. This isn't a request, just ideation.

Comment (abrahamguo) [reply packages/ast-spec/src/type/TSLiteralType/spec.ts]: I'm not seeing any other places in the codebase that this type would be needed.

Is there any precedent for other such types?

Comment (bradzacher) [reply packages/ast-spec/src/type/TSLiteralType/spec.ts]: We could define one interface per operator, then change `UnaryExpression` to a type alias that is a union of all of those.

That way here we could just reference the relevant interfaces rather than the entire union.

This is the same sort of thing we've done for other places that have a known set of variants.

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 love it, thanks!

**Review by bradzacher — APPROVED** [review]
nice -- thanks!
