### PR TITLE
fix(eslint-plugin): [no-base-to-string] check if superclass is ignored

### LINKED ISSUE #11520: Bug: [no-base-to-string] should check if superclass is ignored
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.9.2&fileType=.ts&code=JYOwLgpgTgZghgYwgAgLIE8CiUoHsrIQAekIAJgM7LZ4EDeyAvgFDNkQIA2cUKCuICmEI58ALjRZRUANzNotAHRhcAZTBRQAcwAUAShlA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oCMBDZRLXxdk%2BKkwDm6MAG1w2HImjQO0SABp5CrAuyRKEztEQATAColEAOV4BbFNLm7dkAKLLVkLboC63iAC%2B3n6BIAFAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
interface MyError extends Error { }

declare const error: MyError;
error.toString();
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-base-to-string": [
      "error",
      {
        "ignoredTypeNames": [
          "Error"
        ]
      }
    ]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

There should be no lints.

### Actual Result

```
'error' will use Object's default stringification format ('[object Object]') when stringified. 4:1 - 4:6
```

### Additional Info

There is some discussion in https://github.com/typescript-eslint/typescript-eslint/issues/11420

### PR DESCRIPTION
**Pull request by thebolarin**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11520
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Added isIgnoredTypeOrBase to ensure that a type’s superclass or extended interfaces are properly checked against the ignored types list.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-base-to-string.ts [hunk 1]
```diff
@@ -205,6 +205,37 @@ export default createRule<Options, MessageIds>({
       return Usefulness.Always;
     }
 
+    function hasBaseTypes(type: ts.Type): type is ts.InterfaceType {
+      return (
+        (type.flags & ts.TypeFlags.Object) !== 0 &&
+        (((type as ts.ObjectType).objectFlags & ts.ObjectFlags.Interface) !==
+          0 ||
+          ((type as ts.ObjectType).objectFlags & ts.ObjectFlags.Class) !== 0)
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-base-to-string.ts]: [Refactor] This can be rewritten with fewer characters and a bit more type safety:

```suggestion
        tsutils.isObjectType(type) &&
        tsutils.isObjectFlagSet(
          type,
          ts.ObjectFlags.Interface | ts.ObjectFlags.Class,
        )
```


#11625

File: packages/eslint-plugin/src/rules/no-base-to-string.ts [hunk 2]
```diff
@@ -205,6 +205,37 @@ export default createRule<Options, MessageIds>({
...
+      const typeName = getTypeName(checker, type);
+      let result = ignoredTypeNames.includes(typeName);
+
+      if (!result && hasBaseTypes(type)) {
+        result = checker
+          .getBaseTypes(type)
+          .some(base => isIgnoredTypeOrBase(base, seen));
+      }
+
+      return result;
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-base-to-string.ts]: [Refactor] The current code was a little confusing to me at first. But it actually reduces down nicely:

```suggestion
      return !!(
        ignoredTypeNames.includes(typeName) ||
        type.getBaseTypes()?.some(base => isIgnoredTypeOrBase(base, seen))
      );
```

**Comment by thebolarin** [comment]
@JoshuaKGoldberg Thanks for the review. I've also pushed a commit to adopt your suggestions

**Comment by webmaster128** [comment]
💐
