### PR TITLE
fix(eslint-plugin): [consistent-type-exports] check value flag before resolving alias

### LINKED ISSUE #11761: Bug: [consistent-type-exports] Importing a shadowing type breaks consistent-type-imports/exports
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

The following piece of code has two issues:

```ts
import { SomeThing } from './types.js';

const SomeThing = { foo: 'bar' };

export { SomeThing };
```

Firstly, it does not flag that `import { SomeThing } from './types.js';` should be `import { type SomeThing } from './types.js';` (problem with `consistent-type-imports`).

Secondly, it does error with "All exports in the declaration are only used as types.", even though the export is very clearly _not_ a type.

This issue manifested itself in v8.43.0. I suspect it is a regression to do with https://github.com/typescript-eslint/typescript-eslint/pull/11457

### Reproduction Repository Link

https://github.com/simon-abbott/ts-eslint-issue-mre-import-shadowing

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run lint`

Running `npm run lint` _should_ error on the `import` in `src/index.ts`, and _should not_ error on the export. Instead it does the reverse.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.46.4` |
| `@typescript-eslint/parser`            | `8.46.4` |
| `TypeScript`                           | `5.9.2` |
| `ESLint`                               | `8.57.1` |
| `node`                                 | `22.19.0` |

### PR DESCRIPTION
**Pull request by ntdiary**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11761
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Make sure the current symbol doesn't have `SymbolFlags.Value` before resolving alias.

I submit the recursive version here, which is just 1 line shorter than the `while` iteration.
If we prefer using iteration, can be done like this:

```ts
while (symbol && !checker.isUnknownSymbol(symbol)) {
  if (
    symbol.getDeclarations()?.some(ts.isTypeOnlyImportOrExportDeclaration)
  ) {
    return true;
  }
  if (symbol.flags & ts.SymbolFlags.Value) {
    return false;
  }
  if (!(symbol.flags & ts.SymbolFlags.Alias)) {
    return true;
  }
  symbol = checker.getImmediateAliasedSymbol(symbol)
}
return undefined;
```
💖

### CODE REVIEW

File: packages/eslint-plugin/src/rules/consistent-type-exports.ts [hunk 1]
```diff
@@ -90,18 +90,20 @@ export default createRule<Options, MessageIds>({
...
+      if (
+        symbol.getDeclarations()?.some(ts.isTypeOnlyImportOrExportDeclaration)
+      ) {
+        return true;
+      }
+      if (symbol.flags & ts.SymbolFlags.Value) {
+        return false;
+      }
+      return symbol.flags & ts.SymbolFlags.Alias
+        ? isSymbolTypeBased(checker.getImmediateAliasedSymbol(symbol))
```
Comment (ntdiary) [inline packages/eslint-plugin/src/rules/consistent-type-exports.ts:105]: replace `getAliasedSymbol` with `getImmediateAliasedSymbol`.
Because the latter can handle this case as well:
```ts
// a.ts
export const NAME = 1;
export type NAME = 1;
// b.ts
import { type NAME as Foo } from './a';
export { Foo };
```

**Comment by JoshuaKGoldberg** [comment]
I ended up not having time to merge this in for the Monday release this week. Will leave open.
