### PR TITLE
fix(eslint-plugin): [no-unnecessary-condition] better handling for unary negation

### LINKED ISSUE #2255: [no-unnecessary-condition] False positive for nested arrays
**Repro**

```JSON
{
 "extends": [
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking"
  ],
  "rules": {
    "@typescript-eslint/no-unnecessary-condition": "warn"
  }
}
```

```TS
const latencies: number[][] = [];

function recordData(): void {
    if (!latencies[0])
        latencies[0] = [];
    latencies[0].push(4);
}

recordData();
```

**Expected Result**
No errors or warnings.
**Actual Result**
```
4:7  warning  Unnecessary conditional, value is always falsy  @typescript-eslint/no-unnecessary-condition
```
**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.4.0` |
| `@typescript-eslint/parser`        | `3.2.0` |
| `TypeScript`                       | `3.9.5` |
| `ESLint`                           | `7.2.0` |
| `node`                             | `12.18.1` |
| `npm`                              | `6.14.5` |

### PR DESCRIPTION
**Pull request by renugasaraswathy**
Fixes #2255 

Added handing for unary negation expression. 
cc @bradzacher 

Please let me know if any change is required.

### CODE REVIEW

**Comment by renugasaraswathy** [comment]
Will work on the code coverage and push.

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 1]
```diff
@@ -166,6 +166,14 @@ export default createRule<Options, MessageId>({
      * if the type of the node is always true or always false, it's not necessary.
      */
     function checkNode(node: TSESTree.Expression): void {
+      // Check if the node is Unary Negation expression and handle it
+      if (
+        node.type === AST_NODE_TYPES.UnaryExpression &&
+        node.operator === '!'
+      ) {
+        return checkIfUnaryNegationExpressionIsNecessaryConditional(node);
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:174]: perhaps this should just call `checkNode(node.argument)`?

Comment (renugasaraswathy) [reply packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:174]: Thank you for your review @bradzacher. If checkNode is called here, the following example reports alwaysTruthy, but I believe that the expectation is alwaysFalsy. 

```js
const a = true;
if (!a) {
}

assert.strictEqual(received, expected)

Expected value to strictly be equal to:
  "alwaysFalsy"
Received:
   "alwaysTruthy"
``` 

Have added the new function to handle this. Please suggest if there is better way to do this.
