### PR TITLE
fix(eslint-plugin): don’t mark `declare class` as unused

### LINKED ISSUE #106: [no-unused-vars] Don’t mark `declare class` expressions as unused
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-unused-vars": ["error", { "args": "none" }]
  }
}
```

```TS
declare class ResizeObserver {
  public constructor(cb: (entries: ReadonlyArray<IResizeObserverEntry>) => void)

  public disconnect(): void
  public observe(e: HTMLElement): void
}
```

**Expected Result**

No error

**Actual Result**

```
.../desktop/app/src/lib/globals.d.ts
  220:15  error  'ResizeObserver' is defined but never used  @typescript-eslint/no-unused-vars
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.0.0` |
| `@typescript-eslint/parser`        | `1.0.0` |
| `ESLint`                           | `5.8.0` |
| `node`                             | `8.12.0` |
| `npm`                              | ??? |

### PR DESCRIPTION
**Pull request by j-f1**
Fixes #106.

### CODE REVIEW

File: packages/eslint-plugin/lib/rules/no-unused-vars.js [hunk 1]
```diff
@@ -92,6 +92,12 @@ module.exports = Object.assign({}, baseRule, {
       },
       '*[declare=true] Identifier'(node) {
         context.markVariableAsUsed(node.name);
+        const scope = context.getScope();
+        const { variableScope } = scope;
+        if (variableScope !== scope) {
+          const superVar = variableScope.set.get(node.name);
+          if (superVar) superVar.eslintUsed = true;
+        }
```
Comment (armano2) [inline packages/eslint-plugin/lib/rules/no-unused-vars.js]: we should execture `context.markVariableAsUsed` in `else`

Comment (j-f1) [reply packages/eslint-plugin/lib/rules/no-unused-vars.js]: I wanted to keep both, since `markVariableAsUsed` modifies the class’s scope, while my additions modify the module scope.
