### PR TITLE
fix(eslint-plugin): [explicit-module-boundary-types] don't check returned functions if parent function has return type

### LINKED ISSUE #1845: [explicit-module-boundary-types] Complains about inner function expressions
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/explicit-function-return-type": [2, {"allowExpressions": true}],
    "@typescript-eslint/explicit-module-boundary-types": [2]
  }
}
```

```TS
export function foo(): (n: number) => string {
  return (n) => String(n)
}
```

**Expected Result**

Since the module boundary (`foo`) is fully typed, I would not expect to have to type the inner function expression.

**Actual Result**

`explicit-function-return-type` permits this code when the `allowExpressions` option is enabled. But `explicit-module-boundary-types` complains that the argument and return value of the inner function expression are untyped, and the rule doesn't have a corresponding expressions option.

**Additional Info**

n/a

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.26.0` |
| `@typescript-eslint/parser`        | `2.26.0` |
| `TypeScript`                       | `3.8.3` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `13.11.0` |
| `npm`                              | `6.14.4` |

### PR DESCRIPTION
**Pull request by ifiokjr**
## Description

Version 3.0.0 of the plugin enabled `explicit-module-boundary-types` by default. Unfortunately it doesn't currently handle the case where the parent function has a type signature. The following correct code produces an error. 

```ts
export const foo = (a: string): (n: number) => string => {
  return (n) => String(n)
}
```

This fixes the problem by checking the parent nodes of exported declarations to see if they are already typed. If they are typed it doesn't show the error for child functions.

Fixes #1845

### CODE REVIEW

File: packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts [hunk 1]
```diff
@@ -315,14 +291,105 @@ function checkFunctionExpressionReturnType(
...
+          isValidFunctionExpressionReturnType(ancestor, options) ||
+          isValidFunctionReturnType(ancestor, options, true);
+        break;
+      case AST_NODE_TYPES.FunctionDeclaration:
+        hasType = isValidFunctionReturnType(ancestor, options, true);
+        break;
+    }
+
+    ancestor = ancestor.parent;
+  }
```
Comment (bradzacher) [inline packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts:385]: Almost correct, I can see two problems with this:

1. You should exit if you see anything that's not a `ReturnStatement`.

Otherwise the following code will match:
```ts
function a(): void {
  function b() {} // not returned
  const x = () => {};  // not returned
  return;
}
```

This is that it will return `false` for the following case:

```ts
function a() /* no return */ {
  return function b(): () => void {
    return function 
  }
}

```

File: packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts [hunk 2]
```diff
@@ -315,14 +291,105 @@ function checkFunctionExpressionReturnType(
...
+
+  return hasType;
+}
```
Comment (bradzacher) [inline packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts:388]: Almost correct, I can see two problems with this:

1.

You should exit this loop if:
- you see anything that's not a `ReturnStatement`.
- you see a function declaration.

Examples that will currently behave incorrectly:

```ts
function a(): void {
  function b() {} // not returned, shouldn't care about the parent fn's return type
  const x = () => {}; // not returned, shouldn't care about the parent fn's return type
  (function () {}); // not returned, shouldn't care about the parent fn's return type

  function c() {
    return () => {}; // returned from inner function - should not be affected by outer function's return type
  }

  return;
}
```

2.

This is will return whatever the outer-most function's return type is, and ignore any functions it encounters along the way.

Eg, this will return false, even though it encountered a return type in function `b`:
```ts
function a() /* no return */ {
  return function b(): () => void {
    return function c() {}
  }
}
```

You probably want to hard-exit when `hasType === true`

Comment (ifiokjr) [reply packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts]: > You probably want to hard-exit when `hasType === true`

I added a couple more tests from the docs and breaking errors came from the point you made in 2. Breaking early fixed all of those. 

> You should exit this loop if:
>
> - you see anything that's not a ReturnStatement.
> - you see a function declaration.

I couldn't replicate what you mentioned in number 1. The code passed fine in the tests and exiting when not a return statement broke a lot of other tests.

Since this new method augments the previous check, it was only meant to catch stuff that was previously missed. The new failures I found were also failing beforehand (I think).

I can add even more tests. I was going through the docs and adding test cases to check my assumptions.

**Comment by ifiokjr** [comment]
I've just pushed again to:

- Exit early when the type of the ancestor of the node being checked is not a return statement.
- Immediately return the value from `FunctionExpression` ancestor checks
- Remove comments from the test source code.
- Add one more deeply nested test case.

File: packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts (hunk 2 above)
Comment (ifiokjr) [reply packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts]: Okay see my latest comment. I think I figured it out.
