### PR TITLE
fix(eslint-plugin): [no-unnecessary-type-assertion] should report readonly class properties with a literal initializer 

### LINKED ISSUE #10617: Bug: [no-unnecessary-type-assertion] should report `readonly` class properties with a literal initializer
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.7.2&fileType=.ts&code=C4TwDgpgBAylC8UCMAGA3AKAwem1AThGAPb7AQAmUAxqYdcADYga0B2AzsFAIYJQByHgN4caxTsEzsuUAEb8AzKKiLpE2dX6oVMTK0Y8OYgCpQA3hihRcUDgAtiAV0ZU50QiTKUA-FYIQPBQSzLz8QiJG4pL%2BhEEhIPJKKoqxgcFsoVqIOlEwGAC%2BQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
type S = 10;

// reported correctly
const a = 'a' as const;
const b = 3 as 3;
const c = 10 as S;

class T {
  // should be reported?
  readonly a = 'a' as const
  readonly b = 3 as 3
  readonly c = 10 as S
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unnecessary-type-assertion": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expected these to be reported, similarly to the `const` declarations.

### Actual Result

The various `readonly` declarations haven't been reported.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by y-hsgw**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10617
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Fixed the bug described in the title.

🐛

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts [hunk 1]
```diff
@@ -176,6 +176,14 @@ export default createRule<Options, MessageIds>({
       );
     }
 
+    function isReadonlyClassProperty({
+      parent,
+    }: TSESTree.TSAsExpression | TSESTree.TSTypeAssertion) {
+      return (
+        parent.type === AST_NODE_TYPES.PropertyDefinition && parent.readonly
```
Comment (ronami) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts:183]: [Bug]: `const` declarations also check that [template literals nodes have no expressions in them](https://github.com/typescript-eslint/typescript-eslint/blob/f2a3e8c0cf13e58ab027cd0a6df6c563e1a3ede8/packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts#L171-L175). I think this is relevant to `readonly` declarations too ([deploy preview link](https://deploy-preview-10618--typescript-eslint.netlify.app/play/#ts=5.7.3&fileType=.tsx&code=MYewdgzgLgBAZiEMC8MDkCRoNwChcD0BMYIsATgKYAOI5UlAJrqJLA9CjAAYAkA3pgC%2B3GAEMIMVtHzAANhMkAVSp364YMIjCq16TDTGrkAlgDcxDHZTGNwcgJ4wOsVH0GIR4ydKh4huEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)).

File: packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts [hunk 2]
```diff
@@ -1138,6 +1138,40 @@ var x = 1;
     },
     {
       code: `
+type S = 10;
+
+class T {
+  readonly a = 'a' as const;
+  readonly b = 3 as 3;
+  readonly c = 10 as S;
+}
```
Comment (ronami) [inline packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts:1147]: [Testing] One thing under test per case please (https://typescript-eslint.io/contributing/pull-requests#granular-unit-tests).

I think it would be useful having valid cases, like for a non literal class property, or a class property without the `readonly` modifier.

**Review by ronami — CHANGES_REQUESTED** [review]
Just minor changes requested. Looks great! 🚀

File: packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts (hunk 1 above)
Comment (y-hsgw) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts:187]: Oh, you're right.
I fixed in b0924e7.

Comment (ronami) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts:187]: Nice!

It would be nice if the template literal check could be written once for both cases. What do you think about something along the following (note the different function name):

```ts
function isImplicitlyNarrowedLiteralDeclaration({
  expression,
  parent,
}: TSESTree.TSAsExpression | TSESTree.TSTypeAssertion): boolean {
  /**
   * Even on `const` variable declarations, template literals with expressions can sometimes be widened without a type assertion.
   * @see https://github.com/typescript-eslint/typescript-eslint/issues/8737
   */
  if (isTemplateLiteralWithExpressions(expression)) {
    return false;
  }

  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  const maybeDeclarationNode = parent.parent!;

  return (
    (maybeDeclarationNode.type === AST_NODE_TYPES.VariableDeclaration &&
      maybeDeclarationNode.kind === 'const') ||
    (parent.type === AST_NODE_TYPES.PropertyDefinition && parent.readonly)
  );
}
```

The `castType.isLiteral()` ternary check will then be simplified too:

```ts
const wouldSameTypeBeInferred = castType.isLiteral()
  ? isImplicitlyNarrowedLiteralDeclaration(node)
  : !isConstAssertion(node.typeAnnotation);
```

**Review by ronami — CHANGES_REQUESTED** [review]
The implementation looks great to me, nice! 👏

Just requesting changes a bit on tests and potentially checking template literals just once, thanks!

File: packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts (hunk 2 above)
Comment (y-hsgw) [reply packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts]: I should have noticed it from the first comment 🥲
Thank you for pointing it out! I’ve split it in d000227!

File: packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts (hunk 1 above)
Comment (y-hsgw) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts]: Your suggested code is simpler and better!
I’ve updated it in cc7a718.

**Review by ronami — CHANGES_REQUESTED** [review]
👍👍 Thanks! looking really good! Requesting small adjustments around testing.

File: packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts [hunk 3]
```diff
@@ -154,6 +154,26 @@ class Foo {
...
+    `,
+    {
+      code: `
+const foo = 'foo';
+
+class T {
+  readonly a = 'a';
+  readonly b = 3;
+  readonly test = \`\${foo}\` as const;
+}
```
[the remark this answers is not in the document]
Comment (y-hsgw) [reply packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts]: I added it in 6f2326b, how does it look?

File: packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts [hunk 4]
```diff
@@ -151,6 +151,38 @@ const y: number = x!;
...
+    `
+class T {
+  a = 3 as 3;
+}
+    `,
+    `
+class T {
+  a = 10;
+}
+    `,
```
Comment (ronami) [inline packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts:170]: [Tests]: I apologize, I didn't notice this previously, but I think the tests that include no assertions can be removed, as the rule checks specifically for unnecessary type assertions ([there's also this one](https://github.com/typescript-eslint/typescript-eslint/blob/6f2326bea63527e94dff6b2d2ae38f51387d894e/packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts#L179-L181)).

**Review by ronami — CHANGES_REQUESTED** [review]
Just one small change I missed previously, other than that this looks fantastic 🏆

File: packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts (hunk 4 above)
Comment (y-hsgw) [reply packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts]: Thanks! I removed in [a320eaf](https://github.com/typescript-eslint/typescript-eslint/pull/10618/commits/a320eaf6cd280f6d6941eede2c368a0e57b9cd84).

**Review by ronami — APPROVED** [review]
Thank you for pushing this 🚀

**Review by JoshuaKGoldberg — APPROVED** [review]
🚀
