### PR TITLE
fix(eslint-plugin): [return-await] correct handling of ternaries

### LINKED ISSUE #1838: [return-await] --fix (amusingly) confused by ternaries
**Repro**
```JSON
{
  "rules": {
    "@typescript-eslint/return-await": ["error", "always"],
  }
}
```

```TS
async function one() {}
async function one() {}
async function two() {}
async function three() {}

async function problem() {
  return (await one()) 
    ? two()
    : three();
}
```

**Expected Result**
```
async function problem() {
  return await ((await one()) 
    ? two()
    : three());
}
```

or:

```
async function problem() {
  return (await one()) 
    ? await two()
    : await three();
}
```

I think I prefer the second?

**Actual Result**

```
return await await await await await await await await await await (await one()) ? two() : three();
```

Yes, that's ten of them.

**Additional Info**

This new code is valid, possibly not even wrong? I don't know the binding order on `await foo ? bar : baz;`. It does, however, trigger "unnecessary await", pretty amusingly.

Full eslintrc / package.json (templates, without this specific lint enabled, at least, at time of writing):
https://github.com/snyk/unless-overloaded/blob/master/.eslintrc.json
https://github.com/snyk/unless-overloaded/blob/master/package.json

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.26.0` |
| `@typescript-eslint/parser`        | `2.26.0` |
| `TypeScript`                       | `3.8.3` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.16.1` |
| `npm`                              | `6.14.1` |

### PR DESCRIPTION
**Pull request by yeonjuan**
Fixes #1838

### CODE REVIEW

**Comment by yeonjuan** [comment]
@bradzacher It seems ready to be reviewed :) sorry

File: packages/eslint-plugin/src/rules/return-await.ts [hunk 1]
```diff
@@ -113,24 +106,17 @@ export default util.createRule({
...
     ): TSESLint.RuleFix | null {
-      const targetNode =
-        node.type === AST_NODE_TYPES.ReturnStatement
-          ? node.argument
-          : node.body;
       // There should always be a target node; but let's be safe.
-      /* istanbul ignore if */ if (!targetNode) {
+      /* istanbul ignore if */ if (!node) {
         return null;
       }
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/return-await.ts:114]: you don't need this if any more, because the argument is never `undefined`

Comment (yeonjuan) [reply packages/eslint-plugin/src/rules/return-await.ts]: @bradzacher Sure!
