### PR TITLE
fix(typescript-estree): allow writing to deprecated node properties

### LINKED ISSUE #6668: typescript-estree: allow setting deprecated node properties
## Overview

Following https://github.com/typescript-eslint/typescript-eslint/pull/6525#issuecomment-1473392658: turns out Prettier has logic that reassigns deprecated node properties. We'll need to allow that. Otherwise, https://github.com/prettier/prettier/actions/runs/4445538911/jobs/7804778641?pr=14429#step:4:60:

```plaintext
  TypeError: Cannot set property typeParameters of #<Object> which has only a getter
      at visitNode (file:///home/runner/work/prettier/prettier/src/language-js/parse/postprocess/visit-node.js:20:19)
```

Thanks @fisker for the comments 😄

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6668
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

In the node's `Object.defineProperty` _accessor descriptor_, it's now given a setter that sets it to a _data descriptor_. See terminology on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty.

### CODE REVIEW

File: packages/typescript-estree/src/convert.ts [hunk 1]
```diff
@@ -3319,23 +3319,33 @@ export class Converter {
...
+
+        return node[valueKey];
+      },
+      set(value): void {
+        Object.defineProperty(node, aliasKey, {
+          enumerable: true,
+          writable: true,
+          value,
+        });
+      },
```
Comment (JoshuaKGoldberg) [inline packages/typescript-estree/src/convert.ts:3348]: @fisker - does this set of changes work for you?

Comment (fisker) [reply packages/typescript-estree/src/convert.ts:3348]: This should work for us.

Comment (JoshuaKGoldberg) [reply packages/typescript-estree/src/convert.ts:3347]: Ah, hmm, setting `node[aliasKey] = node[valueKey]` does again make the node properties show up when enumerating - including in AST viewers and our snapshots. @fisker would it work to still always `Object.defineProperty`, with the additions of `configurable: true` and the setter? d3633bb

Comment (fisker) [reply packages/typescript-estree/src/convert.ts:3347]: It should still work. 👍

**Review by fisker — APPROVED** [review]

**Comment by JoshuaKGoldberg** [comment]
(converting to draft as I have to poke at the website build - I probably messed up something in conversion with `this` scope...)

File: packages/typescript-estree/src/convert.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/typescript-estree/src/convert.ts:3347]: Super, thanks!

File: packages/typescript-estree/src/convert.ts [hunk 2]
```diff
@@ -3319,23 +3319,30 @@ export class Converter {
...
-              if (!errored) {
-                // eslint-disable-next-line no-console
-                console.warn(
-                  `The '${aliasKey}' property is deprecated on ${node.type} nodes. Use '${valueKey}' instead. See https://typescript-eslint.io/linting/troubleshooting#the-key-property-is-deprecated-on-type-nodes-use-key-instead-warnings.`,
-                );
-                errored = true;
-              }
+            if (!warned) {
+              // eslint-disable-next-line no-console
+              console.warn(
```
Comment (bradzacher) [inline packages/typescript-estree/src/convert.ts:3331]: should we use nodejs's infra here?
[`process.emitWarning`](https://nodejs.org/api/process.html#processemitwarningwarning-options)

eg
```ts
process.emitWarning(
  `The '${aliasKey}' property is deprecated on ${node.type} nodes. Use '${valueKey}' instead. See https://typescript-eslint.io/linting/troubleshooting#the-key-property-is-deprecated-on-type-nodes-use-key-instead-warnings.`
	'DeprecationWarning',
)
```

**Review by bradzacher — APPROVED** [review]

File: packages/typescript-estree/src/convert.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply packages/typescript-estree/src/convert.ts:3331]: TIL, thanks!
