### PR TITLE
fix(website): acquired types are shown in the editor but not reflected in linting

### LINKED ISSUE #11120: Bug(website): Acquired types are shown in the editor but not reflected in linting
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

website

### Playground Link

https://typescript-eslint.io/play/#ts=5.8.2&fileType=.tsx&code=JYWwDg9gTgLgBAbzgEwKYGcDGVgCNUA0cw8AvnAGZQQhwDkAdhGgFwwYx0DcAUD2lhz4AFHQCGcduk5FhASjgBeAHyIecYjFFj0ATwaYAFtSYBXdHSI79mOPKWqE6jXEwQG6CABtUAOi8QAOaiFBAQdHK8GqSRPDFcQA&eslintrc=N4KABGBECmAeAu0B2ATAzpAXGA2pADgDYCuA5gJZKYAC8AnvtGgMYBO5%2B8AtE4ZfAHo08ds271GXZgAtozANbQUkALoAacFFbFCTLGFAQIkWgyZsO3XvwFIA9lwBmhOwEN4lUl3ys7AW3I0PWxIAHdXViRITQBfEBigA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDAruuGAL4g9A&tokens=false

### Repro Code

```TypeScript
import { describe, it } from 'node:test';

describe('a test', () => {
  it('asynchronous', async () => {
    console.log('foo');
  });
});
```

### ESLint Config

```javascript
{
  "extends": ["plugin:@typescript-eslint/strict-type-checked"],
  "rules": {
    "@typescript-eslint/no-floating-promises": "warn"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strict": true
  }
}
```

### Expected Result

I expect a no-floating-promises error on the `test()` call

### Actual Result

There were two "Unsafe call of a(n) `error` type typed value" errors instead - as if the Automatic Type Acquisition didn't acquire the types at all for the linter.

### Additional Info

_No response_

### Versions

<playground>

### PR DESCRIPTION
**Pull request by mdm317**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11120 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
I think this issue occurs because of differences in the properties used when creating a ts.Program between Monaco and TypeScript-VFS.

> https://github.com/typescript-eslint/typescript-eslint/blob/e57126a23e3f9b0ec67665d47e37a429d7755753/packages/website/src/components/linter/createParser.ts#L29

The modules like [monaco](https://github.com/microsoft/monaco-editor), [typescript](https://github.com/microsoft/TypeScript), and [typescript-website](https://github.com/microsoft/TypeScript-Website) are scattered, so it’s a bit confusing

**1. create `ts.program` by monace**

**When monaco-editor creating this code will excute**   [link](https://github.com/microsoft/monaco-editor/blob/dd6bdfe8dae1b3c134fa7bc7b176b43fd294916e/src/language/typescript/tsWorker.ts#L35-L41)
`private _languageService = ts.createLanguageService(this);` 

 **createLanguageService in typescript**. [link](https://github.com/microsoft/TypeScript/blob/8c62e08448e0ec76203bd519dd39608dbcb31705/src/services/services.ts#L1725-L1830)
```ts
const rootFileNames = host.getScriptFileNames().slice();
 // some code
const options: CreateProgramOptions = {
  rootNames: rootFileNames,
  options: newSettings,
  host: compilerHost, 
  oldProgram: program,
  projectReferences,
};
program = createProgram(options);
```

And filenames output by `getScriptFileNames` will be added in the code below.
`defaults.addExtraLib(code, path)` in [typescript-website](https://github.com/microsoft/TypeScript-Website/blob/98ce24207d992b2b1a31f5e6b941d946175d48f6/packages/sandbox/src/index.ts#L187) => `defaults.addExtraLib(code, path)` in [monaco](https://github.com/microsoft/monaco-editor/blob/dd6bdfe8dae1b3c134fa7bc7b176b43fd294916e/src/language/typescript/monaco.contribution.ts#L610)

So, when creating a ts.Program, the rootNames array includes some libraries, such as Node or React.

**2. create `ts.program` by TypeScript-VFS.**

> https://github.com/typescript-eslint/typescript-eslint/blob/e57126a23e3f9b0ec67665d47e37a429d7755753/packages/website/src/components/linter/createParser.ts#L24-L31

Unlike case 1 above,We don't pass the name of a node_modules folder in fileNames.

In the sentence above, I modified it so that rootNames are provided when creating the `ts.Program` for both the Editor and Linting

## Testing
1. Click a [link](https://deploy-preview-11198--typescript-eslint.netlify.app/play/#ts=5.8.2&fileType=.tsx&code=FASwtgDg9gTgLgAgN4ICYFMDOBjGIBG6ANAiIgL4IBmMUYCA5AHZQYBccWcDA3MMBhx5CACgYBDBJ0zcSIgJQIAvAD5kwBKThjxmAJ5NsAC1osArpgYldB7AgXK1SDZoTYoTTFAA26AHTeUADmYlRQUAzyfJrkUcCxPEA&eslintrc=N4KABGBECmAeAu0B2ATAzpAXGA2uCUADgDYCuA5gJZKYAC8AnodGgMYBOlh8AtC8dXgB6NPE6tejZj1YALaKwDW0FJHwBdADT5I7UsRZYwoAlHpMWHLr36ChSAPY8AZsQcBDeNXI9C7BwC2lGiG2JAA7u7sSGoQAL4gcUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false) that already has code pre-filled.
2. Enter code in an empty playground

### CODE REVIEW

File: packages/website/src/components/linter/bridge.ts [hunk 1]
```diff
@@ -78,6 +80,10 @@ export function createFileSystem(
     const expPath = getPathRegExp(path);
     return [...files.keys()].filter(fileName => expPath.test(fileName));
   };
-
+  system.getScriptFileNames = (): string[] => {
+    return [...files.keys()]
+      .filter(fileName => !fileName.startsWith('/lib.'))
```
Comment (mdm317) [inline packages/website/src/components/linter/bridge.ts:85]: Lib files will be excluded from the Monaco Editor GitHub repository. [monaco-editor](https://github.com/microsoft/monaco-editor/blob/dd6bdfe8dae1b3c134fa7bc7b176b43fd294916e/src/language/typescript/tsWorker.ts#L65-L67)
> 		const models = allModels.filter((uri) => !fileNameIsLib(uri)).map((uri) => uri.toString());

File: packages/website/src/components/linter/bridge.ts [hunk 2]
```diff
@@ -78,6 +80,10 @@ export function createFileSystem(
...
+      .filter(f => !f.endsWith('/.eslintrc') && !f.endsWith('.json'));
```
Comment (mdm317) [inline packages/website/src/components/linter/bridge.ts:86]: These files cause an error in the code below. [typescript-website](https://github.com/microsoft/TypeScript-Website/blob/3977b08d579c69a1efb131580d6a00aa5a788e74/packages/typescript-vfs/src/index.ts#L68-L71)

```
  if (diagnostics.length) {
    const compilerHost = createVirtualCompilerHost(sys, compilerOptions, ts)
    throw new Error(ts.formatDiagnostics(diagnostics, compilerHost.compilerHost))
  }
```

File: packages/website/src/components/linter/createParser.ts [hunk 3]
```diff
@@ -108,6 +107,9 @@ export function createParser(
         visitorKeys: utils.visitorKeys,
       };
     },
+    registerFile(filePath: string, code: string): void {
+      compilerHost.createFile(filePath, code);
+    },
```
Comment (mdm317) [inline packages/website/src/components/linter/createParser.ts:112]: We have to add library files using `compilerHost.createFile`, because adding them directly to the `system` doesn't make them appear in `getScriptFileNames`, and thus they aren't included in the `rootNames ` when creating program. [typescript-website](https://github.com/microsoft/TypeScript-Website/blob/3977b08d579c69a1efb131580d6a00aa5a788e74/packages/typescript-vfs/src/index.ts#L647)
```
export function createVirtualLanguageServiceHost(
  sys: System,
  rootFiles: string[],
  compilerOptions: CompilerOptions,
  ts: TS,
  customTransformers?: CustomTransformers
) {
  const fileNames = [...rootFiles]
  ...somecode

  const languageServiceHost: LanguageServiceHost = {
	
    getScriptFileNames: () => fileNames.slice(),

  }
  ...somecode
}

```

File: packages/website/src/components/linter/createLinter.ts [hunk 4]
```diff
@@ -164,6 +166,11 @@ export function createLinter(
     }
   };
 
+  const registerFile = (fileName: string, code: string) => {
+    parser.registerFile(fileName, code);
+    triggerLintAll();
+  };
```
Comment (mdm317) [inline packages/website/src/components/linter/createLinter.ts:172]: We need this code to add the library and trigger linting after the parser is created, in case the user starts typing code in an empty playground.

File: packages/website/src/components/linter/bridge.ts [hunk 5]
```diff
@@ -14,7 +14,9 @@ export function createFileSystem(
   const files = new Map<string, string>();
   files.set(`/.eslintrc`, config.eslintrc);
   files.set(`/tsconfig.json`, config.tsconfig);
-  files.set(`/input${config.fileType}`, config.code);
+  if (config.code !== '') {
+    files.set(`/input${config.fileType}`, config.code);
+  }
```
Comment (JoshuaKGoldberg) [inline packages/website/src/components/linter/bridge.ts:19]: [Question] Why wouldn't we want to set `''` for code? What if the user explicitly puts in a blank file?

Comment (mdm317) [reply packages/website/src/components/linter/bridge.ts:19]: The above code is executed when the playground is first loaded.
> https://github.com/typescript-eslint/typescript-eslint/blob/ccd07914d933c3f7a284c9a7df5b1d6d40495fc5/packages/website/src/components/linter/createParser.ts#L29-L33

When we set `''` for code in the `system`, a `"File '/input.tsx' not found."` error occurs in `createVirtualTypeScriptEnvironment `

If the above code is missing, the playground will not load successfully when the user clicks the playground button in this [page](https://typescript-eslint.io/)

Therefore, we should avoid setting `''`  fo code in the `system`.


> https://github.com/typescript-eslint/typescript-eslint/blob/ccd07914d933c3f7a284c9a7df5b1d6d40495fc5/packages/website/src/components/linter/createParser.ts#L46-L47

Also, when the user changes the code to `''`, this code prevents the `code` field from being set to `''` in the `system`.

Comment (JoshuaKGoldberg) [reply packages/website/src/components/linter/bridge.ts:19]: Nice, that makes sense. Thanks!
