### PR TITLE
fix(eslint-plugin): [prefer-for-of] fix false positive when using erasable type syntax within update expressions

### LINKED ISSUE #10977: Bug: [prefer-for-of] false positive when using non-null assertion within update expressions
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.8.2&fileType=.tsx&code=MYewdgzgLgBAhgJwXAnjAvDA2gRgDQwDMhBATACwEC0AnALoDcAUEwPSswgDWTAZiAhgAKADYBTWAEsMMAAwMY0gDzwkqAHTiwAcygALBZIDURgJSrkKLJLonmbDrziSRfAcPFSZ8xTBWJLTTEdfUMTcwDUazoAQjsmIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0Wlq4D2fAV3RRe0IZHBgAviFlA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const array = [1, 33, 24, -9];

// ok
for (let i = 0; i < array.length; i++) array[i]++;

// fail
for (let i = 0; i < array.length; i++) array[i]!++;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/prefer-for-of": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

The 7th line shouldn't report `prefer-for-of` error.

### Actual Result

The 7th line reports `prefer-for-of` error.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by zyoshoka**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10977
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Fixed `isAssignee` function to handle erasable type syntax.

### CODE REVIEW

File: packages/eslint-plugin/src/util/isAssignee.ts [hunk 1]
```diff
@@ -53,5 +53,13 @@ export function isAssignee(node: TSESTree.Node): boolean {
     return true;
   }
 
+  // a[i]!++, [...a[i]!] = [0], etc.
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/util/isAssignee.ts:56]: I think we could generalize slightly by recursing right off the bat on any erasable type syntax - what do you think?

My idea would be to put 
```ts
  if (
    parent.type === AST_NODE_TYPES.TSNonNullExpression 
    // TODO in this PR - also check for TSTypeAssertion, TSAsExpression, TSSatisfiesExpression
    // (maybe others? Can't think of anything else)
  ) {
    return isAssignee(parent);
  }
```
right at the top...

What do you think?

**Comment by kirkwaiblinger** [comment]
Nice first PR to typescript-eslint! Looks great already, just minor touchups/enhancements requested!

File: packages/eslint-plugin/src/util/isAssignee.ts (hunk 1 above)
Comment (zyoshoka) [reply packages/eslint-plugin/src/util/isAssignee.ts:56]: Good catch! I believe it is enough to check those expressions as well. I will also add some test cases.

**Review by kirkwaiblinger — APPROVED** [review]
Lovely! I'll leave the PR open for a bit in case another team member wants to take a look, but good to go from my side 🙂 

gif

**Review by JoshuaKGoldberg — APPROVED** [review]
💯
