### PR TITLE
fix(eslint-plugin): [no-import-type-side-effects] correctly ignore zero-specifier imports

### LINKED ISSUE #6431: Bug: [no-import-type-side-effects] doesn't allow side effects only imports
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=JYWwDg9gTgLgBAchgUwM4wHQGNWoUA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1soFtiPodIqVrJKAE0T0AZtMRl8qDACZwYAL4h1QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
import 'test.css'
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-import-type-side-effects": 2,
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

no error

### Actual Result

error, and auto fixed to wrong code:
```
import type 'test.css'
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by bradzacher**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6431
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

<p align="center">
  
</p>

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-import-type-side-effects.ts [hunk 1]
```diff
@@ -29,6 +29,10 @@ export default util.createRule<Options, MessageIds>({
       'ImportDeclaration[importKind!="type"]'(
         node: TSESTree.ImportDeclaration,
       ): void {
+        if (node.specifiers.length === 0) {
+          return;
+        }
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-import-type-side-effects.ts:34]: Per our recent conversation somewhere, if you wanted to, ESQuery can reduce this code count a bit 😄 

```suggestion
      'ImportDeclaration[importKind!="type"][specifiers.0]'(
        node: TSESTree.ImportDeclaration,
      ): void {
```

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM! 🚀

File: packages/eslint-plugin/src/rules/no-import-type-side-effects.ts (hunk 1 above)
Comment (bradzacher) [reply packages/eslint-plugin/src/rules/no-import-type-side-effects.ts:34]: back in the day I was all in on esquery selectors.
now a days though I tend to find that leaning too heavily into the custom DSL makes code less accessible and harder to understand / debug.

`[specifiers.0]` is one of those parts of the DSL that's super unclear as to what it's doing, IMO.

---

also as an interesting aside just because...
I figured out that selectors actually hide performance cost of rules! ESLint only tracks (1) time spent in `create` and (2) time spent in selector functions for a rule.

so time spent compiling and evaluation selector strings is perf cost in ESLint land - not for the rule.

Which is funny for rules like those in [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/2a9c840484ab456ef131cb7ffc61cd46bef443a7/rules/no-useless-length-check.js#L11-L33) which heavily (ab)use selectors over logic, because they'll look like they're faster than other rules!

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-import-type-side-effects.ts:34]: Ooh I wonder if we should have a lint rule for selectors. And maybe put it in `eslint-plugin-eslint-plugin`...

Comment (bradzacher) [reply packages/eslint-plugin/src/rules/no-import-type-side-effects.ts:34]: Separately I've also envisioned a lint rule that enforces the type annotation on the function arg matches the selector to improve safety.

EG
```
// bad
'ImportDeclaration[importKind != "type"]'(node: TSESTree.Literal)
'BlockStatement > *'(node: TSESTree.Literal)

// good
'ImportDeclaration[importKind != "type"]'(node: TSESTree.ImportDeclaration)
'ImportDeclaration[importKind != "type"]'(node: TSESTree.ImportDeclaration & {importKind: 'type'})
'BlockStatement > *'(node: TSESTree.Node)
```

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-import-type-side-effects.ts:34]: * https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/339
* https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/340
