### PR TITLE
fix(eslint-plugin): [no-unnecessary-condition] false positive on optional private field

### LINKED ISSUE #9564: Bug: [no-unnecessary-condition] false positive on optional private field
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.3&fileType=.tsx&code=MYGwhgzhAEDCD2A7CBLCAXApo9AlMiAJtAN4BQ00AxAE4GED8AXNIgK4C2ARpjQNxkK0AOaZ0sMMAAWmQviIAKAJSkhldFLQA6WvWgMGAXmgBZMBq10i8DsoGVKNMWxqJoG7bqL3oAXzL%2BQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDArugDTg2ToAPAIbNcBYkNQAFTLERY8ATwAqi%2BWUod0vAL4gdQA&tokens=false

### Repro Code

```TypeScript
class ConsistentRand {
  #rand?: number;

  getCachedRand() {
    this.#rand ??= Math.random();
    return this.#rand;
  }
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unnecessary-condition": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strict": true,
    "exactOptionalPropertyTypes": true
  }
}
```

### Expected Result

The example code should not be an error for `no-unnecessary-condition`.

The private field is marked optional and typescript acknowledges that it valid to not be initialized off the bat.

### Actual Result

The line 
```
this.#rand ??= Math.random();
```

Results in error
> Unnecessary conditional, expected left-hand side of `??` operator to be possibly null or undefined. 5:5 - 5:15

### Additional Info

Replacing assignment with
```
this.#rand = this.#rand ?? Math.random();
```

No longer produces the error, despite being logically the same, although this will fail on unrelated [logical-assignment-operators](https://eslint.org/docs/latest/rules/logical-assignment-operators).

I suspect the key issues here are combination of a private field, and `exactOptionalPropertyTypes=true` in tsconfig.

### PR DESCRIPTION
**Pull request by StyleShit**
## PR Checklist

- [X] Addresses an existing open issue: fixes #9564
- [X] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [X] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR accounts for private identifiers when checking if a member expression is nullable

Not sure if/which additional test cases I should add here, so I'm open for suggestions 😄

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 1]
```diff
@@ -211,15 +211,20 @@ export default createRule<Options, MessageId>({
       }
       const property = node.property;
 
-      if (property.type === AST_NODE_TYPES.Identifier) {
```
Comment (StyleShit) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:214]: This condition is unnecessary because the property type is `Identifier | PrivateIdentifier`

**Review by kirkwaiblinger — APPROVED** [review]
Looks good to me! Nice 🙂
