### PR TITLE
fix(typescript-estree): persisted parse and module none

### LINKED ISSUE #1502: Parsing errors when tsconfig.json's compilerOption's module is set to none
**What code were you trying to parse?**

```ts
// Parsing error: Cannot read property 'text' of undefined
const foo = 1;

// Parsing error: Cannot read property 'kind' of undefined
(() => { })();

// Parsing error: Cannot use 'in' operator to search for 'name' in undefined
let a: "a" | "b";
```

**What did you expect to happen?**
No parsing errors

**What actually happened?**
Got parsing errors

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.17.0` |
| `TypeScript`                | `3.7.5` |
| `ESLint`                    | `6.8.0` |
| `node`                      | `10.18.1` |
| `npm`                       | `6.13.6` |

### PR DESCRIPTION
**Pull request by armano2**
This PR fixes issue when persisted parse is called with module option set to "none",

fixes #1502

### CODE REVIEW

File: packages/typescript-estree/src/create-program/createWatchProgram.ts [hunk 1]
```diff
@@ -218,6 +218,8 @@ function getProgramsForProjects(
 
     // cache watch program and return current program
     knownWatchProgramMap.set(tsconfigPath, programWatch);
+    // sets parent pointers in source files when module === none
+    program.getTypeChecker();
```
Comment (armano2) [inline packages/typescript-estree/src/create-program/createWatchProgram.ts]: this line is not needed when other module types are used, same for other calls

**Comment by armano2** [comment]
i don't like this change as it can slow down parsing, i'm looking for a way to validate if/when we actually need to call it

File: packages/typescript-estree/src/create-program/createWatchProgram.ts [hunk 2]
```diff
@@ -175,7 +175,7 @@ function getProgramsForProjects(
 
       updatedProgram =
         updatedProgram ?? existingWatch.getProgram().getProgram();
-      // sets parent pointers in source files
+      // sets parent pointers in source files when module === none
```
Comment (bradzacher) [inline packages/typescript-estree/src/create-program/createWatchProgram.ts]:
```suggestion
      // sets parent pointers in source files
```

I thought this was required regardless, not just when in no module mode?

File: packages/typescript-estree/src/create-program/createWatchProgram.ts [hunk 3]
```diff
@@ -206,7 +206,7 @@ function getProgramsForProjects(
         continue;
       }
 
-      // sets parent pointers in source files
+      // sets parent pointers in source files when module === none
```
Comment (bradzacher) [inline packages/typescript-estree/src/create-program/createWatchProgram.ts]: ditto

File: packages/typescript-estree/src/create-program/createWatchProgram.ts (hunk 2 above)
Comment (armano2) [reply packages/typescript-estree/src/create-program/createWatchProgram.ts]: This seems to be no longer needed (at least for ts 3.7) if module is != none

**Comment by armano2** [comment]
Typescript actually calls this function to "fix" parent nodes.

https://github.com/microsoft/TypeScript/blob/9ba45fcaace07510ef259d4cda2bc5ec523cf6d1/src/compiler/parser.ts#L887-L917

**Comment by armano2** [comment]
i'm tempted to remove calls to parent node from converter as we are traversing already nodes anyway,
that should allow me to remove this code and remove it from other places

**Comment by armano2** [comment]
@bradzacher should i made those changes to converter in this PR or create new one

removing usage of parent node is kinda big change as involves every call to `convertChild`, `convertPattern`, `convertType`, `converter`, `convertTSTypeParametersToTypeParametersDeclaration`, `convertParameters` (its not hard change to do as in most of cases we just have to pass 2nd parameter as current `node`)

it will also require change to how we are generating tokens because we are have some logic involving parents for jsx detecion

**Comment by bradzacher** [comment]
I think I'd prefer the changes in #1521
It's much larger, but it means we can never mess it up accidentally.
