### PR TITLE
fix(typescript-estree): only run projectService setHostConfiguration when needed

### LINKED ISSUE #9312: Bug: Vue + TypeScript project slowdown with v8 alpha
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

After upgrading a fairly standard Vue + TypeScript project (ESLint from v8 to v9, and `typescript-eslint` from v7 to v8), with a similar configuration the linting time goes from +/- 20 seconds to 3 minutes.

The command is `eslint src`, where  `src` is a directory containing only `.ts` and `.vue` files.

Old `.eslintrc.json`:
```json
{
  "root": true,
  "parser": "vue-eslint-parser",
  "parserOptions": {
    "parser": "@typescript-eslint/parser",
    "project": true,
    "extraFileExtensions": [".vue"]
  },
  "extends": [
    "plugin:@typescript-eslint/strict-type-checked",
    "plugin:@typescript-eslint/stylistic-type-checked",
    "plugin:vue/vue3-recommended",
    "prettier"
  ],
  "overrides": [
    {
      "files": ["src/types/*.d.ts"],
      "rules": {
        "@typescript-eslint/no-extraneous-class": ["error", { "allowConstructorOnly": true }]
      }
    }
  ]
}
```

New `eslint.config.js`
```ts
import eslintConfigPrettier from 'eslint-config-prettier';
import pluginVue from 'eslint-plugin-vue';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  ...pluginVue.configs['flat/recommended'],
  eslintConfigPrettier,
  {
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
        projectService: true,
        extraFileExtensions: ['.vue']
      }
    }
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { caughtErrorsIgnorePattern: 'ignore' }]
    }
  },
  {
    files: ['src/types/*.d.ts'],
    rules: {
      '@typescript-eslint/no-extraneous-class': ['error', { allowConstructorOnly: true }]
    }
  },
  {
    ignores: ['eslint.config.js']
  }
);
```

### Reproduction Repository Link

Private repository but I can give people access to it

### Repro Steps

1) clone the repo
2) `pnpm install`
3) `pnpm lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript-eslint`     | `8.0.0-alpha.29` |
| `TypeScript`                           | `5.4.5` |
| `ESLint`                               | `9.4.0` |
| `node`                                 | `22.2.0` |

### PR DESCRIPTION
**Pull request by higherorderfunctor**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9312
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

~~Moves `ProjectService.setHostConfiguration` from `useProgramFromProjectService` where it is called on every source to `createProjectService` where it is only called once per `ProjectService`.~~ See comments regarding updated implementation.

`ProjectService.setHostConfiguration` [reloads](https://github.com/microsoft/TypeScript/blob/27bcd4cb5a98bce46c9cdd749752703ead021a4b/src/server/editorServices.ts#L3458) the whole project.  The way `vue-eslint-parser` sends template fragments causes a reload to start and then get [canceled](https://github.com/microsoft/TypeScript/blob/27bcd4cb5a98bce46c9cdd749752703ead021a4b/src/server/editorServices.ts#L3504) for _n - 1_ template fragments per file.

This fix along with https://github.com/typescript-eslint/typescript-eslint/issues/9223 if using `eslint-plugin-import`/`eslint-plugin-import-x` vastly improves performance.

~~I am open to suggestions on improving the signature of `createProjectService`.  I appended as a new 3rd argument called `parseSettings` which is an object to allow for additional settings to be added in the future if needed.  I could see this being merged with the second argument, but I was not sure of the implications in making a breaking change to the existing signature.~~

### CODE REVIEW

File: packages/typescript-estree/src/create-program/createProjectService.ts [hunk 1]
```diff
@@ -22,9 +22,14 @@ export interface ProjectServiceSettings {
...
 }
 
+export interface ProjectServiceParseSettings {
+  extraFileExtensions?: string[];
+}
+
 export function createProjectService(
   optionsRaw: boolean | ProjectServiceOptions | undefined,
   jsDocParsingMode: ts.JSDocParsingMode | undefined,
+  parseSettings?: ProjectServiceParseSettings,
```
Comment (JoshuaKGoldberg) [inline packages/typescript-estree/src/create-program/createProjectService.ts:32]: [Refactor] How about moving `jsDocParsingMode` into `ProjectServiceParseSettings`? They're both about parsing, after all:

```suggestion
export interface ProjectServiceParseSettings {
  extraFileExtensions?: string[];
  jsDocParsingMode?: ts.JSDocParsingMode;
}

export function createProjectService(
  optionsRaw: boolean | ProjectServiceOptions | undefined,
  parseSettings?: ProjectServiceParseSettings,
```

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Tentatively looks lovely to me, with the refactor suggestion factored in. I'll take a deeper look once I have a chance to play with a repro.

cc @jakebailey as an FYI for this & the issue 🙂

**Comment by higherorderfunctor** [comment]
Thanks for the initial review.  I did discover one bug that is fixed in my branch with a collection of changes.  If a user changes extensions from the initial ones, they do not get updated.  I'll carry the fix in and add a test.

File: packages/typescript-estree/src/create-program/createProjectService.ts (hunk 1 above)
Comment (higherorderfunctor) [reply packages/typescript-estree/src/create-program/createProjectService.ts]: I had to refactor to support an ESLint configuration that changes `extraFileExtensions` in the same linting session.  As such, I've moved the logic back to `packages/typescript-estree/src/useProgramFromProjectService.ts`.

**Comment by higherorderfunctor** [comment]
Taking out of draft.  Notable updates:

* Discovered a bug when changing `extraFileExtensions` in the same linting session.
  * Added positive and negative test cases for this situation.
* Moved the logic back to `packages/typescript-estree/src/useProgramFromProjectService.ts`.
* The approach now caches the last set `extraFileExtensions` and only calls `setHostConfiguration` when there is a difference.
  * I'm caching directly on the `ProjectService` with `__extra_file_extensions` so it gets garbage collected with `clearTSServerProjectService`.  If you prefer a proper cleanup with it's own function, I can do so, but it may take a few days to find availability.
  * Using sets yielded the best performance when testing hence the `symmetricDifference` logic.  I did not exhaustively look at other options, just some tests iterating with for-loops.  Let me know if you want a different approach.
* I've added documentation to the site explaining how to minimize project reloads by setting `extraFileExtensions` only once.

This is part of a larger set of changes discussed on https://github.com/typescript-eslint/typescript-eslint/issues/9312#issuecomment-2166787001 and https://github.com/typescript-eslint/typescript-eslint/issues/8835#issuecomment-2164423027.

- Fixes `extends` not getting processed by the default config used for `projectService` inferred projects. https://github.com/typescript-eslint/typescript-eslint/pull/9306
- Adds tsserver logging. https://github.com/typescript-eslint/typescript-eslint/pull/9337
- Minimizes how many times `setHostConfiguration` is called. https://github.com/typescript-eslint/typescript-eslint/pull/9336
- Adds support to use watches with a Trie lookup (without actual FS watching) to update tsserver with changes (e.g., file created) to fix https://github.com/typescript-eslint/typescript-eslint/issues/8835.
- Caches open files with tsserver and closes them using an LRU based on access order.
- Sends incremental diffs instead of re-opening files if already open.

File: docs/troubleshooting/Performance.mdx [hunk 2]
```diff
@@ -79,6 +79,86 @@ module.exports = {
 
 See [Glob pattern in parser's option "project" slows down linting](https://github.com/typescript-eslint/typescript-eslint/issues/2611) for more details.
 
+## Changes to `extraFileExtensions` with `projectService` in your ESLint options
+
+Using different [`extraFileExtensions`](../packages/Parser.mdx#extrafileextensions) for different files with [`projectService`](../packages/Parser.mdx#projectservice) will cause a full project reload.
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:84]: [Docs]

> will cause a full project reload

This is a little vague out of context. Can you be a bit more specific? In what scenario(s) does it cause the reload? How does that impact code? How would a user observe this?

Comment (higherorderfunctor) [reply docs/troubleshooting/Performance.mdx:84]: Changing `extraFileExtensions` with tsservers `setHostConfiguration` causes tsserver to initiate a project reload to update the project structure with the extension changes: https://github.com/microsoft/TypeScript/blob/b1c52c53cc6c8cf35b19accfc3e29916489c821e/src/server/editorServices.ts#L3781

Tsserver does not appear to do any checks if the old file extensions match the new file extensions.

The current implementation of `typescript-estree` updates the file extension for every file when `extraFileExtensions` is set.  This compounds with plugins like `vue-eslint-parser` where each template fragment triggers this.

This PR caches the last set `extraFileExtensions` to minimize these project reloads.

Users can further optimize, which is why I added it to the docs, by making sure `extraFileExtensions` is only set once.

I can merge in main now that the logging PR was accepted to expose tsserver logs and provide some examples.

A user could look for this log message as an example: https://github.com/microsoft/TypeScript/blob/b1c52c53cc6c8cf35b19accfc3e29916489c821e/src/server/editorServices.ts#L3825

Comment (JoshuaKGoldberg) [reply docs/troubleshooting/Performance.mdx:84]: Oh, just clarifying, I meant those questions as rhetorical. They're things that the docs should answer. I'm requesting additions to the docs. Sorry for not being clear 😅

File: packages/typescript-estree/src/useProgramFromProjectService.ts [hunk 3]
```diff
@@ -13,6 +13,46 @@ const log = debug(
   'typescript-eslint:typescript-estree:useProgramFromProjectService',
 );
 
+const union = <T>(self: Set<T>, other: Set<T>): Set<T> =>
+  new Set([...self, ...other]);
+const difference = <T>(self: Set<T>, other: Set<T>): Set<T> =>
+  new Set([...self].filter(elem => !other.has(elem)));
+const symmetricDifference = <T>(self: Set<T>, other: Set<T>): Set<T> =>
+  union(difference(self, other), difference(other, self));
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply packages/typescript-estree/src/useProgramFromProjectService.ts:21]: Does it have to be even that complicated? It seems like overkill to optimize even for order, in which case you may as well just use [`util.isDeepStrictEqual`](https://nodejs.org/api/util.html#utilisdeepstrictequalval1-val2) or something.

[the remark this answers is not in the document]
Comment (higherorderfunctor) [reply packages/typescript-estree/src/useProgramFromProjectService.ts:21]: Average of 100 runs on the `AllkindsICP` package from the issue: before=0:28.36 after=0:28.96.

Not enough of a difference to matter.  Moving forward with `isDeepStrictEqual`.

File: docs/troubleshooting/Performance.mdx [hunk 4]
```diff
@@ -79,7 +79,113 @@ module.exports = {
...
 
-## The `indent` / `@typescript-eslint/indent` rules
+## Changes to `extraFileExtensions` with `projectService` in your ESLint options
+
+Using different [`extraFileExtensions`](../packages/Parser.mdx#extrafileextensions) for different files with
+[`projectService`](../packages/Parser.mdx#projectservice) causes the TypeScript server to perform a full project reload.
+Project reloads can be observed using the [debug environment variable](../packages/typescript-estree/#debugging): `DEBUG='typescript-eslint:typescript-estree:*'`.
+
+```
+typescript-estree:useProgramFromProjectService Updating extra file extensions: before=[]: after=[ '.vue' ]
```
Comment (higherorderfunctor) [inline docs/troubleshooting/Performance.mdx:89]: I trimmed these log messages on the left so they would (mostly) fit horizontally on screen.  If accuracy is preferred, I can undo this.

```typescript-estree:useProgramFromProjectService```

vs

```2024-06-17T16:58:28.942Z typescript-eslint:typescript-estree:useProgramFromProjectService```

File: packages/typescript-estree/src/useProgramFromProjectService.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (higherorderfunctor) [reply packages/typescript-estree/src/useProgramFromProjectService.ts]: These changes have been made!

File: packages/typescript-estree/src/useProgramFromProjectService.ts [hunk 5]
```diff
@@ -13,6 +13,46 @@ const log = debug(
...
+
+const updateExtraFileExtensions = (
+  service: ts.server.ProjectService & {
+    __extra_file_extensions?: Set<string>;
```
[the remark this answers is not in the document]
Comment (higherorderfunctor) [reply packages/typescript-estree/src/useProgramFromProjectService.ts]: Updated to `WeakMap`.  Thanks!

File: docs/troubleshooting/Performance.mdx (hunk 2 above)
Comment (higherorderfunctor) [reply docs/troubleshooting/Performance.mdx]: Additions have been added.  Let me know if additional detail is needed in any area.

I added my [own comment](https://github.com/typescript-eslint/typescript-eslint/pull/9336#discussion_r1643353701) to point out a creative liberty taken to help with readability.

I can revert for accuracy if preferred.

File: docs/troubleshooting/Performance.mdx (hunk 4 above)
Comment (JoshuaKGoldberg) [reply docs/troubleshooting/Performance.mdx:89]: Yeah +1 this is preferable IMO. I don't think users will be upset at not having to read through arbitrary timestamps. 😄

File: docs/troubleshooting/Performance.mdx [hunk 6]
```diff
@@ -79,7 +79,120 @@ module.exports = {
...
+typescript-estree:useProgramFromProjectService Extra file extensions updated: []
+...
+typescript-estree:useProgramFromProjectService Updating extra file extensions: before=[]: after=[ '.vue' ]
+typescript-estree:tsserver:info reload projects.
+typescript-estree:useProgramFromProjectService Extra file extensions updated: [ '.vue' ]
+```
+
+As files are received, if `extraFileExtensions` differs from the previous file,
+the TypeScript server is updated to match your ESLint options.
+The TypeScript server incrementally updates the project structure by creating an execution pipeline.
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:104]: [Docs] I think we can get away without mentioning the concept of the execution pipeline...

```suggestion
```

File: docs/troubleshooting/Performance.mdx [hunk 7]
```diff
@@ -79,7 +79,120 @@ module.exports = {
...
+a project reload may occur before the last pipeline completes.
+In turn, this can lead to cascading performance issues.
+
+```
+typescript-estree:tsserver:info Scheduled: /path/to/tsconfig.src.json, Cancelled earlier one +0ms
+typescript-estree:tsserver:info Scheduled: *ensureProjectForOpenFiles*, Cancelled earlier one +0ms
+```
+
+The impact of setting `extraFileExtensions` per file type in a project may be negligible depending on the order files are received.
+That said, complex ESLint options, cached linting results altering which files are evaluated,
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:115]: ...and trimming out further details that enforce the idea of _"don't let this change"_:

```suggestion
```

File: docs/troubleshooting/Performance.mdx [hunk 8]
```diff
@@ -79,7 +79,120 @@ module.exports = {
 
 See [Glob pattern in parser's option "project" slows down linting](https://github.com/typescript-eslint/typescript-eslint/issues/2611) for more details.
 
-## The `indent` / `@typescript-eslint/indent` rules
+## Changes to `extraFileExtensions` with `projectService` in your ESLint options
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:82]: [Docs] A bit more trim:

```suggestion
## Changes to `extraFileExtensions` with `projectService`
```

File: docs/troubleshooting/Performance.mdx (hunk 4 above)
Comment (JoshuaKGoldberg) [reply docs/troubleshooting/Performance.mdx:89]: That being said, could you move this debug information to the bottom? I think it'd be easier for folks to have the order be:

1. Introduction to this idea (don't change `extraFileExtensions` between files)
2. Why this is the case (full project reloads)
3. Ancillary info, like debugging tips

File: docs/troubleshooting/Performance.mdx [hunk 9]
```diff
@@ -79,7 +79,120 @@ module.exports = {
...
+```
+
+The impact of setting `extraFileExtensions` per file type in a project may be negligible depending on the order files are received.
+That said, complex ESLint options, cached linting results altering which files are evaluated,
+and switching between files with different `extraFileExtensions` while using
+[typescript-eslint-language-service](https://www.npmjs.com/package/typescript-eslint-language-service)
+may all be sources of unintended project reloads.
+The optimal approach to avoid project reloads altogether is to use the same `extraFileExtensions` across `parserOptions`.
+
+<Tabs groupId="eslint-config">
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:121]: [Praise] These diffs are very helpful 🙂 nice!

File: docs/troubleshooting/Performance.mdx [hunk 10]
```diff
@@ -79,7 +79,120 @@ module.exports = {
...
+      },
+    },
+  ],
+};
+```
+
+</TabItem>
+</Tabs>
+
+## The `indent` / `@typescripst-eslint/indent` rules
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:195]: oopity

```suggestion
## The `indent` / `@typescript-eslint/indent` rules
```

**Review by JoshuaKGoldberg — APPROVED** [review]
Looks great to me, thanks! 🙌 

Mostly touching up on the docs FAQs. I think they're pretty close, just need some reordering.

File: docs/troubleshooting/Performance.mdx (hunk 2 above)
Comment (JoshuaKGoldberg) [reply docs/troubleshooting/Performance.mdx]: These additions are fantastic! I hadn't thought of adding an FAQ article, but it makes a ton of sense. Strong +1 😄

**Comment by higherorderfunctor** [comment]
Made the reordering and trimming changes requested.  I also updated the links with the title change in the performance section.

Let me know if any further edits are needed!

File: docs/troubleshooting/Performance.mdx [hunk 11]
```diff
@@ -79,6 +79,107 @@ module.exports = {
 
 See [Glob pattern in parser's option "project" slows down linting](https://github.com/typescript-eslint/typescript-eslint/issues/2611) for more details.
 
+## Changes to `extraFileExtensions` with `projectService`
+
+Changes to [`extraFileExtensions`](../packages/Parser.mdx#extrafileextensions) between files in the same project with
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:84]: [Docs] Nice tip I've picked up, using different wording in the header vs. the body. The two tend to have different kind of phrasing, and this body text is a bit more precise.

```suggestion
Using a different `extraFileExtensions`](../packages/Parser.mdx#extrafileextensions) between files in the same project with
```

File: docs/troubleshooting/Performance.mdx [hunk 12]
```diff
@@ -79,6 +79,107 @@ module.exports = {
...
+the [`projectService`](../packages/Parser.mdx#projectservice) option is likely to cause more overhead than expected updating the project.
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:85]: [Docs] For succinctness:

```suggestion
the [`projectService`](../packages/Parser.mdx#projectservice) option may cause performance degredations.
```

File: docs/troubleshooting/Performance.mdx [hunk 13]
```diff
@@ -79,6 +79,107 @@ module.exports = {
...
+The optimal approach is to use the same `extraFileExtensions` value across all files in the project.
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:86]: [Docs] Redundant with the previous sentence, I think.

```suggestion
```

File: docs/troubleshooting/Performance.mdx [hunk 14]
```diff
@@ -79,6 +79,107 @@ module.exports = {
...
+For every file linted, we update the `projectService` whenever `extraFileExtensions` changes to match your ESLint options.
+This causes the underlying TypeScript server to perform a full project reload to account for new and removed files from the project.
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:88]: [Docs] Not necessary to mention for this, I think:

```suggestion
This causes the underlying TypeScript server to perform a full project reload.
```

File: docs/troubleshooting/Performance.mdx [hunk 15]
```diff
@@ -79,6 +79,107 @@ module.exports = {
 
 See [Glob pattern in parser's option "project" slows down linting](https://github.com/typescript-eslint/typescript-eslint/issues/2611) for more details.
 
+## Changes to `extraFileExtensions` with `projectService`
+
+Changes to [`extraFileExtensions`](../packages/Parser.mdx#extrafileextensions) between files in the same project with
+the [`projectService`](../packages/Parser.mdx#projectservice) option is likely to cause more overhead than expected updating the project.
+The optimal approach is to use the same `extraFileExtensions` value across all files in the project.
+For every file linted, we update the `projectService` whenever `extraFileExtensions` changes to match your ESLint options.
```
Comment (JoshuaKGoldberg) [inline docs/troubleshooting/Performance.mdx:87]: [Docs] Redundant:

```suggestion
For every file linted, we update the `projectService` whenever `extraFileExtensions` changes.
```

**Review by JoshuaKGoldberg — APPROVED** [review]
Lovely, thanks for this! 🙌 

I just have docs nitpicks left over. We'll make sure this is merged before our Monday release in two days. 🚀 thanks a bunch @higherorderfunctor!

**Comment by higherorderfunctor** [comment]
All review suggestions have been committed.  Thanks again!

**Comment by higherorderfunctor** [comment]
Inspecting pipeline errors and some of the links aren't rendering locally.  Inspecting now.

**Comment by higherorderfunctor** [comment]
Fixes made.  So long as the pipeline succeeds, we should be good to merge!

**Review by JoshuaKGoldberg — APPROVED** [review]
🔥 ! Very excited to get this released, thank you! A bit of a relief to fix such a disruptive performance issue for Vue users.

I'll merge this in now, merge #9024 into `main`, and then merge `main` into `v8` - so all the FAQs including this one will be nicely organized.
