### PR TITLE
fix(eslint-plugin): [no-unnecessary-type-assertion] detect unnecessary non-null-assertion on a call expression

### LINKED ISSUE #8141: Bug: [no-unnecessary-type-assertion] does not detect unnecessary non-null-assertion on a call expression
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unnecessary-type-assertion

### Description

I propose that the `no-unnecessary-type-assertion` rule should also check for the return type of a function.

### Fail

```TypeScript
declare function foo(): number;
const a = foo()!; // no error report
const b = foo() as number; // report error but bad fixed: `const b = foo() ; `
const c = <number>foo(); // good now
```

### Pass

```TypeScript
declare function foo(): number;
const a = foo();
const b = foo();
const c = foo();
```

### Additional Info

Im ready to send a PR after the issue is marked with the `accepting prs` label as indicated on the PR Checklist. Welcome to provide more test cases.

### PR DESCRIPTION
**Pull request by lvjiaxuan**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8141
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts:1]: [Cleanup] I can't comment on an unchanged file 😄 but it looks like this bugfix found an unnecessary `!` assertion in `packages/eslint-plugin/src/rules/no-unnecessary-condition.ts`! Great!

We ensure that lint rules pass on our current codebase as a form of testing. So that'll need to be fixed as part of this PR.

File: packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts:1]: [Testing] Interestingly, the fact that this line in `no-unnecessary-condition.ts` wasn't caught by the rule:

```ts
const callback = node.arguments[0]!;
```

...indicates a gap in code coverage for the rule which this change also fixes. Could you please add test coverage that case too?

File: packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts [hunk 1]
```diff
@@ -169,18 +169,18 @@ export default createRule<Options, MessageIds>({
...
 
           context.report({
             node,
             messageId: 'unnecessaryAssertion',
             fix(fixer) {
-              return fixer.removeRange([
-                node.expression.range[1],
-                node.range[1],
-              ]);
+              return fixer.removeRange([node.range[1] - 1, node.range[1]]);
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts:183]: [Praise] Nice call for the parenthesis!

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Good stuff! Looks like it works well, so just requesting changes on test coverage and fixing the internal lint complaint.

Btw this is a bugfix rather than a feature so I've edited the PR title. They show up differently in the changelog and have different semver version bump implications.

Girl from the Muppet Christmas Carol saying 'wonderful' happily

File: packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Comment (lvjiaxuan) [reply packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts:1]: okay, I will do it later.

**Review by JoshuaKGoldberg — APPROVED** [review]
Swell, thanks! 🙌
