### PR TITLE
fix(eslint-plugin): honor ignored base types on generic classes

### LINKED ISSUE #11758: Bug: [no-base-in-string] generic classes don't check for ignored superclasses
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.tsx&code=MYGwhgzhAEBCYDsDm0CmAPALqhATGAogE5ED2R0A3gFDUC%2B1okMsppAtgDwAqAfGlhz5oxMhRrRouVJjABLEBABc0bgG56tAGYBXBMExzSCaFrYAKVCXIr4yAJRVqk4MYikQqAHQhSSS9ZEXpikAMqYRHLI5vb2Ggy6%2BobG0ABGYEQ8vAFitmxcfI4S0K4I7p4%2BfjnkwWERUf6x8UA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oCMBDZRLXxdk%2BKkwDm6KImjQO0SODABfECqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
class Boom<T> extends Error {
  details: T;
}

function bar<T>(error: Boom<T>) {
  console.log(error.toString());
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-base-to-string": "error,
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Since no-base-to-string checks whether a plain class's supertypes are ignored (see #11520), I expect it to also check whether a generic class's supertypes are ignored.

### Actual Result

> 'error' will use Object's default stringification format ('[object Object]') when stringified. 12:15 - 12:20

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by OleksandraKordonets**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11758 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR fixes a false positive in `@typescript-eslint/no-base-to-string` where `.toString()` calls on values typed as generic subclasses of ignored types, such as `Error`, were being incorrectly reported. The rule previously only checked the type’s direct name, causing cases like `class Boom<T> extends Error {}` to be treated as unsafe, so this update adds recursive base-type checking with cycle protection to ensure that if a type or any of its ancestors match `ignoredTypeNames`, the call is allowed. A test is included to confirm `.toString()` is not reported for both direct and chained generic subclasses of `Error`, while preserving all existing rule behavior and configuration.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-base-to-string.ts [hunk 1]
```diff
@@ -211,14 +211,37 @@ export default createRule<Options, MessageIds>({
...
-      );
+      ) {
+        interfaceType = type as ts.InterfaceType;
+      }
+
+      if (!interfaceType) {
+        return [];
+      }
+
+      return checker.getBaseTypes(interfaceType);
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-base-to-string.ts:233]: [Style] The `let` variable confused me a bit - there are a few points of duplication in the code. What do you think about this vague streamlining attempt?

```ts
const interfaceTarget = tsutils.isTypeReference(type)
  ? type.target
  : type;
const interfaceType =
  tsutils.isObjectFlagSet(
    interfaceTarget,
    ts.ObjectFlags.Interface | ts.ObjectFlags.Class,
  ) && (interfaceTarget as ts.InterfaceType);

if (!interfaceType) {
  return [];
}

return checker.getBaseTypes(interfaceType);
```

File: packages/eslint-plugin/src/rules/no-base-to-string.ts [hunk 2]
```diff
@@ -232,12 +255,12 @@ export default createRule<Options, MessageIds>({
...
-          checker
-            .getBaseTypes(type)
-            .some(base => isIgnoredTypeOrBase(base, seen)))
+      if (ignoredTypeNames.includes(typeName)) {
+        return true;
+      }
+
+      return getBaseTypesForType(type).some(base =>
+        isIgnoredTypeOrBase(base, seen),
       );
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-base-to-string.ts]: [Style] If you want to save a few lines 😄 

```suggestion
      return (
        ignoredTypeNames.includes(getTypeName(checker, type)) ||
        getBaseTypesForType(type).some(base => isIgnoredTypeOrBase(base, seen))
      );
```

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, thanks! ✨ 

I just left a couple of stylistic nitpicks in case you're interested. No worries at all if you prefer the code as-is, I just like refactoring as a form of reading the code. Totally up to you. 🙂

**Comment by JoshuaKGoldberg** [comment]
> That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)

Btw, I wouldn't recommend sending PRs for issues that aren't yet marked as accepting prs. In this case it worked out because the issue was straightforward and accepted. But we've previously had to close PRs where the author put in a lot of work but the issue wasn't actually something that could be accepted. That feels bad for everyone.

https://typescript-eslint.io/docs/contributing
