### PR TITLE
fix(scope-manager): fix asserted increments not being marked as write references

### LINKED ISSUE #10270: Bug: [prefer-const] False positives when using increment operator with non-null assertion operator
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.6.3&fileType=.ts&code=DYUwLgBAhhC8EEZoGcIDsCuBbARiAThAD4QZoAmIAZgJZojkDcAsAFBQCEA1F40A&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQA7UQDNFoBaAYwHsA7ZAF3ShOkuknDAF8ROg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=true

### Repro Code

```TypeScript
let a = 1 as number | undefined;
a!++;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "prefer-const": "error",
  },
};
```

### tsconfig

_No response_

### Expected Result

It should not error.

### Actual Result

ESLint shows a message `'a' is never reassigned. Use 'const' instead. 1:5 - 1:6`

### Additional Info

Similar to #2804

### PR DESCRIPTION
**Pull request by janek515**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10270
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
This PR is analogous to #2809, but addresses increment operators.

### CODE REVIEW

File: packages/scope-manager/src/referencer/Referencer.ts [hunk 1]
```diff
@@ -752,8 +752,19 @@ class Referencer extends Visitor {
   }
 
   protected UpdateExpression(node: TSESTree.UpdateExpression): void {
-    if (PatternVisitor.isPattern(node.argument)) {
-      this.visitPattern(node.argument, pattern => {
+    let argument = node.argument;
```
Comment (janek515) [inline packages/scope-manager/src/referencer/Referencer.ts:755]: This could be extracted into a function (as it's the same as lines 328-338), but I have no idea how to name it.

Comment (JoshuaKGoldberg) [reply packages/scope-manager/src/referencer/Referencer.ts:755]: Good callout. Maybe... `visitExpressionLeft`? `visitExpressionLeftBypassingAssertion`? I'd put it at the end of `// Visit helpers` maybe.

**Review by JoshuaKGoldberg — APPROVED** [review]
Nice and clean, well done! ✨ 

I don't mind a little bit of code duplication (["WET" and all](https://softwareengineering.stackexchange.com/questions/425245/why-would-you-ever-want-wet-code)), but would lean towards deduplicating. Whichever the next team member prefers is ok with me. 🙂 

Three dogs clapping. Caption: "WELL DONE! YAY!"

File: packages/scope-manager/src/referencer/Referencer.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/scope-manager/src/referencer/Referencer.ts:755]: Coming back to this, I'll go with `visitExpressionTarget`. Only the other one of the two is about the _"left"_.
