### PR TITLE
fix(eslint-plugin): [space-infix-ops] support for optional property without type

### LINKED ISSUE #5154: Bug: [space-infix-ops] false positive with optional property since version 5.27.0
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=MYGwhgzhAECiAeYC2AHEBTaBvAUNaA9igC4CWBAdmCAPzQC80AZtROgNx7QD03+-0AHrQA8inQAnMMQIToAchrzoSAK4Ri0AEaYIKMMHQATAHQ4AvkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKWQBwEMBjRAWgEsA7AM3IA9SB7PVDSR66yAGnG0gACAFwCeeFEWjk8Q0inhUhAenzEyVWg2asoiaNEbRIfAL4gTQA&tsconfig=N4XyA

### Repro Code

```typescript
class Example {
  optional? = false;
  //      ^ Operator '?' must be spaced.
}
```

### ESLint Config

```javascript
{
  "rules": {
    "space-infix-ops": "off",
    "@typescript-eslint/space-infix-ops": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

no error

```ts
class Example {
  optional? = false;
  //      ^ Operator '?' must be spaced.

  // no error when explicitly typed or untyped
  explicitlyTypedOptionalWithInitialValue?: boolean = false;
  explicitlyTypedOptional?: boolean;
  untypedOptional?;
}
```

### Actual Result

`2:11 error Operator '?' must be spaced. @typescript-eslint/space-infix-ops`

### Additional Info

_No response_

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.27.1` |
| `@typescript-eslint/parser`            | `5.27.1` |
| `TypeScript`                           | `4.7.2` |
| `ESLint`                               | `8.15.0` |
| `node`                                 | `14.19.3` |

### PR DESCRIPTION
**Pull request by armano2**
## PR Checklist

-   [x] Addresses an existing open issue: fixes #5154
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Additional regression fix for #5041 `/^[=|?|:]$/.test(token.value)`

```
class Example {
  optional? = false;
}
```

---------------

Optimizations:
- reduce amount of computations needed to find tokens (we can use nodes as they contain proper information's about range)

### CODE REVIEW

File: packages/eslint-plugin/src/rules/space-infix-ops.ts [hunk 1]
```diff
@@ -69,17 +69,16 @@ export default util.createRule<Options, MessageIds>({
 
     function isSpaceChar(token: TSESTree.Token): boolean {
       return (
-        token.type === AST_TOKEN_TYPES.Punctuator &&
-        /^[=|?|:]$/.test(token.value)
```
Comment (armano2) [inline packages/eslint-plugin/src/rules/space-infix-ops.ts:73]: this regexp was not correct, it should be, `/^[=?:]$/` or `/^(=|?|:)$/`

File: packages/eslint-plugin/src/rules/space-infix-ops.ts [hunk 2]
```diff
@@ -124,9 +123,11 @@ export default util.createRule<Options, MessageIds>({
     function checkForPropertyDefinitionAssignmentSpace(
       node: TSESTree.PropertyDefinition,
     ): void {
-      const leftNode = sourceCode.getLastToken(
-        node.typeAnnotation ?? node.key,
-      )!;
+      const leftNode =
+        node.optional && !node.typeAnnotation
+          ? sourceCode.getTokenAfter(node.key)
+          : sourceCode.getLastToken(node.typeAnnotation ?? node.key);
```
Comment (armano2) [inline packages/eslint-plugin/src/rules/space-infix-ops.ts:129]: `isSpaceChar` is allowing `?` as token, than we have to skip it,

**Comment by armano2** [comment]
i'm starting to think that this rule need bigger overhaul, i don't understand why we are doing so many token selections there

**Comment by armano2** [comment]
looks like this is stil not correctly formatted

```
type Test=|string|(((() => void)));
```

File: packages/eslint-plugin/src/rules/space-infix-ops.ts (hunk 1 above)
Comment (Josh-Cena) [reply packages/eslint-plugin/src/rules/space-infix-ops.ts:73]: I recommend [this plugin](https://ota-meshi.github.io/eslint-plugin-regexp/playground/#eJyrVkrOT0lVslLSj4u2rbGvsYpV0dcrSS0u0SjJz07N0ytLzClN1YzJU6oFACNGDhE=), if you have a lot of non-trivial regexps to lint
