### PR TITLE
fix(eslint-plugin): [no-deprecated] max callstack exceeded when class implements itself

### LINKED ISSUE #10031: Bug: [no-deprecated] Maximum call stack size exceeded when class implements itself
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

If you have a class in TypeScript that implements itself (i.e. `class Foo implements Foo`), inside which is a getter method (i.e. `get bar(): number { return 42; }`) that is used by another method (i.e. `baz(): number { return this.bar; }`), then upon running `npx eslint Foo.ts` I get the error "RangeError: Maximum call stack size exceeded" while running rule `@typescript-eslint/no-deprecated`, which occurs while linting the line containing `return this.bar`.

Now, why exactly you would want a class to implement itself is quite beyond me, but I accidentally had that in my code and it took me quite a while to figure out what was going on. TypeScript itself seems to have no problem with it at all. I have no problem at all if the resolution is to detect this and then give an error, but that error must be descriptive.

My reproduction repo is quite minimal, so I'm not sure why I was unable to reproduce it in the playground. I'm not too good with node-ish setups, I guess.

### Reproduction Repository Link

https://github.com/FWDekker/typescript-eslint-no-deprecated-bug

### Repro Steps

1) clone the repo
2) `npm install`
3) `npx eslint Foo.ts`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.6.0` |
| `@typescript-eslint/parser`            | `8.6.0` |
| `@typescript-eslint/scope-manager`     | `8.6.0` |
| `@typescript-eslint/typescript-estree` | `8.6.0` |
| `@typescript-eslint/type-utils`        | `8.6.0` |
| `@typescript-eslint/utils`             | `8.6.0` |
| `TypeScript`                           | `5.5.4` |
| `ESLint`                               | `9.11.0` |
| `node` (Debian package)                                 | `20.17.0` |

### PR DESCRIPTION
**Pull request by tarunrajput**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10031
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

wraps `getJsDocTags` call in a try-catch

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-deprecated.ts [hunk 1]
```diff
@@ -116,17 +116,21 @@ export default createRule({
     function getJsDocDeprecation(
       symbol: ts.Signature | ts.Symbol | undefined,
     ): string | undefined {
-      const tag = symbol
-        ?.getJsDocTags(checker)
-        .find(tag => tag.name === 'deprecated');
+      try {
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-deprecated.ts:119]: Let's try to be as surgical about the try/catch as we can - can we make it so that essentially _only_ the `getJsDocTags()` call is wrapped?

File: packages/eslint-plugin/src/rules/no-deprecated.ts
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-deprecated.ts:1]: let's add the test case from the issue to the `valid` cases in packages/eslint-plugin/tests/rules/no-deprecated.test.ts with a note that it's just there to ensure it doesn't crash and link the github issue https://github.com/typescript-eslint/typescript-eslint/issues/10031.

File: packages/eslint-plugin/src/rules/no-deprecated.ts [hunk 2]
```diff
@@ -116,17 +116,21 @@ export default createRule({
...
+          return undefined;
+        }
 
-      const displayParts = tag.text;
+        const displayParts = tag.text;
 
-      return displayParts ? ts.displayPartsToString(displayParts) : '';
+        return displayParts ? ts.displayPartsToString(displayParts) : '';
+      } catch {
+        return;
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-deprecated.ts:132]: could you add a comment that says something like `// workaround for https://github.com/microsoft/TypeScript/issues/60024`?

**Review by kirkwaiblinger — CHANGES_REQUESTED** [review]

**Comment by kirkwaiblinger** [comment]
awesome, thanks! 🙂 

gif about infinite loop

**Review by kirkwaiblinger — APPROVED** [review]

**Review by auvred — APPROVED** [review]
Thanks!
