### PR TITLE
fix(type-utils): isTypeReadonly now handles conditional types

### LINKED ISSUE #4420: [isTypeReadonly] Conational types are always marked as readonly
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```TS
`type TestType<T> = T extends number[] ? string[] : number[];`,
```

```TS
isTypeReadonly(checker, type, {})
```

**Expected Result**

`isTypeReadonly` should return `false`

**Actual Result**

`isTypeReadonly` returns `true` for any conditional type.

**Additional Info**

Conditional types aren't being tested for and are thus being treated as primitives.

https://github.com/typescript-eslint/typescript-eslint/blob/97c0e8606705dc0b4ef8b4ee5206111276c8a170/packages/type-utils/src/isTypeReadonly.ts#L201-L205

**Versions**

| package                         | version |
| ------------------------------- | ------- |
| `@typescript-eslint/type-utils` | `5.9.0` |
| `@typescript-eslint/type-utils` | `5.9.0` |
| `TypeScript`                    | `4.5.4` |
| `node`                          | `17.1.0` |

Also note the error in the template in **Versions**: `@typescript-eslint/type-utils`'s version is requested twice. I assume there is supposed to be only one or one is supposed to be `@typescript-eslint/experimental-utils`

### PR DESCRIPTION
**Pull request by RebeccaStevens**
## PR Checklist

-   [x] Addresses an existing issue: fixes #4420
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

`isTypeReadonly` now checks conditional types properly.

Note: This PR builds off #4416

### CODE REVIEW

File: packages/type-utils/src/isTypeReadonly.ts [hunk 1]
```diff
@@ -198,6 +199,20 @@ function isTypeReadonlyRecurser(
...
+      .every(
+        t =>
+          seenTypes.has(t) ||
+          isTypeReadonlyRecurser(checker, t, options, seenTypes) ===
+            Readonlyness.Readonly,
+      );
+
+    const readonlyness = result ? Readonlyness.Readonly : Readonlyness.Mutable;
+    return readonlyness;
+  }
```
Comment (JoshuaKGoldberg) [inline packages/type-utils/src/isTypeReadonly.ts:214]: Nit: you might consider writing a function with a name something like `getChildTypeParts`, since the `isUnionType` and `isConditionalType` blocks are pretty much the same _except_ for how the types are retrieved.

```ts
const childTypeParts = getChildTypeParts(type);
if (childTypeParts) {
  const result = childParts.map(checker.getTypeFromTypeNode).every(...)
  // ...
}
```

Not a blocker IMO since it's only twice 🤷, more posting for visibility if there's another case we find later on.

**Review by JoshuaKGoldberg — APPROVED** [review]
Super, thanks so much for this & the other issues+PRs @RebeccaStevens! Very much appreciated!

File: packages/type-utils/src/isTypeReadonly.ts (hunk 1 above)
Comment (RebeccaStevens) [reply packages/type-utils/src/isTypeReadonly.ts:214]: I might rebase #4417 of this PR and make that change there seems it likely going to need to add 3rd case.

**Comment by bradzacher** [comment]
I merged your test PR first - just needs the conflict resolved and we can merge this!

**Comment by bradzacher** [comment]
man I hate how git handles these types of conflicts.
it's so truly horrible at them.
