### PR TITLE
fix(eslint-plugin): [member-delimiter-style] correct invalid fix for multiline with params on the same line

### LINKED ISSUE #2982: [member-delimiter-style] member-delimiter-style autofixer produces invalid code with {delimiter: 'none'}
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

.eslintrc.json
```JSON
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "rules": {
    "@typescript-eslint/member-delimiter-style": ["warn", {"multiline": {"delimiter": "none"}}]
  }
}
```

test.ts:
```TS
type Test = {
    a: {
        one: 1
    }; b: 2
};
```

`eslint --fix test.ts`

**Expected Result**

Autofix would not be enabled for this comma

```
  4:7  warning  Unexpected separator (;)  @typescript-eslint/member-delimiter-style
```

**Actual Result**

Autofixer created invalid code

```TS
type Test = {
    a: {
        one: 1
    } b: 2
//  ^ 4:6  error  Parsing error: ';' expected
};
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.14.1` |
| `@typescript-eslint/parser`        | `4.14.1` |
| `TypeScript`                       | `4.1.3` |
| `ESLint`                           | `7.18.0` |
| `node`                             | `14.15.3` |

### PR DESCRIPTION
**Pull request by tanohzana**
Everything was explained here: https://github.com/typescript-eslint/typescript-eslint/issues/2982

The rule would produce invalid code when trying to fix it.

Fixes #2982

### CODE REVIEW

File: packages/eslint-plugin/src/rules/member-delimiter-style.ts [hunk 1]
```diff
@@ -21,14 +28,26 @@ type Config = BaseOptions & {
     typeLiteral?: BaseOptions;
     interface?: BaseOptions;
   };
-  multilineDetection?: 'brackets' | 'last-member';
+  multilineDetection?: string;
```
Comment (armano2) [inline packages/eslint-plugin/src/rules/member-delimiter-style.ts:31]: i think this is not correct, with new implementation we are using this in one condition, and type should not be changed here

```ts
options.multilineDetection === 'last-member'
```

Comment (tanohzana) [reply packages/eslint-plugin/src/rules/member-delimiter-style.ts:31]: Could you explain a little bit more please ? 🙂

Comment (armano2) [reply packages/eslint-plugin/src/rules/member-delimiter-style.ts:31]: instead of accepting any string, we should explicitly state allowed type
```ts
  multilineDetection?: 'last-member';
```

see 
https://github.com/typescript-eslint/typescript-eslint/blob/74d7e537927643393320c48d31363b0ff013e364/packages/eslint-plugin/src/rules/member-delimiter-style.ts#L280

Comment (tanohzana) [reply packages/eslint-plugin/src/rules/member-delimiter-style.ts]: You're right. I fixed it here : 14491bceec7c9514ef325c51fe4146aa636b8385

File: packages/eslint-plugin/src/rules/member-delimiter-style.ts [hunk 2]
```diff
@@ -2,6 +2,10 @@ import {
   TSESTree,
   AST_NODE_TYPES,
 } from '@typescript-eslint/experimental-utils';
+import {
+  RuleFix,
+  RuleFixer,
+} from '@typescript-eslint/experimental-utils/src/ts-eslint';
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/member-delimiter-style.ts:8]: don't add deep imports on `/src` from plugins.
This is availaible on the `TSESLint` export of `@typescript-eslint/experimental-utils`

File: packages/eslint-plugin/src/rules/member-delimiter-style.ts [hunk 3]
```diff
@@ -83,9 +143,6 @@ export default util.createRule<Options, MessageIds>({
             },
             additionalProperties: false,
           },
-          multilineDetection: {
-            enum: ['brackets', 'last-member'],
-          },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/member-delimiter-style.ts:88]: why have you removed this from the schema entirely?

File: packages/eslint-plugin/src/rules/member-delimiter-style.ts [hunk 4]
```diff
@@ -21,14 +28,26 @@ type Config = BaseOptions & {
     typeLiteral?: BaseOptions;
     interface?: BaseOptions;
   };
-  multilineDetection?: 'brackets' | 'last-member';
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/member-delimiter-style.ts:24]: why have you removed this option entirely?

**Review by bradzacher — CHANGES_REQUESTED** [review]
there are a lot of changes here which seem to go further than fixing the bug.
could you please detail why you've removed an option from the rule to fix the bug?

File: packages/eslint-plugin/src/rules/member-delimiter-style.ts (hunk 2 above)
Comment (tanohzana) [reply packages/eslint-plugin/src/rules/member-delimiter-style.ts]: Fixed here: a27e2e38c955f9211c8f223ce966b289f128e779

File: packages/eslint-plugin/src/rules/member-delimiter-style.ts (hunk 4 above)
Comment (tanohzana) [reply packages/eslint-plugin/src/rules/member-delimiter-style.ts]: Fixed here: e5353a9ea7bdff443335c057e61f75de893ec901

File: packages/eslint-plugin/src/rules/member-delimiter-style.ts (hunk 3 above)
Comment (tanohzana) [reply packages/eslint-plugin/src/rules/member-delimiter-style.ts]: Fixed here: 75e83de73f53175e9d38a6f47ae1ff46c1b0c853

**Comment by tanohzana** [comment]
Sorry for the unneeded changes, I had differences between the version I cloned a few weeks ago and the new one. But all should be fixed now

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for working on this!
