### PR TITLE
fix(eslint-plugin): [unbound-method] false positive on property function initializer

### LINKED ISSUE #1869: [unbound-method] referencing a property with a function type should cause error
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/unbound-method": [
            "error",
            {
                "ignoreStatic": true
            }
        ]
  }
}
```

```TS
class SomeClass {
    functionProperty = function(this: any) { console.log(`this is ${this}`); };
}

const myFunctionProperty = new SomeClass().functionProperty;  // X - Missing eslint error
myFunctionProperty();  // Doesn't work, despite no eslint error
```

**Expected Result**
`unbound-method` error when initializing `myfunctionProperty `

**Actual Result**
No error, but calling `myFunctionProperty()` prints out `this is undefined`

**Additional Info**
I wonder if there should also be a rule for requiring the `this` parameter in inline function definitions be declared to have the most specific type possible(?).  If I declare `functionProperty = function(this: SomeClass) { ... }` then there's a compiler error when I try to call `myFunctionProperty()`:
```
The 'this' context of type 'void' is not assignable to method's 'this' of type 'MyClass'.ts(2684)
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.17.0` |
| `@typescript-eslint/parser`        | `2.17.0` |
| `TypeScript`                       | `3.7.5` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `10.19.0` |
| `npm`                              | `6.13.4` |

### PR DESCRIPTION
**Pull request by vapurrmaid**
resolves #1869

### CODE REVIEW

File: packages/eslint-plugin/src/rules/unbound-method.ts [hunk 1]
```diff
@@ -197,6 +197,16 @@ function isDangerousMethod(symbol: ts.Symbol, ignoreStatic: boolean): boolean {
...
 
+  if (valueDeclaration.kind === ts.SyntaxKind.PropertyDeclaration) {
+    const propertyDeclaration = valueDeclaration as ts.PropertyDeclaration;
+    if (
+      propertyDeclaration.initializer &&
+      propertyDeclaration.initializer.kind === ts.SyntaxKind.FunctionExpression
+    ) {
+      return true;
+    }
+  }
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/unbound-method.ts:208]: nit - move this into the switch below eg

```ts
case ts.SyntaxKind.PropertyDeclaration:
  const propertyDeclaration = valueDeclaration as ts.PropertyDeclaration;
  return (
    propertyDeclaration.initializer?.kind === ts.SyntaxKind.FunctionExpression
  );
```

Comment (vapurrmaid) [reply packages/eslint-plugin/src/rules/unbound-method.ts]: oof, nice catch!

**Comment by markfields** [comment]
Thanks @vapurrmaid!
