### PR TITLE
fix(eslint-plugin): fix schemas across several rules and add schema tests

### LINKED ISSUE #6852: Bug: [array-type] the config `simple-array` should be disallowed by the schema
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.0.2&sourceType=module&code=MYewdgzgLgBAhgLhgCmgJwJZgOYwD4xgCuAtgEYCmaAlANoC6MAvDAwNwBQoksZSx5Kg2at6nbtBjAkAQTRo4ATwA86LLgIDKaAHwj2XcJIAms+UuVaqeluyA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AQ2mncNqNPRgA2pERcA9tEgAaTJAAmiAGbsE+QZGSUAtsSS1O3QpAC+AXXBgTIE0A

### Repro Code

```typescript
const a: (string | number)[] = [];
const b: number[] = [];
const c: Array<string | number> = [];
const d: Array<number> = [];
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  "rules": {
    "@typescript-eslint/array-type": ["error", {"default": "simple-array"}]
  }
};
```

### tsconfig

_No response_

### Expected Result

The constants a and d should fail the 'array-simple' rule and thus cause the following errors:

a: `Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>'`
d: `Array type using 'Array<number>' is forbidden for simple types. Use 'number[]' instead.`

### Actual Result

All four constants fail the rule and cause errors. This means for example that neither `number[]` nor `Array<number>` is allowed, making it impossible to annotate array types without causing eslint error, if the "array-type" rule is configured with "simple-array".

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by domdomegg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6852, #6892
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Rebase of #6894 on top of v6, as per https://github.com/typescript-eslint/typescript-eslint/pull/6894#issuecomment-1516224308

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-restricted-imports.ts [hunk 1]
```diff
@@ -19,37 +19,95 @@ const baseRule = getESLintCoreRule('no-restricted-imports');
...
+// possible, we'll fallback to less strict checks.
+const tryAccess = <T>(getter: () => T, fallback: T): T => {
+  try {
+    return getter();
+  } catch {
+    return fallback;
+  }
+};
+
+const baseSchema = baseRule.meta.schema as {
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-restricted-imports.ts:33]: question: why did you switch back to basing off of the base rule's schema here?
Any reason or was it just to go back to de-duping things?

File: packages/eslint-plugin/src/rules/parameter-properties.ts [hunk 2]
```diff
@@ -59,7 +59,6 @@ export default util.createRule<Options, MessageIds>({
             items: {
               $ref: '#/items/0/$defs/modifier',
             },
-            minItems: 1,
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/parameter-properties.ts:62]: question: why remove this? isn't it better if we keep this for strictness to prevent empty arrays?

File: packages/eslint-plugin/tests/areOptionsValid.ts [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+    return false;
+  }
+
+  return valid;
+}
+
+function normalizeSchema(
+  schema: JSONSchema4 | readonly JSONSchema4[],
+): JSONSchema4 {
+  if (!Array.isArray(schema)) {
```
Comment (bradzacher) [inline packages/eslint-plugin/tests/areOptionsValid.ts:25]: We could export this from the `index.ts` in the package and use it here
https://github.com/typescript-eslint/typescript-eslint/blob/3e3b7891a73136136929b6912ace9301b30fb0f3/packages/rule-schema-to-typescript-types/src/isArray.ts

Which will fix the safety caused by the TS bug

File: packages/eslint-plugin/tests/rules/array-type.test.ts [hunk 4]
```diff
@@ -2156,3 +2157,19 @@ type BrokenArray = {
...
+    }
+  });
+
+  // https://github.com/typescript-eslint/typescript-eslint/issues/6892
+  test('array-type does not accept non object option', () => {
+    if (areOptionsValid(rule, ['array'])) {
+      throw new Error(`Options succeeded validation for bad options`);
+    }
+  });
+});
```
Comment (bradzacher) [inline packages/eslint-plugin/tests/rules/array-type.test.ts:2175]: I wonder if we should do a rule-tester style API here to remove the boilerplate.
For example something like this:

```ts
ruleOptionsTester(rule, {
  valid: [ ... ],
  invalid: [
    [{ default: 'simple-array' }],
    ['array'],
  ],
});
```

File: packages/eslint-plugin/src/rules/no-restricted-imports.ts (hunk 1 above)
Comment (domdomegg) [reply packages/eslint-plugin/src/rules/no-restricted-imports.ts:33]: No strong reason: just to dedupe things / keep things in sync.

File: packages/eslint-plugin/tests/areOptionsValid.ts (hunk 3 above)
Comment (domdomegg) [reply packages/eslint-plugin/tests/areOptionsValid.ts:25]: Nice - didn't see this helper existed. Have moved it from the rule-schema-to-typescript-types package to the utils package and have used here.

File: packages/eslint-plugin/tests/rules/array-type.test.ts (hunk 4 above)
Comment (domdomegg) [reply packages/eslint-plugin/tests/rules/array-type.test.ts:2175]: Yeah, I think something like this would be neat if we end up doing a lot of these kinds of tests. For now I think it's simple enough that we can leave this to be done in future if necessary?

**Comment by JoshuaKGoldberg** [comment]
Removing from the v6 milestone as it doesn't actually block releasing v6 (I believe). Someone yell at me if that's wrong. 🙂

**Comment by JoshuaKGoldberg** [comment]
Oh also, @domdomegg just checking in - are you waiting on us for anything? I believe our last status was waiting on you to re-request review to take another look.

File: packages/eslint-plugin/tests/rules/array-type.test.ts (hunk 4 above)
Comment (bradzacher) [reply packages/eslint-plugin/tests/rules/array-type.test.ts:2175]: Note that there is
https://github.com/eslint/rfcs/pull/103 and the implementing PR https://github.com/eslint/eslint/pull/16823

This would allow us to include these tests in the rule like:
```
tester.run('rule', rule, {
  valid: [ ... ],
  invalid: [ ... ],
  fatal: [
    {
      options: ['simple-array'],
      error: {
        name: 'SchemaValidationError',
        message: 'Whatever the json schema error is',
      },
    },
    {
      options: ['array'],
      error: {
        name: 'SchemaValidationError',
        message: 'Whatever the json schema error is',
      },
    },
  ],
}
```

**Review by bradzacher — DISMISSED** [review]

**Comment by bradzacher** [comment]
@domdomegg if you want to update this against `v6` and resolve the conflicts, and get the CI passing - then we're good to merge this in!

**Comment by domdomegg** [comment]
I think we're ready @bradzacher / @JoshuaKGoldberg :)

**Comment by JoshuaKGoldberg** [comment]
This was unintentionally auto-closed when we merged the `v6` branch 🙃 it'll be recreated.

**Comment by domdomegg** [comment]
Thanks @JoshuaKGoldberg :raised_hands:
