### PR TITLE
fix(utils): handle missing `FlatESLint` and `LegacyESLint`

### LINKED ISSUE #11629: Bug: Conditionally re-export LegacyESLint if it exists
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I'm not quite sure I understand why, but `@typescript-eslint\utils` contains a reference to `LegacyESLint` from the `eslint` package. `LegacyESLint` will be removed in ESLint v10, and typescript-eslint then errors because `LegacyESLint` is not found. We're already seeing this in our work on v10.

It is a **really bad practice** to depend on anything in the `/use-at-your-own-risk` entrypoint, especially redistributing it as something that a plugin will include. 

### Reproduction Repository Link

https://github.com/eslint/eslint/tree/remove-eslintrc-cli

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/parser`            | `8.4.0` |

### PR DESCRIPTION
**Pull request by fasttime**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11629
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR updates `FlatESLint` and `LegacyESLint` from `@typescript-eslint/utils/ts-eslint` to ensure compatibility with ESLint v10.

ESLint v10 does not provide exports for `FlatESLint` and `LegacyESLint`, which are used as base classes for their homonymous typescript-eslint counterparts. To maintain compatibility under ESLint v10, this PR adds the following fallback behavior:
- `FlatESLint` will use `ESLint` as a base class.
- `LegacyESLint` remains defined, but invoking its constructor or any static method will throw an error.

### CODE REVIEW

File: packages/utils/src/ts-eslint/ESLint.ts [hunk 1]
```diff
@@ -1,7 +1,6 @@
 export { FlatESLint } from './eslint/FlatESLint';
 export { FlatESLint as ESLint } from './eslint/FlatESLint';
 export {
-  // TODO(eslint@v10) - remove this in the next major
```
Comment (JoshuaKGoldberg) [inline packages/utils/src/ts-eslint/ESLint.ts:4]: [Docs] Heh, I suppose this is now for _our_ next major, not ESLint's (and really has always been)...

```suggestion
  // TODO(typescript-eslint@v9) - remove this in the next major
```
/

File: packages/utils/src/ts-eslint/eslint/FlatESLint.ts [hunk 2]
```diff
@@ -34,7 +35,8 @@ declare class FlatESLintBase extends Shared.ESLintBase<
  *
  * If you want to lint code on browsers, use the Linter class instead.
  */
-export class FlatESLint extends (ESLintFlatESLint as typeof FlatESLintBase) {}
+export class FlatESLint extends ((useAtYourOwnRisk.FlatESLint ??
+  ESLint) as typeof FlatESLintBase) {}
```
Comment (JoshuaKGoldberg) [inline packages/utils/src/ts-eslint/eslint/FlatESLint.ts:39]: > fallback behavior: `FlatESLint` will use `ESLint` as a base class.

[Praise] 👍 yes I think this is the right strategy. Thinking out loud - if there's no `useAtYourOwnRisk.FlatESLint` then we're on ESLint >=10, so `ESLint `_is_ the flat class version. Clean! 🙂

File: packages/utils/src/ts-eslint/ESLint.ts (hunk 1 above)
Comment (fasttime) [reply packages/utils/src/ts-eslint/ESLint.ts:4]: I see, thanks. Updated in ec1fac63cd93fbc6f68dd290f0b245761c0a8140.
