### PR TITLE
fix: fix tsconfig-less check errors, fix `@types/eslint` incompatibilities, add tests

### LINKED ISSUE #8459: Docs: getting started guide causes type errors in eslint.config.js
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

steps to reproduce:
```
mkdir test
cd test
npm init --yes
npm install --save-dev eslint typescript typescript-eslint
vim eslint.config.mjs
```
(paste in the code directly from the getting started guide)
```
code .
```
(open eslint.config.mjs inside vscode)
(observe the red squiggly)

Perhaps something is wrong with the published typescript definitions?

### Affected URL(s)

https://typescript-eslint.io/getting-started/

### PR DESCRIPTION
**Pull request by bradzacher**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8459, #8467
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR addresses a few problems:

1) Our flat config types are completely incompatible with `@types/eslint` - meaning plugins defined using those types cannot be used in `tseslint.config(..)` (#8467)
2) Our packages do not support `node10` (#8459)
3) We had no tests to validate how someone might use `typescript-eslint` IRL

---

For (3) I added an integration test which runs TS over a `eslint.config.js` file and validates the outputs so we can truely validate that `typescript-eslint` works as intended with no errors.

---

For (1) I went through and updated the types to align them or loosen them.
We've chatted about this before and I don't love loosening them but there's just severe incompatibilities between the two that means we have no choice really. We're a lot stricter than the DT types to enforce users do the right thing - but DT isn't about enforcing strictness; it's about correctly representing the state of the world.
i.e. the types are just fundamentally incompatible as they serve different use cases!

-----

For (2) ... Users right now are running into a problem:
Our getting started guide tells them to add `// @ts-check` to their `eslint.config.js` file.
When they copy+paste the example code into their file they see a type error from TS:
```
Cannot find module 'typescript-eslint' or its corresponding type declarations.ts(2307)
```

Playing around I believe the issue is that their `eslint.config.js` is not included in any `tsconfig.json`s. Without a `tsconfig.json` TS uses the "default" compiler options which sadly means the file is checked with `module: node10` 😢 (#7284).

So we have a three options really:
1) update the getting started guide to tell everyone to reconfigure their `tsconfig.json` so that they have their `eslint.config.js` included in it
2) make the package work under `node10`
3) remove `// @ts-check` and don't recommend typechecking of config files

Option (3) I hate. The entire point of `tseslint.config` was so that we could allow users to have typechecked config files. We have all the properties jsdoc'd so that users get autocomplete with all the documentation in their IDE.
So removing that from the guide is a MASSIVE step back.

Option (1) could work - however it's not going to be easy to write generic and simple docs to tell the user how to cover the `eslint.config.js` file with a tsconfig. For example if the user has just one `tsconfig.json` in their repo that they use for their build they need to separate their build config into a `tsconfig.build.json` so that they can add non-build files to `tsconfig.json`. Essentially we don't know the user's setup so it's hard to provide that succinct "silver bullet" advice on how you might do things.
Given that we want the getting started guide to be super simple - IMO this makes option (1) a non-starter.

So that means (2) is the best bet 😭. I hate it because as per #7284 we really don't want to do this hack for backwards compat.

### CODE REVIEW

**Comment by Zamiell** [comment]
Also note that in the ultra long term, TypeScript itself would update the default value from Node10 to the newer setting. In that world, this PR could be reverted. So maybe in 5 years or so?

**Comment by bradzacher** [comment]
@Zamiell - https://github.com/microsoft/TypeScript/issues/54500 - TS 6.0 maybe?
we're on 5.3 - +0.1 per quarter so 7 quarters -- 2 years!?!?

**Comment by htho** [comment]
Hi, I opened #8459 which is primarily a documentation issue, but it also shows, that type information for `tseslint.config()` is (partially) missing.

I manually applied ["main": "./dist/index.js", to my ./node_modules/typescript-eslint/package.json](https://github.com/typescript-eslint/typescript-eslint/pull/8460/commits/da23118848d17c7f33d4bbe9024f43806d4d1369)

The Problem is @typescript-eslint/utils/ts-eslint can not be resolved, and therefore FlatConfig can not be imported.

Maybe `"main": "./dist/index.js"` has to be applied to other `package.json` files too?

**Comment by bradzacher** [comment]
Hmm. My little toy tester didn't actually paste the example in - I just had the import and fixed the error.

Will defs need to think on this more 🤔

**Comment by bradzacher** [comment]
Cc @jakebailey do you know of a way we can help users solve this easily in a consistent, generic way? Or are we just stuck because of the `node10` default?

**Comment by jakebailey** [comment]
Just to be super clear, are you worried about the editor case?

In the next version of TypeScript, there's a new mode that vscode will use as its default for the implicit project; module=preserve  + moduleResolution=bundler, which will likely make this all go away as that combo will be export map aware.

**Comment by bradzacher** [comment]
@jakebailey yeah IMO the editor usecase is the primary concern. I think a lot of people won't want to strictly typecheck their config files via the CLI - if they do then this problem goes away!

Using `// @ts-check` means that they can have type errors and autocomplete in their IDE whilst authoring their config which should be "good enough" given eslint also checks the config at lint-time.

> default for the implicit project; module=preserve + moduleResolution=bundler, which will likely make this all go away as that combo will be export map aware

That's great to hear!
But that default will require people to upgrade to TS5.4, right? Or will it apply to vscode's setup by default?

**Review by JoshuaKGoldberg — APPROVED** [review]
👍 makes sense.

Once the experimental project service is stabilized and #8206 resolved, this should no longer be an issue. We then should be able to remove it for v8.

**Comment by bradzacher** [comment]
> Once the experimental project service is stabilized and https://github.com/typescript-eslint/typescript-eslint/issues/8206 resolved, this should no longer be an issue

@JoshuaKGoldberg it won't fix anything! This isn't a problem with ESLint reporting on the file - it's a problem with TypeScript itself reporting on the file!

**Comment by jakebailey** [comment]
> But that default will require people to upgrade to TS5.4, right? Or will it apply to vscode's setup by default?

Yes, people would need to update. Though, a lot of people use the built-in version of TS, which helps.

I'll note that the fact that vscode uses different defaults for the inferred (implicit? one of those) poses the question of what defaults you all should set too; I suspect that you may want to mirror them.

**Comment by bradzacher** [comment]
The big two things we strongly disagree with is
- the default of `node10` module resolution -- we push everyone to `node16`
- the default of same strict settings like `strictNullChecks` -- we push everyone to turn them on.

But the former is the only requirement we've imposed (much to some people's chagrin #7284).

We honestly hate the fact that node10 resolution is the default and will likely remain the default till TS 6.0 because it's a land mine for a lot of usecases.

**Comment by jakebailey** [comment]
In 5.4+, VS Code will default to module=preserve/moduleResolution=bundler, and it has defaulted to strictNullChecks and strictFunctionTypes for a year or two. I do feel like you'd stand to benefit from also setting those defaults if available; it'll only affect random files not in projects, and these are the settings I'd hazard to say that most people see anyway if they never configured TypeScript.

But, yes, I don't think these defaults are going to change until 6.0 unless we decide to change what we announced about setting stability previously. I'm not totally sure what a better default would be, though; the combo I described above is a perfect case for VS Code as it never emits, and arguably eslint, but it's not a great default for regular tsconfigs as its emit is probably not super helpful.

**Comment by bradzacher** [comment]
@JoshuaKGoldberg this PR has been radically updated from the 1 line PR you stamped.
Please re-review 😄

File: packages/utils/src/ts-eslint/Rule.ts [hunk 1]
```diff
@@ -632,33 +632,48 @@ interface RuleModule<
    */
   create(context: Readonly<RuleContext<TMessageIds, TOptions>>): TRuleListener;
 }
-type AnyRuleModule = RuleModule<string, readonly unknown[]>;
+export type AnyRuleModule = RuleModule<string, readonly unknown[]>;
 
-type RuleCreateFunction<
+/**
+ * A loose definition of the RuleModule type for use with configs. This type
```
Comment (JoshuaKGoldberg) [inline packages/utils/src/ts-eslint/Rule.ts:638]:
```suggestion
 * A loose definition of the RuleModule type for use with configs. This type is
```

File: packages/utils/src/ts-eslint/Rule.ts [hunk 2]
```diff
@@ -632,33 +632,48 @@ interface RuleModule<
...
-  RuleFix,
-  RuleFixer,
-  RuleFunction,
-  RuleListener,
-  RuleListenerExtension,
-  RuleMetaData,
-  RuleMetaDataDocs,
-  RuleModule,
-  SharedConfigurationSettings,
-};
```
Comment (JoshuaKGoldberg) [inline packages/utils/src/ts-eslint/Rule.ts:664]: [Non-Actionable] That reminds me, I totally forgot about https://github.com/typescript-eslint/typescript-eslint/issues/5871 ...

File: packages/utils/src/ts-eslint/Rule.ts [hunk 3]
```diff
@@ -632,33 +632,48 @@ interface RuleModule<
...
+ * A loose definition of the RuleModule type for use with configs. This type
+ * intended to relax validation of types so that we can have basic validation
+ * without being overly strict about nitty gritty details matching.
+ *
+ * For example the plugin might be declared using an old version of our types or
+ * they might use the DefinitelyTyped eslint types. Ultimately we don't need
+ * super strict validation in a config - a loose shape match is "good enough" to
+ * help validate the config is correct.
+ *
+ * See also LooseParserModule, LooseProcessorModule
```
Comment (JoshuaKGoldberg) [inline packages/utils/src/ts-eslint/Rule.ts:647]: [Docs] Nit: for nice JSDoc linkage

```suggestion
 * @see {@link LooseParserModule}, {@link LooseProcessorModule}
```

File: packages/utils/src/ts-eslint/Parser.ts [hunk 4]
```diff
@@ -20,13 +20,15 @@ export namespace Parser {
    * A loose definition of the ParserModule type for use with configs
    * This type intended to relax validation of configs so that parsers that have
    * different AST types or scope managers can still be passed to configs
+   *
+   * See also LooseRuleDefinition, LooseProcessorModule
```
Comment (JoshuaKGoldberg) [inline packages/utils/src/ts-eslint/Parser.ts:24]:
```suggestion
   * @see {@link LooseRuleDefinition}, {@link LooseProcessorModule}
```

File: packages/utils/src/ts-eslint/Processor.ts [hunk 5]
```diff
@@ -45,4 +45,43 @@ export namespace Processor {
      */
     supportsAutofix?: boolean;
   }
+
+  /**
+   * A loose definition of the ParserModule type for use with configs
+   * This type intended to relax validation of configs so that parsers that have
+   * different AST types or scope managers can still be passed to configs
+   *
+   * See also LooseRuleDefinition, LooseParserModule
```
Comment (JoshuaKGoldberg) [inline packages/utils/src/ts-eslint/Processor.ts:54]:
```suggestion
   * @see {@link LooseRuleDefinition}, {@link LooseParserModule}
```

**Review by JoshuaKGoldberg — DISMISSED** [review]
Yeah 😬 I don't see a way around this. Good work!

**Review by JoshuaKGoldberg — APPROVED** [review]
