### PR TITLE
fix(typescript-estree): ensure consistent TSMappedType AST shape

### LINKED ISSUE #11055: Bug: Inconsistent TSMappedType AST shape for optional and readonly
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### Playground Link

https://typescript-eslint.io/play/#ts=5.8.3&showAST=es&fileType=.ts&code=G4QwTgBCBcEN4QNoGsIEsB2UME8C6sIuEAvgFBmiQBGsCK6WR%2BA-IceZeBAMZ0RgApiAAmAewwAbHElSZs%2BdjM5UII-gGohoidNmMFeNgtIVVg-gFpt4qTIbzmBEySA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=true

### Repro Code

```TypeScript
var a: { [k in any]: any }

var b: { [k in any]?: any }

var c: { readonly [k in any]: any }

var d: { +readonly [k in any]?: any }

var e: { -readonly [k in any]: any }
```

### ESLint Config

```javascript

```

### tsconfig

```jsonc

```

### Expected Result

The 1st TSMappedType should have properties `{ optional: false, readonly: undefined }`

The 2nd TSMappedType should have property `{ readonly: undefined }`

The 3rd TSMappedType should have property `{ optional: false }`

The 5th TSMappedType should have property `{ optional: false }`

### Actual Result

The aforementioned TSMappedTypes are missing such properties, resulted to inconsistent AST shapes.

### Additional Info

_No response_

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `8.29.1` |

### PR DESCRIPTION
**Pull request by dbarabashh**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11055 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

```typescript
var a: { [k in any]: any }              // No modifiers
var b: { [k in any]?: any }             // Optional modifier
var c: { readonly [k in any]: any }     // Readonly modifier
var d: { +readonly [k in any]?: any }   // +readonly and optional modifier
var e: { -readonly [k in any]: any }    // -readonly modifier
```

#### Example a: `{ [k in any]: any }`
```javascript
{
  type: "TSMappedType",
  constraint: {
    type: "TSAnyKeyword"
  },
  key: {
    type: "Identifier",
    name: "k"
  },
  nameType: null,
  optional: false,             // Now has explicit false value
  readonly: undefined,         // Now has explicit undefined value
  typeAnnotation: {
    type: "TSAnyKeyword"
  }
}
```

#### Example b: `{ [k in any]?: any }`
```javascript
{
  type: "TSMappedType",
  constraint: {
    type: "TSAnyKeyword"
  },
  key: {
    type: "Identifier",
    name: "k"
  },
  nameType: null,
  optional: true,              // Has true value because of ? modifier
  readonly: undefined,         // Now has explicit undefined value
  typeAnnotation: {
    type: "TSAnyKeyword"
  }
}
```

#### Example c: `{ readonly [k in any]: any }`
```javascript
{
  type: "TSMappedType",
  constraint: {
    type: "TSAnyKeyword"
  },
  key: {
    type: "Identifier",
    name: "k"
  },
  nameType: null,
  optional: false,             // Now has explicit false value
  readonly: true,              // Has true value because of readonly modifier
  typeAnnotation: {
    type: "TSAnyKeyword"
  }
}
```

#### Example d: `{ +readonly [k in any]?: any }`
```javascript
{
  type: "TSMappedType",
  constraint: {
    type: "TSAnyKeyword"
  },
  key: {
    type: "Identifier",
    name: "k"
  },
  nameType: null,
  optional: true,              // Has true value because of ? modifier
  readonly: "+",               // Has "+" value because of +readonly modifier
  typeAnnotation: {
    type: "TSAnyKeyword"
  }
}
```

#### Example e: `{ -readonly [k in any]: any }`
```javascript
{
  type: "TSMappedType",
  constraint: {
    type: "TSAnyKeyword"
  },
  key: {
    type: "Identifier",
    name: "k"
  },
  nameType: null,
  optional: false,             // Now has explicit false value
  readonly: "-",               // Has "-" value because of -readonly modifier
  typeAnnotation: {
    type: "TSAnyKeyword"
  }
}
```

### CODE REVIEW

File: packages/typescript-estree/src/convert.ts [hunk 1]
```diff
@@ -2870,14 +2870,14 @@ export class Converter {
...
-                (node.readonlyToken.kind === SyntaxKind.ReadonlyKeyword ||
-                  getTextForTokenKind(node.readonlyToken.kind)),
+              optional: node.questionToken
+                ? node.questionToken.kind === SyntaxKind.QuestionToken ||
+                  getTextForTokenKind(node.questionToken.kind)
+                : false,
+              readonly: node.readonlyToken
+                ? node.readonlyToken.kind === SyntaxKind.ReadonlyKeyword ||
+                  getTextForTokenKind(node.readonlyToken.kind)
+                : undefined,
```
Comment (JoshuaKGoldberg) [inline packages/typescript-estree/src/convert.ts:2880]: > Note that `readonly` is an enum of `true`, `+` and `-`. So previously I proposed `undefined` as the default value. I guess `false` does no harm here.

Agreed that either could work, and also agreed on going with `undefined`. That feels to me like a more normal default when there are multiple truthy options (`'+'`, `'-'`). I can see why `false` might make sense as a counterpoint to `true`, but visually I think it makes less sense.

File: packages/typescript-estree/tests/lib/convert.test.ts [hunk 2]
```diff
@@ -449,5 +449,79 @@ describe('convert', () => {
       expect(tsMappedType.typeParameter).toBeUndefined();
       expect(Object.keys(tsMappedType)).toContain('typeParameter');
     });
+
+    describe('TSMappedType AST shape consistency', () => {
```
Comment (JoshuaKGoldberg) [inline packages/typescript-estree/tests/lib/convert.test.ts:453]: [Testing] We normally put fixtures in `packages/ast-spec/src`. Is there a reason not to here?

If not, I think `packages/ast-spec/src/type/TSMappedType` would be the right place to add new fixtures around `readonly` and/or optional mapped types.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
🙌 The source code change looks good to me, thanks! Requesting changes on going with the ast-spec tests that other types of syntax conversions are verified with too.

**Review by bradzacher — APPROVED** [review]
thanks -- just because my review time is limited I took a moment to fix up your fixtures (you had nested the folders incorrectly which meant the snapshots weren't generated -- we might wanna add an error for this...). And I added a few extra snapshots to cover some more cases.

this all LGTM!

**Comment by dbarabashh** [comment]
@bradzacher Thank you so much. I was just about to write a comment about the file structure.

and one more question, what should we do about the coverage rate?
