### PR TITLE
fix(eslint-plugin): [no-unnecessary-type-constraint] correctly fix in cts/mts files

### LINKED ISSUE #5449: Bug: [no-unnecessary-type-constraint] False positive for generics on arrow functions in .mts files
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Issue Description

When using the new ([as of TS 4.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#new-file-extensions)) `.mts` file extension the `const foo = <T>() => ...` syntax for generic arguments is reserved similar to JSX files. The suggestion from tsc recommends defining an explicit constraint:

image

Since my function doesn't need or nor do I want a type constraint, but I need one for the syntax, I reached for the noop constraint of `extends any`, but then I was violating the `no-unnecessary-type-constraint` rule.

image

In this case, with the `.mts` extension and it's limited syntax I think it's unfair to say it "doesn't do anything and is unnecessary".

### Reproduction Repository Link

https://github.com/spalger/reproduce-issues/tree/ts-eslint-no-unnecessary-type-constraint

### Repro Steps

1) clone the repo with `--branch`

    `git clone git@github.com:spalger/reproduce-issues.git --branch ts-eslint-no-unnecessary-type-constraint`

2) `npm i`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.33.0` |
| `@typescript-eslint/parser`            | `5.33.0` |
| `TypeScript`                           | `4.7.4` |
| `ESLint`                               | `8.21.0` |
| `node`                                 | `18.7.0` |

### PR DESCRIPTION
**Pull request by WoodyWoodsta**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5449 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

- Suggest comma disambiguation on `.mts`, `cts` as well as jsx variant files

### CODE REVIEW

**Comment by WoodyWoodsta** [comment]
I've specifically left out unit tests for this, as it doesn't appear that any of the fixtures for `eslint-plugin` include .mts or .cts files. It seems like something which should require test-wide/project-wide consensus. Please correct me if I'm wrong!

**Comment by WoodyWoodsta** [comment]
I've noticed two things:
- My changes don't address the problem (at least in my project via linking)
- I can add tests as you can specify the `filename` on the `RuleTester`. Will do that now.

File: packages/typescript-estree/src/create-program/getScriptKind.ts [hunk 1]
```diff
@@ -1,6 +1,32 @@
 import path from 'path';
 import * as ts from 'typescript';
 
+function isNewModuleExtension(filePath: string): boolean {
```
Comment (Josh-Cena) [inline packages/typescript-estree/src/create-program/getScriptKind.ts:4]: I suggest a better name, because "new" doesn't age where. What about `isNodeNextModuleExtension`

Comment (Josh-Cena) [reply packages/typescript-estree/src/create-program/getScriptKind.ts:4]: The reason why I didn't go with `Node16` is exactly because it's tied to a specific feature and if that resolution mode goes out of fashion (e.g. when `Node24` is introduced, etc.), the function would seem awkward. Unless you plan to make this function do exactly `Node16` logic and do not intend it to accomodate new extensions in the future, I suggest using something more fluid like `NodeNext`.

Comment (WoodyWoodsta) [reply packages/typescript-estree/src/create-program/getScriptKind.ts:4]: That's fine - more just aware that "node-next" is something that changes meaning over time, but the method logic won't unless updated. Ultimately happy with either, so will make it `isNodeNextModuleExtension`.

File: packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts [hunk 2]
```diff
@@ -60,14 +65,21 @@ export default util.createRule({
...
       : new Map([[AST_NODE_TYPES.TSUnknownKeyword, 'unknown']]);
 
-    const inJsx = context.getFilename().toLowerCase().endsWith('tsx');
+    const filename = context.getFilename();
+    const scriptKind = getScriptKind(
+      filename,
+      !!context.parserOptions.ecmaFeatures?.jsx,
+    );
+    const inJsx = getLanguageVariant(scriptKind) === ts.LanguageVariant.JSX;
+    const newModuleExtension = isNewModuleExtension(filename);
```
[the remark this answers is not in the document]
Comment (WoodyWoodsta) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts:74]: I don't know the codebase well enough to understand where `program` comes from.

File: packages/typescript-estree/src/create-program/getScriptKind.ts (hunk 1 above)
Comment (WoodyWoodsta) [reply packages/typescript-estree/src/create-program/getScriptKind.ts]: https://github.com/typescript-eslint/typescript-eslint/pull/6795/commits/5a5bc878a65e62682cba2c61cf8ccafc34b35e58

File: packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (armano2) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts]: i updated comment with an example

[the remark this answers is not in the document]
Comment (WoodyWoodsta) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts]: Oh right ok I understand where `program` comes from now. It looks like you get the script kind as well, so no need to export and use `getLanguageVariant` and `getScriptKind` from `typescript-estree`.

File: packages/typescript-estree/src/create-program/getScriptKind.ts [hunk 3]
```diff
@@ -1,6 +1,32 @@
 import path from 'path';
 import * as ts from 'typescript';
 
+function isNodeNextModuleExtension(filePath: string): boolean {
```
Comment (bradzacher) [inline packages/typescript-estree/src/create-program/getScriptKind.ts:4]: we don't need to put this within `typescript-estree` as t's not used here and won't ever be used here - this can just live directly in our plugin - I think it can probably live directly within the rule's file.

I'm don't think we really want to expose this - I don't think many other plugins (if any) are going to be wanting this sort of thing.

**Review by bradzacher — CHANGES_REQUESTED** [review]
Apologies - it appears that I've lead you astray due to my misunderstanding of TS.
I've never actually used `.mts` for JSX, but I knew it errored on JSX-ambiguous syntax, so I had assumed it actually supported JSX.

In testing I now see that this isn't actually the case - `.mts`/`.cts` doesn't support JSX, it just errors on ambiguous syntax, and does not actually support JSX in the files. I assume that this just the TS team future-proofing - reading the design meeting notes it appears like they didn't want to lock in one-way or the other for the first release, so they just made sure they could make it JSX later if they wanted to by banning ambiguous syntax.

This obviously the reason why the `getScriptKind` function returns "TS" as the kind for the file instead of "TSX" - which was another thing I hadn't noticed in passing earlier.

Which provides a problem as you've noticed our suggested solution obviously won't fix it.

So what would be a good solution?
Now that I know what we know - I think we should just go back to hard-coding this. Something like this would do the job:
```ts
function requiresGenericDeclarationDisambiguation(filename: string) {
  const ext = path.ext(filename).toLowerCase();
  switch (ext) {
    case ts.Extension.Tsx:
    case ts.Extension.Cts:
    case ts.Extension.Mts:
      return true;

    default:
      return false;
  }
}
```

File: packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts [hunk 4]
```diff
@@ -60,14 +65,22 @@ export default util.createRule({
...
     const source = context.getSourceCode();
 
     const checkNode = (
       node: TypeParameterWithConstraint,
       inArrowFunction: boolean,
     ): void => {
-      const constraint = unnecessaryConstraints.get(node.constraint.type);
+      const constraint =
+        !nodeNextModuleExtension &&
+        unnecessaryConstraints.get(node.constraint.type);
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts:83]: note that if we're in a `.mts` or `.cts` file - we still want to report and apply a fix!
It just needs to be the JSX-style fix, not the non-JSX fix.
I.e. instead of fixing `<T extends any>` to `<T>`, we need to fix it to `<T,>`.

File: packages/typescript-estree/src/create-program/getScriptKind.ts (hunk 3 above)
Comment (WoodyWoodsta) [reply packages/typescript-estree/src/create-program/getScriptKind.ts:4]: Sure 👍

File: packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts (hunk 4 above)
Comment (WoodyWoodsta) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts:83]: Is this correct though? In my experience, something like `prettier` will then format `<T,>` to `<T>` as also highlighted [here](https://github.com/typescript-eslint/typescript-eslint/issues/5449#issuecomment-1265318049). If you have a pipeline which employs `eslint` **and** `prettier` fixes, then the behaviour will be unexpected.

**Comment by WoodyWoodsta** [comment]
@bradzacher To sum up your comments and relate to the issue:

### Original Issue
- `<T>` requires disambiguation in `mts`, `cts` and JSX language variant files
- `<T extends any>` as a disambiguation reports `no-unnecessary-type-constraint` in `mts` and `cts` files
- rule fix, `<T>` -> `<T,>`, is stripped of the dangling comma with at least `prettier` as a formatter returning it to the place of needing disambiguation

### Fix
- Only report `no-unnecessary-type-constraint` for `<T extends any>` in files which do not require disambiguation (everything other than `mts`, `cts` and JSX language variant files)

No changes to eslint fix required.

Let me know if this sounds correct.

---

Of course this could also be resolved in some way in formatters (i.e. to not strip the dangling comma here), but:
- it's a matter of opinion which of `<T,>` and `<T extends any>` is "better"
- stripping dangling commas from single-line argument lists **except** for in this case requires quite a lot of contextual awareness which I'm not sure whether these formatters have 🤷

**Comment by bradzacher** [comment]
> rule fix, <T> -> <T,>, is stripped of the dangling comma with at least prettier as a formatter returning it to the place of needing disambiguation

If prettier is stripping the syntactically necessary comma when formatting a `.cts/mts`  file, then that's a prettier bug to be reported and fixed.

It has already been reported: https://github.com/prettier/prettier/issues/14518

> stripping dangling commas from single-line argument lists except for in this case requires quite a lot of contextual awareness which I'm not sure whether these formatters have

Formatters are powered by the AST - they know exactly and unambiguously that `<T,>() => {}` is an arrow function with a type parameter declaration because the parser has encoded that in the AST.

The formatter then decides how to print the code - if it prints the type parameter on a single line, its trivial to also insert the comma.

**Comment by bradzacher** [comment]
> Only report no-unnecessary-type-constraint for <T extends any> in files which do not require disambiguation (everything other than mts, cts and JSX language variant files)

This is not correct, no.

The rule should **_always_** report on the unnecessary `extends any` and the fix is to remove it in `.ts` files, and replace it with a comma in `.tsx/cts/mts` files.

**Comment by WoodyWoodsta** [comment]
> Formatters are powered by the AST

@bradzacher Ok you confirm what I thought. So if I understand correctly, there is actually nothing to do here in `typscript-eslint`? 😆

**Comment by bradzacher** [comment]
My [last comment](https://github.com/typescript-eslint/typescript-eslint/pull/6795#issuecomment-1493443420) describes the change we need to make to the rule - we need to fix to `<T,>` in `mts/cts` files.

**Comment by WoodyWoodsta** [comment]
@bradzacher Hopefully I've now understood. Please see https://github.com/typescript-eslint/typescript-eslint/pull/6795/commits/6bfccc6f6987b8552dd6c16a659cc09dae7dad92

File: packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts [hunk 5]
```diff
@@ -1,3 +1,5 @@
+import { extname } from 'node:path';
```
[the remark this answers is not in the document]
Comment (WoodyWoodsta) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts:1]: Or I can just change the import to `'path'` if that's what is used throughout the project. Looks like it is.

[the remark this answers is not in the document]
Comment (WoodyWoodsta) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts]: @armano2 https://github.com/typescript-eslint/typescript-eslint/pull/6795/commits/ff2a40310de43f1a96dc195ebab38006e67c7c25

**Comment by JoshuaKGoldberg** [comment]
@bradzacher is this still something you have time to review?

**Review by bradzacher — DISMISSED** [review]
this LGTM!

**Review by bradzacher — APPROVED** [review]
