### PR TITLE
fix(eslint-plugin): [no-extra-parens] handle ESLint 7.19.0

### LINKED ISSUE #2986: Exception when upgrading to eslint 7.19.0
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

After upgrading to eslint 7.19.0, I get the following error message:

```
TypeError: rules.ForInStatement, ForOfStatement is not a function
Occurred while linting /Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/framework/backend/jsonDataConvertPara.ts:44
    at ForInStatement, ForOfStatement (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-extra-parens.js:119:63)
    at /Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/linter.js:952:32
    at Array.forEach (<anonymous>)
```

**jsonDataConvertPara.ts:44**
```TS
...
	if (!isObject(para) || Array.isArray(para)) {
		throw new Error('The parameter "data" must be an object or null');
	}

	for (const prop in para) { // line 44
		if (para.hasOwnProperty(prop)) {
			const VALUE = para[prop];
			const TYPE = getType(VALUE);
...
```

**Expected Result**

**Actual Result**

**Additional Info**

```
...
  eslint:file-enumerator Yield: jsonDataConvertPara.ts +302ms
  eslintrc:cascading-config-array-factory Load config files for /Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/framework/backend. +302ms
  eslintrc:cascading-config-array-factory Cache hit: /Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/framework/backend. +0ms
  eslint:cli-engine Lint /Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/framework/backend/jsonDataConvertPara.ts +302ms
  eslint:linter Linting code for /Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/framework/backend/jsonDataConvertPara.ts (pass 1) +2ms
  eslint:linter Verify +0ms
  eslint:linter With ConfigArray: /Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/framework/backend/jsonDataConvertPara.ts +0ms
  eslint:linter An error occurred while traversing +23ms
  eslint:linter Filename: /Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/framework/backend/jsonDataConvertPara.ts +0ms
  eslint:linter Line: 44 +1ms
  eslint:linter Parser Options: {
  ecmaVersion: 8,
  ecmaFeatures: { jsx: true, globalReturn: false },
  project: [ './tsconfig.json', './test/selenium/tsconfig.json' ],
  sourceType: 'module'
} +0ms
  eslint:linter Parser Path: /Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/@typescript-eslint/parser/dist/index.js +0ms
  eslint:linter Settings: {
  jsdoc: { mode: 'typescript' },
  react: { version: 'detect' },
  'import/resolver': {
    node: { extensions: [Array] },
    webpack: {
      config: '/Users/doberkofler/MyDev/ljs_app/trunk/periscope/scripts/webpack.config.resolve.js'
    }
  }
} +0ms
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.14.1` |
| `@typescript-eslint/parser`        | `4.14.1` |
| `TypeScript`                       | `4.1.3` |
| `ESLint`                           | `7.19.0` |
| `node`                             | `14.15.3` |

### PR DESCRIPTION
**Pull request by midgleyc**
Fixes #2986.

This works on eslint 7.19.0, but breaks on earlier versions (I'd expect). If I left in the previous version of the function (and types) with `'ForInStatement, ForOfStatement'`, it might work on those as well.

If I don't do that, I think the version of eslint in `package.json` should be bumped.

Which would you prefer?

### CODE REVIEW

**Review by bradzacher — CHANGES_REQUESTED** [review]
Thanks for the PR! 

We need to maintain compatibility with old versions of eslint as well as new versions - so we need to maintain a (guarded) call to the old selector.

File: packages/eslint-plugin/src/rules/no-extra-parens.ts [hunk 1]
```diff
@@ -256,6 +241,56 @@ export default util.createRule<Options, MessageIds>({
         }
       },
     };
+    if (semver.satisfies(TSESLint.ESLint.version, '>=7.19.0')) {
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-extra-parens.ts:244]: Instead of using a semver check here, as these can be pretty hairy to get right.

Just guard appropriately.

```js
if (rules.ForInStatement && rules.ForOfStatement) {
  // new version
} else {
  // old version
}
```

**Review by bradzacher — CHANGES_REQUESTED** [review]

File: packages/eslint-plugin/src/rules/no-extra-parens.ts (hunk 1 above)
Comment (midgleyc) [reply packages/eslint-plugin/src/rules/no-extra-parens.ts]: Nice, thanks!

**Review by bradzacher — APPROVED** [review]
thanks for doing this!

**Comment by orgads** [comment]
When do you plan to release?
