### PR TITLE
fix(eslint-plugin): [naming-convention] allow an array of selectors with types and modifiers

### LINKED ISSUE #2376: [naming-convention] Can't use array of selectors
eslint-plugin 3.8.0 introduced the ability to specify `selector` as an array. But it doesn't actually work.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": ["variable", "parameter", "property", "accessor"],
        "types": ["boolean"],
        "format": ["PascalCase"],
        "prefix": ["is", "should", "has", "can", "did", "will"]
      }
    ]
  }
}
```

```TS
// any code
```

**Expected Result**

Rule should not throw.

**Actual Result**

Rule throws 

```text
Configuration for rule "@typescript-eslint/naming-convention" is invalid:
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value ["variable","parameter","property","accessor"] should be string.
        Value ["variable","parameter","property","accessor"] should be equal to one of the allowed values.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value ["variable","parameter","property","accessor"] should be string.
        Value ["variable","parameter","property","accessor"] should be equal to one of the allowed values.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value ["variable","parameter","property","accessor"] should be string.
        Value ["variable","parameter","property","accessor"] should be equal to one of the allowed values.
        Value ["variable","parameter","property","accessor"] should be string.
        Value ["variable","parameter","property","accessor"] should be equal to one of the allowed values.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value ["variable","parameter","property","accessor"] should be string.
        Value ["variable","parameter","property","accessor"] should be equal to one of the allowed values.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should NOT have additional properties.
        Value {"selector":["variable","parameter","property","accessor"],"types":["boolean"],"format":["PascalCase"],"prefix":["is","should","has","can","did","will"]} should match exactly one schema in oneOf.
```

**Additional Info**

Previously, I was using separate configuration for each selector, and it worked:

```json
{
  "rules": {
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "variable",
        "types": ["boolean"],
        "format": ["PascalCase"],
        "prefix": ["is", "should", "has", "can", "did", "will"]
      },
      {
        "selector": "parameter",
        "types": ["boolean"],
        "format": ["PascalCase"],
        "prefix": ["is", "should", "has", "can", "did", "will"]
      },
      {
        "selector": "property",
        "types": ["boolean"],
        "format": ["PascalCase"],
        "prefix": ["is", "should", "has", "can", "did", "will"]
      },
      {
        "selector": "accessor",
        "types": ["boolean"],
        "format": ["PascalCase"],
        "prefix": ["is", "should", "has", "can", "did", "will"]
      }
    ]
  }
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.8.0` |
| `@typescript-eslint/parser`        | `3.8.0` |
| `TypeScript`                       | `3.9.7` |
| `ESLint`                           | `7.6.0` |
| `node`                             | `14.6.0` |
| `npm`                              | `6.14.6` |

### PR DESCRIPTION
**Pull request by ginger-kang**
Fixes #2376 

Please let me know if there are any required changes!

### CODE REVIEW

File: packages/eslint-plugin/src/rules/naming-convention.ts [hunk 1]
```diff
@@ -1309,16 +1314,23 @@ function normalizeOption(option: Selector): NormalizedSelector {
...
-    ...normalizedOption,
-  };
+  const allowedType = [1 << 0, 1 << 2, 1 << 3, 1 << 4, 1 << 6];
+  const config: NormalizedSelector[] = [];
+  selectors
+    .map(selector =>
+      isMetaSelector(selector) ? MetaSelectors[selector] : Selectors[selector],
+    )
+    .forEach(selector =>
+      allowedType.includes(selector)
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/naming-convention.ts:1324]: nit - use the selector enum instead of redefining the numbers.

```suggestion
  const selectorsAllowedToHaveTypes = new Set<Selector>([
    Selectors.variable,
    Selectors.parameter,
    Selectors.property,
    Selectors.parameterProperty,
    Selectors.accessor,
  ]);
  const config: NormalizedSelector[] = [];
  selectors
    .map(selector =>
      isMetaSelector(selector) ? MetaSelectors[selector] : Selectors[selector],
    )
    .forEach(selector =>
      selectorsAllowedToHaveTypes.has(selector)
```

**Review by bradzacher — CHANGES_REQUESTED** [review]
almost there - this is looking great!
One last change and this is good to go.
Thanks for your work!

**Comment by ginger-kang** [comment]
@bradzacher Thanks for review :)
Actually, a type error occurs because the `selector` in forEach is of Selectors | MetaSelectors type. So, I modified `selectorsAllowedToHaveTypes` to an array of Selectors type.

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for your contribution!
