### PR TITLE
fix(eslint-plugin): [no-unnecessary-type-constraint] change to suggestion fix, fix multiple trailing comma failures

### LINKED ISSUE #4062: [no-unnecessary-type-constraint] false positive for generic type with default type on arrow function in a JSX/TSX file
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
https://github.com/AllySummers/typescript-eslint-jsx-generics
Repo has eslint v8 and typescript-eslint v5, issue still happens on eslint 7 and typescript-eslint 4 (including alpha).
To install eslint v7/typescript-eslint v4 in that repo do this:
`npm i --save @typescript-eslint/eslint-plugin@4.33.1-alpha.15 @typescript-eslint/eslint-plugin@4.33.1-alpha.15 eslint@7.32.0`

The issue can also be seen from running `npm run lint`

**not-working.tsx**
```ts
export interface GenericComponentProps<T> {
  prop: T
}

export const GenericComponent = <T>(props: GenericComponentProps<T>) => (
  <div>hello</div>
);
// Error: 5:70  error  Parsing error: Unexpected token. Did you mean `{'>'}` or `&gt;`?
```
**working.tsx** (sort-of)
```ts
export interface GenericComponentProps<T> {
  prop: T
}

export const GenericComponent = <T extends unknown = unknown>(props: GenericComponentProps<T>) => (
  <div>hello</div>
);
// Error: 5:34  error  Constraining the generic type `T` to `unknown` does nothing and is unnecessary  @typescript-eslint/no-unnecessary-type-constraint
```

Please consider creating an isolated reproduction repo to make it easy for the volunteer maintainers debug your issue.
-->

```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "plugins": [
    "@typescript-eslint"
  ],
  "rules": {
    "@typescript-eslint/no-unnecessary-type-constraint": "error"
  }
}
```

**Expected Result**

Typescript eslint should not issue a warning as the suggested code (as below) 

**Actual Result**

The code provided in `working.tsx` is required due to how generics are parsed in Typescript/React, one cannot simply write `<T>`.

**Additional Info**
The attempted fix is invalid code:
```ts
export const GenericComponent = <T, = unknown>(props: GenericComponentProps<T>) => (
  <div>hello</div>
);
```

**Versions**
(Tested both)

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.2.0` |
| `@typescript-eslint/parser`        | `5.2.0` |
| `TypeScript`                       | `4.4.4` |
| `ESLint`                           | `8.1.0` |
| `node`                             | `14.16.0` |

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.33.1-alpha.15` |
| `@typescript-eslint/parser`        | `4.33.1-alpha.15` |
| `TypeScript`                       | `4.4.4` |
| `ESLint`                           | `7.32.0` |
| `node`                             | `14.16.0` |

### PR DESCRIPTION
**Pull request by Josh-Cena**
## PR Checklist

-   [x] Addresses an existing open issue: fixes #4062
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

1. This rule has been moved to suggestion, as it can report false-positives (around `{}` being the actual constraint)
2. The algorithm for adding trailing commas is improved: it now only adds a trailing comma where there's actual ambiguity, preventing some weird syntax errors being generated.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts [hunk 1]
```diff
@@ -58,25 +60,43 @@ export default util.createRule({
...
       const constraint = unnecessaryConstraints.get(node.constraint.type);
+      function shouldAddTrailingComma(): boolean {
+        if (!inArrowFunction || !inJsx) {
+          return false;
+        }
+        // Only <T>() => {} would need trailing comma
+        return (
+          (node.parent as TSESTree.TSTypeParameterDeclaration).params.length ===
+            1 &&
+          source.getTokensAfter(node)[0].value !== ',' &&
```
Comment (Josh-Cena) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts:78]: I don't know a better way to get the presence of trailing comma...

File: packages/eslint-plugin/tests/rules/no-unnecessary-type-constraint.test.ts [hunk 2]
```diff
@@ -171,13 +291,18 @@ class Data {
...
-      output: `
+          suggestions: [
+            {
+              messageId: 'removeUnnecessaryConstraint',
+              output: `
 class Data {
   member<T>() {}
 }
-      `,
+              `,
```
[the remark this answers is not in the document]
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/tests/rules/no-unnecessary-type-constraint.test.ts:301]: Huh, other rule tests have to use `.trim()` or similar. I don't like this haha. Maybe file an issue on us to relax our lint rules about specifically the end of `output: ...` suggestions?

File: packages/eslint-plugin/tests/rules/no-unnecessary-type-constraint.test.ts [hunk 3]
```diff
@@ -88,10 +108,85 @@ function data<T extends TODO>() {}
...
+              messageId: 'removeUnnecessaryConstraint',
+              output: noFormat`const data = <T,>() => {};`,
+            },
+          ],
+        },
+      ],
+      filename: 'react.tsx',
+    },
+    {
+      code: noFormat`const data = <T extends any,>() => {};`,
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/no-unnecessary-type-constraint.test.ts:122]: Checking for commas tends to make me nervous because it's easy to write logic that's sensitive to the amount of spaces around tokens such as the `,`. Although the rule works as-is, it'd be easy to slip up in the future. 

Could you add a few test cases for spacing around the comma? Maybe:

* `const data = <T extends any ,>() => {};`,
* `const data = <T extends any, >() => {};`,
* `const data = <T extends any  ,  >() => {};`,

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Looks great so far! Posted a suggestion about the whitespace shenanigans, and a request for a bit more testing. But the logic looks good!

**Review by JoshuaKGoldberg — APPROVED** [review]
Super, thanks! ✨

**Comment by Josh-Cena** [comment]
I'm not sure why the docs test is erroring. I've already removed the fixable icon.

**Comment by Josh-Cena** [comment]
I'm not sure why the docs test is erroring. I've already removed the fixable icon.

**Comment by bradzacher** [comment]
> I'm not sure why the docs test is erroring. I've already removed the fixable icon.

there are two rules lists that need to be updated.
run `yarn generate:rules-lists` in the plugin package root to update the tables automatically.

**Review by bradzacher — APPROVED** [review]

**Comment by bradzacher** [comment]
thanks for this!
