### PR TITLE
fix(typescript-estree): correctly account for trailing slash in includes

### LINKED ISSUE #1110: IDE Persistent Parse does not handle tsconfigs with no "include" and no "files" with deeply nested folder structures
Spinning off of https://github.com/typescript-eslint/typescript-eslint/issues/1080#issuecomment-544198857

if you provide a tsconfig without "includes" (or "files"), I.e. an empty tsconfig: `{}`, then typescript uses a different codepath to setup the folder watchers.
Triggering a directory change does not work the same was as when the tsconfig has "includes".

It won't block the release on Monday, as it's an edge case of sorts, but I'll need to look deeper into it to figure out how it all works!

### LINKED ISSUE #1159: v2.6.0: `Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.`
**What code were you trying to parse?**

A new, empty file.

**What did you expect to happen?**

No `eslint` error should occur in the VS Code IDE for the new file.

**What actually happened?**

When creating a new file in my `src` dir (which is in `tsconfig.json`) in any of my TypeScript projects, in VS Code, the following error immediately appears on the file (via the VS Code ESLint extension):

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/test.ts.
The file must be included in at least one of the projects provided.
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.6.0` |
| `TypeScript`                | `3.6.3` |
| `ESLint`                    | `6.6.0` |
| `node`                      | `12.12.0` |
| `npm`                       | `6.12.1` |

Also, MacOS 10.14.6 and VS Code 1.39.2.

I know this issue has been mentioned several times in this repo, but it seems like they're all closed. The issue was supposedly resolved in 2.6.0 of the parser, but it's not fixed for me. 

The new file I am creating are definitely in a directory that is included in `tsconfig.json`. The error disappears when I use `Reload Window` in VS Code, but I'd rather not want to do that for every new file I create, primarily because I have several scripts that run when a VS Code workspace is opened, and so I'd have to wait a few minutes after reloading the window.

.eslintrc.js:

```js
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json"
  },
  "plugins": ["@typescript-eslint"],
  "extends": ["plugin:@typescript-eslint/recommended"]
}
```

tsconfig.json:

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "module": "CommonJS",
    "outDir": "./dist/",
    "resolveJsonModule": true,
    "rootDir": "./src/",
    "strict": true,
    "target": "ES2020"
  },
  "include": ["./src/"],
  "exclude": [
    "**/build/**",
    "**/coverage/**",
    "**/dist/**",
    "**/node_modules/**"
  ]
}
```

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #1159
Fixes #1110

If you provide `{ "include": ["src/"] }`, then typescript will ask for a watch callback for `<absolute>/src/`.
If you provide `{ "include": ["src"] }`, then typescript will ask for a watch callback for `<absolute>/src`.

A bit frustrating, but what you gonna do...

I also added tests for #1110, and I'm not sure if it's this change, or a previous one, but it looks like that is fixed and working correctly.

### CODE REVIEW

File: packages/typescript-estree/src/create-program/createWatchProgram.ts [hunk 1]
```diff
@@ -246,8 +246,7 @@ function createWatchProgram(
   watchCompilerHost.readFile = (filePathIn, encoding): string | undefined => {
     const filePath = getCanonicalFileName(filePathIn);
     const fileContent =
-      path.normalize(filePath) ===
-      path.normalize(currentLintOperationState.filePath)
+      filePath === currentLintOperationState.filePath
```
Comment (bradzacher) [inline packages/typescript-estree/src/create-program/createWatchProgram.ts]: I noticed here that this is normalising an already normalised path:
Both `filePath` and `currentLintOperationState.filePath` are `CanonicalPath`
