### PR TITLE
fix(eslint-plugin): report deprecations used in default export

### LINKED ISSUE #10327: Bug: [no-deprecated] Rule doesn't report on call inside default export
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.6.2&fileType=.tsx&code=PQKhAIAEBMFMAcBOsDGBDALra5oHtwA7PDcAVwGdZwMALASwvADMzCUN69DwRgAoVu07dwADwAUASnABvfuHDIMZRD1kBfANz8N-fsGDh0ZAOa0M-SVJ0GjxUifOXYY%2BHkSk4zNGQA2pNZaQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oBNFjpEZAIb5E3dFETRoHaJHBgAviEVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
/** @deprecated do not use this function */
function x() {
  return {};
}

// caught
x();

// not caught
export default x();
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-deprecated": "error"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expected that line `export default x();` will show error about using deprecated function, this worked properly with `eslint-plugin-deprecation`.

### Actual Result

Line `export default x();` did not show linting error.

### Additional Info

Additional demo: https://stackblitz.com/edit/tvzmwg-17xps4?file=src%2Findex.ts

### PR DESCRIPTION
**Pull request by wszydlak**
## PR Checklist

- [X] Addresses an existing open issue: fixes #10327
- [X] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [X] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Report deprecations which are used in default exports - this is the way typescript compiler reports deprecations.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-deprecated.ts
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-deprecated.ts:1]: [Testing] Unit tests please 😇 

https://typescript-eslint.io/contributing/pull-requests#testing-changes

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Thanks for starting this! 🙌

File: packages/eslint-plugin/src/rules/no-deprecated.ts
Comment (wszydlak) [reply packages/eslint-plugin/src/rules/no-deprecated.ts:1]: Sure, added, however I decided to add only `invalid` case 👍

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-deprecated.ts:1]: Any reason not to add a `valid`? I think it'd be good to make sure the rule doesn't erroneously report on a non-deprecated `export default`.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Good `invalid` test, thanks! Just asking about `valid`.

File: packages/eslint-plugin/src/rules/no-deprecated.ts
Comment (wszydlak) [reply packages/eslint-plugin/src/rules/no-deprecated.ts:1]: As default exports are not checked by rule, there is no difference between  https://github.com/typescript-eslint/typescript-eslint/blob/746560aab8b8df6fed02219f03e866795cdc58c6/packages/eslint-plugin/tests/rules/no-deprecated.test.ts#L101 test. Do to not add additional valid test for longer CI scripts i decided not to add, but if you need i can add one.

Comment (wszydlak) [reply packages/eslint-plugin/src/rules/no-deprecated.ts:1]: Done 👍

**Review by JoshuaKGoldberg — DISMISSED** [review]
💯 thanks!

File: packages/eslint-plugin/tests/rules/no-deprecated.test.ts [hunk 1]
```diff
@@ -100,6 +100,16 @@ ruleTester.run('no-deprecated', rule, {
 
       a('b');
     `,
+    `
```
[the remark this answers is not in the document]
Comment (wszydlak) [reply packages/eslint-plugin/tests/rules/no-deprecated.test.ts:103]: Added additional valid test 🙂

[the remark this answers is not in the document]
Comment (wszydlak) [reply packages/eslint-plugin/tests/rules/no-deprecated.test.ts:103]: Added additional valid test 🙂

**Review by kirkwaiblinger — APPROVED** [review]
Thanks! 👍
