### PR TITLE
fix(eslint-plugin): [prefer-optional-chain] remove dangling closing parenthesis

### LINKED ISSUE #11818: Bug: [prefer-optional-chain] suggestion produces syntax error when used with type assertions
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play#ts=5.9.2&fileType=.ts&code=MYewdgzgLgBAZiEMC8MDeBYAUDGAjAQwCcAudAX20q2wSQDJ6YAKOgOkKJkZfc5gIQBYAJ4BKDgQBeY7EA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WloHsalfkwCG8WmQAWo5uii9o-aJHBgAviHVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const foo = {
  bar: {}
}

foo && (foo.bar && (foo.bar as any).baz)
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/prefer-optional-chain": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

produces `foo?.bar && (foo.bar as any).baz`

### Actual Result

produces `foo?.bar && (foo.bar as any).baz)`

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by mdm317**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11818
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

`foo && (foo.bar && (foo.bar as any).baz)` => `foo?.bar && (foo.bar as any).baz`

`foo && (foo.bar && baz)` => `foo?.bar && baz`

[new playground link](https://deploy-preview-11865--typescript-eslint.netlify.app/play/#ts=5.9.2&fileType=.ts&code=CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPFCgJ4DcAUKJLAsulgEZQBehx5FXuS8AZH3gAKHgDpmMfoJF5xsImiKkAlHJbKuFHlOFiJO5uqA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WloHsalfkwCG8WmQAWo5uii9o-aJHBgAviHVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

### CODE REVIEW

File: packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts [hunk 1]
```diff
@@ -464,8 +464,45 @@ function getReportDescriptor(
...
-  const fix: ReportFixFunction = fixer =>
-    fixer.replaceTextRange(reportRange, newCode);
+  const fix: ReportFixFunction = fixer => {
+    const replacedCode = sourceCode.text.substring(
+      reportRange[0],
+      reportRange[1],
+    );
+    let unclosedParens = 0;
+
+    for (const char of replacedCode) {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts]: [Bug] The problem with counting characters in raw `sourceCode.text` is that you also have to account for comments. Which is really, _really_ hard.

Adding this as a test case causes an error:

```ts
foo && /* gotcha :( */ (foo.bar && (foo.bar as any).baz)
```

Instead of going off `sourceCode.text`, I believe this logic will have to actually look for parentheses. You should be able to use `sourceCode.getToken` to look for them.

But let me know if this is actually a huge pain and a lot of code to deal with. I know tokens can be... tricky 😅

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
The general direction is a good start, but I believe there's a bug that'll need to be handled? Thanks for jumping on this one too! ❤️

File: packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts (hunk 1 above)
Comment (mdm317) [reply packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts]: I implemented this using `getToken` and fixed a few additional error cases.
