### PR TITLE
fix(eslint-plugin): [no-unnecessary-condition] improve error message for literal comparisons

### LINKED ISSUE #9643: Bug: [no-unnecessary-condition] Confusing message when comparing a variable to all possible values
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.tsx&code=KYOwrgtgBAYgTmAlgFygbwFBSgQQA54A2wANFlAEICGINVGAvhhgCbADGhVcwU7A9iADOqAGYIUALlgTkAbmaJRUABTikqALzaZGgHT4ivAD7Go6lFG2bdKPdVq0AlOnIB6N1D3fGzZAE88XgB5ZAALYDh4DSsoAHIqAmI4qDM4gCM6WjiFVg4uHj5BESh%2BcMjoqShQiKjZXKVVMtrKrR0EpOAU01LyupjreMzHKjiXTGwPLx8GIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
type Fruit = 'apple' | 'banana';

declare const fruit: Fruit;

if (fruit === 'apple' || fruit === 'banana') {
  // ...
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unnecessary-condition": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

A message that tells me that the condition is always truthy because I'm comparing the variable to all its valid options

### Actual Result

Getting a confusing message, only on the last part of the condition, saying that both sides are literal

### Additional Info

I encountered this message [here](https://github.com/typescript-eslint/typescript-eslint/pull/9602/files#r1685784246), which made me confused for a bit 😅

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9643 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

In addition to changing the wording, I've also had the error message compute whether the condition is actually true or false.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 1]
```diff
@@ -63,13 +63,83 @@ const isPossiblyNullish = (type: ts.Type): boolean =>
 const isAlwaysNullish = (type: ts.Type): boolean =>
   tsutils.unionTypeParts(type).every(isNullishType);
 
-// isLiteralType only covers numbers and strings, this is a more exhaustive check.
-const isLiteral = (type: ts.Type): boolean =>
-  tsutils.isBooleanLiteralType(type) ||
-  type.flags === ts.TypeFlags.Undefined ||
-  type.flags === ts.TypeFlags.Null ||
-  type.flags === ts.TypeFlags.Void ||
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:71]: Note that I intentionally omitted the `void` check.

1. It is not tested for
2. We've gone towards thinking of `void` as `unknown` in terms of its possible values, rather than `undefined` only. And if it doesn't have a specific, knowable value such that we can precompute the condition... then it's an indication that we can't in good faith tell the user the condition is unnecessary.

**Comment by kirkwaiblinger** [comment]
Note to self: align impl with changes in https://github.com/typescript-eslint/typescript-eslint/pull/10205

File: packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts [hunk 2]
```diff
@@ -30,16 +27,6 @@ const optionsWithExactOptionalPropertyTypes = {
...
-const ruleError = (
-  line: number,
-  column: number,
-  messageId: MessageId,
-): TestCaseError<MessageId> => ({
-  column,
-  line,
-  messageId,
-});
-
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts:42]: [Praise] Nice cleanup 😄

**Review by JoshuaKGoldberg — DISMISSED** [review]
The word 'Stellar' above a black sky, with a light effect tracing the 'S'

**Comment by kirkwaiblinger** [comment]
> merge

yeah, there's a bit of duplicated code, lemme just merge from main and clean that up 👍

**Review by JoshuaKGoldberg — APPROVED** [review]
👍
