### PR TITLE
fix(eslint-plugin): [consistent-type-imports] dont report on types used in export assignment expressions

### LINKED ISSUE #8330: Bug: [consistent-type-imports] erroneous report on type used in an `export =` assertion
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

n/a - the broken commit hasn't released yet so it doesn't repro on playground

### Repro Code

```TypeScript
import type Foo from 'foo';

export = {} as Foo;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/consistent-type-imports": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

No error

### Actual Result

Type import "Foo" is used by decorator metadata

### Additional Info

Looks like it was introduced by #8265

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8330
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

I missed that in https://github.com/typescript-eslint/typescript-eslint/pull/8265 :

In cases like `export = {} as T`, T was referenced as `isTypeReference: true` and `isValueReference: true`. Now it's only referenced as a type

### CODE REVIEW

**Review by bradzacher — CHANGES_REQUESTED** [review]
Thanks for hopping on this so fast!

I believe here should be no change required to the rule here - just a fix to the scope analysis. The tests are correct to add though!

Given the export equals declaration accepts an expression - we don't want to drop down into the export visitor. We just need a special case for the one special case - the identifier case. All other cases can be handled as a normal expression would.

In the identifier case we can immediately create a dual-reference. We know it's just this case because both `T[U]` and `T.U` are semantic errors from TS if `T` is a type, or `T.U` is a type (any syntactically those are the two valid ways to "chain" off a type reference).

File: packages/eslint-plugin/src/rules/consistent-type-imports.ts [hunk 1]
```diff
@@ -183,12 +183,15 @@ export default createRule<Options, MessageIds>({
...
+                       * export = Type;
                        */
                       if (
                         ref.identifier.parent.type ===
                           AST_NODE_TYPES.ExportSpecifier ||
                         ref.identifier.parent.type ===
-                          AST_NODE_TYPES.ExportDefaultDeclaration
+                          AST_NODE_TYPES.ExportDefaultDeclaration ||
+                        ref.identifier.parent.type ===
+                          AST_NODE_TYPES.TSExportAssignment
```
Comment (auvred) [inline packages/eslint-plugin/src/rules/consistent-type-imports.ts:194]: Thanks for the review!

---

> I believe here should be no change required to the rule here - just a fix to the scope analysis. The tests are correct to add though!

If we don't check `TSExportAssignment` here, then cases such as

```ts
import type A from 'foo';
export = A;
```

will result in false positives. From my understanding, export assignment here behaves like default export (exports type/value as is).

Please correct me if I'm wrong

Comment (bradzacher) [reply packages/eslint-plugin/src/rules/consistent-type-imports.ts:194]: ah you're right.
I'd just assumed that the rule would handle these dual-type-value references and not enforce anything for the import - I didn't remember that it was special-cased.

**Review by bradzacher — APPROVED** [review]
brilliant - thanks!
