### PR TITLE
fix(eslint-plugin): [return-await] do not auto-fix when type is `any`/`unknown`

### LINKED ISSUE #2598: [@typescript-eslint/return-await] False positive removal of `await` leading to control flow tampering
- [v] I have tried restarting my IDE and the issue persists.
- [v] I have updated to the latest version of the packages.
- [v] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/return-await": ["error"]
  }
}
```

```TS
const typedFunctionThatReturnsPromise = async (): Promise<void> => Promise.resolve()

async function foo(ambiguouslyTypedFunctionThatReturnsPromise) {
  try {
    return await ambiguouslyTypedFunctionThatReturnsPromise()
  } catch (e) {
    console.log('if (e instanceof ImportantException) { handleImportantException() }')
  }
}

export default async (): Promise<void> => {
  try {
    console.log('functionThatMayThrow()')
    return await foo(typedFunctionThatReturnsPromise) // we did NOT expect it to flow, but all exceptions handled internally
  } catch (e) {
    console.log('disastrousOperation')
  }
}

```

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "pretty": true,
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "lib": ["es2017"]
  }
}
```

**Expected Result**

The `await` keyword inside `return await ambiguouslyTypedFunctionThatReturnsPromise()` MUST be preserved, when we applied `eslint --fix` regardless of the options, be it `always` or `in-try-catch` (default option)

**Actual Result**

The [code](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/return-await.ts#L172-L179) is unconditionally removing the keyword `await` regardless of how it is configured. In other words, the option `always` and `in-try-catch` (default option) does not help prevent the much needed `await` inside a try-catch block from removal.

With `@typescript-eslint/return-await` applied, the `eslint --fix` was found to remove the `await` keyword because of an ambiguous type that could be actually a promise (ex. `any`, which was the default type for untyped or type-unresolved functions). The code was written correctly because the developer knew `ambiguouslyTypedFunctionThatReturnsPromise()` does return a promise (it was just not perfectly typed). However, the rewritten code, without the `await` keyword, will effectively bypass any error handling logic inside the catch block, thus leaving logics such as ImportantException to be never executed. The error exception was just thrown to the outer caller's scope.

As a result, an unhandled promise exception can be unexpectedly resulted at the caller's scope, potentially leading to a server crash, bypass of important error handling, and unintended code execution.

We believe `return-await` might expect everything to be strongly-typed (despite that its README did not have such a disclaimer, nor there's any automatic check to ensure that), if not aggressively making an assumption that an untyped function (ex. `any`) could actually return a `promise`, and thus the `await` keyword must be preserved when it is inside the try-catch block for correctness. We were also surprised that even when we switched the option to `always`, the `await` keyword was still removed, as also confirmed from their source code. We also verified with latest versions of whatever packages required.

No auto fixing should tamper the control flow.

**Additional Info**

eslint didn't throw an exception. 

If we run `eslint code.ts`, the following rule error is reported
`  3:12  error  Returning an awaited value that is not a promise is not allowed                                                               @typescript-eslint/return-await`

But if we run eslint code.ts --fix`, the code is simply rewritten without any warning.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.2.0` |
| `@typescript-eslint/parser`        | `4.2.0` |
| `TypeScript`                       | `4.0.3` |
| `ESLint`                           | `7.9.0` |
| `node`                             | `12.18.4` |

c.c. @keegan-lillo

### PR DESCRIPTION
**Pull request by thomasmichaelwallace**
Resolves #2598 

Specifically tadhgmister's solution:

> If it detected that the value is type any and make a suggestion instead of a fix would that be satisfactory? That way it still gives a warning and IDE has quick fix but the --fix command doesn't remove your await?

### CODE REVIEW

**Comment by thomasmichaelwallace** [comment]
Hmm. I'll take a look at the coverage.

File: packages/eslint-plugin/src/rules/return-await.ts [hunk 1]
```diff
@@ -169,11 +169,24 @@ export default util.createRule({
         return;
       }
 
+      // any could be thenable; do not auto-fix
+      const useAutoFix = !util.isTypeAnyType(type);
+      const removeFix = (fixer: TSESLint.RuleFixer): TSESLint.RuleFix | null =>
+        removeAwait(fixer, node);
       if (isAwait && !isThenable) {
         context.report({
```
Comment (tadhgmister) [inline packages/eslint-plugin/src/rules/return-await.ts:177]: I'd slightly prefer these variables to be inside the below if statement but that is pretty minor.  

Probably want to use suggestion for `unknown` also since [`unknown | Promise<unknown>` collapses to just `unknown`](https://www.typescriptlang.org/play?#code/FAQwzgngdgxgBAMwK6wC4EsD2VEAoAeAXHCgNZSYDuOAPnAAoBOmAtumAKYA8ZF1AfAEoA3sDji4jDqiSMcISiHSo4+ANzAAvkA) so auto removing await there might also be undesirable. 

```suggestion
      if (isAwait && !isThenable) {
        // `any` or `unknown` could be thenable; do not auto-fix
        const useAutoFix = !(util.isTypeAnyType(type) || util.isTypeUnknownType(type));
        const removeFix = (fixer: TSESLint.RuleFixer): TSESLint.RuleFix | null =>
          removeAwait(fixer, node);
        context.report({
```

**Review by tadhgmister — CHANGES_REQUESTED** [review]
While I don't expect people to run into the `unknown` case as much, since type `unknown | Promise<unknown>` collapses to just `unknown` and is therefore not considered await-able it is definitely desirable to also do suggestion for unknown types.

File: packages/eslint-plugin/tests/rules/return-await.test.ts [hunk 2]
```diff
@@ -312,6 +312,27 @@ ruleTester.run('return-await', rule, {
...
+      output: `
+        const fn = (): any => null;
+        async function test() {
+          return await fn();
+        }
+      `,
+      errors: [
+        {
+          line: 4,
+          messageId: 'nonPromiseAwait',
```
Comment (tadhgmister) [inline packages/eslint-plugin/tests/rules/return-await.test.ts:332]: can add suggestion info here: (just found out this was a thing while looking at [this](https://github.com/typescript-eslint/typescript-eslint/pull/2672/files))
```suggestion
          messageId: 'nonPromiseAwait',
          suggestions: [
             {
               messageId: 'nonPromiseAwait',
               output: `
                 const fn = (): any => null;
                 async function test() {
                   return fn();
                 }
               `,
             },
           ],
```

File: packages/eslint-plugin/src/rules/return-await.ts (hunk 1 above)
Comment (thomasmichaelwallace) [reply packages/eslint-plugin/src/rules/return-await.ts]: Good point; change made (test added).

File: packages/eslint-plugin/tests/rules/return-await.test.ts (hunk 2 above)
Comment (thomasmichaelwallace) [reply packages/eslint-plugin/tests/rules/return-await.test.ts:350]: Cool - looking at the example, seems that I can drop the outer `output` test too (although I couldn't see a way of not having to break the indentations). Change made.

**Review by tadhgmister — APPROVED** [review]

File: packages/eslint-plugin/tests/rules/return-await.test.ts (hunk 2 above)
Comment (tadhgmister) [reply packages/eslint-plugin/tests/rules/return-await.test.ts:350]: If the internal rule for formatting test cases is giving you grief you can prefix the template string with `noFormat` to disable that rule for that code block.

**Review by bradzacher — APPROVED** [review]
nice and simple. Thanks for fixing this.
