### PR TITLE
fix(typescript-estree): ensure mjs/mts files are always be parsed as ESM

### LINKED ISSUE #9101: Bug(typescript-estree): always parse mts/mjs as ESM for non-type-aware parsing
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### Playground Link

_No response_

### Repro Code

```TypeScript
import { parse } from "@typescript-eslint/typescript-estree"

const ast = parse('await(1)', {
  project: false,
  filePath: 'foo.mts'
})

console.log(ast.body[0].expression)
```

### ESLint Config

```javascript
N/A
```

### tsconfig

```jsonc
None
```

### Expected Result

The expression should be `AwaitExpression` instead of `CallExpression`.

### Actual Result

As described above.

### Additional Info

_No response_

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `7.8.0` |
| `TypeScript`                           | `5.4.5` |
| `node`                                 | `20` |

### PR DESCRIPTION
**Pull request by goldentrash**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9101
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Sorry, while synchronizing with the [repository I forked](https://github.com/goldentrash/typescript-eslint), I clicked the wrong button on github and it automatically closed the [previously open PR](https://github.com/typescript-eslint/typescript-eslint/pull/9121) (#9121), so I re-opened it.

## Last maintainer's request (@bradzacher)

the logic itself is looking good here - we just need a test to validate that this is working correctly.

can you please add three tests:
Two tests into https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-estree/tests/lib/parse.test.ts

- one test to test the "non-type-aware" (isolated parsing) case
- one test to test the "type-aware" + "project service" case

One test into https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-estree/tests/lib/parse.project-true.test.ts

- one test to test the "type-aware" + "project: true" case
    
## My final comment

Sorry for the late response, @bradzacher. As discussed above, I modified the code to determine the `sourceType` based on the settings in `eslint.config.js` rather than `tsconfig.json`, and wrote the associated tests. There are a few things I need to ask, so I'll leave a comment.

1. There are three tests that were requested. I first wrote a test under `typescript-estree/tests/lib/parse.test.ts` that checks for TLA-allowed parsing **based on sourceType and extension**. (I thought this was the **type-aware** thing you were referring to.) However, I didn't quite understand your intent when you mentioned **Project Service**. Also, I checked the file `typescript-estree/tests/lib/parse.project-true.test.ts` and it seems to validate parent & sibling project detection regardless of ESM parsing, so I didn't write any additional tests. If you can be a bit more specific, I'll write those tests as well.
2. I've added a new property (`sourceType`) to `typescript-estree/src/parser-options.ts`. Based on the comments, it looks like we need to modify the documentation accordingly. Do I need to modify the relevant pages for this as well, and if so, which files?
3. If you look at `parser/src/parser.ts`, you'll see code like this
    ```ts
    const parserOptions: TSESTreeOptions = {};
    Object.assign(parserOptions, options, {
      sourceType: options.sourceType,     // Here's some code that didn't exist before.
    });

    ...

    const { ast, services } = parseAndGenerateServices(code, parserOptions);
    ast.sourceType = options.sourceType;  // Is this the right place for this code?
     ```
    I was thinking about moving the last line, `ast.sourceType = options.sourceType;`, inside `parseAndGenerateServices`, but I was worried about **side effects** I wasn't aware of, so I left it unmodified for now and kept the existing structure. Should I move that code inside `parseAndGenerateServices()` and `parse()`? (The two functions don't reference each other, so if I move it, I'd have to put it inside both of them.) If not, should I modify `astConverter` in `typescript-estree/src/ast-converter.ts` to fulfill that role together? Or is the status quo still fine?
4. Finally, my branch now has a **conflict** with `main`. Should I resolve that conflict myself? If so, which method should I use? `Rebase` for linear history or `merge`?

### CODE REVIEW

**Comment by kirkwaiblinger** [comment]
(ignore me - just seeing if i was able to reopen your original PR, but no dice for me either 🤷‍♂️ )

File: packages/typescript-estree/src/parser-options.ts [hunk 1]
```diff
@@ -12,6 +13,12 @@ import type { TSESTree, TSESTreeToTSNode, TSNode, TSToken } from './ts-estree';
 //////////////////////////////////////////////////////////
 
 interface ParseOptions {
+  /**
+   * Specify the `sourceType`.
+   * For more details, see https://github.com/typescript-eslint/typescript-eslint/pull/9121
+   */
+  sourceType?: SourceType;
+
```
Comment (bradzacher) [inline packages/typescript-estree/src/parser-options.ts:21]: This needs to be added to the docs too
https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/packages/TypeScript_ESTree.mdx

**Review by bradzacher — CHANGES_REQUESTED** [review]
LGTM - -just needs the docs

File: packages/typescript-estree/src/parser-options.ts (hunk 1 above)
Comment (goldentrash) [reply packages/typescript-estree/src/parser-options.ts:21]: > This needs to be added to the docs too https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/packages/TypeScript_ESTree.mdx

I've updated the documentation!

**Review by JoshuaKGoldberg — DISMISSED** [review]
🚀 LGTM, thanks!

If @bradzacher doesn't protest by ~1pm Eastern today, I'll merge to get it into this week's release.

**Comment by bradzacher** [comment]
Looks like we've got some conflicts before we can merge this -- the branch is a few hundred commits behind `main`

behind

Can merge once it's updated!

**Comment by goldentrash** [comment]
> Looks like we've got some conflicts before we can merge this -- the branch is a few hundred commits behind `main`
> 
> behind
> 
> Can merge once it's updated!

You mean I have to resolve the conflict myself. Are there any rules for resolving conflicts? Is it okay to `merge` with the `main` branch? Or do I have to do a `rebase`?

File: docs/packages/TypeScript_ESTree.mdx [hunk 2]
```diff
@@ -33,6 +33,12 @@ Parses the given string of code with the options provided and returns an ESTree-
 
 ```ts
 interface ParseOptions {
+  /**
+   * Specify the `sourceType`.
+   * For more details, see https://github.com/typescript-eslint/typescript-eslint/pull/9121
```
Comment (fisker) [inline docs/packages/TypeScript_ESTree.mdx:38]: PR number changed

File: packages/typescript-estree/src/parser-options.ts [hunk 3]
```diff
@@ -15,6 +16,12 @@ export type { ProjectServiceOptions } from '@typescript-eslint/types';
 //////////////////////////////////////////////////////////
 
 interface ParseOptions {
+  /**
+   * Specify the `sourceType`.
+   * For more details, see https://github.com/typescript-eslint/typescript-eslint/pull/9121
```
Comment (fisker) [inline packages/typescript-estree/src/parser-options.ts:21]: PR number changed

File: packages/typescript-estree/src/parseSettings/createParseSettings.ts [hunk 4]
```diff
@@ -46,6 +48,14 @@ export function createParseSettings(
       ? tsestreeOptions.tsconfigRootDir
       : process.cwd();
   const passedLoggerFn = typeof tsestreeOptions.loggerFn === 'function';
+  const filePath = ensureAbsolutePath(
+    typeof tsestreeOptions.filePath === 'string' &&
+      tsestreeOptions.filePath !== '<input>'
```
Comment (fisker) [inline packages/typescript-estree/src/parseSettings/createParseSettings.ts:53]: As I checked [`<text>` still used in ESLint](https://github.com/search?q=repo%3Aeslint%2Feslint%20%3Ctext%3E&type=code), should we ignore it too? This code exists before this PR, proberly won't cause problems. When I saw this code, I thought maybe they removed `<text>` placeholder. :)

File: docs/packages/TypeScript_ESTree.mdx (hunk 2 above)
Comment (goldentrash) [reply docs/packages/TypeScript_ESTree.mdx:38]: > PR number changed

I accidentally opened a new PR, but most of the conversation about the problem and how to fix it happened in the old PR. The current PR is mostly about supplementing the documentation for the change, and updating the branch to match main. Since I mentioned the current PR as the last comment in the old PR, I thought it was appropriate to mention the old PR in the comments, because after all, what I want to show in the comments is why the property was needed, and that's also in the conversation in the old PR.

Should I change the PR number to the current PR?

File: packages/typescript-estree/src/parseSettings/createParseSettings.ts (hunk 4 above)
Comment (goldentrash) [reply packages/typescript-estree/src/parseSettings/createParseSettings.ts:53]: I thought the `<text>` placeholder was never used because [typescript-eslint provides a default value](https://typescript-eslint.io/packages/typescript-estree#parsing) for filepath. The documentation described the code as follows,

```ts
const PARSE_DEFAULT_OPTIONS: ParseOptions = {
  comment: false,
  filePath: 'estree.ts', // or 'estree.tsx', if you pass jsx: true
  jsDocParsingMode: 'all',
  jsx: false,
  loc: false,
  loggerFn: undefined,
  range: false,
  tokens: false,
};

declare function parse(
  code: string,
  options: ParseOptions = PARSE_DEFAULT_OPTIONS,
): TSESTree.Program;
```

But, here's the code I actually found

```ts
function parse<T extends TSESTreeOptions = TSESTreeOptions>(
  code: string,
  options?: T,  // there's no default value
): AST<T> {
  const { ast } = parseWithNodeMapsInternal(code, options, false);
  return ast;
}
```

Maybe it's just something missed over time. 

Should this be fixed in the current PR? I feel like the problem we're dealing with is a little different.

**Review by bradzacher — APPROVED** [review]

**Comment by bradzacher** [comment]
thanks for doing this work!
goodjobpotter

**Review by Thompson1985 — APPROVED** [review]

**Comment by injae-kim** [comment]
great work!! 👍
