### PR TITLE
fix(eslint-plugin): [strict-boolean-expressions] replace dangerous fixer with suggestions

### LINKED ISSUE #7312: Bug: @typescript-eslint/strict-boolean-expressions breaks code on --fix
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Running `eslint --fix` breaks code when the rule `@typescript-eslint/strict-boolean-expressions` has the option `allowNullableObject` set to false

Code before fix
```
type Items = {
    foo: string
}
const items: Items[] = [
    {foo: 'bar'},
    {foo: 'bar'},
]
function someFn (items?: Items[]) {
    return JSON.parse(
        JSON.stringify(items || []),
    );
}
const test = someFn(items)
console.log(test); // [ { foo: 'bar' }, { foo: 'bar' } ]
```
code after fix
```
...
function someFn (items?: Items[]) {
    return JSON.parse(
        JSON.stringify((items != null) || []),
    );
}
const test = someFn(items)
console.log(test); // true
```

**What did you expect to happen?**
Code gets changed with the `??` operator or not changed at all

### Reproduction Repository Link

https://github.com/fasenderos/typescript-eslint-strict-boolean

### Repro Steps

Clone the repo and run `npm install`, then try the code before fix

- `npm run build`
- `npm start`

The output will be `[ { foo: 'bar' }, { foo: 'bar' } ]`

Now run the fix and try again

- `npm run lint:fix`
- `npm run build`
- `npm start`

The output will be `true`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `^6.2.0` |
| `@typescript-eslint/parser`            | `^6.2.0` |
| `TypeScript`                           | `^5.1.6` |
| `ESLint`                               | `^8.45.0` |
| `node`                                 | `18.16.1` |

### PR DESCRIPTION
**Pull request by kemilbeltre**
Remove explicit rule check for logical negation expressions

## PR Checklist

- [x] Addresses an existing open issue: fixes #7312
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/eslint-plugin/src/rules/strict-boolean-expressions.ts [hunk 1]
```diff
@@ -715,11 +715,6 @@ export default util.createRule<Options, MessageId>({
             context.report({
               node,
               messageId: 'conditionErrorNullableObject',
-              fix: util.getWrappingFixer({
-                sourceCode,
-                node,
-                wrap: code => `${code} != null`,
-              }),
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/strict-boolean-expressions.ts:722]: Could you move this to a [_suggestion_ (`suggest`)](https://eslint.org/docs/latest/extend/custom-rules#providing-suggestions) instead? It's useful to offer this to users, just we can't auto-apply it under `--fix`.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Close!

File: packages/eslint-plugin/src/rules/strict-boolean-expressions.ts [hunk 2]
```diff
@@ -715,11 +715,16 @@ export default util.createRule<Options, MessageId>({
...
+              suggest: [
+                {
+                  messageId: 'conditionErrorNullableObject',
+                  fix: util.getWrappingFixer({
+                    sourceCode,
+                    node,
+                    wrap: code => `${code} != null`,
+                  }),
+                },
+              ],
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/strict-boolean-expressions.ts:727]: [Testing] And now that this is a `suggest` instead of a `fix`, we'll need unit testing for it. Could you add them in please?

`suggestions: [` is a good search term for other rules that give suggestions.

File: packages/eslint-plugin/src/rules/strict-boolean-expressions.ts [hunk 3]
```diff
@@ -715,11 +715,16 @@ export default util.createRule<Options, MessageId>({
...
               node,
               messageId: 'conditionErrorNullableObject',
-              fix: util.getWrappingFixer({
-                sourceCode,
-                node,
-                wrap: code => `${code} != null`,
-              }),
+              suggest: [
+                {
+                  messageId: 'conditionErrorNullableObject',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/strict-boolean-expressions.ts:720]: [Bug] Ah, suggestion messages should generally to be different from the parent report. You'll want to add a new `messageId` for this case.

Filed https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/368 to help automate enforcing this.

File: packages/eslint-plugin/src/rules/strict-boolean-expressions.ts [hunk 4]
```diff
@@ -715,11 +715,16 @@ export default util.createRule<Options, MessageId>({
             context.report({
               node,
               messageId: 'conditionErrorNullableObject',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/strict-boolean-expressions.ts:717]: [Bug] So I just scrolled up a bit in the file and found another usage of `messageId: 'conditionErrorNullableObject'`. Looks like there's another `fix` that uses this same message ID. I think this'll need to also switch that one to a `suggestion`.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Getting closer! 🙌

**Review by JoshuaKGoldberg — APPROVED** [review]
Super, thanks @kemilbeltre! 🙌
