### PR TITLE
fix(eslint-plugin): [no-unnecessary-type-parameters] fix AST quick path scope analysis

### LINKED ISSUE #9889: Bug: [no-unnecessary-type-parameters] Nested mapped return types in curried functions false positive
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.4&fileType=.tsx&code=C4TwDgpgBAyglgGwSAPAFQHxQLxQN5QDaAClHAHZQDWEIA9gGZRoC6AXMyS1AL4DcAWABQw0JFiJkAMTp10AGigA1AIYIArhCy54SVARJlKNek1YdVG6DwyCRQsdBly0iy5u34ipCtVqNmdmU1TV47YQATCABjBBUAJ2gGdXJo4Dg6SgZZBSgAYUyAZ2AVcmAMAAoIlRKOVyhojgLyYtLgAEoOZ1zm1rLbSJi4xKhk1PTM0Zz63pL%2Bisb8ormOjiqalTr2nCxumeW2gfso2ISklLSMykLJED3FWcP12uZFRceyzok9e6WWlaOJ2G53GVygNx%2B0weB3m7xhqygz02zG22CwumkUL%2BfXKdiAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWsRFCAtonyJoqDJCXQO0SODABfELqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
type Silly<T> = { [P in keyof T]: T[P] };

type SillyFoo<T, Value> = Silly<{ [P in keyof T]: Value }>;

type Foo<T, Value> = { [P in keyof T]: Value };

declare function foo<T, Constant>(data: T, c: Constant): Foo<T, Constant>;
declare function foo<T, Constant>(c: Constant): (data: T) => Foo<T, Constant>;

declare function sillyFoo<T, Constant>(data: T, c: Constant): SillyFoo<T, Constant>;
declare function sillyFoo<T, Constant>(c: Constant): (data: T) => SillyFoo<T, Constant>;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unnecessary-type-parameters": "error",
  },
};
```

### tsconfig

_No response_

### Expected Result

Mapping the type doesn't change the semantics of the type parameter, it's used just the same.

### Actual Result

The rule fails to see "inside" the nested/recursive mapping.

### Additional Info

This happens in our codebase when a type is wrapped with type-fest's `Simplify` type. It looks like the double mapping is causing it.

This was surfaced when migrating Remeda to v8 (https://github.com/remeda/remeda/pull/801); it happens in this file, for example https://github.com/remeda/remeda/blob/main/src/mapValues.ts.

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9889 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

The existing code was inspecting the `references` on the `Scope` itself, but we want to be inspecting the `references` on the corresponding `Variable`.

 * [docs for `references` property on `Scope`](https://eslint.org/docs/latest/extend/scope-manager-interface#references)
 * [docs for `references` property on `Variable`](https://eslint.org/docs/latest/extend/scope-manager-interface#references-1)

Coauthor credit to Josh for the breadcrumbs in https://github.com/typescript-eslint/typescript-eslint/issues/9889#issuecomment-2313374807

Co-authored-by: @JoshuaKGoldberg

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts [hunk 1]
```diff
@@ -38,19 +38,31 @@ export default createRule({
...
           );
-        const scope = context.sourceCode.getScope(esTypeParameter);
+
+        const smTypeParameterVariable = nullThrows(
+          scope.variables.find(
+            variable =>
+              // type identifiers can only be declared once, unlike var.
+              variable.identifiers.length === 1 &&
+              variable.identifiers[0] === esTypeParameter.name,
+          ),
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts:56]: You can use `scope.set.get(esTypeParameter.name)` - there's a map storing the vars by name.

Comment (bradzacher) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts:56]: Also you can use `variable.isTypeVariable` to see if it's a type definition. If you want to make doubly sure also check `!variable.isValueVariable`

Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts]: made changes 👍

File: packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts [hunk 2]
```diff
@@ -38,19 +38,33 @@ export default createRule({
...
+      const scope = context.sourceCode.getScope(node);
+
       for (const typeParameter of tsNode.typeParameters) {
         const esTypeParameter =
           parserServices.tsNodeToESTreeNodeMap.get<TSESTree.TSTypeParameter>(
             typeParameter,
           );
-        const scope = context.sourceCode.getScope(esTypeParameter);
+
+        const smTypeParameterVariable = nullThrows(
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts:50]: ...what does "sm" stand for here?

[Naming] Maybe, `scopedVariable`? Something like that?

**Review by bradzacher — APPROVED** [review]

File: packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts:50]: meh it's fine :)
