### PR TITLE
fix(eslint-plugin): [prefer-readonly] support modifiers of unions and intersections

### LINKED ISSUE #7221: Bug: [prefer-readonly] False positive if property was assigned after type guard for class properties
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=MYGwhgzhAEAqCmEAu0DeAoa0AOBXARiAJbDQB288AJhLAPYBC8AIvAGZEVUD8AXObgC2%2BeACcA3Okw5RRAG5gk8cnSQAleGCp0yIAJ4AxOnT4DhYydOyyFSles3bdehmFGmyQkRKlY8hEmglZABZeCQACzoqIzoACgBKNGksIjZoOIBCSKIIADpQSAgABVE6bDEkPQBxXDcqRKSMLBboUXDcUTJJVoBfFKCI3LyyVQ0tHX1Y6ABeaABGHuh%2BqwJiUmCkMMjo11FE5Na0jOyh-NHRQTAQWD0K2vq4nPPKGnomVg4uBKaBrHakJ1ugN%2Bq1niMxo5Ji43LNoAAmJYrPw2RTKQpQUrlSo1OqiBoJfjPaC5QakgBkaHIr1ojBY7E41H4nnMomWhxaAKBZJe1FpHwZXGgmRmc1wZCoguoSN8MnkaJUl2ut3ueIaChAuHgzK8YmgAB9oOLJV9qIToBqtSSYCzvBz-h0uhbrlaRWKJVKqDLekA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0Wls4CGAEwD2TeIXRRe0EdEjgwAXxBKgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylAGYBDVCXTgwAXxCygA&tokens=false

### Repro Code

```typescript
class Test {
  public needsToBeDefined?: number;

  private notReadonlyFoo?: number;

  private notReadonlyBar?: number;

  public testMethodFoo() {
    if (!this.classPropertyGuard()) {
      return;
    }
    this.notReadonlyFoo = 1;
  }

  public testMethodBar() {
    if (!this.normalTypeGuard(this.needsToBeDefined)) {
      return;
    }
    this.notReadonlyBar = 2;
  }

  private classPropertyGuard(): this is this & { needsToBeDefined: number } {
    return this.needsToBeDefined !== undefined;
  }

  private normalTypeGuard(value: number | undefined): value is number {
    return value !== undefined;
  }
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/prefer-readonly": "error"
  },
};
```

### tsconfig

_No response_

### Expected Result

I expected that `private notReadonlyFoo?: number;` would not report any errors.

### Actual Result

`@typescript-eslint/prefer-readonly` error on the 4th line: 
```
Member 'notReadonlyFoo' is never reassigned; mark it as `readonly`. 4:3 - 4:35
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #7221
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/eslint-plugin/src/rules/prefer-readonly.ts [hunk 1]
```diff
@@ -251,6 +251,13 @@ type ParameterOrPropertyDeclaration =
 const OUTSIDE_CONSTRUCTOR = -1;
 const DIRECTLY_INSIDE_CONSTRUCTOR = 0;
 
+enum TypeToClassRelation {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/prefer-readonly.ts:254]: [Praise] I found this enum and the logic around it to be quite helpful in understanding the new logic. Very readable. Nice! 👏

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 !
