### PR TITLE
fix(eslint-plugin): [consistent-type-definitions] don't leave trailing parens when fixing type to interface

### LINKED ISSUE #10233: Bug: consistent-type-definitions leaves trailing parenthesis when converting a paren-wrapped type to an interface
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

This isn't actually a complex issue, but I didn't immediately see how to set eslint version 9 in the playground and I wasn't interested in learning, since I already had a reproduction repo set up.

The issue is that when you use the --fix argument with the `@typescript-eslint/consistent-type-definitions` rule, it will leave a trailing parenthesis if the type it converts was wrapped in parens.

For example, the following code

```typescript
export type Interface = ({
    [key: string]: unknown;
});
```

becomes

```typescript
export interface Interface {
    [key: string]: unknown;
});
```

triggering a syntax error.

I tried this on the latest version of typescript-eslint, including 8.12.2 and 8.12.3-alpha.1

### Reproduction Repository Link

https://github.com/rdecoito/repro-consistent-type-definitions

### Repro Steps

Copy-pasted from README in repo:

1. Clone this repo
2. Run `npm i`
3. Run `npm run lint`
	- You'll see an error reported that the type defined in src/index.ts should be an interface instead
4. Run `npm run lint -- --fix`
	- You'll see a new syntax error reported. Open src/index.ts to see the problem: the rule left behind a parenthesis that it shouldn't have

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript-eslint`             | `~8.11.0` |
| `TypeScript`                           | `5.6.3` |
| `ESLint`                               | `~9.13.0` |
| `node`                                 | `20.18.0` |

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10233 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

rewrite the fixer to be more robust

### CODE REVIEW

**Review by auvred — APPROVED** [review]
Nice!

**Review by bradzacher — DISMISSED** [review]

File: packages/eslint-plugin/src/rules/consistent-type-definitions.ts [hunk 1]
```diff
@@ -68,15 +71,27 @@ export default createRule({
...
+                    afterToken.type === AST_TOKEN_TYPES.Punctuator &&
+                    afterToken.value === ';'
+                  ) {
+                    fixes.push(fixer.remove(afterToken));
+                    break;
+                  }
+                }
+
+                break;
               }
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/consistent-type-definitions.ts:95]: The better way to do this might be to do (psuedocode):
1) `getTokenBefore(typeAnnotation, '=')`
2) `getTokenAfter(typeAnnotation, ';')`
3) replace range from (1) to (2) with `typEAnnotation`

Comment (Josh-Cena) [reply packages/eslint-plugin/src/rules/consistent-type-definitions.ts:95]: ^Agreed; this feels a bit hacky

Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/consistent-type-definitions.ts]: yeah, this was a good call. Result is much cleaner now 👍

File: packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts [hunk 2]
```diff
@@ -347,6 +359,61 @@ export declare interface Test {
...
+  a: string;
+}
+      `,
+    },
+    {
+      code: noFormat`
+type Foo = ((((((((({
+  a: string;
+})))))))));
+      `,
```
Comment (bradzacher) [inline packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts:388]: Could you add a test case like

```ts
type Foo = ((({
  a: string;
})))

// next statement has a semi
const bar = 1;
```

To ensure we are handling the no-semi case?

Comment (kirkwaiblinger) [reply packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts:388]: sure! added 👍

Comment (kirkwaiblinger) [reply packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts:388]: Note that the risk of messing up a semi/no-semi issue is also lessened now that the fixer isn't querying for it; it's just deleting up to `node.range[1]`.

**Review by bradzacher — DISMISSED** [review]

**Review by bradzacher — APPROVED** [review]
