### PR TITLE
fix(eslint-plugin): [sort-type-constituents, sort-type-union-intersection-members] handle some required parentheses cases in the fixer

### LINKED ISSUE #6117: Bug: [sort-type-union-intersection-members] Fix for constituents with leading pipes or ampersands produces invalid output
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=C4TwDgpgBAKlC8UAUAfKBvAvgSigMg0wCgg&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZAe2jqNNtiaUOTWs3yJoyRGXxCRAW0TyARhNQYATODABfEDqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
type T = (| {}) & {}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/sort-type-union-intersection-members": 2
  },
};
```

### tsconfig

_No response_

### Expected Result

`eslint --fix` should result in valid TypeScript output:

```ts
type T = {} & (| {})
```

### Actual Result

`eslint --fix` results in this invalid code:

```ts
type T = {} & | {}
```

### Additional Info

_No response_

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.44.0` |
| `@typescript-eslint/parser`            | `5.44.0` |
| `TypeScript`                           | `4.9.3` |
| `ESLint`                               | `8.28.0` |
| `node`                                 | `18.12.1` |

### PR DESCRIPTION
**Pull request by cherryblossom000**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6117
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

`requiresParentheses` now returns `true` for union types starting with `|` and intersection types starting with `&`.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts [hunk 1]
```diff
@@ -96,10 +96,18 @@ function getGroup(node: TSESTree.TypeNode): Group {
   }
 }
 
-function requiresParentheses(node: TSESTree.TypeNode): boolean {
+interface Constituent {
+  group: number;
+  node: TSESTree.TypeNode;
+  text: string;
+}
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts:103]: 🤔 this code is getting more complex _(which is good, it's working better!)_ and is roughly duplicated across two files. Could you extract it to a shared helper please? Maybe, `typeNodeRequiresParentheses`? `packages/eslint-plugin/src/util/` would be a good place to put it.

File: packages/eslint-plugin/src/rules/sort-type-constituents.ts [hunk 2]
```diff
@@ -183,7 +191,7 @@ export default util.createRule<Options, MessageIds>({
     function checkSorting(
       node: TSESTree.TSIntersectionType | TSESTree.TSUnionType,
     ): void {
-      const sourceOrder = node.types.map(type => {
+      const sourceOrder = node.types.map((type): Constituent => {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/sort-type-constituents.ts:194]: Nit: any particular reason to add the return type explicitly, here and in the other file?

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Code looks great, thanks! Just requesting changes on deduplicating it a bit. ✨

File: packages/eslint-plugin/src/rules/sort-type-constituents.ts (hunk 2 above)
Comment (cherryblossom000) [reply packages/eslint-plugin/src/rules/sort-type-constituents.ts]: I wanted to make it clear what the `Constituent` was and where it came from. I ended up getting rid of `Constituent` when I extracted `requiresParentheses` into a utility function.

**Comment by cherryblossom000** [comment]
The force push is because I rebased with main due to a merge conflict.

**Comment by cherryblossom000** [comment]
I also realised another bug with this rule:

```ts
type T = (B | C) & A
```

gets fixed to

```ts
type T = C | A & B
```

This is because `(B | C) & A` gets incorrectly fixed to `A & B | C`, which is then fixed to `C | A & B`.

**Review by bradzacher — COMMENTED** [review]
I wonder if we want to leverage TS's utilities here for completeness?
https://github.com/microsoft/TypeScript/blob/1b75edcec60415dfa77be2e04aeafce0efa2222e/src/compiler/factory/parenthesizerRules.ts

We probably can't consume them directly (cos I don't think the util existed in old versions of TS) - but we could probably fork it? Maybe something to do in a separate PR?

**Review by bradzacher — APPROVED** [review]
Thanks for the fix for both rules!

flextape

I'm going to land this as is so we can get the fix out ASAP.
If we want to strengthen the logic further we can follow up in a separate PR.
