### PR TITLE
fix(eslint-plugin): replace auto-fix of class literal property style rule with suggestion

### LINKED ISSUE #5962: Bug: [class-literal-property-style] The overridden literal getter does not pass lint and incorrectly auto-fix
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&code=MYGwhgzhAECC0G8CwAoa0D6AXAphLAXNPgE4CWAdgOYDcqq6VOW0u+AFAJRGmVWIN00EswCuJCqwAWZCADpseLHTTQAvqg0pUoSDABC0HAA9cFACYx4yVUxZssXHlnLUBq9CKzjJAcge+KuhaWkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6M+AQ2WVsf0TRO8WsWgB7UtCK1kRJOiiCJ0SODABfEBqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUjoAHoizJ46IngCGqACL9YmNXl3Cwo9FIC+IM0A

### Repro Code

```typescript
class A {
  _test: string;

  get test(): string {
    return this._test;
  }
}

class B extends A {
  get test(): string {
    return 'test';
  }
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/class-literal-property-style": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true,
    "experimentalDecorators": true
  }
}
```

### Expected Result

There are no errors because the getter is overridden

### Actual Result

Error: `Literals should be exposed using readonly fields.`

Auto-fix:
```
class A {
  _test: string;

  get test(): string {
    return this._test;
  }
}

class B extends A {
  readonly test = 'test';
}
```

Then TypeScript error:
`'test' is defined as an accessor in class 'A', but is overridden here in 'B' as an instance property.`

### Additional Info

_No response_

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.42.1` |
| `@typescript-eslint/parser` | `5.42.1` |
| `TypeScript` | `4.8.4` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

### PR DESCRIPTION
**Pull request by Melandra**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5962 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
This PR changes the fixer for the class literal property style rule in the eslint-plugin package from an autofixer to a suggestion fixer.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/class-literal-property-style.ts [hunk 1]
```diff
@@ -45,10 +49,13 @@ export default util.createRule<Options, MessageIds>({
         'Enforce that literals on classes are exposed in a consistent style',
       recommended: 'strict',
     },
-    fixable: 'code',
+    hasSuggestions: true,
     messages: {
       preferFieldStyle: 'Literals should be exposed using readonly fields.',
+      preferFieldStyleSuggestion:
+        'Try replacing the literals with readonly fields.',
```
Comment (Melandra) [inline packages/eslint-plugin/src/rules/class-literal-property-style.ts:56]: I wasn't sure what messaging to use here, I'm open for other suggestions 🙂

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/class-literal-property-style.ts:56]: Ah yeah these can be tricky. Searching around other rules that have `hasSuggestions: true`, we normally go with language like _"Do X with Y"_. Here I think that'd be:

```diff
- 'Try replacing the literals with readonly fields.'
+ 'Replace the literals with readonly fields.'
```

What do you think about that?

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
🙌 The code looks great  - love a clean swap like this one! 

Just requesting changes to suggest a change to the text, as you brought up. Thoughts?

If you're happy with the suggestion or have one of your own then ✅ we can merge!

(sorry for the delay in reviewing - we've been focusing on `v6`...)

File: packages/eslint-plugin/src/rules/class-literal-property-style.ts (hunk 1 above)
Comment (Melandra) [reply packages/eslint-plugin/src/rules/class-literal-property-style.ts]: Yes, that sounds good, I've updated both suggestion messages.

**Comment by Melandra** [comment]
No worries 🙂 
I've update the messages as you proposed.

**Review by JoshuaKGoldberg — DISMISSED** [review]
🙌 Super, thanks @Melandra! 

Darryl from The Office saying 'yay'
