### PR TITLE
fix(eslint-plugin): [explicit-function-return-type] support AllowTypedFunctionExpression within AllowHigherOrderFunction

### LINKED ISSUE #682: [explicit-function-return-type] allowTypedFunctionExpressions should support return values and default parameters
**Repro**

```JSON
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint"],
  "rules": {
    "@typescript-eslint/explicit-function-return-type": ["error", {
      "allowTypedFunctionExpressions": true,
    }]
  }
}
```

```TS
function outer(): () => string {
  return () => 'hello';
}

function func(param: () => string = () => 'hello'): string {
  return param();
}

interface X {
  foobar: () => string;
}

function makeX(): X {
  return {
    foobar: () => 'hi',
  };
}
```

**Expected Result**

No errors;

* The function returned by `outer` *must* be a `() => string` due to the return type of the containing function
* The type of the default parameter for `func` *must* be `() => string` because the parameter is typed as that
* The type of `foobar` in `makeX` can be inferred from the return type

**Actual Result**

> ```
> Missing return type on function (@typescript-eslint/explicit-function-return-type) at foobar/Tests.ts:2:10
> Missing return type on function (@typescript-eslint/explicit-function-return-type) at foobar/Tests.ts:5:37
> Missing return type on function (@typescript-eslint/explicit-function-return-type) at foobar/Tests.ts:15:13
> ```

**Additional Info**

After reporting #679 I started looking for other situations where `allowTypedFunctionExpressions` feels like it should apply but currently has no effect. I don't have specific use-cases in mind for each, but some examples:

* The first example is a common pattern for a function factory or monadic function chain; only the type of the base function is really needed, because it contains all information about the returned function already.
* The second example is a pretty clear DRY violation; right now it would need to be written as `func(param: () => string = (): string => 'hello')` (worse if it takes parameters)
* The third example is rare, but could happen if building an object to implement an interface on-the-fly rather than using a proper class. I think it would be OK if the current behaviour remained in this case. It could also appear for input parameters when using the named parameter pattern (not sure if that was resolved as part of #680)

For the monad case, there may even be an argument for inferring the parent type from a child type, but I think that is a separate issue (and likely a separate option).

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.11.0` |
| `@typescript-eslint/parser`        | `1.11.0` |
| `TypeScript`                       | `3.5.2` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `12.4.0` |
| `npm`                              | `6.9.0` |

### LINKED ISSUE #758: [explicit-function-return-type] Return type needed after injection by higher order functions despite options
**Repro**

```JSON
"rules": {
    "@typescript-eslint/explicit-function-return-type": [
      "warn",
      {
        "allowTypedFunctionExpressions": true,
        "allowHigherOrderFunctions": true
      }
    ],
}
```

```TS


type MyFunctionType = (randomString: string) => string;
type InjectString<T> = (injectedString: string) => T;

const myfunction: InjectString<MyFunctionType> = injectedString => input => injectedString + input; // rule complains of missing return

const myFunctionAfterInjection = myfunction('potato'); // TS correctly infers a result of type MyFunctionType
const myFunctionResolved = myFunctionAfterInjection('anotherPotato'); // TS correctly infers a result of type string

```

**Expected Result**
Since 
a) my function is already typed
b)  I've marked as true both allowTypedFunctionExpressions and allowHigherOrderFunctions
c) Typescript is able to handle inference fine

I would expect the rule to accept this as an explicitly typed return type
**Actual Result**

The rule forces me to state the last return explicitly.

**Additional Info**

I could see how some people would prefer the last return function to be explicitly stated anyway, but I can't find a way to make my preference work: Typing just the function, but keeping the rule active for cases where the return type hasn't been stated in the function itself nor in the return type. I would like either dropping the need of the last return, a new option that handles this use case or a different rule if this is considered out of the scope for this specific rule - any way that can handle the use case would be fine.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.13.0` |
| `@typescript-eslint/parser`        | `1.9.0` |
| `TypeScript`                       | `3.4.5` |
| `ESLint`                           | `5.10.0` |
| `node`                             | `10.15.3` |
| `npm`                              | `6.4.1` |

### LINKED ISSUE #2839: [explicit-function-return-type] option to ignore return value on functions with return type signatures
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/explicit-function-return-type": ["error"]
  }
}
```

```TS
interface SomeObject {
  hello: string;
  callback: () => string;
}

function foo(): SomeObject {
  return {
    hello: 'world',
    callback: () => 'this is a callback', // Missing return type on function.eslint@typescript-eslint/explicit-function-return-type
  };
}

function bar(): SomeObject {
  return {
    hello: 'world',
    callback: () => 'this is a callback', // This one is fine.
  } as SomeObject;
}
```

**Expected Result**

When returning an object from a function (that itself has a type signature) you arguably don't need the explicit return type here as you have it in the function's type signature. It would be nice to be able to have an option to ignore this case. This is most useful when you have factory functions.

**Actual Result**

`Missing return type on function.eslint@typescript-eslint/explicit-function-return-type`

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.9.0` |
| `@typescript-eslint/parser`        | `4.9.0` |
| `TypeScript`                       | `3.9.7` |
| `ESLint`                           | `7.6.0` |
| `node`                             | `v12.2.0` |

### PR DESCRIPTION
**Pull request by lonyele**
## PR Checklist

-   [x] Addresses an existing issue: 
Fixes #758
Fixes #682 
Fixes #2839
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

#### Before
It errors when the last return type of higher order function is not typed even though `AllowTypedFunctionExpression` is true
#### After
If the ancestor(top level) is typed, ignore the last return type of higher order function since It is explicitly typed at the beginning.
#### Context
It seems like this functionality has already been used at `explicit-boundary-module-type` which looks to be usable at this rule finding if the top level is already typed. I wanted to use `ancestorHasReturnType` somewhere inside of `isTypedFunctionExpression` or `checkFunctionExpressionReturnType `, but these are also used at `explicit-boundary-module-type` [liek this](https://github.com/typescript-eslint/typescript-eslint/blob/6c3816b3831e6e683c1a7842196b34248803d69b/packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts#L468-L503) thus I made this solution. Hope I got near to the solution.

Big shame that I didn't finish other PR's that you've already commented... I haven't thought about me away from programming for somehow. From now on, I plan to finish some unfinished jobs(#894, #901) and I thought this functionality needs to be done first

### CODE REVIEW

File: packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts [hunk 1]
```diff
@@ -287,11 +287,58 @@ function checkFunctionExpressionReturnType(
...
+
+  while (ancestor) {
+    switch (ancestor.type) {
+      case AST_NODE_TYPES.ArrowFunctionExpression:
+      case AST_NODE_TYPES.FunctionExpression:
+      case AST_NODE_TYPES.FunctionDeclaration:
+        if (ancestor.returnType) {
+          return true;
+        }
+        // assume
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts:317]: assume... what?

**Review by JoshuaKGoldberg — DISMISSED** [review]
Looks good to me, thanks!

I'm a little shaky on this rule in particular so I'll defer to another maintainer on full approval.

File: packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts (hunk 1 above)
Comment (bradzacher) [reply packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts:317]: this was copy pasted from the old code.
idk what it was supposed to be (I probably wrote it lol)

**Review by bradzacher — CHANGES_REQUESTED** [review]
I see you've added tests for
```
          allowTypedFunctionExpressions: true,
          allowHigherOrderFunctions: true,
```

Could you also ensure that there are suitable tests for all of these option combos as well?
```
          allowTypedFunctionExpressions: false,
          allowHigherOrderFunctions: true,
```
```
          allowTypedFunctionExpressions: true,
          allowHigherOrderFunctions: false,
```
```
          allowTypedFunctionExpressions: false,
          allowHigherOrderFunctions: false,
```

Just want to ensure that there aren't any regressions accidentally introduced by a change in logic in this very complicated rule!

File: packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts (hunk 1 above)
Comment (lonyele) [reply packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts]: I think it was just a mistake to remove it. Comments on this function I found are already giving some good "whys" and leaving it may confuse others(actually including me when I first saw it) thus I removed it.

**Comment by lonyele** [comment]
Yeah, you were dead right. There was a flaw. I somehow touched this same code before when figuring out how to approach this problem and missed including it in my final approach. Now it looks much better.

**Review by bradzacher — APPROVED** [review]
thanks for building this!
