### PR TITLE
fix(eslint-plugin): [naming-convention] fix precedence of method and property meta selectors

### LINKED ISSUE #2860: [naming-convention] Precedence of property selector has been changed
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "memberLike",
        "format": ["camelCase"]
      },
      {
        "selector": "property",
        "format": ["camelCase", "PascalCase"]
      }
    ]
  }
}
```

```TS
const foo = { MyProperty: 42 };
```

**Expected Result**
Because typescript-eslint 4.8.2 doesn't report error for this, I expect typescript-eslint 4.9.x also doesn't report error.

**Actual Result**
The following error is reported.
```
  1:15  error  Object Literal Property name `MyProperty` must match one of the following formats: camelCase  @typescript-eslint/naming-convention
```

Previously `property` had a higher precedence than `memberLike`, but it is now a meta selector and the precedence seems to be lower (ref: https://github.com/typescript-eslint/typescript-eslint/pull/2807).

I know it works as expected if I use `"selector": ["classProperty", "objectLiteralProperty", "typeProperty"]` instead of `"selector": "property"`, but I report this issue because it feels like a breaking change in a minor upgrade for me.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.9.1` |
| `@typescript-eslint/parser`        | `4.9.1` |
| `TypeScript`                       | `4.1.2` |
| `ESLint`                           | `7.15.0` |
| `node`                             | `14.6.0` |

### PR DESCRIPTION
**Pull request by susisu**
Fixes #2860

### CODE REVIEW

**Comment by susisu** [comment]
@bradzacher Should I also update the docs for this?

**Comment by bradzacher** [comment]
> Should I also update the docs for this

No need - you're fixing a regression, so the docs should already match this behaviour.

**Comment by susisu** [comment]
> No need - you're fixing a regression, so the docs should already match this behaviour.

OK, thanks.

File: packages/eslint-plugin/src/rules/naming-convention-utils/validator.ts [hunk 1]
```diff
@@ -49,6 +53,14 @@ function createValidator(
...
       }
 
+      // for backward compatibility, method and property have higher precedence than other meta selectors
+      if (isMethodOrPropertySelector(a.selector)) {
+        return -1;
+      }
+      if (isMethodOrPropertySelector(b.selector)) {
+        return 1;
+      }
+
```
Comment (susisu) [inline packages/eslint-plugin/src/rules/naming-convention-utils/validator.ts:63]: The ordering can be modified by adding a flag bit to `method` and `property` selectors, as suggested in https://github.com/typescript-eslint/typescript-eslint/issues/2860#issuecomment-741604143.
But I think it's bit tricky, and I implemented a simpler one.
This should work well as long as `method` and `property` are the only exceptional cases.

Perhaps this can be removed in a future version.

Comment (bradzacher) [reply packages/eslint-plugin/src/rules/naming-convention-utils/validator.ts:63]: I'm happy to special case this here. It's the easiest way to handle it. We can always expand on it later if we need to!

----

This is almost correct!
This logic will create an unstable ordering when both selectors are method/property - but both aren't the same selector.

If both are method/property (and not the same selector), then the order will be the order as written.

This is technically "consistent" for the most part as config rarely changes, but if someone changes their config and reorders the config then all of a sudden the rule could produce a different result - which will be super confusing and hard to figure out.

**Review by bradzacher — CHANGES_REQUESTED** [review]
So far LGTM - almost there!
Just one comment.
Thanks for this!

**Review by bradzacher — APPROVED** [review]
thanks!
