### PR TITLE
fix(ast-spec): function-call-like callee should be Expression not LeftHandSideExpression

### LINKED ISSUE #9229: Bug: [ast-spec] wrong type for callee of CallExpression, NewExpression, TaggedTemplateExpression
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&showAST=ts&fileType=.tsx&code=BQQwBAPhYEYJTDgbgFADsCmB3MpLXkVTyljgANzUg&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRQA7iKaRwYAL4hNQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
(a || b)();
new (a || b)();
(a || b)``;
```

### ESLint Config

_No response_

### tsconfig

_No response_

### Expected Result

The callee should have type `Expression`

### Actual Result

The callee has type `LeftHandSideExpression` which doesn't include `BinaryExpression`. This is probably a remnant from when we had `ParenthesizedExpression`.

Also see estree: https://github.com/estree/estree/blob/master/es5.md#callexpression, https://github.com/estree/estree/blob/master/es2015.md#taggedtemplateexpression

### Additional Info

_No response_

### Versions

Everything latest

### PR DESCRIPTION
**Pull request by Josh-Cena**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9229
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Also fixed two other types that are similarly too strict

### CODE REVIEW

File: packages/ast-spec/src/expression/ClassExpression/spec.ts [hunk 1]
```diff
@@ -5,5 +5,4 @@ export interface ClassExpression extends ClassBase {
   type: AST_NODE_TYPES.ClassExpression;
   abstract: false;
   declare: false;
-  decorators: [];
```
Comment (bradzacher) [inline packages/ast-spec/src/expression/ClassExpression/spec.ts:8]: This was added in 450dd47c0d35c54ae8ac693a4c67905df79488a2 as `decorators?: undefined` to demark that unlike `ClassBase` (and thus `ClassDeclaration`), `ClassExpression` had no decorators.
Then in df131e258c93e5714c88c0373cfeb2e1e75afc75 Josh removed the optionality from the tree and forced this to be an empty array.

And indeed you can see here that the converter always sets this to an empty array:
https://github.com/typescript-eslint/typescript-eslint/blob/988b31e3be10ad83018b20338db3aefa0c570a08/packages/typescript-estree/src/convert.ts#L1842-L1843

So this line will need to be reverted

**Review by bradzacher — CHANGES_REQUESTED** [review]
I can trace these types all the way back to 773723b4e38e7b33f43fff0c9e4a109742ebb332 where the first types were added for the AST.

IDK why it was restricted given that the ESTree spec lists it as `Expression` https://github.com/estree/estree/blob/master/es5.md?plain=1#L680-L684.

🤷 oh well thanks for fixing!

File: packages/ast-spec/src/expression/ClassExpression/spec.ts (hunk 1 above)
Comment (Josh-Cena) [reply packages/ast-spec/src/expression/ClassExpression/spec.ts:8]: @bradzacher What about this then? [playground](https://typescript-eslint.io/play#ts=5.4.5&showAST=es&fileType=.ts&code=MYewdgzgLgBAhjAvDAAgMxCGwA2cIQwDCMA3gL5A&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

Comment (bradzacher) [reply packages/ast-spec/src/expression/ClassExpression/spec.ts:8]: That case could be made a hard error - for sure!

The non-error case is correct though - [`const a = class C {}` produces an AST with `decorators: []`](https://typescript-eslint.io/play/#ts=5.4.5&showAST=es&fileType=.ts&code=MYewdgzgLgBAhjAvDYAbOEIwMIwN4C%2BQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

Comment (Josh-Cena) [reply packages/ast-spec/src/expression/ClassExpression/spec.ts:8]: @bradzacher This is valid TypeScript code.
