### PR TITLE
fix(typescript-estree): only create project service from env setting if project is enabled

### LINKED ISSUE #7348: Repo: Our EXPERIMENTAL_useProjectService unit tests are much slower in CI
### Suggestion

Taking 18ea3b1f8938e25053f89b7e4ec8dcc6c453118a's https://github.com/typescript-eslint/typescript-eslint/actions/runs/5588135268/ as an example:

* [`eslint-plugin` run without the flag](https://github.com/typescript-eslint/typescript-eslint/actions/runs/5588135268/job/15134401904): 8m 6s
* [`eslint-plugin` run with the flag](https://github.com/typescript-eslint/typescript-eslint/actions/runs/5588135268/job/15134396350): 34m 9s

The Node version is 18 with the flag and 16 or 20 without, but that's just a quirk of the CI file. I've found it to be slower locally as well. This should be investigated.

@bradzacher and I noticed this when we first merged. cc @jakebailey - if you have the time, we'd appreciate any tips you have on it. We haven't investigated deeply yet.

### LINKED ISSUE #8131: Repo: Failure on main: Run Unit Tests with Experimental TSServer (eslint-plugin)
### Suggestion

It started after merging #7752. https://github.com/typescript-eslint/typescript-eslint/actions/runs/7317242945/job/19932592486:

```plaintext
Summary of all failing tests
 FAIL  tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts (17.679 s, 1025 MB heap size)
  ● no-unused-vars › invalid › 
/*global ����, ��*/
����;
      
    assert(received)
    Expected value to be equal to:
      true
    Received:
      false
    
    Message:
      A fatal parsing error occurred: Parsing error: Invalid character.

      356 |         }
      357 |         const fatalErrorMessage = messages.find(m => m.fatal);
    > 358 |         (0, node_assert_1.default)(!fatalErrorMessage, `A fatal parsing error occurred: ${fatalErrorMessage?.message}`);
          |                                 ^
      359 |         // Verify if autofix makes a syntax error or not.
      360 |         if (messages.some(m => m.fix)) {
      361 |             output = SourceCodeFixer.applyFixes(code, messages).output;

      at RuleTester.runRuleForItem (../rule-tester/dist/RuleTester.js:358:33)
      at RuleTester.runRuleForItem (../rule-tester/dist/RuleTester.js:503:25)
    Message:
      A fatal parsing error occurred: Parsing error: Invalid character.

      356 |         }
      357 |         const fatalErrorMessage = messages.find(m => m.fatal);
    > 358 |         (0, node_assert_1.default)(!fatalErrorMessage, `A fatal parsing error occurred: ${fatalErrorMessage?.message}`);
          |                                 ^
      359 |         // Verify if autofix makes a syntax error or not.
      360 |         if (messages.some(m => m.fix)) {
      361 |             output = SourceCodeFixer.applyFixes(code, messages).output;

      at RuleTester.runRuleForItem (../rule-tester/dist/RuleTester.js:358:33)
      at RuleTester.runRuleForItem (../rule-tester/dist/RuleTester.js:503:25)
      at Object.call (../rule-tester/dist/RuleTester.js:237:119)
 FAIL  tests/eslint-rules/no-undef.test.ts (13.747 s, 631 MB heap size)
  ● no-undef › valid › 
interface IteratorCallback<Subject, Key, Value> {
  (this: Subject, value: Value, key: Key, subject: Subject): void | false;
}
function eachr<Value>(
  subject: Array<Value>,
  callback: IteratorCallback<typeof subject, number, Value>,
): typeof subject;
function eachr<Key, Value>(
  subject: Map<Key, Value>,
  callback: IteratorCallback<typeof subject, Key, Value>,
): typeof subject;
function eachr<Object extends object, Key extends keyof Object>(
  subject: Object,
  callback: IteratorCallback<Object, Key, Object[Key]>,
): Object;
function eachr<Object extends object, Key, Value>(
  subject: Object | Array<Value> | Map<Key, Value>,
  callback: IteratorCallback<typeof subject, Key, Value>,
): typeof subject {
  return subject;
}
    
    assert.strictEqual(received, expected)
    Expected value to strictly be equal to:
      0
    Received:
      2
    
    Message:
      Should have no errors but had 2: [
      {
        ruleId: 'no-undef',
        severity: 2,
        message: "'Map' is not defined.",
        line: 10,
        column: 12,
        nodeType: 'Identifier',
        messageId: 'undef',
        endLine: 10,
        endColumn: 15
      },
      {
        ruleId: 'no-undef',
        severity: 2,
        message: "'Map' is not defined.",
        line: 18,
        column: 36,
        nodeType: 'Identifier',
        messageId: 'undef',
        endLine: 18,
        endColumn: 39
      }
    ]

      484 |     const result = this.runRuleForItem(ruleName, rule, item);
      485 |     const messages = result.messages;
    > 486 |     node_assert_1.default.strictEqual(messages.length, 0, node_util_1.default.format('Should have no errors but had %d: %s', messages.length, node_util_1.default.inspect(messages)));
          |                           ^
      487 |     assertASTDidntChange(result.beforeAST, result.afterAST);
      488 | }, _RuleTester_testInvalidTemplate = function _RuleTester_testInvalidTemplate(ruleName, rule, item) {
      489 |     node_assert_1.default.ok(typeof item.code === 'string', "Test case must specify a string value for 'code'");

      at RuleTester.strictEqual (../rule-tester/dist/RuleTester.js:486:27)
      at Object.call (../rule-tester/dist/RuleTester.js:222:117)
  ● no-undef › valid › 
function eachr<Key, Value>(subject: Map<Key, Value>): typeof subject;
    
    assert.strictEqual(received, expected)
    Expected value to strictly be equal to:
      0
    Received:
      1
    
    Message:
      Should have no errors but had 1: [
      {
        ruleId: 'no-undef',
        severity: 2,
        message: "'Map' is not defined.",
        line: 2,
        column: 37,
        nodeType: 'Identifier',
        messageId: 'undef',
        endLine: 2,
        endColumn: 40
      }
    ]

      484 |     const result = this.runRuleForItem(ruleName, rule, item);
      485 |     const messages = result.messages;
    > 486 |     node_assert_1.default.strictEqual(messages.length, 0, node_util_1.default.format('Should have no errors but had %d: %s', messages.length, node_util_1.default.inspect(messages)));
          |                           ^
      487 |     assertASTDidntChange(result.beforeAST, result.afterAST);
      488 | }, _RuleTester_testInvalidTemplate = function _RuleTester_testInvalidTemplate(ruleName, rule, item) {
      489 |     node_assert_1.default.ok(typeof item.code === 'string', "Test case must specify a string value for 'code'");

      at RuleTester.strictEqual (../rule-tester/dist/RuleTester.js:486:27)
      at Object.call (../rule-tester/dist/RuleTester.js:222:117)
Test Suites: 3 failed, 174 passed, 177 total
Tests:       5 failed, 1 skipped, 28600 passed, 28606 total
Snapshots:   136 passed, 136 total
Time:        822.794 s
Ran all test suites.

```

I honestly thought this was some kind of weird merge conflict. Seemed odd to me that the change would cause it. Sigh.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #7348; fixes #8131
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

I spent some time trying to investigate #8131's unit test failures. I made a bit of progress and then realized... wait, why is the project service enabled for either of these rules? We don't normally enable `parserOptions.project` for un-typed lint rules. Therefore, I don't think we'd want the presence of the environment variable to enable the project service unless `options.project` was also set.

### CODE REVIEW

**Review by bradzacher — APPROVED** [review]

File: packages/typescript-estree/src/parseSettings/createParseSettings.ts [hunk 1]
```diff
@@ -80,10 +80,10 @@ export function createParseSettings(
     errorOnTypeScriptSyntacticAndSemanticIssues: false,
     errorOnUnknownASTType: options.errorOnUnknownASTType === true,
     EXPERIMENTAL_projectService:
-      (options.EXPERIMENTAL_useProjectService &&
-        process.env.TYPESCRIPT_ESLINT_EXPERIMENTAL_TSSERVER !== 'false') ||
-      (process.env.TYPESCRIPT_ESLINT_EXPERIMENTAL_TSSERVER === 'true' &&
-        options.EXPERIMENTAL_useProjectService !== false)
+      options.EXPERIMENTAL_useProjectService ||
+      (options.project &&
```
Comment (fisker) [inline packages/typescript-estree/src/parseSettings/createParseSettings.ts:84]: Hello @JoshuaKGoldberg , should we check it's non-empty?

I don't know this `project` options, asking this only because I use `project:[]` in [prettier](https://github.com/prettier/prettier/blob/9db174aadd612ebade27bf8c00ba83dbbc68117c/src/language-js/parse/typescript.js#L20) and [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/41ac4228c6edbbcb7c29bd568b7695e36755cb4d/test/utils/parsers.mjs#L51), I don't remember why, maybe prevent search for `tsconfig.json`?

Comment (fisker) [reply packages/typescript-estree/src/parseSettings/createParseSettings.ts:84]: Looking at [the docs](https://typescript-eslint.io/packages/parser#project), maybe I should use `project: false`?

Comment (JoshuaKGoldberg) [reply packages/typescript-estree/src/parseSettings/createParseSettings.ts:84]: Hmm, yes, or `project: null`.

Comment (fisker) [reply packages/typescript-estree/src/parseSettings/createParseSettings.ts:84]: Back to my question, shouldwe treat `[]` as false?

Comment (JoshuaKGoldberg) [reply packages/typescript-estree/src/parseSettings/createParseSettings.ts:84]: Good question 🤔. My gut instinct is that it should probably be an error. I'm not sure though... Filed #8210.
