### PR TITLE
feat(eslint-plugin): [consistent-type-imports] support fixing to inline types

### LINKED ISSUE #4338: [consistent-type-imports] prefer inline type import syntax
### Description

I would like to propose an extension to the existing `consistent-type-imports` rule. This is linked to the work done in https://github.com/typescript-eslint/typescript-eslint/pull/4237

I think it would be beneficial for people who are interested in adopting the new [inline type import syntax introduced in Typescript 4.5](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names). We can introduce a flag, for example `preferInlineTypeImports?: boolean`.

Like @bradzacher mentioned, it's tricky to do a fixer, so we don't need it for now, but at least a way to warn people about violation would be great.

### Fail

```ts
import type { c } from './c';
import { a } from './a'; 
import type { b } from './a';
```

### Pass

```ts
import type { c } from './c';
import { a, type b } from './a';
```

---

Let me know what you think about this. If you give me a green light, I think if I can try working on this feature.

### PR DESCRIPTION
**Pull request by snewcomer**
## PR Checklist

-   [x] Addresses an existing open issue: fixes #4338
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

This PR adds a configuration option `inline-type-imports` that users can utilize to inline their type imports.

Previously, as on Typescript 3.8, we had the ability to `import type`.  This import would be elided from the build deterministically.

```
import A, { CType } from 'foo';
import type { AType } from 'foo';
import { BType } from 'foo';
```

As of 4.5, we can inline that type, making it easier to manage top level imports.

```
import A, { tye CType } from 'foo';
import type { AType } from 'foo';
import { type BType } from 'foo';
```

The summation of the discussion and work is as follows.

1. fixes a **Type** import to **Inline Type** - https://github.com/import-js/eslint-plugin-import/pull/2473. 
2. (this PR) fixes a **Value** import to **Inline Type**
3. adds support for resolving duplicate **Type** imports to **Inline Types** to existing import source https://github.com/import-js/eslint-plugin-import/pull/2475

### CODE REVIEW

File: packages/eslint-plugin/src/rules/consistent-type-imports.ts [hunk 1]
```diff
@@ -93,12 +100,14 @@ export default util.createRule<Options, MessageIds>({
...
       prefer: 'type-imports',
       disallowTypeAnnotations: true,
+      fixStyle: 'separate-type-imports',
     },
   ],
 
   create(context, [option]) {
     const prefer = option.prefer ?? 'type-imports';
     const disallowTypeAnnotations = option.disallowTypeAnnotations !== false;
+    const fixStyle = option.fixStyle ?? 'separate-type-imports';
```
Comment (chriskrycho) [inline packages/eslint-plugin/src/rules/consistent-type-imports.ts:110]: This makes sense for backwards compatibility, but it's unfortunate since the experience is so much better the other way. 😩

**Comment by snewcomer** [comment]
Fixing a bug with inlining to a value ImportDefaultSpecifier....leaving in draft

**Comment by snewcomer** [comment]
Just a small fYI.  Looks like the ember.js repo with this fixer ran on it works. 

https://github.com/emberjs/ember.js/pull/20101

**Review by JoshuaKGoldberg — COMMENTED** [review]
This PR looks very snazzy and great at first glance, thanks for sending it! I just want to confirm with @bradzacher that it's not doing more than it should? (I suspect the part of the fixer that merges imports together is not needed)

File: packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts [hunk 2]
```diff
@@ -1833,5 +1893,447 @@ const b = B;
...
+    {
+      code: `
+import B, { C } from 'foo';
+import type { A } from 'foo';
+
+C();
+const foo: A = B();
+      `,
+      output: `
+import B, { C, type A } from 'foo';
```
[the remark this answers is not in the document]
Comment (snewcomer) [reply packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts:2074]: I think I am seeing what you are suggesting.  I might be all over the place here, but bear with me 😆.  Example at the end that summarizes some thoughts.  

To dedupe `import`/`import type` sources, use [import/no-duplicates](https://github.com/import-js/eslint-plugin-import/blob/376747914b47fbdcf99212b9e9bd4d5e09825385/docs/rules/no-duplicates.md)?  (the one in this repo that extends from this is deprecated it seems)

A few questions that follow.  

1. To dedupe imports, we would need to make sure the eslint rule `import/no-duplicates` could inline the type specifier to an existing non type import source.  Seems like that rule is mainly to merge two sources but not necessarily if one is a value and one is a type import. I'm guessing any additions to this rule would have to assume the "other" dup import was not an `import type` since we wouldn't want the rule to lead to a possible regression and move a type import spec from it's separate type import to a value import.  Which leaves the question, what do we do with the "other" `import type`.  Seems to be in our court?
2. Then, your second suggestion is that on our side, we should prefix a type only specifier in a value import with `type` if a flag is specified?  How does it work that this rule necessarily follows the fixes from `import/no-duplicates`?  Or would a user have to have the right combination of import rules to both inline the import type spec and add the inline `type` prefix? 

e.g.
```js
import { A, B } from 'foo';
import type { Z } from 'foo';
import { R } from 'foo';

type C = B;
A();
let c: Z;
let d: R;

----eslint fixer
import { A, B, R } from 'foo';
import type { Z } from 'foo';

----typescript fixer
import { A, type B, type R } from 'foo';
import type { Z } from 'foo';

----typescript fixer maybe take it this far???  If so, then I think this PR may still apply.
import { A, type B, type R, type Z } from 'foo';
```

To rehash some assumptions I made, `import/no-duplicates` would inline `R` but not `Z` b/c moving Z without the ability to specify the inline `type Z` spec is a regression (assumption that specifying the inline `type` is not in their realm).  Then we would do a pass to add the inline `type R` and inline `type B`.  Lastly, as in the case of the Ember.js repo, we want that `Z` type import to be inlined as well. 

If the eslint import rule would inline `import type { Z }`, I like the simplicity for this repo!  Just add some inline `type` prefixes if necessary.  However, I made a strong/wrong? assumption that doing so on their side might be a possible source of regression.  Let me know what you think and thanks for bearing with me.

[the remark this answers is not in the document]
Comment (bradzacher) [reply packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts:2074]: The thing to think about is that rules should take on one concern at a time.
They should be looking for and solving one problem.
Why? Because otherwise rules blow out and get really complicated - they need many options to help users specify which behaviours they do and don't want.

For `consistent-type-imports` its sole purpose is ensuring that you use type imports (or don't) when an imported name is only used as a type.

Based on the single-purpose mandate, that means that the rule:
1) does not care if you have duplicate imports.
    - this is handled by rules such as `import/no-duplicates`
2) does not care if you use inline vs top-level specifiers.
    - this is, as far as I can tell, not handled by any rules currently. IMO this feature belongs in the import plugin, not here - I have filed https://github.com/import-js/eslint-plugin-import/issues/2469.

---

Now onto the fixer...
In an ideal world the rule would just pick one style to fix to and be done with it, and allow another rule to pick up that import and enforce whether it needs to be deduplicated or inlined or whatever.

However we're not in an ideal world - users want some level of convenience. Hence we're accepting an option to control whether it fixes to a top-level or inline specifier.

What we do *not* want to do, however, is have the fixer be in the business of changing imports that do not violate its single-purpose.

To be clear - if the fix style is set to inline specifier, and there is a top-level specifier - then the rule is not to change it. I.e.

```ts
import type {Foo} from 'T';
import {Bar} from 'T';

type T = Foo | Bar;
```
should fix to
```ts
import type {Foo} from 'T';
import {type Bar} from 'T';

type T = Foo | Bar;
```
and ***NOT***
```ts
import {type Foo, type Bar} from 'T';

type T = Foo | Bar;
```

**Review by bradzacher — CHANGES_REQUESTED** [review]
we'll also need to document the new option

File: packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (snewcomer) [reply packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts:2074]: Thanks Brad.  So it sounds like this PR doesn't have much validity and should be closed.  My concern is focused on taking the existing type imports and inlining them with a value import of possible.  That was the desire expressed by folks on the ember.js repo and my company API codebase.  

Based on your thoughts, it seems like `import/no-duplicates` is where this work should go.  However, what was not clear to me is if inlining an existing `import type` to a value import is even something this rule should do. For the practical use case, it necessarily depends on prefixing it with `type` as well.  Otherwise, you are moving an explicit type import to a value import that relies on TS eliding it (which likely happens but doesn't always, thus the explicit type import).  And would rely on pairing this with a rule here.  Is that ok with you?  Just trying to think of the logistics before opening an issue and getting confirmation that I should start work there on `imports/no-duplicates`...

[the remark this answers is not in the document]
Comment (bradzacher) [reply packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts:2074]: To be clear - I think there are 3 rules that should exist:

(1) `@typescript-eslint/consistent-type-imports`

This rule concerns itself with enforcing that your imports that are only used with types are marked as type-only imports.

(2) `import/no-duplicates`

This rule concerns itself with enforcing that you do not have duplicate import declarations for the same module, unless they are differing top-level import kinds.

(3) New rule https://github.com/import-js/eslint-plugin-import/issues/2469

This rule concerns itself with enforcing the style of import kind that you use - whether you always use inline specifiers, or top-level specifiers.

---

To illustrate with an example:

Say we have the following config:
```json5
{
  rules: {
    '@typescript-eslint/consistent-type-imports': 'error',
    'import/no-duplicates': 'error',
    'import/new-rule-issue-2469': ['error', 'prefer-inline'],
  },
}
```

And the following code:
```ts
import type {Foo} from 'T';
import {Bar} from 'T';

type T = Foo | Bar;
```

First pass we would see the following errors:
```ts
import type {Foo} from 'T';
//     ^^^^^^^^^^ Error: prefer inline type specifiers (import/new-rule-issue-2469)
import {Bar} from 'T';
//      ^^^ Error: imports only used as a type must be marked as such (@typescript-eslint/consistent-type-imports)

type T = Foo | Bar;
```
We'd run the fixers for both rules and end up with:
```ts
import {type Foo} from 'T';
import {type Bar} from 'T';

type T = Foo | Bar;
```
This would then cause the following error:
```ts
import {type Foo} from 'T';
import {type Bar} from 'T';
//^^^^^^^^^^^^^^^^^^^^^^^^^ Error: duplicate import from module 'T' (import/no-duplicates)

type T = Foo | Bar;
```
We'd run the fixers and end up with:
```ts
import {type Foo, type Bar} from 'T';

type T = Foo | Bar;
```

Side note to explain how this would really work for a user. They might choose to do things by hand by manually applying the fixer for each rule in their IDE. In this case it'll take 3 manual fixer triggers to reach the code.
If they use autofix-on-save, or if they use the CLI `eslint --fix`, then ESLint will do 10 passes on the file, finding and applying fixes - so all 3 fixes will be applied at once (i.e. takes just 1 user action).

[the remark this answers is not in the document]
Comment (snewcomer) [reply packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts:2074]: Ok.  I like the direction.  😢 a lot of this work is shot but at least you have laid out a more precise integration here.  Will close the PR then and open an issue in `import/no-duplicates`.  Unsure when/if I will be able to get to this.  Also, need to make sure I get buy in.

[the remark this answers is not in the document]
Comment (snewcomer) [reply packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts:2074]: On the other hand, the rub I have with this fixer rule is that it is refactoring my code to an outdated(?) Typescript pattern (separate import types) without the new rule you filed an issue for.  Do you have any thoughts on that @bradzacher?  For example, say the standard recommended pattern was inline type modifier. Wouldn’t we want to do that in the fixer here?

[the remark this answers is not in the document]
Comment (bradzacher) [reply packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts:2074]: > outdated(?)

Nothing outdated about top-level type-specifier for imports.
It's just a matter or personal preference.

> For example, say the standard recommended pattern was inline type modifier. Wouldn’t we want to do that in the fixer here

I think it's definitely a good option to have the fixer that fixes the erroneous named type import to have a type-only specifier.
That's what the issue is about - adding that exact functionality!!

The thing we *don't* want is to merge or change other imports. The only thing the fixer should do is fix the import that's missing a specifier.

To reiterate my previous example:

```ts
import type {Foo} from 'T';
import {Bar} from 'T';

type T = Foo | Bar;
```
should fix to
```ts
import type {Foo} from 'T';
import {type Bar} from 'T';

type T = Foo | Bar;
```
and ***NOT***
```ts
import {type Foo, type Bar} from 'T';

type T = Foo | Bar;
```

I'm more than happy if this rule has an option to fix the flagged import by making it an inline-type-only import instead of making it a separate, top-level type-only import!

[the remark this answers is not in the document]
Comment (snewcomer) [reply packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts]: @bradzacher I was so focused on taking a few codebases from the separate type import refactor back to inline that I didn't realize I could go backwards with `prefer: 'no-type-imports'` and then apply the inline type fixer!  Thanks for the clear direction.  PR is a lot simpler now 👍.  Let me know what you think!

[the remark this answers is not in the document]
Comment (snewcomer) [reply packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts]: Looks like the test suite is still passing.

https://github.com/emberjs/ember.js/pull/20101

[the remark this answers is not in the document]
Comment (snewcomer) [reply packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts]: I believe we have two pending `eslint-plugin-import` PRs that are blocking this work?

https://github.com/import-js/eslint-plugin-import/pull/2475
https://github.com/import-js/eslint-plugin-import/pull/2473

File: packages/eslint-plugin/docs/rules/consistent-type-imports.md [hunk 3]
```diff
@@ -48,6 +48,49 @@ type T = Foo;
 const x: Bar = 1;
 ```
 
+### `fixStyle`
+
+This option defines the expected type modifier to be added when an import is detected as used only in the type position. Valid values for `fixStyle` are:
+
+- `separate-type-imports` will add the type keyword after the import keyword `import type { A } from '...'`. It is the default.
+- `inline-type-imports` will inline the type keyword `import { type A } from '...'` and is only available in TypeScript 4.5 and onwards. See [documentation](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names) here.
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/docs/rules/consistent-type-imports.md:56]: Fun fact, having a link with an ambiguous name like just _"documentation"_ isn't great accessibility practice. https://blog.pope.tech/2018/07/26/why-ambiguous-links-are-problematic/#:~:text=Ambiguous%20links%20are%20flagged%20by,could%20be%20impossible%20for%20some

```suggestion
- `inline-type-imports` will inline the type keyword `import { type A } from '...'` and is only available in TypeScript 4.5 and onwards. See [documentation here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names "TypeScript 4.5 release notes").
```

File: packages/eslint-plugin/docs/rules/consistent-type-imports.md [hunk 4]
```diff
@@ -48,6 +48,49 @@ type T = Foo;
...
+
+Examples of the fixer `{fixStyle: 'separate-type-imports'}`.
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/docs/rules/consistent-type-imports.md:58]: Nit:

```suggestion
Examples of the fixer with `{ fixStyle: 'separate-type-imports' }`:
```

File: packages/eslint-plugin/docs/rules/consistent-type-imports.md [hunk 5]
```diff
@@ -48,6 +48,49 @@ type T = Foo;
...
+will fix to
+
+```ts
+import type { Foo } from 'Foo';
+import type Bar from 'Bar';
+type T = Foo;
+const x: Bar = 1;
+```
+
+Examples of the fixer `{fixStyle: 'inline-type-imports'}`.
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/docs/rules/consistent-type-imports.md:76]: Nit:

```suggestion
Examples of the fixer with `{ fixStyle: 'inline-type-imports' }`:
```

File: packages/eslint-plugin/src/rules/consistent-type-imports.ts [hunk 6]
```diff
@@ -50,7 +54,8 @@ type MessageIds =
   | 'valueOverType'
   | 'noImportTypeAnnotations'
   | 'someImportsInDecoMeta'
-  | 'aImportInDecoMeta';
+  | 'aImportInDecoMeta'
+  | 'inlineTypes';
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/consistent-type-imports.ts:58]: The new `inlineTypes` message ID is no longer used anywhere.

```suggestion
  | 'aImportInDecoMeta';
```

File: packages/eslint-plugin/src/rules/consistent-type-imports.ts [hunk 7]
```diff
@@ -71,6 +76,7 @@ export default util.createRule<Options, MessageIds>({
         'Type import {{typeImports}} is used by decorator metadata.',
       valueOverType: 'Use an `import` instead of an `import type`.',
       noImportTypeAnnotations: '`import()` type annotations are forbidden.',
+      inlineTypes: 'Type imports can be inlined.',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/consistent-type-imports.ts:79]: The new `inlineTypes` message ID is no longer used anywhere.

```suggestion
```

File: packages/eslint-plugin/src/rules/consistent-type-imports.ts [hunk 8]
```diff
@@ -418,16 +445,17 @@ export default util.createRule<Options, MessageIds>({
...
         // import DefType, {Type1, Type2} from 'foo'
         const openingBraceToken = util.nullThrows(
           sourceCode.getTokenBefore(
-            typeNamedSpecifiers[0],
+            subsetNamedSpecifiers[0],
             util.isOpeningBraceToken,
           ),
           util.NullThrowsReasons.MissingToken('{', node.type),
         );
+        // TODO: why require default import as well?  What about import type { type1, type2 }?
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/consistent-type-imports.ts:458]: Is this TODO still relevant? Looks like there are test cases covering it?

**Review by JoshuaKGoldberg — COMMENTED** [review]
😕 I'm having a crisis of confidence here. Adding 175 lines of new code to an already-large rule to support fixing outside the rule's responsibilities is... a lot. If this PR were to be merged roughly as-is we'd be making it much harder to contribute to the `consistent-type-imports` rule in the future. Given that the [`canonical/prefer-inline-type-import`](https://github.com/gajus/eslint-plugin-canonical#eslint-plugin-canonical-rules-prefer-inline-type-import) rule exists -as noted in the issue-, I don't know that such a large addition to the rule is worth it. 😕 

Do you have a strong opinion @snewcomer? I want to be respectful that you've already put a ton of great work into this rule, and I do hate to close PRs that have so time spent on them. 

cc @bradzacher

**Comment by snewcomer** [comment]
@JoshuaKGoldberg Thanks for the review!  The totality of the discussion/work explored in this PR is split up into 3 parts and in sum will solve many existing projects who have not used `Type` imports and also projects who have `Type` imports but would rather have `Inline Type` imports.

1. fixes a **Type** import to **Inline Type** - https://github.com/import-js/eslint-plugin-import/pull/2473. This is analogous with the _Canonical rule_ noted in the issue albeit in a more common package to have installed - eslint-plugin-import.
2. (this PR) fixes a **Value** import to **Inline Type**
3. adds support for resolving duplicate **Type** imports to **Inline Types** to existing import source https://github.com/import-js/eslint-plugin-import/pull/2475

So pending those first two eslint-plugin-import PRs, this PR will add `Value` in a type position to `Inline Type` or `top level Type` fixer which doesn't exist to my knowledge.

**Comment by me4502** [comment]
In terms of consistency with `consistent-type-exports`, would it make sense to also have an option that will inline `type` rather than split, but for cases where all imports are types, use a top-level `type` tag? 

That's what the inline option on the exports rule does, https://typescript-eslint.io/rules/consistent-type-exports/#fixmixedexportswithinlinetypespecifier

**Comment by bradzacher** [comment]
@me4502 exports are really easy to deal with here compared to imports.

There's complexities due to default vs named vs namespace imports and duplicate modules etc that make things very hard to work with - which is why we want this fixer to be as simple as possible.

We're looking to push modifier consistency out to other rules - https://github.com/import-js/eslint-plugin-import/issues/2469 and https://github.com/import-js/eslint-plugin-import/issues/2470 to keep concerns separated.
The comments on this PR go deeper into this.

**Comment by JoshuaKGoldberg** [comment]
@snewcomer this hasn't been showing up on my queue because Brad's review is still marked as pending - do you want us to take another look? I'm excited for it to go in 😄 

Also, the lint task is failing for `consistent-type-imports.md`. I can take a look once it's passing.

**Comment by snewcomer** [comment]
@JoshuaKGoldberg A review would be lovely!

**Review by JoshuaKGoldberg — COMMENTED** [review]
Thought I posted this yesterday 😬 sorry!

File: packages/eslint-plugin/docs/rules/consistent-type-imports.md [hunk 9]
```diff
@@ -36,6 +36,49 @@ type T = Foo;
...
 ```
 
+### `fixStyle`
+
+This option defines the expected type modifier to be added when an import is detected as used only in the type position. Valid values for `fixStyle` are:
+
+- `separate-type-imports` will add the type keyword after the import keyword `import type { A } from '...'`. It is the default.
+- `inline-type-imports` will inline the type keyword `import { type A } from '...'` and is only available in TypeScript 4.5 and onwards. See [documentation here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names).
+
+Examples of the fixer with `{ fixStyle: 'separate-type-imports' }`:
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/docs/rules/consistent-type-imports.md:46]: Docs nit: I think you could streamline this explanation with tabs.

```md
<!--tabs-->

#### ❌ Incorrect

(original code snippet)

#### ✅ With `inline-type-imports`

(separate-type-imports fixed version)

#### ✅ With `separate-type-imports`

(separate-type-imports fixed version)

<!-- /tabs -->
```

What do you think?

File: packages/eslint-plugin/src/rules/consistent-type-imports.ts [hunk 10]
```diff
@@ -603,15 +693,29 @@ export default util.createRule<Options, MessageIds>({
           if (sourceImports.typeOnlyNamedImport.range[1] <= node.range[0]) {
             yield insertTypeNamedSpecifiers;
           } else {
+            // TODO: delay inserting b/c....
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/consistent-type-imports.ts:695]: b/c...?

File: packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts [hunk 11]
```diff
@@ -1833,5 +1920,277 @@ const b = B;
...
+      ],
+    },
+    {
+      code: `
+import A, { B, C } from 'foo';
+type T = B;
+type U = C;
+type V = A;
+      `,
+      output: noFormat`
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts:2070]: These actually aren't necessary anymore:

```suggestion
      output: `
```

File: packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts [hunk 12]
```diff
@@ -1833,5 +1920,277 @@ const b = B;
...
+      ],
+    },
+    {
+      code: `
+import A, { B, C as D } from 'foo';
+type T = B;
+type U = D;
+type V = A;
+      `,
+      output: noFormat`
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts:2093]:
```suggestion
      output: `
```

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Ok yes the code still looks great, thanks! There are just a few TODO comments we should either remove or fill out.

File: packages/eslint-plugin/src/rules/consistent-type-imports.ts (hunk 10 above)
Comment (snewcomer) [reply packages/eslint-plugin/src/rules/consistent-type-imports.ts]: ack that was me just learning the rules.  Was hoping to ask a question about the patterns.  But we simplified this PR greatly once we moved a ton of logic to eslint-plugin-import.  Been so long, I forgot as well.

File: packages/eslint-plugin/docs/rules/consistent-type-imports.md (hunk 9 above)
Comment (snewcomer) [reply packages/eslint-plugin/docs/rules/consistent-type-imports.md]: This is how it looks now!

Screen Shot 2022-11-07 at 4 40 37 PM

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/docs/rules/consistent-type-imports.md]: Close enough 😄

**Review by JoshuaKGoldberg — APPROVED** [review]
Awesome - thanks so much for iterating on this with us @snewcomer! I'm pumped to get this shipped 😄

**Comment by ysulyma** [comment]
Can this be removed from the docs (https://typescript-eslint.io/rules/consistent-type-imports/#fixstyle) until it is released? I just spent several minutes troubleshooting
```
Error: .eslintrc.json:
	Configuration for rule "@typescript-eslint/consistent-type-imports" is invalid:
	Value {"fixStyle":"inline-type-imports"} should NOT have additional properties.
```

**Comment by JoshuaKGoldberg** [comment]
@ysulyma sorry about that - please see #5939
