### PR TITLE
fix(typescript-estree): use token type of `PrivateIdentifier` instead of `Identifier` for private identifiers

### LINKED ISSUE #11022: Bug: The token type of a private name should be PrivateIdentifier instead of Identifier and the value should be the string value of a private name
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### Playground Link

https://typescript-eslint.io/play/#ts=5.6.2&showAST=es&fileType=.tsx&code=MYGwhgzhAEDC0G9oGIAOBuaBfIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=true

### Repro Code

```TypeScript
class C { #p; }
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

`.ast.tokens[3].type` should be `PrivateIdentifier` and `.ast.tokens[3].value` should be `"p"`.

### Actual Result

`.ast.tokens[3].type` is `Identifier` and `.ast.tokens[3].value` is `#p`.

### Additional Info

_No response_

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | 8.28.0 |

### PR DESCRIPTION
**Pull request by ronami**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11022
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This was less straightforward than #11021 since [there's no token type for a private identifier](https://github.com/typescript-eslint/typescript-eslint/blob/7fad1a51da006477d78e170ed8d6b2215197dc06/packages/ast-spec/src/ast-token-types.ts#L2-L12).

I've resorted to adding a new token type for private identifiers, please let me know if this isn't the correct way to resolve this.

---

Codecov seems off (reports missing line coverage) and I think this is related to https://github.com/typescript-eslint/typescript-eslint/issues/6116.

### CODE REVIEW

File: packages/typescript-estree/src/node-utils.ts [hunk 1]
```diff
@@ -602,6 +605,16 @@ export function convertToken(
       value,
     };
   }
+
+  if (tokenType === AST_TOKEN_TYPES.PrivateIdentifier) {
+    return {
+      type: tokenType,
+      loc,
+      range,
+      value: value.slice(1),
```
Comment (ronami) [inline packages/typescript-estree/src/node-utils.ts:614]: I've tried to reproduce the same behavior in: https://github.com/typescript-eslint/typescript-eslint/blob/f0072dc5f00fc24815fc25ad0e645412c1b84f38/packages/typescript-estree/src/convert.ts#L968

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, but someone with deeper experience in these things like @bradzacher should definitely verify.

**Review by bradzacher — APPROVED** [review]
