### PR TITLE
feat(eslint-plugin): [no-useless-default-assignment] fix some cases to optional syntax

### LINKED ISSUE #11847: Bug: [no-useless-default-assignment] False positive when defaulting parameter to undefined
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play#ts=5.9.2&fileType=.tsx&code=GYVwdgxgLglg9mABAWwJ4DFzXmAFABwEYAuRAZygCcYwBzAGkXwCZSwRkAjAU0sQB9E4ACbdgNbsMQBeIWFHiwkgJSIA3gFgAUIkQQEZOABtuAOiNxaBQoxbKA3NoC%2B27WkyRYCXAHJCPh20gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYkACAXAngA4oDG0AlobgLQrzkB2uA9AwPbWzKJLLLUATRADMAhghqi%2B5AOYMAtoibooiaNDbRIAXxDagA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
function myFunction(p1: string, p2: number | undefined = undefined) {
  console.log(p1, p2);
}

myFunction('1');
```

### ESLint Config

```javascript
module.exports = {
  "rules": {"@typescript-eslint/no-useless-default-assignment": "error"}
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

This use should get flagged.

### Actual Result

When removing the default, typescript will reports the error `2554: Expected 2 arguments, but got 1. 5:1 - 5:11`

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by ulrichstark**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11847
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

While working on this, I split the function reportUselessDefault into three functions. One for every message.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-useless-default-assignment.ts [hunk 1]
```diff
@@ -28,6 +31,8 @@ export default createRule<[], MessageId>({
     },
     fixable: 'code',
     messages: {
+      preferOptionalSyntax:
+        'Using `= undefined` to make a parameter optional is verbose. Use the `?` optional syntax instead.',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-useless-default-assignment.ts]:
```suggestion
        'Using `= undefined` to make a parameter optional adds unnecessary runtime logic. Use the `?` optional syntax instead.',
```

**Review by JoshuaKGoldberg — DISMISSED** [review]
Nice, LGTM - thanks!

File: packages/eslint-plugin/tests/rules/no-useless-default-assignment.test.ts [hunk 2]
```diff
@@ -499,5 +499,26 @@ ruleTester.run('no-useless-default-assignment', rule, {
...
+      errors: [
+        {
+          column: 66,
+          endColumn: 75,
+          line: 2,
+          messageId: 'preferOptionalSyntax',
+        },
+      ],
+      output: `
+        function myFunction(p1: string, p2?: number | undefined) {
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/tests/rules/no-useless-default-assignment.test.ts:518]: (no action requested)

This will still have an "unnecessary" `| undefined`, i.e. could be further fixed to

`function myFunction(p1: string, p2?: number) {`

But thankfully that check is already covered by [no-duplicate-type-constituents](https://typescript-eslint.io/rules/no-duplicate-type-constituents/)! And this rule uses type information, so `p2: SomeType = undefined` would also correctly get fixed to `p2?: SomeType` with the current implementation, without ever examining the syntax for the literal appearance of `| undefined`.

Anyway, that's all just to say, I think that what you have here is valid behavior for this feature 👍

File: packages/eslint-plugin/src/rules/no-useless-default-assignment.ts [hunk 3]
```diff
@@ -236,25 +247,63 @@ export default createRule<[], MessageId>({
...
+            fixes.push(
+              fixer.insertTextAfterRange(
+                [left.range[0], left.range[0] + left.name.length],
+                '?',
+              ),
+            );
+          }
+
+          return fixes;
         },
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-useless-default-assignment.ts]: nit - you can use the generator form for this to save a few lines.

```suggestion
        *fix(fixer) {
          yield removeDefault(fixer, node);

          const { left } = node;
          if (left.type === AST_NODE_TYPES.Identifier) {
            yield fixer.insertTextAfterRange(
              [left.range[0], left.range[0] + left.name.length],
              '?',
            );
          }
        },
```

File: packages/eslint-plugin/tests/rules/no-useless-default-assignment.test.ts
Comment (kirkwaiblinger) [inline packages/eslint-plugin/tests/rules/no-useless-default-assignment.test.ts:1]: (Testing)

I didn't manage to find any bugs, but could you add a test that contains comments in weird positions for the fixer? For example

```ts
type SomeType = number | undefined;
function f(/* comment */ x /* comment 2 */ : /* comment 3 */ SomeType /* comment 4 */ = /* comment 5 */ undefined) {
}
```

File: packages/eslint-plugin/src/rules/no-useless-default-assignment.ts (hunk 3 above)
Comment (ulrichstark) [reply packages/eslint-plugin/src/rules/no-useless-default-assignment.ts]: Oh that's cool. I never really used generators before, but this looks handy.
