### PR TITLE
fix(type-utils): add union type support to TypeOrValueSpecifier

### LINKED ISSUE #11452: Bug: [only-throw-error] TypeOrValueSpecifier does not handle union
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.ts&code=GYVwdgxgLglg9mABMAjAHgCoD4AUBKRAbwChFEAbAUykUoCc6AuRABTrgFsYBnSzLANylEUABbsA7rQZCAvsWKhIsBMgBMmFABpEGNbgIkyVGvSat2XXpqyIAPhc48%2BewcLGTpdOUA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AeyfkNvwAto7AO71og6OjABtcNhyIx7CQBpZcrHOyQAhvHjDJMzZsgAFQQFtKyRJDWaAuvYgBfe09cgXQA&tsconfig=&tokens=false

### Repro Code

```TypeScript
function f1<T>() {
  let err: Promise<T>;
  throw err;
}

function f2<T1, T2>() {
  let err: Promise<T1> | Promise<T2>;
  throw err;
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/only-throw-error": [
      "error",
      {
        "allow": [
          "Promise"
        ]
      }
    ]
  }
}
```

### tsconfig

```jsonc

```

### Expected Result

The only-throw-error warning should not be triggered by `f1()` or `f2()`. When the "allow" option is `Promise`, I should be able to throw an error of `Promise<A> | Promise<B>`.

### Actual Result

The "only-throw-error" rule triggers when a union is thrown.

> Expected an error object to be thrown. 8:9 - 8:12

Expected an error object to be thrown. 8:9 - 8:12

### Additional Info

My actual use-case is with TanStack Router, which allows users to `throw redirect(...)` (this throws a `Redirect` type). I have a function that can return various redirects (which are later thrown):

```ts
function getRedirect(a, b) {
    if (a) return redirect(...); // returns Redirect<A>
    else return redirect(...); // returns Redirect<B>
}
```

This returns a union of `Redirect<A> | Redirect<B>`. The following code triggers and ESLint error because it is trying to throw a union type.

```ts
throw getRedirect(a, b);
```

### PR DESCRIPTION
**Pull request by y-hsgw**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11452 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Add union type support to TypeOrValueSpecifier.

🐛

### CODE REVIEW

File: packages/type-utils/src/TypeOrValueSpecifier.ts [hunk 1]
```diff
@@ -169,6 +169,10 @@ export function typeMatchesSpecifier(
   specifier: TypeOrValueSpecifier,
   program: ts.Program,
 ): boolean {
+  if (tsutils.isUnionType(type)) {
+    return type.types.some(t => typeMatchesSpecifier(t, specifier, program));
```
Comment (kirkwaiblinger) [inline packages/type-utils/src/TypeOrValueSpecifier.ts]: I think this should have `.every()` semantics, no? That's both my intuition and what I take away from https://github.com/typescript-eslint/typescript-eslint/issues/11452#issuecomment-3206818686

Could you please also add a test that cements this behavior? (e.g. ensuring matching `Promise<A> | B` should or should not be matched)

Comment (y-hsgw) [reply packages/type-utils/src/TypeOrValueSpecifier.ts]: You're right, every is the correct approach.
My interpretation was off... 😂
I’ve fixed it in [c878727](https://github.com/typescript-eslint/typescript-eslint/pull/11526/commits/c878727f0e3280c3a973b11da6a594d731911e82).

**Review by kirkwaiblinger — APPROVED** [review]

**Review by JoshuaKGoldberg — APPROVED** [review]
Great, thanks! 🙌
