### PR TITLE
fix(scope-manager): exclude Program from DefinitionBase node types

### LINKED ISSUE #11334: Bug: DefinitionBase shouldn't allow its Node type to be TSESTree.Program
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

scope-manager

### Playground Link

_No response_

### Repro Code

See https://github.com/typescript-eslint/typescript-eslint/pull/11322/files#r2158282689

### Expected Result

The types of nodes on scope-manager definitions are, to my knowledge, always nodes _inside_ a source file. They're never the `TSESTree.Program` themselves. Thus, they should always have a defined `parent` property set to some parent node.

### Actual Result

`DefinitionBase`'s `node` property's type is from a type parameter constrained to `TSESTree.Node`:

https://github.com/typescript-eslint/typescript-eslint/blob/a157fd4c62741d2dec2e4f47f738f499b616035d/packages/scope-manager/src/definition/DefinitionBase.ts#L11

https://github.com/typescript-eslint/typescript-eslint/blob/a157fd4c62741d2dec2e4f47f738f499b616035d/packages/scope-manager/src/definition/DefinitionBase.ts#L32

`TSESTree.Node` includes `TSESTree.Program` as a type constituent. Which is problematic because that's the only type of node that doesn't have a required `parent` property.

We see in https://github.com/typescript-eslint/typescript-eslint/pull/11322/files#r2158282689 that some areas of code have to use a `!` after `node.parent`.

### Additional Info

My initial instinct for solving this is to:

1. Make a `TSESTree.NodeWithParent` type union with all the constituents of `TSESTree.Node` _except_ `TSESTree.Program`
2. Use that `TSESTree.NodeWithParent` in `DefinitionBase` and other scope-manager types that can only ever be a node inside a file (i.e. with a parent)

### Versions

| package                                | version  |
| -------------------------------------- | -------- |
| `@typescript-eslint/scope-manager`     | `8.34.1` |
| `@typescript-eslint/types`             | `8.34.1` |

💖

### PR DESCRIPTION
**Pull request by dbarabashh**
Fix #11334

## PR Checklist

- [x] Addresses an existing open issue: fixes #11334
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR improves type safety in the `scope-manager` package by preventing `TSESTree.Program` nodes from being used as definition nodes.

### CODE REVIEW

**Comment by dbarabashh** [comment]
I am not sure that the linter failed now exactly because of my changes, because locally this command was successful

**Comment by JoshuaKGoldberg** [comment]
Try a `yarn build` first, then a `yarn lint`? It looks like the types are better informed because of this change (nice!), so lint rules are pointing out previously missed unnecessary `?.`s and the like.

**Comment by dbarabashh** [comment]
@JoshuaKGoldberg thank you, done

**Comment by kirkwaiblinger** [comment]
@dbarabashh Would you mind also auditing for uses of `nullThrows` that can be removed? For example, 

https://github.com/typescript-eslint/typescript-eslint/blob/63ab00225eea8c9e4c8fadc22d5c3081daf13e18/packages/eslint-plugin/src/rules/no-confusing-void-expression.ts#L368

File: packages/scope-manager/src/definition/DefinitionBase.ts [hunk 1]
```diff
@@ -5,10 +5,15 @@ import type { DefinitionType } from './DefinitionType';
 import { createIdGenerator } from '../ID';
 
 const generator = createIdGenerator();
+/**
+ * Helper type to exclude Program from valid definition nodes
+ * Program is the root node and doesn't have a parent property
+ */
+export type NodeWithParent = Exclude<TSESTree.Node, TSESTree.Program>;
```
Comment (JoshuaKGoldberg) [inline packages/scope-manager/src/definition/DefinitionBase.ts]: 🤔 This type doesn't really belong to the scope-manager. Any consumer of the TSESTree nodes is likely to want it, such as the `collectUnusedVariables` change already in this PR. I this this should really be `TSESTree.NodeWithParent`.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
+1 to what Kirk said. I also think the new type is good enough that it should be moved to `@typescript-eslint/types` altogether. Thanks for starting this! 🙌

File: packages/scope-manager/src/definition/DefinitionBase.ts (hunk 1 above)
Comment (dbarabashh) [reply packages/scope-manager/src/definition/DefinitionBase.ts]: I got it, will do

Comment (dbarabashh) [reply packages/scope-manager/src/definition/DefinitionBase.ts]: I hope the commit I made meets the expectations. If something is needed, let me know.

**Review by JoshuaKGoldberg — APPROVED** [review]
🤤 look at all those removed `?~s and `nullThrows()`s! Absolutely lovely. Thanks!

**Review by kirkwaiblinger — APPROVED** [review]
🎉🎉
