### PR TITLE
fix(eslint-plugin): [dot-notation] fix false positive when accessing private/protected property with optional chaining

### LINKED ISSUE #8813: Bug: [dot-notation] False positive with optional chaining and allowPrivateClassPropertyAccess: true
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.3&fileType=.ts&code=MYGwhgzhAEAa0G8BQ1oAcBOBLAbmALgKbrY4D6mA9mtALzQCMATAMwDcSAvkkiIftAAeALjjQAPtACuAOwAmhAGZYZhOR2CUZESnwB0ISgHMAFIID8egNoAiTLgoZqNgLoBKJEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQCYHsAXAWgDsiBDQgS31PSnwDMnIAacbSAAUIE8ADigDG0agJIp41UoQD0BEuUJVa9DAG1O2KImjR80dtuxYdXCvHj4A7gAUxANyqIAwvArJkD-EOj8AQWFhFFQMQjhEEwgAXxMAXU44mKA&tsconfig=&tokens=false

### Repro Code

```TypeScript
class X {
  private priv_prop = 123;
}

let x: X | undefined;
// ["priv_prop"] is better written in dot notation.
console.log(x?.["priv_prop"])
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "dot-notation": "off",
    "@typescript-eslint/dot-notation": [
      "error",
      {
        "allowPrivateClassPropertyAccess": true
      }
    ]
  }
}
```

### Expected Result

Expect no ESLint errors.

### Actual Result

This ESLint error.
`["priv_prop"] is better written in dot notation.`

### Additional Info

Similar issues：https://github.com/typescript-eslint/typescript-eslint/issues/3510

### PR DESCRIPTION
**Pull request by developer-bandi**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8813
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
fix error when chaning operation is used in member acceess. thanks to #3711, i resolve this problem

additionally, the issue was not refer to protected option, but protected option also make false positive, so fix too.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/dot-notation.ts [hunk 1]
```diff
@@ -89,7 +90,17 @@ export default createRule<Options, MessageIds>({
           node.computed
         ) {
           // for perf reasons - only fetch symbols if we have to
-          const propertySymbol = services.getSymbolAtLocation(node.property);
+          const propertySymbol =
+            services.getSymbolAtLocation(node.property) ??
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/dot-notation.ts:94]: Unit tests still pass without this line. Either there's a missing unit test or this line can be removed.

```suggestion
```

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, thanks!

Leaving in `1 approval` in case anybody else has time to review.
