### PR TITLE
fix(eslint-plugin): [keyword-spacing] unexpected space before/after in `import type`

### LINKED ISSUE #6063: Bug: [@typescript-eslint/keyword-spacing] Unexpected space(s) before "{" in import type
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

none

### Repro Code

```typescript
import type {SavedQueries} from "./SavedQueries.js";
import type http2 from "node:http2";
import type http from "node:http";

where SavedQueries.js contains only: export const SavedQueries;
```

### ESLint Config

```javascript
parser: '@typescript-eslint/parser'

plugins:
    - '@typescript-eslint'

extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:@typescript-eslint/recommended-requiring-type-checking'

parserOptions:
    ecmaVersion: 2021
    ecmaFeatures:
        impliedStrict: true
    project:
        - ./server/tsconfig.json

settings:
    import/parsers: {'@typescript-eslint/parser': [.ts, .tsx]}
    import/resolver: {typescript: {}}
    import/extensions: [.js, .ts]
    import/ignore: [node_modules]

env:
    es2021: true
    node: true

rules:
    keyword-spacing: off
    '@typescript-eslint/keyword-spacing':
        - warn
        - before: true
          after: false
          overrides:
            else: {after: true}
            return: {after: true}
            try: {after: true}
            catch: {after: false}
            case: {after: true}
            const: {after: true}
            throw: {after: true}
            let: {after: true}
            do: {after: true}
            of: {after: true}
            as: {after: true}
            finally: {after: true}
            from: {after: true}
            import: {after: true}
            export: {after: true}
            default: {after: true}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "lib": [
        "esnext",
    ],
    "removeComments": true,
    "strict": true,
    "alwaysStrict": true,
    "useDefineForClassFields": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "moduleResolution": "node",
    "types": [
        "node",
    ],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "importsNotUsedAsValues": "remove",
    "strictNullChecks": true
  },
  "include": [
      "*"
  ],
  "exclude": [
      "./node_modules",
      "./tests"
  ]
}
```

### Expected Result

The rule always worked on my codebase with version 5.43.0. The error message appeared as soon as I moved to version 5.44.0

### Actual Result

```
warning: Unexpected space(s) before "{" (@typescript-eslint/keyword-spacing) at server\ServerResources.ts:13:13:
> 13 | import type {SavedQueries} from "./SavedQueries.js";
     |             ^
  14 | import type http2 from "node:http2";
  15 | import type http from "node:http";
  16 |

warning: Unexpected space(s) before "http2" (@typescript-eslint/keyword-spacing) at server\ServerResources.ts:14:13:
  13 | import type {SavedQueries} from "./SavedQueries.js";
> 14 | import type http2 from "node:http2";
     |             ^
  15 | import type http from "node:http";
  16 |

warning: Unexpected space(s) before "http" (@typescript-eslint/keyword-spacing) at server\ServerResources.ts:15:13:
  13 | import type {SavedQueries} from "./SavedQueries.js";
  14 | import type http2 from "node:http2";
> 15 | import type http from "node:http";
     |             ^
  16 |
 ```

### Additional Info

Also it is not possible to add as `overrides` the line `type: {after: true}` that elicits the following error running eslint:
```
Oops! Something went wrong! :(

ESLint: 8.28.0

Error: --config:
        Configuration for rule "@typescript-eslint/keyword-spacing" is invalid:
        Value {"else":{"after":true},"return":{"after":true},"try":{"after":true},
"catch":{"after":false},"case":{"after":true},"const":{"after":true},"throw":{"after":true},
"let":{"after":true},"do":{"after":true},"of":{"after":true},"as":{"after":true},"finally":{"after":true},
"from":{"after":true},"import":{"after":true},"export":{"after":true},"default":{"after":true},
"type":{"after":true}} should NOT have additional properties.
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.44.0` |
| `@typescript-eslint/parser`            | `5.44.0` |
| `TypeScript`                           | `4.9.3` |
| `ESLint`                               | `8.28.0` |
| `node`                                 | `18.12.1` |

### PR DESCRIPTION
**Pull request by omril1**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6063
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

This is very hard to define correctly as the type keyword sits between already supported tokens from the base rule that have their own defined before/after.
For now, this is how I think the defining cases should be but I'm open to changing them or add more as you see fit

- I'm not sure if I should add support for an overrides option for type, and how to do it with extending the base rule

### CODE REVIEW

File: packages/eslint-plugin/src/rules/keyword-spacing.ts [hunk 1]
```diff
@@ -56,6 +56,11 @@ export default util.createRule<Options, MessageIds>({
       ): void {
         const typeToken = sourceCode.getFirstToken(node, { skip: 1 })!;
         const punctuatorToken = sourceCode.getTokenAfter(typeToken)!;
+        if (
+          node.specifiers?.[0]?.type === AST_NODE_TYPES.ImportDefaultSpecifier
+        ) {
+          return;
+        }
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/keyword-spacing.ts:63]: I'm confused. The preview deploy's playground still shows an unexpected space for one of the three issue's sample cases: https://deploy-preview-6095--typescript-eslint.netlify.app/play/#ts=4.9.3&sourceType=module&code=FASwtgDg9gTgLgAjgTwgUwQbwQZQIYBuaAJgIoCuaMIaAzggL4IBmMUYCARAHQD0+RMpWp1uAK1qcA3KEixEKdAgAWcOBABMLNh04A7KMTQAuVeo3TZ0eElQYzEbey4GjptREtA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Aa0UIHcB7aACa1kxAIZlmAc3RgA2uGw5uo6E0gAaBYqyLskAEaIAZv0Qz8cRJt17RR-Imgyjo+MitbdkXgDdHVARQZHRscRDczDBDQnDsHJwwLWERPGwBfaxioaER8WFVg1NDIOMdzSyLFDMq9C0JCrNt7MsSKxurGyDJRfDIACwbGqFKEsBcImogOrK7Rd0HOkfLkybBpmK7eJmR8BZml1pX2zI38Puhebj2Ng7AklOPVyCRdqNXY5tH71fXigV5rsVbt9Hp1eEZATYSp9lg8sr8oXNIV5gW14SdikZmK54PU3kNhjDDnCYgivEYLgBbZGKaHxWE-DFQyiU4j8V6Yd6E+nExlPRAADzZ0A50RuRLuaNJTK8gRcCFFXLpLUlR3hNTSRU1igAugpNWkgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA. Am I missing something?

```ts
import type { SavedQueries } from "./SavedQueries.js";
```

**Review by JoshuaKGoldberg — COMMENTED** [review]
Did you mean to put this as a draft? Since it doesn't yet address the original issue, I'll convert it. Let me know if anything's unclear. And thanks for working on this!

File: packages/eslint-plugin/src/rules/keyword-spacing.ts (hunk 1 above)
Comment (omril1) [reply packages/eslint-plugin/src/rules/keyword-spacing.ts:63]: I thought draft means you won't review it (Sorry, I guess it meant something else to me).

I opened it for review because I can't think of a way to solve it without adding an override option for the `type` keyword or should it use the existing option for the `import` keyword.

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/keyword-spacing.ts:63]: Oh I just didn't realize there was a question associated with this! Sorry, i misinterpreted the discussion. Will think on it 🙂

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/keyword-spacing.ts:63]: Or, actually, definitely yes. Since the `type` option doesn't exist in ESLint core and is TypeScript-specific, we should add in a feature for it. Yes please 😄

Comment (omril1) [reply packages/eslint-plugin/src/rules/keyword-spacing.ts:63]: Any example I can look at how to do that? The types seem looser than the schema validation (typed as `overrides?: Record<string, { before?: boolean; after?: boolean;}>` but adding `type: { after: true }` to object breaks the schema validation

**Review by bradzacher — APPROVED** [review]
strange_bugfix

thanks so much for following up to fix this!
