### PR TITLE
fix(website): correct crash when switching to dark/light mode in playground

### LINKED ISSUE #6335: Bug: Playground crashes when switching between light and dark mode
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

website

### Playground Link

https://typescript-eslint.io/play#ts=4.9.3&sourceType=module&code=C4TwDgpgBAglC8UDeUC+BYAUFgJhAxgDYCGATtAG5lQAeAXFEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
Visit provided playground link to see the issue.
```

### ESLint Config

```javascript
N/A (see playground link)
```

### tsconfig

```jsonc
N/A (see playground link)
```

### Expected Result

The playground should not crash when switching from light to dark mode, or vice-versa. Playground state should be preserved when switching.

### Actual Result

The playground state may disappear and reappear after around 5 seconds of waiting. Then the page crashes.

### Additional Info

Here's a video showing the issue:

https://user-images.githubusercontent.com/567041/212404261-c2f11517-4502-4311-833d-a1b063742c96.mp4

Note that in this video I don't paste in any code -- the page loads up blank, then when I hit the dark mode button, after several seconds the code appears. Then it crashes.

The video shows the page crashing after I refresh it following a previous crash, but this also occurs for me in a fresh incognito session, ie. without any service workers, cookies, localstorage or other persistent state set.

### Versions

- Firefox 108
- Chrome 108

### PR DESCRIPTION
**Pull request by armano2**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6335
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/website/src/components/editor/useSandboxServices.ts [hunk 1]
```diff
@@ -145,7 +145,10 @@ export const useSandboxServices = (
         model.dispose();
       }
     };
-  }, [props.ts, colorMode, props.jsx, onLoaded]);
+    // colorMode can't be reactive here, this is going to cause crash while switching dark/light mode
+    // updating of colorMode is handled in LoadedEditor
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [props.ts, props.jsx, onLoaded]);
```
Comment (armano2) [inline packages/website/src/components/editor/useSandboxServices.ts:151]: we have to make sure that this value is non reactive,

@JoshuaKGoldberg if you don't like eslint disable we can save this value to state and never mutate it

```
const [darkMode] = setState(() => colorMode)
```

File: packages/website/src/components/editor/useSandboxServices.ts [hunk 2]
```diff
@@ -145,7 +145,10 @@ export const useSandboxServices = (
         model.dispose();
       }
     };
-  }, [props.ts, colorMode, props.jsx, onLoaded]);
+    // colorMode can't be reactive here, this is going to cause crash while switching dark/light mode
```
Comment (JoshuaKGoldberg) [inline packages/website/src/components/editor/useSandboxServices.ts:148]: Could you elaborate here on why?

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 thanks! This seems cleaner to me.

File: packages/website/src/components/editor/useSandboxServices.ts (hunk 2 above)
Comment (armano2) [reply packages/website/src/components/editor/useSandboxServices.ts:148]: not sure what else you want me to write here, i pushed small fix for jsx, (chaning jsx option was causing crash to)

Comment (JoshuaKGoldberg) [reply packages/website/src/components/editor/useSandboxServices.ts:148]: I mean, _why_ would providing `colorMode` cause a crash?

Comment (armano2) [reply packages/website/src/components/editor/useSandboxServices.ts:148]: hmm, how to put it in proper sentence...

> in this context `useEffect` is used as constructor/destructor, constructor uses singletor to generate code and destructor is triggered always causing code to not be correctly initialized.
> This forces external lib to recreate editor when we want to update theme or one of options.

i'm bad at explaining stuff xd

Comment (JoshuaKGoldberg) [reply packages/website/src/components/editor/useSandboxServices.ts:148]: Ah I think I got it! How about...

```suggestion
    // colorMode can't be reactive here because we don't want to force a recreation
    // of the editor whenever options or theme changes
```

**Review by JoshuaKGoldberg — DISMISSED** [review]
🔥

**Review by bradzacher — APPROVED** [review]
