### PR TITLE
fix(eslint-plugin): [no-magic-numbers] handle UnaryExpression for enums

### LINKED ISSUE #1414: [no-magic-numbers] False positive on negative numbers in enums w/ ignoreEnums flag on
Hello! I came across this odd behavior when trying to add the no-magic-numbers rule to a project: 
**Repro**

```JSON
{
  "rules": {
   'no-magic-numbers': 'off',
    '@typescript-eslint/no-magic-numbers': [
      'error',
      {
        'ignoreEnums': true,
      },
    ],
  }
}
```

```TS
enum KeyboardNav {
  IS_ACTIVE = 0,
  IS_NOT_ACTIVE = -1,
}
```

**Expected Result**
To pass without returning any errors

**Actual Result**
eslint returns: `error: No magic number: -1 (@typescript-eslint/no-magic-numbers)` .
 0, on the other hand, is not flagged.
**Additional Info**

Eslint exited with a status 1, no errors were thrown. 
When run with the debug flag, this is the dump of the output related to the file containing this enum:

```
  eslint:ignored-paths contains: +6ms
  eslint:ignored-paths   target   = "/...stuff.../shouldBeKeyboardNavAccessible.ts" +0ms
  eslint:ignored-paths   base     = "/...stuff.../" +0ms
  eslint:ignored-paths   relative = "/...stuff.../shouldBeKeyboardNavAccessible.ts" +0ms
  eslint:ignored-paths   result   = false +0ms
  eslint:file-enumerator Yield: shouldBeKeyboardNavAccessible.ts +6ms
  eslint:cli-engine Lint /...stuff.../shouldBeKeyboardNavAccessible.ts +6ms
  eslint:linter Linting code for /...stuff.../shouldBeKeyboardNavAccessible.ts (pass 1) +0ms
  eslint:linter Verify +0ms
  eslint:linter With ConfigArray: /...stuff.../shouldBeKeyboardNavAccessible.ts +0ms
  eslint:linter Generating fixed text for/...stuff.../shouldBeKeyboardNavAccessible.ts (pass 1) +7ms
  eslint:source-code-fixer Applying fixes +7ms
  eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `^2.2.0` |
| `@typescript-eslint/parser`        | `^2.2.0` |
| `TypeScript`                       | `~3.6.3` |
| `ESLint`                           | `~6.3.0` |
| `node`                             | `10.16.2` |
| `npm`                              | `6.13.4` |

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #1414

Also fixes a consistency issue wherein our extension would include the `+` when reporting, but the base rule doesn't.
Also reformatted the code a bit:
- moved utility functions outside of create
- used optional chaining

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-magic-numbers.ts [hunk 1]
```diff
@@ -229,3 +110,111 @@ export default util.createRule<Options, MessageIds>({
     };
   },
 });
+
+/**
+ * Gets the true parent of the literal, handling prefixed numbers (-1 / +1)
+ */
+function getLiteralParent(node: TSESTree.Literal): TSESTree.Node | undefined {
+  if (
+    node.parent?.type === AST_NODE_TYPES.UnaryExpression &&
```
Comment (armano2) [inline packages/eslint-plugin/src/rules/no-magic-numbers.ts]: hmm, i was thinking what to do with `node.parent?`

parent is always defined in eslint context for nodes (with exception of Program).

Comment (bradzacher) [reply packages/eslint-plugin/src/rules/no-magic-numbers.ts]: yeah we should probably fix the types.
I was considering just adding a new type to ts-estree:

```ts
type KnownParent<TNode extends Node, TParent extends Node> = TNode & { parent: TParent };
```

But that type wouldn't doesn't fix cases like this. It would let us express direct parent selectors like `VariableDeclaration > VariableDeclarator`, so it's probably a nice thing to add as a non-breaking feature.

---

I was considering doing this via generics to make it even more explicit. _But this only works if we make it non-optional._
```ts
interface BaseNode<TParent extends Node = Node> {
  // ...
  parent: TParent;
}

interface VariableDeclarator<TParent extends Node = Node> extends BaseNode<TParent> {}

interface Program extends BaseNode {
  parent?: never;
}
```

The problem with making it non-optional is that this complicates the converter code because the converter isn't the one that adds the `parent`, eslint is.

Comment (armano2) [reply packages/eslint-plugin/src/rules/no-magic-numbers.ts]: q: what do you think mayby about adding d.ts with override for type in eslint-utils or plugin itself?

```
define module ....
```
