### PR TITLE
fix(eslint-plugin): [no-unnecessary-condition] don't flag values of an unconstrained or valid type parameter

### LINKED ISSUE #10442: Bug: [no-unnecessary-condition] don't flag values of an unconstrained or valid type parameter
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.7.2&fileType=.tsx&code=CYUwxgNghgTiAEYD2A7AzgF3hkmCMAXPABQCU8AvAHzwBGSSEIUKA3AFCiSwLLpY5MAJiJlKNAK4oA1iiQB3Np3DQ4iVJmy4MAZiIAeACpUx1eIY5dVvDQO0AWA4fggAHjhTA0dBkxYnyMwt2dgB6UPgAByg0NFx2AG08ABp4FAkICABdADoAMwBLCBwYYkEMPFIOMIjo2Pik1PTM3MLikFLyoSqQ8Pg0AAskDOAomLRElLSM7PyikrLtHR6a-qGRsdjJppnW%2BY7FzHseoA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
declare const test1: () => boolean;
declare const test2: () => unknown;
declare const test3: <T>() => T;
declare const test4: <T extends boolean>() => T;

// passes
[1, null].filter(test1);

// passes
[1, null].filter(test2);

// should pass
[1, null].filter(test3);

// should pass
[1, null].filter(test4);
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unnecessary-condition": "error"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expect all use-cases to be consistent and not report as errors.

### Actual Result

The use-cases with a type constraint report (unnecessarily) as an error.

### Additional Info

This seems similar to #10311 and looks like the fix should be similar.

### PR DESCRIPTION
**Pull request by ronami**
## PR Checklist

- [x] Addresses an existing open issue: fixes #10442
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR addresses #10442 and handles a potential return type being a type constraint.

The PR suffers from the same issues around `getConstrainedTypeAtLocation` described by @kirkwaiblinger on #10438 and requires a small workaround.

Note that `no-unnecessary-condition` makes a lot of use of `getConstrainedTypeAtLocation`, but going over them roughly, I couldn't find additional bugs around unconstrained type parameters.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 1]
```diff
@@ -646,22 +646,32 @@ export default createRule<Options, MessageId>({
...
         // Predicate is always necessary if it involves `any` or `unknown`
-        if (returnTypes.some(t => isTypeAnyType(t) || isTypeUnknownType(t))) {
+        if (
+          // https://github.com/typescript-eslint/typescript-eslint/issues/10438
+          returnTypes.some(t => !t || isTypeAnyType(t) || isTypeUnknownType(t))
+        ) {
           return;
         }
-        if (!returnTypes.some(isPossiblyFalsy)) {
+        if (!returnTypes.some(t => t && isPossiblyFalsy(t))) {
```
Comment (ronami) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:668]: Checking `t` here is unnecessary (as the `returnTypes.some` check above would return), but I preferred having this over a type assertion.

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 2]
```diff
@@ -646,22 +646,32 @@ export default createRule<Options, MessageId>({
...
             getConstrainedTypeAtLocation(services, callback),
           )
-          .map(sig => sig.getReturnType());
+          .map(sig => sig.getReturnType())
+          .map(t => {
+            if (tsutils.isTypeParameter(t)) {
+              return checker.getBaseConstraintOfType(t);
+            }
+
+            return t;
```
Comment (ronami) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:655]: Optimally, we could use `getConstrainedTypeAtLocation` here once https://github.com/typescript-eslint/typescript-eslint/issues/10438 is tackled.

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:668]: -1 from me, since we know `t` is truthy the extra runtime `t &&` check is confusing.

I also find it kind of clunky that there are three `.some`s on the same array in rapid succession... and also a five-year-old `/* istanbul ignore if */` just before them. 

WDYT about something like this?

```ts
let reportMessage: MessageId | undefined;

for (const type of returnTypes) {
  if (!type || isTypeAnyType(type) || isTypeUnknownType(type)) {
    return;
  }

  if (isPossiblyFalsy(type)) {
    reportMessage = 'alwaysTruthyFunc';
  } else if (isPossiblyTruthy(type)) {
    reportMessage = 'alwaysFalsyFunc';
  }
}

if (reportMessage) {
  context.report({ node: callback, messageId: reportMessage });
}
```

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:655]: 👍 agreed, that'd be nice. Suggestion: I'd put a TODO comment here so it's not lost.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Nice! Just requesting changes on a bit of cleanup for the older code.

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts (hunk 1 above)
Comment (ronami) [reply packages/eslint-plugin/src/rules/no-unnecessary-condition.ts]: Yes! That's significantly easier to understand 👍 

I've made some changes since it doesn't exactly match the current implementation (a couple of failing tests). The existing code is somewhat confusing with: https://github.com/typescript-eslint/typescript-eslint/blob/ce5d3e3b5b1c2d85482c9ee6f66fed59fe04d584/packages/eslint-plugin/src/rules/no-unnecessary-condition.ts#L658-L669

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 3]
```diff
@@ -646,22 +646,43 @@ export default createRule<Options, MessageId>({
...
+            // https://github.com/typescript-eslint/typescript-eslint/pull/10496
+            if (tsutils.isTypeParameter(t)) {
+              return checker.getBaseConstraintOfType(t);
+            }
+
+            return t;
+          });
+
+        let hasFalsyReturnTypes = false;
+        let hasTruthyReturnTypes = false;
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:661]: One more optimization: we know that we won't care about possibly truthy types if there was a possibly falsy type. So this can become:

```suggestion
        let knownReturnType: 'falsy' | 'truthy' | undefined;
```

...and the truthiness check below could be:

```ts
} else if (knownReturnType !== 'falsy' && isPossiblyTruthy(type)) {
  knownReturnType = 'truthy';
}
```

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
One last touchup, since you're humoring me 😄

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts (hunk 3 above)
Comment (ronami) [reply packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:661]: I like the suggested optimization, but I don't think the proposed change matches the current implementation (some tests fail unless I've missed something).

To my understanding, the current code can be changed to the following so that as soon as both a truthy and a falsy values exist, the function bails:

```diff
for (const type of returnTypes) {
  // Predicate is always necessary if it involves `any` or `unknown`
  if (!type || isTypeAnyType(type) || isTypeUnknownType(type)) {
    return;
  }

  if (isPossiblyFalsy(type)) {
    hasFalsyReturnTypes = true;
  }

  if (isPossiblyTruthy(type)) {
    hasTruthyReturnTypes = true;
  }

+  if (hasFalsyReturnTypes && hasTruthyReturnTypes) {
+    return;
+  }
}
```

I think the same value can be possibly-truthy and possibly-falsy at the same time (e.g. `boolean`), so both checks have to run for every return type.

I think matching the current implementation with a single value state (`let knownReturnType: 'falsy' | 'truthy' | undefined`) will require potentially nested if statements, as even something like the following fails to catch some cases (like the returned `boolean` type):

```ts
if (isPossiblyFalsy(type) && knownReturnType !== 'truthy') {
  knownReturnType = 'falsy';
}

if (isPossiblyTruthy(type) && knownReturnType !== 'falsy') {
  knownReturnType = 'truthy';
}
```

I'll be happy to update with the above diff if it makes sense or something different if I'm missing something.

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:661]: Gotcha - that works!

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM! I think this is ready if you are ✨

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 4]
```diff
@@ -646,22 +646,48 @@ export default createRule<Options, MessageId>({
           .getCallSignaturesOfType(
             getConstrainedTypeAtLocation(services, callback),
           )
-          .map(sig => sig.getReturnType());
-        /* istanbul ignore if */ if (returnTypes.length === 0) {
-          // Not a callable function
-          return;
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:652]: minor regression.... which I _think_ hit this line previously, but I haven't validated that.
```ts
declare const lol: any;
[1, 2, 3].filter(lol); // should not flag
```

Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:652]: Sweet! Thanks! Yeah, IIRC `any` and `Function` are the two types I know of that are permitted to be called without any TS errors, but don't have any call signatures. Some obscure linting trivia 🤷‍♂️

**Review by kirkwaiblinger — APPROVED** [review]
🚀 

Bug is solved and the existing code is better for it, too. 
yay
