### PR TITLE
fix(eslint-plugin): guard against negative paramIndex in no-useless-default-assignment

### LINKED ISSUE #12068: Bug: [no-useless-default-assignment] Cannot read properties of undefined (reading 'flags')
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.9.2&fileType=.ts&code=JYOwLgpgTgZghgYwgAgGIHt0GdkG8BQyyARnFAPwBcyIArgLbHT4C%2B%2B%2BC6IWYyMmWahmwBtALrIAvMnEBudv2wA6GABs4YALJwADgAo9uEmSnIALACZkLAJRSAfMag35QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tmUSWWS0AJogBmAQwR1xAygHMmAW0Qt0URNGgdokADThseIqWQVqdBszawmAIw42htZfgAWHIWsgatOgwF8QfyA&tsconfig=N4XyA&tokens=false

### Repro Code

```TypeScript
interface Foos {
  bar?: number
}

const foos: Foos[] = [];

foos.flatMap(({ bar = 42 }) => bar);
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-useless-default-assignment": "error",
    "@typescript-eslint/unbound-method": "error"
  }
}
```

### tsconfig

```jsonc
{}
```

### Expected Result

No errors.

### Actual Result

Linting fails with

```
TypeError: Cannot read properties of undefined (reading 'flags')
```

### Additional Info

This seems to only occur if both `@typescript-eslint/no-useless-default-assignment` and `@typescript-eslint/unbound-method` are enabled. `flatMap` produces the error but `map` does not.

### PR DESCRIPTION
**Pull request by NewtonYuan**
## PR Checklist

- [x] Addresses an existing open issue: fixes #12068 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Problem: Crash in no-useless-default-assignment caused by negative paramIndex.
Fix: Add bounds checks to prevent accessing undefined parameters.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-useless-default-assignment.ts [hunk 1]
```diff
@@ -165,7 +165,7 @@ export default createRule<Options, MessageId>({
             }
 
             const params = signatures[0].getParameters();
-            if (paramIndex < params.length) {
+            if (paramIndex >= 0 && paramIndex < params.length) {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-useless-default-assignment.ts]: [Cleanup] This is already covered by the `if (paramIndex !== -1) {` on line 149:

```suggestion
            if (paramIndex < params.length) {
```

**Comment by ArnaudBarre** [comment]
I believe the issue was that https://github.com/typescript-eslint/typescript-eslint/pull/11949 was doing the `index--` too aggressively. 

With the current code, this will not be reported:
```ts
const foos: { bar: number }[] = [];
foos.flatMap(({ bar = 42 }) => bar);
```

Instead in tsl I changed the paramIndex to be computed like this:
```ts
const paramIndex = parent.parent.parameters
      .filter((p) => p.name.getText() !== "this")
      .indexOf(parent);
```
And removed the `thisParameter` condition
