### PR TITLE
fix(eslint-plugin): [no-magic-numbers] add support for enums

### LINKED ISSUE #573: [@typescript-eslint/no-magic-numbers] enum's are treated as "magic numbers"
**Repro**

```js
    'no-magic-numbers': 'off',
    '@typescript-eslint/no-magic-numbers': ['error', { ignoreNumericLiteralTypes: true }],

```
**Repro**
```ts
enum HttpStatus {
  Ok = 200
}
```

**Expected Result**
Don't treat it as a magic number. It will be used in the code somewhere as `HttpStatus.Ok` that's definitely a defined number.

**Actual Result**
The value `200` is treated as a magic number. Probably because to define a different starting point for `enum` is to use `=` which confuses linter.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.9.0` |
| `@typescript-eslint/parser`        | `1.9.0` |
| `TypeScript`                       | `3.3.3333` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `10.15.3` |
| `npm`                              | `6.4.1` |

### PR DESCRIPTION
**Pull request by jonathanrdelgado**
Fixes #573.

Currently, the following code will fail to lint using the default no-magic-numbers configuration
```
enum foo {
  SECOND = 1000,
  NUM = '0123456789',
}
```

One could make the argument that perhaps we instead want to define it in some other way, perhaps using constants and referring to them such as:
```
const MS_SECONDS = 1000;
enum foo {
  SECOND = MS_SECONDS,
  NUM = '0123456789',
}
```
However, this will result in a compiler error `Computed values are not permitted in an enum with string valued members.ts(2553)`.

I made these changes to resolve that problem. I tried to follow the existing code pattern as much as possible, however, I am open to changes. I also assumed updating the documentation would be unnecessary for this fix, let me know if we would like a change there and I'll handle it.

Thanks for your time!

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-magic-numbers.ts [hunk 1]
```diff
@@ -55,6 +55,18 @@ export default util.createRule<Options, MessageIds>({
       return typeof node.value === 'number';
     }
 
+    /**
+     * Checks if the node grandparent is a Typescript enum declaration
+     * @param node the node to be validated.
+     * @returns true if the node grandparent is a Typescript enum declaration
+     * @private
+     */
+    function isGrandparentTSEnumDeclaration(node: TSESTree.Node): boolean {
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-magic-numbers.ts]: how come you're checking for the grandparent instead of just checking for the parent?
`TSEnumDeclaration` > `TSEnumMember` > `Literal`

File: packages/eslint-plugin/src/rules/no-magic-numbers.ts [hunk 2]
```diff
@@ -55,6 +55,18 @@ export default util.createRule<Options, MessageIds>({
...
+      return node.parent && node.parent.parent
+        ? node.parent.parent.type === AST_NODE_TYPES.TSEnumDeclaration
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-magic-numbers.ts]: no need for a ternary to switch between a boolean outcome

File: packages/eslint-plugin/src/rules/no-magic-numbers.ts (hunk 1 above)
Comment (jonathanrdelgado) [reply packages/eslint-plugin/src/rules/no-magic-numbers.ts]: I assumed that would be the safest, I wasn't sure if there were other cases in which there would be a node type other than `TSEnumMember`, I'll change that.

File: packages/eslint-plugin/src/rules/no-magic-numbers.ts (hunk 2 above)
Comment (jonathanrdelgado) [reply packages/eslint-plugin/src/rules/no-magic-numbers.ts]: I was trying to copy the style of all the other methods in that file. I'll change that.
