### PR TITLE
fix(eslint-plugin): [no-explicit-any] error with ignoreRestArgs option

### LINKED ISSUE #1795: [@typescript-eslint/no-explicit-any] Error when specifying `ignoreRestArgs` option
**Repro**
Here is repo:
https://github.com/doniyor2109/demo-error-for-typescript-eslint-no-exlicit-any

```JSON
{
  "rules": {
    "@typescript-eslint/no-explicit-any": [
      "error",
      {
        "ignoreRestArgs": true
      }
    ]
  }
}
```

```TS
	type Request = any;
```

**Expected Result**
Should report about usage of `any`.
**Actual Result**
Throws error: `TypeError: Cannot read property 'type' of null`

**Additional Info**
Stack trace
```
node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-explicit-any.js:71:26)
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.25.0`|
| `@typescript-eslint/parser`        | `2.25.0`|
| `TypeScript`                       | `3.8.3` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.2.0`|
| `npm`                              | `6.9.0` |

### PR DESCRIPTION
**Pull request by doniyor2109**
Fixes #1795

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-explicit-any.ts [hunk 1]
```diff
@@ -146,11 +144,10 @@ export default util.createRule<Options, MessageIds>({
...
       return (
-        typeof node.parent !== 'undefined' &&
-        typeof node.parent.parent !== 'undefined' &&
+        node.parent?.parent != null &&
         isNodeValidTSType(node.parent.parent) &&
-        typeof node.parent.parent.parent !== 'undefined' &&
-        typeof node.parent.parent.parent.parent !== 'undefined' &&
+        node.parent.parent.parent != null &&
+        node.parent.parent.parent.parent != null &&
         isNodeRestElementInFunction(node.parent.parent.parent.parent)
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-explicit-any.ts]: nit - might as well consolidate the parent check
```ts
    function isGreatGreatGrandparentRestElement(node: TSESTree.Node): boolean {
      return (
        node.parent?.parent?.parent?.parent != null &&
        isNodeValidTSType(node.parent.parent) &&
        isNodeRestElementInFunction(node.parent.parent.parent.parent)
      );
    }
```
