### PR TITLE
fix(eslint-plugin): [consistent-indexed-object-style] don't report on indirect circular references

### LINKED ISSUE #7863: Bug: [consistent-indexed-object-style] Interface with recursive index signature autofixed to Record instead of mapped type
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.ts&code=KYDwDg9gTgLgBDAnmYcCiICGBbMAbYAVQDsBLCYuAXjgCMIIDNKAfOYgV21uCgG4AUANCRYCZKgw58wAEoN4NKbgIlyrdFhXAA8rQBWwAMYxBw8NHiliMXgDNMRyVpl7DJuAG8BcOAG0Aa2BEAC44AGcYKGsAcwBdMOUZeQhTAQBfASA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra1mAE0QAPRMNocARgCtEZOn0JJ0URNGgdokcGAC%2BIA0A&tsconfig=&tokens=false

### Repro Code

```typescript
export type ExampleUnion = boolean | number;

export type ExampleRoot = ExampleUnion | ExampleObject;

export interface ExampleObject {
  [key: string]: ExampleRoot;
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

This interface can be either be left as-is or auto-fixed to a mapped object type:

```ts
export type ExampleObject = {
  [key in string]: ExampleRoot;
};
```

### Actual Result

It's actually autofixed to `Record<string, ExampleRoot>`, which causes TypeScript to give complaints that `Type alias '(Example(Root|Object)' circularly references itself.`

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.ts&code=KYDwDg9gTgLgBDAnmYcCiICGBbMAbYAVQDsBLCYuAXjgCMIIDNKAfOYgV21uCgG4AUANCRYCZKgw58wAEoN4NKbgIlyrdFhXAA8rQBWwAMYxBw8NHhIUm6QT2GT1OLOPQAJgB4AzjCiliAHMAGltteQgYAD5BIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra1mAE0QAPRMNocARgCtEZOn0JJ0URNGgdokcGAC%2BIA0A&tsconfig=&tokens=false

### Additional Info

I suspect this is in the same area as #4730 and #6598 but not quite the same.

Found while trying to enable the rule on typescript-eslint:

https://github.com/typescript-eslint/typescript-eslint/blob/4972ecd7ebf3ec1a74082607a2ad9d3e141d8ea9/packages/utils/src/json-schema.ts#L35-L38

### PR DESCRIPTION
**Pull request by ronami**
## PR Checklist

- [x] Addresses an existing open issue: fixes #7863
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR tackles #7863 and replaces the current logic for detecting circular references with one that also checks for indirect cycles:

```ts
export type ExampleUnion = boolean | number;

export type ExampleRoot = ExampleUnion | ExampleObject;

export interface ExampleObject {
  [key: string]: ExampleRoot;
}
```

The PR also flags some recursive patterns that are valid as a type reference (and can be fixed into a `Record<...>` form), which currently the rule doesn't flag ([playground link](https://typescript-eslint.io/play/#ts=5.7.2&fileType=.ts&code=JYOwLgpgTgZghgYwgAgCoQM5gIzIN4BQyyA2gNYQCeAXMllKAOYC6teyMA9p7elrgF8A3AQEECAegnIwACxRwARpwBuKYBmQB5ANLI4muDMoAHFFAgxoEEEmSKArmGQaQAcmcWTnKJAAmBGCmKHxgAEzIALzIAEoQCD5%2BADz0TAA0%2BBzcvJjhyAIAfCIEoJCwiCG5AMz4RKQUNHRgDCAsOVhVJMwiYpLScgrKai6auvqGxmbIFlYWtiiOzq4e0xDevhABQVOhACxRsfGJKc3paLm7XUXipdDwdqEArLXE5FS0qa2syAAUAJRRArnLCPHriKQyeT6IbqUZ6Az6SbmSzWeb2JwjdyeNY%2BfyBYLAsAANgOcQSUGSn0YGX%2BgMJROuQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra1mAE0QAPRMNocARgCtEZOn0JJ0URNGgdokcGAC%2BIA0A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)). There is no open issue for this, but it made sense to me. This means the rule will flag certain recursive patterns that it currently doesn't.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts [hunk 1]
```diff
@@ -269,3 +267,99 @@ function findParentDeclaration(
...
+  visited: Set<TSESTree.Node>,
+): boolean {
+  if (visited.has(node)) {
+    // something on the chain is circular but it's not the reference being checked
+    return false;
+  }
+
+  visited.add(node);
+
+  switch (node.type) {
```
Comment (ronami) [inline packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts:293]: I went over the possibilities and I think I got them all, though it's possible I missed some 🙈

File: packages/utils/src/json-schema.ts [hunk 2]
```diff
@@ -34,7 +34,6 @@ export type JSONSchema4TypeExtended =
 
 // Workaround for infinite type recursion
 // Also, https://github.com/typescript-eslint/typescript-eslint/issues/7863
-// eslint-disable-next-line @typescript-eslint/consistent-indexed-object-style
```
Comment (ronami) [inline packages/utils/src/json-schema.ts:37]: This is no longer needed, dog-fooding 🎉

File: packages/utils/src/json-schema.ts [hunk 3]
```diff
@@ -32,9 +32,6 @@ export type JSONSchema4TypeExtended =
   | JSONSchema4Object
   | JSONSchema4Type;
 
-// Workaround for infinite type recursion
-// Also, https://github.com/typescript-eslint/typescript-eslint/issues/7863
-// eslint-disable-next-line @typescript-eslint/consistent-indexed-object-style
```
Comment (ronami) [inline packages/utils/src/json-schema.ts:37]: This is no longer needed, dog-fooding 🎉

File: packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts:283]: This is pretty thorough and for a not-very-common case. I'm never surprised by edge cases popping up in _"check all kinds of nodes/types"_ logic, but would be surprised if many came out of this.
