### PR TITLE
fix(eslint-plugin): [no-var-requires] do not report require created from createRequire

### LINKED ISSUE #4035: [no-var-requires] require created by createRequire should be ignored
similar to: https://github.com/typescript-eslint/typescript-eslint/issues/3713

```JSON
{
  "rules": {
    "@typescript-eslint/no-var-requires": 2
  }
}
```

```TS
import { createRequire } from 'module'

const require = createRequire(import.meta.url)

const json = require('./some.json')
```

**Expected Result**

**Actual Result**

```
error  Require statement not part of import statement  @typescript-eslint/no-var-requires
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.1.0` |
| `@typescript-eslint/parser`        | `5.1.0` |
| `TypeScript`                       | `4.4.4` |
| `ESLint`                           | `8.0.1` |
| `node`                             |`17.0.1` |

### PR DESCRIPTION
**Pull request by asdf93074**
## PR Checklist

-   [x] Addresses an existing issue: fixes #4035 
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Used [this](https://github.com/typescript-eslint/typescript-eslint/issues/3713) as a reference. Pretty much the same solution if I am not mistaken.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-var-requires.ts [hunk 1]
```diff
@@ -32,6 +33,8 @@ export default util.createRule<Options, MessageIds>({
             ? node.parent.parent
             : node.parent;
 
+        const variable = ASTUtils.findVariable(context.getScope(), 'require');
```
Comment (armano2) [inline packages/eslint-plugin/src/rules/no-var-requires.ts:36]: small optimization, can you move this search to only be executed if constant conditions do pass?

```
          // constant checks
          parent &&
          [
            AST_NODE_TYPES.CallExpression,
            AST_NODE_TYPES.MemberExpression,
            AST_NODE_TYPES.NewExpression,
            AST_NODE_TYPES.TSAsExpression,
            AST_NODE_TYPES.TSTypeAssertion,
            AST_NODE_TYPES.VariableDeclarator,
          ].includes(parent.type)
```

Comment (armano2) [reply packages/eslint-plugin/src/rules/no-var-requires.ts:36]:
```ts
        if (
          !parent ||
          ![
            AST_NODE_TYPES.CallExpression,
            AST_NODE_TYPES.MemberExpression,
            AST_NODE_TYPES.NewExpression,
            AST_NODE_TYPES.TSAsExpression,
            AST_NODE_TYPES.TSTypeAssertion,
            AST_NODE_TYPES.VariableDeclarator,
          ].includes(parent.type)
        ) {
          return;
        }

        const variable = ASTUtils.findVariable(context.getScope(), 'require');
        if (!variable?.identifiers.length) {
          return;
        }
         
        context.report({
          node,
          messageId: 'noVarReqs',
        });
```

or

```ts
        if (
          parent &&
          [
            AST_NODE_TYPES.CallExpression,
            AST_NODE_TYPES.MemberExpression,
            AST_NODE_TYPES.NewExpression,
            AST_NODE_TYPES.TSAsExpression,
            AST_NODE_TYPES.TSTypeAssertion,
            AST_NODE_TYPES.VariableDeclarator,
          ].includes(parent.type)
        ) {
          const variable = ASTUtils.findVariable(context.getScope(), 'require');
          if (variable?.identifiers.length) {
            context.report({
              node,
              messageId: 'noVarReqs',
            });
          }
        }
```

Comment (asdf93074) [reply packages/eslint-plugin/src/rules/no-var-requires.ts]: Done. BTW the condition in your first snippet is incorrect. 
```Typescript
         // shouldn't have ! here since we want to return if variable?.identifiers.length is truthy
        if (!variable?.identifiers.length) {
          return;
        }
```

**Review by bradzacher — APPROVED** [review]
thanks for this!
