### PR TITLE
fix(scope-manager): allow visiting of constraint in infer type

### LINKED ISSUE #5330: Bug: [no-unused-vars] Does not recognize usage in TS 4.7 "infer + extends" syntax
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.4&sourceType=module&code=C4TwDgpgBAGlC8UDOwBOBLAdgcygHykwFcBbAIwlQG4AoG0SKASQBMAeAFQD4EoOoIAD2ARMLJFADeUdCwBcMzADNKzFgOGjxsKAF8oAfjVQFmCADdKtGiwgBjADYBDVNCVFMd4OgD2mKEqcXAAU5k4ORBAKHAA0MvJqQQCUCuY+stZKwdKyCgCMenEATEm0QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tidmUQAmtAG4BDaKgwBtcNhyJo0DtEiyIAXVkBfEFqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
type X = string | number;  // 'X' is defined but never used. 1:6 - 1:7

type Id<T> = T extends { id: infer Id extends X } ? Id : never;  // X is used here!

declare function f<T>(value: T, id: Id<T>): void;

f({ id: 1 }, 2);
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unused-vars": ["error"],
  },
};
```

### tsconfig

```jsonc
{
}
```

### Expected Result

I expected no error.

### Actual Result

There was an error on line 1.

### Additional Info

This is using the new `infer` + `extends` syntax from TypeScript 4.7.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.30.5` |
| `@typescript-eslint/parser`            | `5.30.5` |
| `TypeScript`                           | `4.7.4` |
| `ESLint`                               | `8.19.0` |
| `node`                                 | `18.4.0` |

### PR DESCRIPTION
**Pull request by armano2**
## PR Checklist

-   [x] Addresses an existing open issue: fixes #5330
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Add visiting of `constraint` in `infer` type

### CODE REVIEW

File: packages/scope-manager/tests/fixtures/type-declaration/infer-type-constraint.ts.shot [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+      name: "X",
+      references: Array [
+        Reference$2 {
+          identifier: Identifier<"X">,
+          isRead: true,
+          isTypeReference: true,
+          isValueReference: false,
+          isWrite: false,
+          resolved: Variable$2,
+        },
```
Comment (armano2) [inline packages/scope-manager/tests/fixtures/type-declaration/infer-type-constraint.ts.shot:23]: ^

**Review by bradzacher — APPROVED** [review]
