### PR TITLE
fix(typescript-estree): align constructor literal with eslint

### LINKED ISSUE #11084: Bug: `key` of constructor in `class C { "constructor"() {} }` should not be an `Identifier`
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

parser

### Playground Link

https://typescript-eslint.io/play/#ts=5.8.2&showAST=es&fileType=.tsx&code=MYGwhgzhAEDC0G8BQ1oCJgHsB2EAuATgK7B6YFoAUAlItAL5KNA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
class C {
  "constructor"() { }
}
```

### ESLint Config

```javascript
n/a
```

### tsconfig

```jsonc
n/a
```

### Expected Result

I expected `key` property of `MethodDefinition` to be a `Literal`, not an `Identifier`.

This would match Espree ([AST explorer](https://ast-explorer.dev/#eNo9jTEKwzAMRa9iNLWQE2TtFUonL0bVkKJYRpILxeTuVUgIaND/7yENYJjhU77FUJfmMEGLgqwpUQSMgFzM0iONXFPKgFLNtaOLZrjd09hyjQlZQj4lk65Iz1+jDHPkVd6dY58OTLiWF6ktUg/Oxcn84iy49/GG4jhsf6HRNjo=)).

### Actual Result

`key` property of `MethodDefinition` is an `Identifier`:

```json
{
  "type": "MethodDefinition",
  "key": {
    "type": "Identifier",
    "range": [12, 25],
    "name": "constructor",
    "decorators": [],
    "optional": false,
    "typeAnnotation": null
  },
  "kind": "constructor",
  "...": "..."
}
```

Main reason I think this is a bug is that it's different from Espree, where `key` is a `Literal`.

But additionally, I feel this is error-prone, because you can normally assume that the section of source text corresponding to an `Identifier`'s range starts with either a *UnicodeIDStart* character, or `\`. This breaks that rule - the first character is `"`.

### Additional Info

_No response_

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/parser`            | `8.30.1` |

### PR DESCRIPTION
**Pull request by ntdiary**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11084
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

cases:
```ts
// Literal
class A {
  "constructor"() { }
}

// Identifier
class B {
  constructor() { }
}
```

💖

### CODE REVIEW

File: packages/typescript-estree/src/convert.ts [hunk 1]
```diff
@@ -1695,14 +1695,24 @@ export class Converter {
...
 
-        const constructorKey = this.createNode<TSESTree.Identifier>(node, {
-          type: AST_NODE_TYPES.Identifier,
-          range: [constructorToken.getStart(this.ast), constructorToken.end],
-          decorators: [],
-          name: 'constructor',
-          optional: false,
-          typeAnnotation: undefined,
-        });
+        const constructorKey =
```
Comment (nayounsang) [inline packages/typescript-estree/src/convert.ts:1698]: How about add test for this fix?
check `packages/typescript-estree/tests/lib/convert.test.ts`.
1. type is `Literal` if `constructorToken.kind === SyntaxKind.StringLiteral`
2. type is `Identifier` if `constructorToken.kind !== SyntaxKind.StringLiteral`

Try creating ast with `convertNode("sourceCode").`

Comment (ntdiary) [reply packages/typescript-estree/src/convert.ts:1698]: @nayounsang, thank you for the suggestion! I'd be happy to increase the test coverage. I'm new to this repo, and although I've checked the docs, discord, and other PRs recently, I'm still unsure about the best way to add these tests. 😂

Docs mention that AST tests belong in `ast-spec`, I've also seen some `constructor` examples in this package. However, based on my test, this package doesn't resolve the codecov failure comment.


As for `convert.test.ts`, considering that `convertNode` is private, the test code might look like this:
```ts
  describe('should convert constructor node type correctly', () => {
    it('type should be Literal', () => {
      const ast = convertCode('class C { "constructor"() {} }');
      const program = new Converter(ast).convertProgram();
      expect(
        (
          (program.body[0] as TSESTree.ClassDeclaration).body
            .body[0] as TSESTree.MethodDefinitionNonComputedName
        ).key.type,
      ).toBe(AST_NODE_TYPES.Literal);
    });
    it('type should be Identifier', () => {
      const ast = convertCode('class C { constructor() {} }');
      const program = new Converter(ast).convertProgram();
      expect(
        (
          (program.body[0] as TSESTree.ClassDeclaration).body
            .body[0] as TSESTree.MethodDefinitionNonComputedName
        ).key.type,
      ).toBe(AST_NODE_TYPES.Identifier);
    });
  });
```
or
```ts
  describe('should convert constructor node type correctly', () => {
    it('type should be Literal', () => {
      const ast = convertCode('class C { "constructor"() {} }');
      expect(new Converter(ast).convertProgram()).toMatchSnapshot();
    });
    it('type should be Identifier', () => {
      const ast = convertCode('class C { constructor() {} }');
      expect(new Converter(ast).convertProgram()).toMatchSnapshot();
    });
  });
```

Please feel free to let me know your thoughts and then I could push a test commit. :)

Comment (bradzacher) [reply packages/typescript-estree/src/convert.ts:1698]: Please add a fixture test for this:

1) [create a folder here](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/ast-spec/src/element/MethodDefinition/fixtures/), eg called `constructor-string-literal`
2) add a new file called `fixture.ts` within that folder
3) populate that file with the code for a constructor with a string literal identifier
4) goto (1) and create another folder (eg `constructor`) which has code for a constructor with a regular identifier
5) run the tests in the `ast-spec` folder and it'll generate the sanpshots. One of the snapshots is the AST tokens.

**Review by bradzacher — CHANGES_REQUESTED** [review]
change itself LGTM -- RC for adding snapshot tests!

**Review by bradzacher — APPROVED** [review]
