### PR TITLE
fix(eslint-plugin): [no-shadow] ignore type-only imports properly

### LINKED ISSUE #3862: [no-shadow.ignoreTypeValueShadow] false positive against imported types
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
   "@typescript-eslint/no-shadow": [
      "error",
      { "ignoreTypeValueShadow": true }
    ]
  }
}
```

```TS
import type { foo } from './foo';
type bar = number;

// 'foo' is already declared in the upper scope
// 'bar' is fine
function doThing(foo: number, bar: number) {}
```

tsconfig:
```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "compileOnSave": true,
  "compilerOptions": {
    "baseUrl": "./",
    "composite": true,
    "esModuleInterop": true,
    "exactOptionalPropertyTypes": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "isolatedModules": true,
    "module": "ESNext",
    "moduleResolution": "node",
    "noEmit": true,
    "noImplicitAny": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "paths": {
      "@applications/*": ["src/applications/*"],
      "@modules/*": ["src/modules/*"],
      "package.json": ["package.json"]
    },
    "resolveJsonModule": true,
    "rootDirs": [".", "src/modules/seams"],
    "strict": true,
    "typeRoots": ["src/modules/@types", "node_modules/@types"]
  },
  "exclude": ["**/node_modules", "**/build", "**/dist"],
  "include": ["src/**/*", "./*", "./*.json", "config/*", "config/*.json"]
}
```

**Expected Result**

rule should ignore imported types just like it ignores types defined in the file

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.31.0` |
| `@typescript-eslint/parser`        | `4.31.0` |
| `TypeScript`                       | `4.4.2` |
| `ESLint`                           | `7.32.0` |
| `node`                             | `16.8.0` |

### PR DESCRIPTION
**Pull request by rafaelss95**
Fixes #3862.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-shadow.ts [hunk 1]
```diff
@@ -99,7 +99,9 @@ export default util.createRule<Options, MessageIds>({
       }
 
       const isShadowedValue =
-        'isValueVariable' in shadowed ? shadowed.isValueVariable : true;
+        !('isValueVariable' in shadowed) ||
+        (shadowed.defs[0]?.type !== DefinitionType.ImportBinding &&
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-shadow.ts:103]: this isn't quite correct because it will match all import variables.
We specifically only want to match variables imported via `import type`.

**Review by bradzacher — CHANGES_REQUESTED** [review]
thanks for this!
almost there

**Comment by bradzacher** [comment]
This is off-topic from your current change - could you please also update these two lines:
https://github.com/typescript-eslint/typescript-eslint/blob/955d7a62b2e88d9396f7f7b6ce46da6418aea374/packages/eslint-plugin/src/rules/no-shadow.ts#L85
https://github.com/typescript-eslint/typescript-eslint/blob/955d7a62b2e88d9396f7f7b6ce46da6418aea374/packages/eslint-plugin/src/rules/no-shadow.ts#L279

To use `DefinitionType` like you've imported? It'd be great to ensure we're doing the comparisons the same everywhere :)

**Comment by rafaelss95** [comment]
> This is off-topic from your current change - could you please also update these two lines:
> https://github.com/typescript-eslint/typescript-eslint/blob/955d7a62b2e88d9396f7f7b6ce46da6418aea374/packages/eslint-plugin/src/rules/no-shadow.ts#L85
> 
> 
> https://github.com/typescript-eslint/typescript-eslint/blob/955d7a62b2e88d9396f7f7b6ce46da6418aea374/packages/eslint-plugin/src/rules/no-shadow.ts#L279
> 
> To use `DefinitionType` like you've imported? It'd be great to ensure we're doing the comparisons the same everywhere :)

What about adding `DefinitionType` to [`prefer-ast-types-enum rule`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin-internal/src/rules/prefer-ast-types-enum.ts) and fix all possible occurrences once in a separate PR? Would this work for you?

**Comment by bradzacher** [comment]
> What about adding DefinitionType to prefer-ast-types-enum rule and fix all possible occurrences once in a separate PR? Would this work for you?

You can certainly give that a go - I'm not sure if that will false-positive a lot (due to words like `Variable` and `Type` being part of the member). It might be noisy - but we can see if it is or not.

There's an open issue to create a generic rule to do that enum check (#308)

**Comment by rafaelss95** [comment]
I've tested it locally and I think it'll be fine, I'll send it ASAP.

File: packages/eslint-plugin/src/rules/no-shadow.ts (hunk 1 above)
Comment (rafaelss95) [reply packages/eslint-plugin/src/rules/no-shadow.ts]: Good catch! It should be fixed with the `fixup`.

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for your work here!
