### PR TITLE
fix(eslint-plugin): [triple-slash-reference] fix crash with external module reference

### LINKED ISSUE #2762: [triple-slash-reference] TypeError: Cannot read property 'value' of undefined
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

#### .eslintrc.json
```JSON
{
  "root": true,
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": [
          "tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "extends": ["plugin:@typescript-eslint/recommended"]
    }
  ]
}
```
#### .ts
```TS
/// <reference types="@types/googlemaps" />
import DistanceMatrixResponse = google.maps.DistanceMatrixResponse;
```
#### tsconfig.json
```JSON
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "src",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "resolveJsonModule": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": false,
    "strictInjectionParameters": true,
    "preserveWhitespaces": true
  }
}
```

### Expected Result

Evaluate the file, and pass/reject the rule

### Actual Result

Unhandled Exception (see below). Note that disabling all rules (//eslint-disable-next-line) for the problematic line did not stop the exception from occurring.
```
TypeError: Cannot read property 'value' of undefined
Occurred while linting corrupted-file.ts:2
    at ...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\triple-slash-reference.js:67:53
    at Array.forEach (<anonymous>)
    at hasMatchingReference (...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\triple-slash-reference.js:66:24)
    at TSImportEqualsDeclaration (...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\triple-slash-reference.js:88:21)
    at ...\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (...\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (...\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (...\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (...\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
Process finished with exit code -1
```
### Additional Info

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.7.0` |
| `@typescript-eslint/parser`        | `4.7.0` |
| `TypeScript`                       | `4.0.5` |
| `ESLint`                           | `7.13.0` |
| `node`                             | `14.15.0` |

### PR DESCRIPTION
**Pull request by ddubrava**
fixes #2762

https://astexplorer.net/#/gist/cde0bd7d85e03d135e604e7913a999cd/c034332f4ccf256e809629b0552578191e38b3fe

I'm not sure about the solution cuz it's weird that there was used `as TSESTree.TSExternalModuleReference` and didn't handle any other types considering that `moduleReference` has already been typed.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/triple-slash-reference.ts [hunk 1]
```diff
@@ -76,14 +79,29 @@ export default util.createRule<Options, MessageIds>({
...
+          let value: string | number | bigint | boolean | RegExp | null;
+
+          switch (source.type) {
+            case AST_NODE_TYPES.Identifier:
+              value = source.name;
+              break;
+
+            case AST_NODE_TYPES.TSQualifiedName:
+              value = (source.left as TSESTree.Identifier).name;
+              break;
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/triple-slash-reference.ts:97]: I think we should just completely ignore these cases.
There's no import source to compare against here, so doing so will likely lead to some weirdness

**Review by bradzacher — CHANGES_REQUESTED** [review]

**Review by bradzacher — APPROVED** [review]
thanks for this!
