### PR TITLE
fix(eslint-plugin): type assertion in rule no-extra-parens

### LINKED ISSUE #742: [no-extra-parens] incorrect behaviour with angle bracket assertions
**Repro**

```JSON
{
  "rules": {
    "no-extra-parens": 0, 
    "@typescript-eslint/no-extra-parens": 2
  }
}
```

```TS
// type of requestInit is native RequestInit from lib.dom.d.ts
let cookies = (<Headers> requestInit.headers).get('Cookie')
```

**Expected Result**
No error

**Actual Result**
Got error  `Unnecessary parentheses around expression.eslint(@typescript-eslint/no-extra-parens)`
and be changed to below if run `eslint --fix`
```ts
let cookies = <Headers> requestInit.headers.get('Cookie')
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.13.0` |
| `@typescript-eslint/parser`        | `1.13.0` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `6.1.0` |
| `node`                             | `10.16.0` |
| `npm`                              | `6.9.0` |

### LINKED ISSUE #807: [no-extra-parens] behaving incorrectly with a type assertion
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-extra-parens": ["error"]
  }
}
```

```TS
function foo(a: string): number
{
    return ((a as any) | 0) - 1;
}
```

**Expected Result**

No warning.

**Actual Result**

Produces a warning:
> Unnecessary parentheses around expression

Autofixed code has different semantics:

```ts
function foo(a: string): number
{
    return a as any | 0 - 1;
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.13.0` |
| `@typescript-eslint/parser`        | `1.13.0` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `6.1.0` |
| `node`                             | `12.7.0` |
| `npm`                              | `6.10.0` |

**Playground links**
* [Original code](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOcAUBDAXIgzlAJxjAHMBKHMEAWwCMBTAgWACgBvVxLxA+qEAkjSZEGXKLABPMogA+iAAwyAtIgCMAblYBfVqwwAbRlDQp0AcgBMAOgCs5smQ2IA9C-VA)
* [After autofix](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOcAUBDAXIgzlAJxjAHMBKHMEAWwCMBTAgWACgBvVxLxA+qEAkgyIMuEWACeiAD6IADIgC0iAIwBuVgF9WrDABtGUNCnQByAEwA6AKymyZNYgD0T1TaA)

### PR DESCRIPTION
**Pull request by armano2**
This PR adds test cases for type assertion in rule `no-extra-parens` and fixes issue with incorrectly reported parens in binary expressions for type assertions

```
((a as any) | 0) - 1
```

test cases covers changes added in #1369

closes #742
fixes #807

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-extra-parens.ts [hunk 1]
```diff
@@ -35,21 +35,26 @@ export default util.createRule<Options, MessageIds>({
...
+      if (isLeftTypeAssertion && isRightTypeAssertion) {
+        return; // ignore
+      }
+      if (isLeftTypeAssertion) {
         return rule({
           ...node,
           left: {
             ...node.left,
-            type: AST_NODE_TYPES.BinaryExpression as any,
+            type: AST_NODE_TYPES.SequenceExpression as any,
```
Comment (armano2) [inline packages/eslint-plugin/src/rules/no-extra-parens.ts]: `SequenceExpression` has highest priority than it will always enforce parens

https://github.com/eslint/eslint/blob/master/lib/rules/utils/ast-utils.js#L768-L769
```
SequenceExpression = 0
```

File: packages/eslint-plugin/src/rules/no-extra-parens.ts [hunk 2]
```diff
@@ -35,21 +35,26 @@ export default util.createRule<Options, MessageIds>({
       const rule = rules.BinaryExpression as (n: typeof node) => void;
 
       // makes the rule think it should skip the left or right
-      if (util.isTypeAssertion(node.left)) {
+      const isLeftTypeAssertion = util.isTypeAssertion(node.left);
+      const isRightTypeAssertion = util.isTypeAssertion(node.right);
+      if (isLeftTypeAssertion && isRightTypeAssertion) {
```
Comment (armano2) [inline packages/eslint-plugin/src/rules/no-extra-parens.ts]: edge case:
```
(x as '') | (y as '')
```

File: packages/eslint-plugin/src/rules/no-extra-parens.ts (hunk 1 above)
Comment (bradzacher) [reply packages/eslint-plugin/src/rules/no-extra-parens.ts]: yeah this whole rule extension is super dodgy.
We really need to figure out how eslint can expose some internals for easier extension.
