### PR TITLE
fix(eslint-plugin): [prefer-function-type] handle `this` return

### LINKED ISSUE #1756: [prefer-function-type] Quick fixing an interface using this causes tsc error
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/prefer-function-type": 2
  }
}
```

```ts
interface Interface {(): this}
```

**Expected Result**
No error as `this` can only be used in a class or interface.

**Actual Result**

```
/path/to/file.ts
  1:22  error  Interface has only a call signature - use 'type Interface = () => this' instead  @typescript-eslint/prefer-function-type

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Additional Info**

Running eslint with `--fix` results in this code:
```ts
type Interface = () => this
```

which causes a `tsc` error:

```
file.ts:1:24 - error TS2526: A 'this' type is available only in a non-static member of a class or interface.

1 type Interface = () => this
                         ~~~~


Found 1 error.
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.24.0` |
| `@typescript-eslint/parser`        | `2.24.0` |
| `TypeScript`                       | `3.7.5` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.11.0` |
| `npm`                              | `6.11.3` |

### PR DESCRIPTION
**Pull request by tadhgmister**
Fixes #1756

This isn't quite ready yet, it is **missing update to docs** and a few cases described below. Just need some feedback for how to handle some edge cases.

When `this` is used in a call signature of an interface the auto-fix will replace the occurrences of `this` with the name of the interface so the suggested fix is still valid. However:  If the interface defines type parameters and uses `this` then the necessary replacement becomes much more tricky, for example:

```ts
interface Foo<A extends string, B = number> {
  (a: A, b: B): this;
}
// correct replacement would be:
type Foo<A extends string, B = number> = (a: A, b: B) => Foo<A,B>;
```

The current handling for generics can get away with just coping the generics declaration without knowing how to reconstruct `Foo<A,B>` as the valid reference to it's own interface name, so handling this would take some additional effort that I personally don't think is really worth it. (Also I don't trust myself to produce code to do it that is bug free)

Right now my implementation never reports on an interface with both type parameters and refers to `this` but I don't think that is the best course of action, **I'd appreciate some advice on what the best course of action would be in this case.**

The second part is that I think the intent was to offer a suggestion instead of auto fix when `this` is used since technically the suggested fix isn't strictly equivalent. **I'd like some advice on  whether the message should be the same or if there is a different message that should show.**

Thank you! 😄

### CODE REVIEW

**Comment by bradzacher** [comment]
See prior art: https://github.com/typescript-eslint/typescript-eslint/pull/1783

**Comment by tadhgmister** [comment]
second question, the coverage went down slightly because `tsThisTypes?.push` and `tsThisTypes ?? undefined` is only hit in cases where `tsThisTypes` is an actual list so the optional part is never checked, I assume that is fine? If there is something different I should do that would also be welcome feedback.

File: packages/eslint-plugin/src/rules/prefer-function-type.ts [hunk 1]
```diff
@@ -105,13 +158,27 @@ export default util.createRule({
     function checkMember(
       member: TSESTree.TypeElement,
       node: TSESTree.Node,
+      tsThisTypes?: TSESTree.TSThisType[],
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/prefer-function-type.ts:161]: nit just union in null here

```suggestion
      tsThisTypes?: TSESTree.TSThisType[] | null,
```

File: packages/eslint-plugin/src/rules/prefer-function-type.ts [hunk 2]
```diff
@@ -142,14 +209,27 @@ export default util.createRule({
...
+      'TSInterfaceDeclaration TSThisType'(node: TSESTree.TSThisType): void {
+        // inside an interface keep track of all ThisType references.
+        tsThisTypes?.push(node);
+      },
+      'TSInterfaceDeclaration:exit'(
+        node: TSESTree.TSInterfaceDeclaration,
+      ): void {
         if (!hasOneSupertype(node) && node.body.body.length === 1) {
-          checkMember(node.body.body[0], node);
+          checkMember(node.body.body[0], node, tsThisTypes ?? undefined);
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/prefer-function-type.ts:226]: if you union in null you don't need to do this operation
```suggestion
          checkMember(node.body.body[0], node, tsThisTypes);
```

**Comment by bradzacher** [comment]
Suggestion fixers are a good alternative for risky fixers, but here I would probably err on the side of "fix it properly or not at all". We don't want to provide a suggestion that's slightly wrong and then break all of their types.

Note that we don't have to provide a fixer for all cases.
If it's too complicated to produce valid code automatically then it's perfectly fine for us to just report _without_ a fixer.
The user can always manually fix up their code. ESP in this sort of case where it's already pretty advanced TS type - the user should be well-versed enough to be able to manually convert it.

---

codecov doesn't handle optional chaining well. The test coverage is just a guide, if you can cover all of the branches, fine, if there are cases that can't be hit, then feel free to ignore. I will make a judgement when merging to decide if the tests are good enough.

**Comment by tadhgmister** [comment]
I have thought about this more thoroughly and have come to the conclusion that using `this` doesn't make any sense here.  It will refer to the function type which doesn't seem like a useful construct, when people do `return this` in javascript to do method chaining it's rarely 

I think it'd be likely that if people wanted to write a mixin-style method (independent of class but uses `this`) they would want to use a generic `this` parameter instead of referring to the `this` of the function itself.

```ts
function logArg<Self>(this: Self, arg: string): Self {
  console.log(`logging ${arg} from ${this.toString()}`);
  return this;
}
const thing = {logArg, data: "hello"};
// the function returns `thing` in this case, not the `logArg` function:
const data = thing.logArg("logged to console").data;
```
this **is** a useful construct, and in this case using `type MemberMixin = <Self>(this: Self, ...) => Self` would be the correct way to do it, I can absolutely see someone accidentally ending up with just using the `this` type and be surprised when it refers to the function.

So I think if there is an interface that defines only a call signature and uses `this` they should get an error message like:

> `this` refers to the function type {{ interfaceName }}, did you intend to use a generic `this` parameter like `<Self>(this: Self, ...) => Self` instead?

(Offer no suggestion or fix in this case, it represents a semantic change that is application specific, I imagine every application would have some constraint on the `Self` type for the method to be useful.)

This will probably help people move towards what they almost certainly intended in the first place, and if they do replace all occurrences of `this` then the current implementation of the auto fix is absolutely applicable.

Does this seem reasonable?

**Comment by tadhgmister** [comment]
@bradzacher I think it's ready now, still not really sure if or how to mention this in the docs, if you think something should be added please tell me and I'll come up with something, otherwise this should be good to go. 

Thanks.

File: packages/eslint-plugin/src/rules/prefer-function-type.ts [hunk 3]
```diff
@@ -18,6 +18,8 @@ export default util.createRule({
     messages: {
       functionTypeOverCallableType:
         "{{ type }} has only a call signature - use '{{ sigSuggestion }}' instead.",
+      unexpectedThisOnFunctionOnlyInterface:
+        'this refers to the function type {{ interfaceName }}, did you intend to use a generic this parameter like <Self>(this: Self, ...) => Self instead?',
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/prefer-function-type.ts:22]: nit

```suggestion
        '`this` refers to the function type '{{ interfaceName }}', did you intend to use a generic this parameter like `<Self>(this: Self, ...) => Self` instead?',
```

File: packages/eslint-plugin/tests/rules/prefer-function-type.test.ts [hunk 4]
```diff
@@ -146,5 +146,78 @@ interface Foo<T> {
...
+      code: `
+interface Foo<T> {
+  (this: T): void;
+}
+      `,
+      errors: [
+        {
+          messageId: 'functionTypeOverCallableType',
+          type: AST_NODE_TYPES.TSCallSignatureDeclaration,
+        },
```
Comment (bradzacher) [inline packages/eslint-plugin/tests/rules/prefer-function-type.test.ts:159]: I don't know why the rest of the tests don't do this, but could you please add `data` to assert the shape of the message is what we expect?

```suggestion
          type: AST_NODE_TYPES.TSCallSignatureDeclaration,
          data: {
            type: 'Foo',
          },
        },
```

File: packages/eslint-plugin/src/rules/prefer-function-type.ts [hunk 5]
```diff
@@ -18,6 +18,8 @@ export default util.createRule({
     messages: {
       functionTypeOverCallableType:
         "{{ type }} has only a call signature - use '{{ sigSuggestion }}' instead.",
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/prefer-function-type.ts:20]: Slightly unrelated to your change, but whilst we're here....

I think it's probably better to not include the signature in the error message for this one. Lets simplify this - we have an auto fixer so no need to add noise to the error.

Also, might be better to change the parameter to be `typeName` so it aligns with your new message? (I think that's much better than just `type`)

```suggestion
        "'{{ typeName }}' only has a call signature, you should use a function type instead.",
```

File: packages/eslint-plugin/src/rules/prefer-function-type.ts [hunk 6]
```diff
@@ -142,12 +161,36 @@ export default util.createRule({
...
         }
+        // on exit check member and reset the array to nothing.
+        tsThisTypes = null;
+      },
+      // keep track of nested literals to avoid complaining about invalid `this` uses
+      'TSInterfaceDeclaration TSTypeLiteral'(): void {
+        insideLiteral = true;
+      },
+      'TSInterfaceDeclaration TSTypeLiteral:exit'(): void {
+        insideLiteral = false;
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/prefer-function-type.ts:193]: this will cause problems with nested object types.
You will instead want to keep track of this using a stack (push on enter, pop on leave), or using a counter (add on enter, subtract on leave).

Example bug:

```ts
interface Foo {
  (): { // insideLiteral = true
    a: { // insideLiteral = true
      nested: string
    }, // insideLiteral = false

    between: this, // will false-positive due to bug

    b: { // insideLiteral = true
      nested: string
    }, // insideLiteral = false
  } // insideLiteral = false
}
```

**Review by bradzacher — CHANGES_REQUESTED** [review]
logic mostly LGTM.
One bug that needs to be fixed.

thanks for your work.


-------

Responses to your questions:

> So I think if there is an interface that defines only a call signature and uses this they should get an error message like:
> .....
> Does this seem reasonable?

Yup, that seems perfectly reasonable to me. I'm all for having lint rules clearly educate users about how TS actually works (see `ban-types` where I added some education that people constantly butt up against).

> I'm also not sure how to approach this in the docs, is an update needed to mention this or does it fall under "obscure enough edge case we don't have to publicize it"?

I would probably just add it as a examples and add some comments to it.
I don't see a problem of clearly educating people ahead of time as well. I.e.

----

Examples of **incorrect** code for this rule:

`<snip>`

```ts
interface Foo {
  (arg: number): this | undefined;
}

interface Foo {
  (arg: this): void;
}
```

Examples of **correct** code for this rule:

`<snip>`
 
```ts
type Foo<TSelf> = (this: TSelf, arg: number) => TSelf | undefined;

type Foo<TSelf> = (this: TSelf, arg: TSelf) => void
```

File: packages/eslint-plugin/src/rules/prefer-function-type.ts (hunk 5 above)
Comment (tadhgmister) [reply packages/eslint-plugin/src/rules/prefer-function-type.ts:20]: here `type` is referring to the string `'Type literal'` or  `'Interface'` where my message refers to the interface name, so I think I'll rename my message to use `interfaceName` and rename this to be `literalOrInterface` to be clearer. And will remove suggestion from message.

File: packages/eslint-plugin/tests/rules/prefer-function-type.test.ts (hunk 4 above)
Comment (tadhgmister) [reply packages/eslint-plugin/tests/rules/prefer-function-type.test.ts:159]: well the message contained the suggestion so it would have been redundant for the test to assert the fix and message suggestion, the correct behaviour is definitely to remove the suggestion from the message and assert the data.

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for your contribution!
