### PR TITLE
fix(eslint-plugin): [prefer-find] support ternary branches in prefer-find

### LINKED ISSUE #8379: Bug: [prefer-find] Add support for checking ternaries
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://main--typescript-eslint.netlify.app/rules/prefer-find

### Description

This addresses a minor omission when I did the PR for this rule (https://github.com/typescript-eslint/typescript-eslint/pull/8216).

I forgot to add support for checking ternary branches. I've made a quick branch that would add support. See https://github.com/typescript-eslint/typescript-eslint/commit/aa43ec626a718867568f028e0e148f894d3da739

### Fail

```TypeScript
(Math.random < 0.5 ? [1, 2, 3].filter(x => x % 2 === 0) : [4, 5, 6].filter(x => x % 2 === 0))[0]
```

### Pass

```TypeScript
Math.random < 0.5 ? [1, 2, 3].find(x => x % 2 === 0) : [4, 5, 6].find(x => x % 2 === 0)
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8379 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Adds support for recursively checking ternary branches.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/prefer-find.ts [hunk 1]
```diff
@@ -41,20 +41,41 @@ export default createRule({
...
-        return parseIfArrayFilterExpression(lastExpression);
+        return parseArrayFilterExpressions(lastExpression);
       }
 
       if (expression.type === AST_NODE_TYPES.ChainExpression) {
-        return parseIfArrayFilterExpression(expression.expression);
+        return parseArrayFilterExpressions(expression.expression);
+      }
+
+      // This is the only reason we're returning a list rather than a single value.
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/prefer-find.ts:60]: [Praise] I suspect from the code + comments + general flow of this rule that this was probably annoying to implement on your end. Thanks for going through that annoyance. 😄 

(I would be annoyed at it)

File: packages/eslint-plugin/tests/rules/prefer-find.test.ts [hunk 2]
```diff
@@ -70,6 +70,12 @@ ruleTester.run('prefer-find', rule, {
     `,
     "[1, 2, 3].filter(x => x)[Symbol('0')];",
     "[1, 2, 3].filter(x => x)[Symbol.for('0')];",
+    '(Math.random < 0.5 ? [1, 2, 3].filter(x => true) : [1, 2, 3])[0];',
+    `
+      (Math.random < 0.5
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/prefer-find.test.ts:75]: [Testing] Typo:

```suggestion
    '(Math.random() < 0.5 ? [1, 2, 3].filter(x => true) : [1, 2, 3])[0];',
    `
      (Math.random() < 0.5
```

File: packages/eslint-plugin/tests/rules/prefer-find.test.ts [hunk 3]
```diff
@@ -584,5 +590,72 @@ arr.find(f, thisArg);
         },
       ],
     },
+    {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/prefer-find.test.ts:593]: [Testing] Just to be through, could you also add test for a desired report with and within a ternary? Like the `valid` case above, but either with two `.filter`s or with the `[0]` on the other side of the last `)`?

```ts
(Math.random() < 0.5
  ? [1, 2, 3].filter(x => false)
  : [1, 2, 3].filter(x => true))[0];
```

```ts
(Math.random() < 0.5
  ? [1, 2, 3].find(x => true)
  : [1, 2, 3].filter(x => true)[0]);
```

The cases lower down are a bit more complex. It's nice to have more straightforward ones to use as a reference too.

File: packages/eslint-plugin/tests/rules/prefer-find.test.ts [hunk 4]
```diff
@@ -584,5 +590,72 @@ arr.find(f, thisArg);
...
+      code: `
+declare const f: any, g: any;
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/prefer-find.test.ts:595]: [Testing] Nit: here and below, if there's no need to use an `any`, might as well avoid it:

```suggestion
declare const f: unknown, g: unknown;
```

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Code changes look great, nicely done! 👏 

Just requesting changes on a bit more testing.

A League of Legends character dabbing in front of purple smoke and flames. Another character is fly-kicking down towards them from the air.

File: packages/eslint-plugin/tests/rules/prefer-find.test.ts (hunk 4 above)
Comment (kirkwaiblinger) [reply packages/eslint-plugin/tests/rules/prefer-find.test.ts:595]: it would have a type error without. I was just too lazy to write out the actual type of the filter callback (and the rule doesn't care about the type of the filter callback) so i went for the easiest way to not error :)

File: packages/eslint-plugin/src/rules/prefer-find.ts (hunk 1 above)
Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/prefer-find.ts:60]: haha actually i was pleasantly surprised to find that it was quite straightforward :) I was scared there would be complications with overlapping fixes or something, but everything just worked.

File: packages/eslint-plugin/tests/rules/prefer-find.test.ts (hunk 4 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/tests/rules/prefer-find.test.ts:641]: Ha, gotcha. #8298 -> #8351 tracks making tests error on type unhappiness. cc @auvred - do you think we should start asking folks to try to not have type errors?

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, nice! Since it's tricky logic being touched, will leave open for a bit under `1 approval`.

File: packages/eslint-plugin/tests/rules/prefer-find.test.ts (hunk 4 above)
Comment (auvred) [reply packages/eslint-plugin/tests/rules/prefer-find.test.ts:641]: Personally, I'm +1 to avoid semantic errors, at least in newly added tests :)

Especially when it's not that hard:
```diff
- declare const f: any, g: any;
+ declare const f: (x: unknown) => boolean, g: (x: unknown) => boolean;
```

**Review by auvred — DISMISSED** [review]
LGTM :rocket:

File: packages/eslint-plugin/tests/rules/prefer-find.test.ts (hunk 4 above)
Comment (kirkwaiblinger) [reply packages/eslint-plugin/tests/rules/prefer-find.test.ts]: Fair enough, changed

File: packages/eslint-plugin/tests/rules/prefer-find.test.ts [hunk 5]
```diff
@@ -584,5 +590,142 @@ arr.find(f, thisArg);
...
+            },
+          ],
+        },
+      ],
+    },
+
+    {
+      code: `
+declare const spreadArgs: [(x: unknown) => boolean];
+[1, 2, 3].filter(...spreadArgs).at(0);
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/tests/rules/prefer-find.test.ts:712]: not related, just an extra test I wish I'd written on the initial implementation

**Review by auvred — APPROVED** [review]
LGTM! Thanks for updating tests!

Man claps his hands
