### PR TITLE
fix(eslint-plugin): [consistent-type-definitions] remove fixer when the interface is within a global module declaration

### LINKED ISSUE #2707: [consistent-type-definitions] Interface gets changed into type when extending Array.prototype, breaking the code
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "@typescript-eslint/consistent-type-definitions": ["error", "type"]
}
```

```TS
declare global {
  interface Array<T> = {
    intersperse(mkT: (ix: number) => T): T[];
  };
}

if (!('intersperse' in Array.prototype)) {
  Array.prototype.intersperse = function intersperse<T>(this: T[], mkT: (ix: number) => T): T[] {
    return this.reduce((acc: T[], d, ix) => [...acc, mkT(ix), d], []).slice(1);
  };
}
```

**Expected Result**

The `interface` line should stay as it is, because the code won't properly extend `Array` if `type` is used instead.

**Actual Result**

`Interface` got autofixed into `type`, breaking the code.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.5.0` |
| `@typescript-eslint/parser`        | `4.5.0` |
| `TypeScript`                       | `4.0.3` |
| `ESLint`                           | `7.12.0` |

### PR DESCRIPTION
**Pull request by ddubrava**
fixes #2707

### CODE REVIEW

File: packages/eslint-plugin/src/rules/consistent-type-definitions.ts [hunk 1]
```diff
@@ -68,7 +68,9 @@ export default util.createRule({
           });
         }
       },
-      TSInterfaceDeclaration(node): void {
+      ':not(TSModuleDeclaration > TSModuleBlock) > TSInterfaceDeclaration'(
+        node: TSESTree.TSInterfaceDeclaration,
+      ): void {
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/consistent-type-definitions.ts:73]: this will stop the rule reporting at all when an interface is within a module declaration.
Which is too wide of a change.

Instead, we still want to report on interface within a module declaration - but we want to just no automatically fix it if and only if it's within a `declare global`

**Review by bradzacher — CHANGES_REQUESTED** [review]

File: packages/eslint-plugin/src/rules/consistent-type-definitions.ts (hunk 1 above)
Comment (ddubrava) [reply packages/eslint-plugin/src/rules/consistent-type-definitions.ts:73]: What's the manual fix for that case?

Comment (bradzacher) [reply packages/eslint-plugin/src/rules/consistent-type-definitions.ts:73]: the manual fix in that case would be for the engineer to review the lint and disable it in that case.

it's impossible for us to tell exactly what the intentions are so we have three options:
- report with a fixer
  - this is bad because it means we can break the user's code.
- do nothing
  - this isn't great because it means that the user can easily create code which should be marked as invalid.
  - it's impossible to tell if the code was written invalidly because it HAD to be this way, or if the author just wrote it wrong.
- report without a fixer
  - this is a best-of-both worlds.
  - if the code is actually invalid - the user can fix it
  - if it's an edge case - the user can suppress the lint rule to show it's intentionally written this way.

> I thought it's impossible to use the type within a declare in the case so we have to turn off it completely

Nope - it's perfectly acceptable to use `type` declarations or `interface` declarations.
In some cases the latter is better as it will allow specifically for augmentation via declaration merging.

**Comment by ddubrava** [comment]
Should we handle only `declare global {}` or `global {}` is also shouldn't be fixed? And what about not global declarations?

File: packages/eslint-plugin/src/rules/consistent-type-definitions.ts [hunk 2]
```diff
@@ -31,6 +32,21 @@ export default util.createRule({
...
     const sourceCode = context.getSourceCode();
 
+    function isNodeGrandparentGlobalModuleDeclaration(
+      node: TSESTree.Node,
+    ): boolean {
+      if (
+        node.parent?.type === AST_NODE_TYPES.TSModuleBlock &&
+        node.parent.parent?.type === AST_NODE_TYPES.TSModuleDeclaration &&
+        node.parent.parent?.declare &&
+        node.parent.parent?.global
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/consistent-type-definitions.ts:42]: instead of just looking at the grandparent - we could instead look at all the ancestors so we can catch cases like:
```ts
declare global {
  namespace Foo {
    interface Bar {}
  }
}
```

`context.getAncestors()` will return you an array and you can traverse it from the start to go from the highest parent.

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for this!
