### PR TITLE
fix(eslint-plugin): [no-deprecated] report on imported deprecated variables

### LINKED ISSUE #9946: Bug: [no-deprecated] Classes created via dependency injection are not reported
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Angular contains some classes that are deprecated. Because you access these types using dependency injection and don't create an instance of them yourself, the `no-deprecated` rule will not report that they are deprecated.

For example, given this code:
```ts
import { inject, ComponentFactoryResolver } from '@angular/core';

const f1: ComponentFactoryResolver = new ComponentFactoryResolver();

const f2: ComponentFactoryResolver = inject(ComponentFactoryResolver);
```

The usage of `ComponentFactoryResolver` on line 3 (the `f1` instance) is reported at column 42 (`new ComponentFactoryResolver`). However, that is not how you would use this type. Instead, you would get an instance of `ComponentFactoryResolver` using dependency injection, either by using the `inject` function (the `f2` instance), or by using a constructor parameter like 
```ts
constructor(factory: ComponentFactoryResolver) {}
```

Because of this style of usage, the `no-deprecated` rule does not report any usage of deprecated classes.

### Reproduction Repository Link

https://github.com/reduckted/repro-tseslint-no-deprecated

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript-eslint`     | `8.4.0` |
| `TypeScript`                           | `5.5.4` |
| `ESLint`                               | `9.9.1` |
| `node`                                 | `22.2.0` |

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9946
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

JSDoc tags are attached to the original symbols, not to symbol aliases. But symbols of imported variables are aliases, so we need to resolve those aliases, that's it!

### CODE REVIEW

**Review by kirkwaiblinger — APPROVED** [review]

**Comment by auvred** [comment]
@kirkwaiblinger Sorry, I should turn this PR into draft, but I forgot to do it. One false negative failure in `utils:lint` showed me a case that required me to redo all the logic with aliases almost from scratch :(

File: packages/eslint-plugin/src/rules/no-deprecated.ts [hunk 1]
```diff
@@ -34,6 +34,42 @@ export default createRule({
...
     const checker = services.program.getTypeChecker();
 
+    // Deprecated jsdoc tags can be added on some symbol alias, e.g.
+    //
+    // export { /** @deprecated */ foo }
+    //
+    // When we import foo, its symbol is an alias of the exported foo (the one
+    // with the deprecated tag), which is itself an alias of the original foo.
+    // Therefore, we carefully go through the chain of aliases and check each
+    // immediate alias for deprecated tags
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/no-deprecated.ts:44]: [Praise] This was very useful, thanks 😄

**Review by JoshuaKGoldberg — APPROVED** [review]
Looks great to me! Super thorough tests, nicely done. 👏
