### PR TITLE
fix(typescript-estree): use token type of `Numeric` instead of `Identifier` for bigint literals

### LINKED ISSUE #11018: Bug: The token type of a BigInt literal should be Numeric instead of Identifier
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### Playground Link

https://typescript-eslint.io/play/#ts=5.6.2&showAST=es&fileType=.tsx&code=AwOyA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=true

### Repro Code

```TypeScript
0n
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

`.ast.tokens[0].type` should be `Numeric`, aligning to the espree behaviour.

### Actual Result

`.ast.tokens[0].type` is `Identifier`

### Additional Info

_No response_

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | 8.28.0 |

### PR DESCRIPTION
**Pull request by ronami**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11018
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This PR addresses #11018 and changes the token type to use `Numeric` rather than `Identifier`. I added a test to cover this since no tests failed by making this change.

### CODE REVIEW

File: packages/typescript-estree/src/node-utils.ts [hunk 1]
```diff
@@ -527,6 +527,7 @@ export function getTokenType(
 
   switch (token.kind) {
     case SyntaxKind.NumericLiteral:
+    case SyntaxKind.BigIntLiteral:
```
Comment (JLHwung) [inline packages/typescript-estree/src/node-utils.ts:530]: Since we are here, could you also take a look at https://github.com/typescript-eslint/typescript-eslint/issues/11022? Many thanks.

**Review by bradzacher — APPROVED** [review]

File: packages/typescript-estree/src/node-utils.ts (hunk 1 above)
Comment (ronami) [reply packages/typescript-estree/src/node-utils.ts:530]: https://github.com/typescript-eslint/typescript-eslint/pull/11023 🎉
