### PR TITLE
fix(eslint-plugin): [no-unnecessary-condition] improve optional chain handling 2 - electric boogaloo

### LINKED ISSUE #1977: [no-unnecessary-condition] optional chaining clarification
i just want some clarification on this bullet point in https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-condition.md .
> Base values of optional chain expressions

 does that mean it will only check the first value in a chain?
e.g. `foo?.bar`
or will it continue to check down the chain but stop at qux?
e.g. `foo?.bar?.baz?.qux`

### PR DESCRIPTION
**Pull request by yeonjuan**
Fixes #1977 

#1977 occurs when member expression's nullable type is originated from the previous node.
So, I changed it to check whether a member expression's nullable type is origin from its previous.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-condition.ts [hunk 1]
```diff
@@ -426,6 +427,48 @@ export default createRule<Options, MessageId>({
...
+    //  ```
+    function isNullableOriginFromPrev(
+      node: TSESTree.MemberExpression | TSESTree.OptionalMemberExpression,
+    ): boolean {
+      const prevType = getNodeType(node.object);
+      const property = node.property;
+      if (prevType.isUnion() && isIdentifier(property)) {
+        const ownPropertyType = prevType.types
+          .map(type => checker.getTypeOfPropertyOfType(type, property.name))
+          .find(t => t);
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-unnecessary-condition.ts:446]: Mapping over the types in the union isn't quite right, and will cause issues in the following case. The checker API is smart enough to analyse unions to get the type of a property on that union.

```ts
interface Foo {
    a: number;
}

interface Bar {
    a: string | null;
}

declare const x: Foo | Bar;
```

```bash
# type = type of x;
$ type.types.map(t => checker.typeToString(checker.getTypeOfPropertyOfType(t, 'a')))

> ["number", "string | null"]
```
Eg with your current logic, this case will just check the `number` case, and will thus false-positive on the property.

If you instead just ask for the property on the union type itself:
```bash
# type = type of x;
$ checker.typeToString(checker.getTypeOfPropertyOfType(type, 'a'))

> "string | number | null"
```
It will work as expected. However if for some reason the base type is nullish, you need to also scrub the null from the union first:
```ts
interface Foo {
    a: number;
}

interface Bar {
    a: string | null;
}

declare const x: {t: Foo | Bar} | null;

x?.t.a;
```
```bash
# type = type of x?.t;
$ nonNullType = checker.getNonNullableType(type)
$ checker.typeToString(checker.getTypeOfPropertyOfType(nonNullType, 'a'))

> "string | number | null"
```

Comment (yeonjuan) [reply packages/eslint-plugin/src/rules/no-unnecessary-condition.ts]: Thanks for the review. I'll change it soon :)
