### PR TITLE
test(eslint-plugin): [no-misused-promises] add test cases for spread args

### LINKED ISSUE #5744: Bug: [no-misused-promises] An array of promises passed with spread (...args) syntax is not checked
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&code=GYVwdgxgLglg9mABBBBnEBbApgCgHQED6EAhgDZkBGJEA1qgFyICCATqyQJ4A8OAlIgC8APkQA3ODAAmwvkwnTEAb0QBfAFDqyWKMkqohiANr8hogAqs4GGKix5WWVHDJjcUViCx8ANIlMiiJbWtvaOzq7unt4AugDc6ihg6Nj4BBD6fEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oFtLlZkiACa1i0Dr0GoMkRNHHRI4MAF8QKoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
function consume(..._callbacks: Array<() => void>): void { }

let cbs = [() => Promise.resolve(true), () => Promise.resolve(true)];
consume(...cbs)
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-misused-promises": "error"
  },
};
```

### tsconfig

_No response_

### Expected Result

I expected that the 4th line should report "Promise returned in function argument where a void return was expected.", just as if I manually called the function with each value from the array (`consume(cbs[0], consume(cbs[1])`)

### Actual Result

There was no error reported on the fourth line.

### Additional Info

Handling of 'rest' parameters is implemented in https://github.com/typescript-eslint/typescript-eslint/pull/5731 . However, support for an explicit 'spread' argument still needs to be added.

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.39.0` |
| `@typescript-eslint/parser` | `5.39.0` |
| `TypeScript` | `4.8.4` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5744 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Implements the action items detailed in https://github.com/typescript-eslint/typescript-eslint/issues/5744#issuecomment-1947717802.

Only functional change is to add test cases for the concern in the issue.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-misused-promises.ts [hunk 1]
```diff
@@ -674,10 +672,5 @@ function isVoidReturningFunctionType(
  */
 function returnsThenable(checker: ts.TypeChecker, node: ts.Node): boolean {
   const type = checker.getApparentType(checker.getTypeAtLocation(node));
-
-  if (anySignatureIsThenableType(checker, node, type)) {
-    return true;
-  }
-
-  return false;
+  return anySignatureIsThenableType(checker, node, type);
```
Comment (auvred) [inline packages/eslint-plugin/src/rules/no-misused-promises.ts:675]: https://github.com/typescript-eslint/typescript-eslint/pull/8534 is going to add support for unions. And it looks like it's going to make changes exactly on these very lines. So, to avoid merge conflicts, what do you think about reverting these changes in favor of https://github.com/typescript-eslint/typescript-eslint/pull/8534

Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/no-misused-promises.ts]: makes sense! reverting and resolving conflicts

**Review by auvred — APPROVED** [review]
:rocket: LGTM!

Aside: since this PR doesn't make any bug fixes, I think we should rename it from `fix(eslint-plugin): ... ` to `test(eslint-plugin): ... `. What do you think?
