### PR TITLE
fix(eslint-plugin): added safe getTypeOfPropertyOfType wrapper

### LINKED ISSUE #2143: [prefer-readonly-parameter-types] unique symbols as interface keys causes eslint to crash
**Repro**
`tsconfig.json`
```JSON
{}
```

`package.json`
```JSON
{
  "name": "prefer-readonly-parameter-types-test",
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "3.0.2",
    "@typescript-eslint/parser": "3.0.2",
    "eslint": "7.1.0",
    "typescript": "3.9.3"
  }
}
```

`.eslintrc.json`
```JSON
{
    "root": true,
    "parser": "@typescript-eslint/parser",
    "plugins": ["@typescript-eslint"],
    "parserOptions": {
        "project": ["tsconfig.json"]
    },
    "rules": {
        "@typescript-eslint/prefer-readonly-parameter-types": "error"
    }
}
```

`test.ts`
```
const sym = Symbol('sym');

interface MyInterface {
    [sym]: number;
}

const willCrash = (foo: Readonly<MyInterface>) => {};
```

Test command: `eslint . --ext .ts`

**Expected Result**
`eslint . --ext .ts` should not crash (successfully lint code) and for the given minimal rule set above, should not return any errors.

**Actual Result**
```
Oops! Something went wrong! :(

ESLint: 7.1.0

Error: Non-null Assertion Failed: Expected to find a property "__@sym@10" for the type.
Occurred while linting <ROOT>/test.ts:7
    at Object.nullThrows (<ROOT>/node_modules/@typescript-eslint/eslint-plugin/dist/util/nullThrows.js:23:15)
    at isTypeReadonlyObject (<ROOT>/node_modules/@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly.js:83:37)
    at isTypeReadonlyRecurser (<ROOT>/node_modules/@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly.js:128:30)
    at Object.isTypeReadonly (<ROOT>/node_modules/@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly.js:138:13)
    at ArrowFunctionExpression, FunctionDeclaration, FunctionExpression, TSCallSignatureDeclaration, TSConstructSignatureDeclaration, TSDeclareFunction, TSEmptyBodyFunctionExpression, TSFunctionType, TSMethodSignature (<ROOT>/node_modules/@typescript-eslint/eslint-plugin/dist/rules/prefer-readonly-parameter-types.js:79:45)
    at <ROOT>/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (<ROOT>/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (<ROOT>/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (<ROOT>/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
```

**Additional Info**
(I'll save the noise of dumping the debug output, but can provide if requested)

The error is being emitted here: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/util/isTypeReadonly.ts#L104-L105

(So I don't think it is _explicitly_ related to `prefer-readonly-parameter-types`, but it is one that successfully recreates the error).

My understanding is the purpose of this check is to ensure that properties being referenced are defined in the root type.

In my case, the only property is a "unique symbol" that typescript has aliased as `__@sym@10`.
So `property.getName()` => `__@sym@10`.

I can't find _any_ documentation for Typescript's checker, besides the [raw source code](https://raw.githubusercontent.com/Microsoft/TypeScript/master/src/compiler/checker.ts) but that `getTypeOfPropertyOfType` on checker is defined as a higher order function `getTypeOfPropertyOfType: (type, name) => getTypeOfPropertyOfType(type, escapeLeadingUnderscores(name)),`

Note the `escapeLeadingUnderscores` which basically transforms `__@sym@10` => `___@sym@10` (three underscores at start). _That_ key is _not_ present in the `type.members` map, so it returns undefined and results in a thrown error.

Due to typescript's handling of double underscore, this _could_ be a typescript error, but the code compiles and is valid in typescript, so I imagine there is a correct way around this. The decision to prepend double underscore and not pre-escape the value feels like a conscious decision on their part.

All I've been able to do so far is understand _why_ the error is happening... I can't claim I really understand the logic behind the code design, or an alternative solution.

e.g. is there an alternative to `getTypeOfPropertyOfType` that handles this edge case? Or is that call even necessary to perform readonly logic?

I'd be happy to help with a PR, but I as I said I can't find any decent documentation for Typescript's checker, so I don't even know where to start.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.0.2` |
| `@typescript-eslint/parser`        | `3.0.2` |
| `TypeScript`                       | `3.9.3` |
| `ESLint`                           | `7.1.0` |
| `node`                             | `14.3.0` |
| `npm`                              | `6.14.5` |

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #2143. A quick find-all on `getTypeOfPropertyOfType` showed that the bug might also be able to pop up in `no-unnecessary-condition` as well.

### CODE REVIEW

**Comment by bradzacher** [comment]
We should add a lint rule for this to warn against using the method directly.

Could expand this internal lint rule to cover it:

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts

File: packages/eslint-plugin/src/util/propertyTypes.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+    `property "${propertyName}"`,
+    'type',
+  );
+
+  return propertyName.startsWith('__')
+    ? checker.getDeclaredTypeOfSymbol(
+        nullThrows(
+          type
+            .getProperties()
+            .find(property => property.escapedName === propertyName),
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/util/propertyTypes.ts:20]: Heh, this worked for the `prefer-readonly-parameter-types` rule, but is failing for `no-unnecessary-conditions` ([link](https://github.com/typescript-eslint/typescript-eslint/pull/2567/checks?check_run_id=1115991098))... will need to investigate.

Tomorrow! 😪

**Comment by JoshuaKGoldberg** [comment]
TBD whether this original approach works, but it would also be nice to not use an internal TypeScript compiler API... I'd be interested in looking at that too.

File: packages/eslint-plugin/src/util/propertyTypes.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/util/propertyTypes.ts]: Right right, the return type of the general function is intended to be `ts.Type | undefined`, and only one of the two consumers wants a `nullThrows` around it.

File: packages/eslint-plugin/src/util/propertyTypes.ts [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+
+export function getTypeOfPropertyOfName(
+  checker: ts.TypeChecker,
+  type: ts.Type,
+  name: string,
+  escapedName?: ts.__String,
+): ts.Type | undefined {
+  // Most names are directly usable in the checker and aren't different from escaped names
+  if (!escapedName || !name.startsWith('__')) {
+    return checker.getTypeOfPropertyOfType(type, name);
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/util/propertyTypes.ts:11]: This is the content of TypeScript's source for `getTypeOfPropertyOfType`:

```ts
// Return the type of the given property in the given type, or undefined if no such property exists
function getTypeOfPropertyOfType(type: Type, name: __String): Type | undefined {
    const prop = getPropertyOfType(type, name);
    return prop ? getTypeOfSymbol(prop) : undefined;
}
```

I can switch this file to use the same strategy if directed.

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for fixing this!
