### PR TITLE
fix(typescript-estree): forbid invalid modifier in object expression

### LINKED ISSUE #11688: Enhancement: Forbid invalid modifiers in object properties
### Before You File a Proposal Please Confirm You Have Done The Following...

- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [x] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### My proposal is suitable for this project

- [x] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Similar to https://github.com/typescript-eslint/typescript-eslint/issues/11655, but for properties.

```ts
({abstract property: 1});
({async property: 1});
({declare property: 1});
({export property: 1});
({override property: 1});
({private property: 1});
({protected property: 1});
({public property: 1});
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by fisker**
## PR Checklist

- [x] Addresses an existing open issue: fixes #11688
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

File: packages/typescript-estree/src/check-modifiers.ts [hunk 1]
```diff
@@ -128,6 +128,15 @@ function nodeHasIllegalDecorators(
   );
 }
 
+function getModifiers(node: ts.Node): ts.Modifier[] {
+  return (
+    // @ts-expect-error intentional to access `node.modifiers` instead of `ts.getModifiers(node)` to access all modifiers
+    ((node.modifiers as ts.Modifier[]) ?? []).filter(
```
Comment (fisker) [inline packages/typescript-estree/src/check-modifiers.ts]: @bradzacher `ts.getModifiers()` can't access `declare` modifier in `({declare a=1})`, is it fine to access `node.modifiers` directly?

https://github.com/typescript-eslint/typescript-eslint/pull/11689#discussion_r2416713772

File: packages/typescript-estree/src/check-modifiers.ts [hunk 2]
```diff
@@ -128,6 +128,15 @@ function nodeHasIllegalDecorators(
...
 }
 
+function getModifiers(node: ts.Node): ts.Modifier[] {
+  return (
+    // @ts-expect-error intentional to access `node.modifiers` instead of `ts.getModifiers(node)` to access all modifiers
+    ((node.modifiers as ts.Modifier[] | undefined) ?? []).filter(
+      (modifier): modifier is ts.Modifier => !ts.isDecorator(modifier),
+    )
+  );
+}
```
Comment (bradzacher) [inline packages/typescript-estree/src/check-modifiers.ts:138]: question -- why did you do this instead of using the existing `getModifiers` function?

Comment (fisker) [reply packages/typescript-estree/src/check-modifiers.ts:138]: https://github.com/typescript-eslint/typescript-eslint/pull/11931#discussion_r2664342563

File: packages/typescript-estree/src/check-modifiers.ts (hunk 1 above)
Comment (bradzacher) [reply packages/typescript-estree/src/check-modifiers.ts]: https://typescript-eslint.io/play/#ts=5.9.3&fileType=.tsx&code=BQbwBAJgpgxgNgQwE5TAsBeMBGMBfASgCgg&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

looks like we currently have a parser error on that code.
so we probably don't need to do this?

Comment (fisker) [reply packages/typescript-estree/src/check-modifiers.ts]: Mistake `({declare a:1})` (colon)

Comment (fisker) [reply packages/typescript-estree/src/check-modifiers.ts]:
```
p = ts.createSourceFile('foo.ts', '({async a:1})').statements[0].expression.expression.properties[0]
ts.getModifiers(p)
undefined
```

Comment (bradzacher) [reply packages/typescript-estree/src/check-modifiers.ts]: the problem is that this property was purposely removed from the TS API types in TS4.9
accessing it is, ultimately, sketchy -- which is why the `getModifiers` util was created.

Should we just ignore these entirely if TS is choosing to not give us an official way to access them?

Comment (fisker) [reply packages/typescript-estree/src/check-modifiers.ts]: What is the worst result that can be? TypeScript removes `.modifiers`?

How about this, switch back to `ts.getModifiers()`, but make an exception for object properties, if `.modifiers` is removed one day, the syntax check for object properties just silently ignore them. What do you think?

File: packages/typescript-estree/src/check-modifiers.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply packages/typescript-estree/src/check-modifiers.ts:138]: @bradzacher WDYT?

**Comment by fisker** [comment]
@JoshuaKGoldberg https://github.com/typescript-eslint/typescript-eslint/pull/11931#discussion_r2666662391 not addressed.

**Comment by fisker** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/12027

**Comment by JoshuaKGoldberg** [comment]
Ah gotcha, I misinterpreted. thanks!
