### PR TITLE
fix(rule-tester): fix a phantom dependency on the "semver" package 

### LINKED ISSUE #8259: Bug: DependencyConstraint.d.ts fails to compile due to phantom dependency on "semver"
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

rule-tester

### Repro Code

```TypeScript
Try to compile an ESLint plugin project with this code and `skipLibCheck: false` in **tsconfig.json**:

import { RuleTester } from '@typescript-eslint/rule-tester';
```

### Expected Result

The code should compile without errors.

### Actual Result

`tsc` reports a build failure like this:
```
../../common/temp/node_modules/.pnpm/@typescript-eslint+rule-tester@6.19.0_@eslint+eslintrc@3.0.0_eslint@8.7.0_typescript@5.3.3/node_modules
/@typescript-eslint/rule-tester/dist/types
/DependencyConstraint.d.ts:1:35 - error TS7016: Could not find a declaration file for module 'semver'. 'C:/Git/rushstack/common/temp/node_modules/.pnpm/semver@7.5.4/node_modules/semver/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/semver` if it exists or add a new declaration (.d.ts) file containing `declare module 'semver';`

1 import type { RangeOptions } from 'semver';
                                    ~~~~~~~~


Found 1 error in ../../common/temp/node_modules/.pnpm/@typescript-eslint+rule-tester@6.19.0_@eslint+eslintrc@3.0.0_eslint@8.7.0_typescript@5.3.3/node_modules/@typescript-eslint/rule-tester/dist/types/DependencyConstraint.d.ts:1
```

The problem is caused by this code:
https://github.com/typescript-eslint/typescript-eslint/blob/7c673a146d26d4360a25638f901a3c329bcca8c4/packages/rule-tester/src/types/DependencyConstraint.ts#L1-L5

It imports types from `"semver"`, but that dependency is not declared in **package.json**.

Using an old-fashioned [installation model](https://lfx.rushstack.io/pages/concepts/install_models/) such as NPM or Yarn Classic, then the `semver` package will likely get "hoisted" allowing the compiler to load typings from a `semver` folder installed to satisfy some other unrelated package.  However with a modern installation model such as Yarn Plug'n'Play or PNPM, the import will fail; this is more correct behavior, because dependency versions should be explicitly specified rather than fished out of a **node_modules** folder with no idea what version you will get.

 
### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `6.19.0` |
| `TypeScript`                           | `5.3.3` |

### PR DESCRIPTION
**Pull request by octogonz**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8259
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
The obvious fix would be to declare `@types/semver` as a dependency or peer dependency of `@typescript-eslint/rule-tester`.

However the relied upon interface is tiny, so we can simply inline in the **DependencyConstraint.ts** source file.

## Validation

I confirmed that with this change, my project compiles successfully.

### CODE REVIEW

File: packages/rule-tester/src/types/DependencyConstraint.ts [hunk 1]
```diff
@@ -1,4 +1,11 @@
-import type { RangeOptions } from 'semver';
+// `Options` and `RangeOptions` are defined in the 'semver' package.
+// We redeclare them here to avoid a peer dependency on that package:
+export interface Options {
+  loose?: boolean | undefined;
+}
+export interface RangeOptions extends Options {
+  includePrerelease?: boolean | undefined;
```
Comment (JoshuaKGoldberg) [inline packages/rule-tester/src/types/DependencyConstraint.ts:7]: [Style] I'm not a huge fan of general-purpose names like `Options`, especially when they don't pertain to the main export of a package. Since it's just two properties I think it's reasonable to have a single interface exported. Is there a strong reason to keep `Options` standalone?

```suggestion
export interface RangeOptions extends Options {
  includePrerelease?: boolean | undefined;
  loose?: boolean | undefined;
```

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, thanks for the issue & fix! I agree that two properties is a reasonably small enough size to just inline an interface like this.

Just the one style suggestion, then I think we're good to merge. WDYT?

File: packages/rule-tester/src/types/DependencyConstraint.ts (hunk 1 above)
Comment (octogonz) [reply packages/rule-tester/src/types/DependencyConstraint.ts:7]: No reason -- these names are verbatim from `@types/semver`.

We can condense it.

**Review by bradzacher — APPROVED** [review]

**Review by bradzacher — CHANGES_REQUESTED** [review]
```
src/types/DependencyConstraint.ts(3,39): error TS2304: Cannot find name "Options".
```

**Comment by JoshuaKGoldberg** [comment]
I had some spare time today and was going through the PR backlog. Please forgive me for jumping in and applying the fix 😄. I was excited to get our open PRs number down...

**Review by JoshuaKGoldberg — APPROVED** [review]
🚢
