### PR TITLE
fix(eslint-plugin): [no-use-before-define] correctly handle typeof type references

### LINKED ISSUE #2572: [no-use-before-define] False positive when using the `typeof` keyword
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-use-before-define": [
        "warn",
        {
            "classes": false,
            "ignoreTypeReferences": true
        }
    ]
  }
}
```

```TS
interface QuestionOptions
{
    type: typeof MyQuestion.TypeName;
}

class MyQuestion
{
    public static readonly TypeName = "my-custom-question";
}
```

**Expected Result**
No error should be reported as classes and type-references are ignored.

**Actual Result**
An error is reported:
```
'MyQuestion' was used before it was defined. (@typescript-eslint/no-use-before-define)
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.1.2-alpha.3` |
| `@typescript-eslint/parser`        | `4.1.1` |
| `TypeScript`                       | `4.0.2` |
| `ESLint`                           | `7.9.0` |
| `node`                             | `12.18.3` |

### PR DESCRIPTION
**Pull request by Drakota**
Fixes #2572 

The `no-use-before-define` rule wasn't taking into account type reference that comes from values prefixed by the `typeof` operator.

Thank you @bradzacher for your help 🙂

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-use-before-define.ts [hunk 1]
```diff
@@ -92,6 +92,16 @@ function isOuterVariable(
   );
 }
 
+/**
+ * Checks whether or not a given reference is a type reference.
+ */
+function isTypeReference(reference: TSESLint.Scope.Reference): boolean {
+  return (
+    reference.isTypeReference ||
+    reference.identifier.parent?.parent?.type === AST_NODE_TYPES.TSTypeQuery
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-use-before-define.ts:101]: almost! but this will only match one case.

We need to match all of these cases, and more:

- `typeof a`
- `typeof a.b`
- `typeof a.b.c`

Instead an easier way to do this would be with a loop.
Based on the defined types for `TSTypeQuery`, we know that the `exprName` will either be an `Identifier` or a `TSQualifiedName`.
https://github.com/typescript-eslint/typescript-eslint/blob/d7dc108580cdcb9890ac0539e7223aedbff4a0ed/packages/types/src/ts-estree.ts#L1669-L1672

Based on the defined types for `TSQualifiedName`, we know the left will always be an `Identifier` or a `TSQualifiedName`.
https://github.com/typescript-eslint/typescript-eslint/blob/d7dc108580cdcb9890ac0539e7223aedbff4a0ed/packages/types/src/ts-estree.ts#L1572-L1576

This means we can simply loop and look at the parents
The reason I gave you the above is it'll help you constrain the loop so it won't iterate forever

File: packages/eslint-plugin/tests/rules/no-use-before-define.test.ts [hunk 2]
```diff
@@ -219,7 +219,29 @@ type Foo = string | number;
...
+      `,
+      options: [{ ignoreTypeReferences: true }],
+    },
+    {
+      code: `
+const foo = 2;
 
+interface Bar {
+  type: typeof foo;
+}
```
Comment (bradzacher) [inline packages/eslint-plugin/tests/rules/no-use-before-define.test.ts:241]: This test is passing because `foo` is in fact defined before it's used, not because of your changes.

If you move `foo` beneath the `interface`, I believe this test will fail right now.

File: packages/eslint-plugin/tests/rules/no-use-before-define.test.ts [hunk 3]
```diff
@@ -219,7 +219,29 @@ type Foo = string | number;
...
+      `,
+      options: [{ ignoreTypeReferences: true }],
+    },
     // https://github.com/bradzacher/eslint-plugin-typescript/issues/141
     {
       code: `
```
Comment (bradzacher) [inline packages/eslint-plugin/tests/rules/no-use-before-define.test.ts:247]: It would be good to add a few negative tests as well:
Use the same code samples, but with `ignoreTypeReferences: false`.

**Review by bradzacher — CHANGES_REQUESTED** [review]
You're most of the way there!
A few comments.
Thanks for working on this.

File: packages/eslint-plugin/tests/rules/no-use-before-define.test.ts (hunk 2 above)
Comment (Drakota) [reply packages/eslint-plugin/tests/rules/no-use-before-define.test.ts]: Dang it 😅
I didn't think of looping the first time because this test was passing and thought maybe the `TSTypeQuery` was always at the same depth, but the test was passing for this reason.

I've made the necessary changes.

File: packages/eslint-plugin/tests/rules/no-use-before-define.test.ts (hunk 3 above)
Comment (Drakota) [reply packages/eslint-plugin/tests/rules/no-use-before-define.test.ts:261]: Added!

File: packages/eslint-plugin/src/rules/no-use-before-define.ts (hunk 1 above)
Comment (Drakota) [reply packages/eslint-plugin/src/rules/no-use-before-define.ts]: Fixed!

File: packages/eslint-plugin/src/rules/no-use-before-define.ts [hunk 4]
```diff
@@ -219,7 +242,7 @@ export default util.createRule<Options, MessageIds>({
       variable: TSESLint.Scope.Variable,
       reference: TSESLint.Scope.Reference,
     ): boolean {
-      if (reference.isTypeReference && options.ignoreTypeReferences) {
+      if (options.ignoreTypeReferences && isTypeReference(reference)) {
```
Comment (Drakota) [inline packages/eslint-plugin/src/rules/no-use-before-define.ts:245]: I've reversed the conditions, if `options.ignoreTypeReferences` is false we'll just shortcircuit out of this and prevent unnecessary computation.

File: packages/eslint-plugin/src/rules/no-use-before-define.ts [hunk 5]
```diff
@@ -92,6 +92,29 @@ function isOuterVariable(
...
+ * Recursively checks whether or not a given reference has a type query declaration among it's parents
+ */
+function referenceContainsTypeQuery(node: TSESTree.Node): boolean {
+  if (node.type === AST_NODE_TYPES.TSTypeQuery) {
+    return true;
+  } else if (!node.parent) {
+    return false;
+  }
+
+  return referenceContainsTypeQuery(node.parent);
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-use-before-define.ts:105]: Almost there!

We can constrain this a little more so we don't recursively traverse up the whole tree unnecessarily.
[We know that the node must always be either be a `TSQualifiedName`, `Identifier` or `TSTypeQuery`](https://github.com/typescript-eslint/typescript-eslint/pull/2623#discussion_r498631601).

```ts
switch (node.type) {
  case AST_NODE_TYPES.TSTypeQuery:
    return true;

  case AST_NODE_TYPES.TSQualifiedName:
  case AST_NODE_TYPES.Identifier:
    return referenceContainsTypeQuery(node.parent);

  default:
    // if we find a different node, there's no chance that we're in a TSTypeQuery
    return false;
}
```

Comment (Drakota) [reply packages/eslint-plugin/src/rules/no-use-before-define.ts]: I see! I wasn't sure of what you meant in your first comment.
I've changed it.

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for your contribution!

**Comment by Drakota** [comment]
Thank you for guiding me through this @bradzacher, I appreciate it 🙂
