### PR TITLE
fix(eslint-plugin): [no-unnecessary-type-assertion] fix TSNonNullExpression fixer

### LINKED ISSUE #8987: Docs: Add links to npm packages in typescript-eslint/packages/*
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I just noticed that package docs pages like https://typescript-eslint.io/packages/eslint-plugin never actually link to the npm packages like https://www.npmjs.com/package/@typescript-eslint/eslint-plugin. It'd be a nice convenience for them to add that link.

Maybe, the common kind of npm badge image a lot of projects use, like from shields.io? Note that we should self-host the image (i.e. have a React component) so we don't take a dependency on the external service.

### Affected URL(s)

https://typescript-eslint.io/packages/*

### LINKED ISSUE #9897: Bug: [no-unnecessary-type-assertion] fixer produces incorrect code for ternary operator in parenthesis
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.4&fileType=.tsx&code=MYewdgzgLgBAhjAvDARCg3AWAFCkrAIwC4ZoAnASzAHMYAfGAVzABMBTAMyrZaRgAoEAfiatO3XiTgBKAITogA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const a = "";
const b: string | undefined = (a ? undefined : a)!;
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-unnecessary-type-assertion": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Run fixer on line 2 should produce `const b: string | undefined = a ? undefined : a;`

### Actual Result

The fixer produces `const b: string | undefined = (a ? undefined : a;`, which is invalid code.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9897  
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Updates the fixer to remove the range of the `!` token.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts [hunk 1]
```diff
@@ -246,9 +254,7 @@ export default createRule<Options, MessageIds>({
           context.report({
             node,
             messageId: 'unnecessaryAssertion',
-            fix(fixer) {
-              return fixer.removeRange([node.range[1] - 1, node.range[1]]);
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts:250]: this fixer was valid, too. It just wasn't used in the other locations.

File: packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts [hunk 2]
```diff
@@ -294,12 +300,7 @@ export default createRule<Options, MessageIds>({
               context.report({
                 node,
                 messageId: 'contextuallyUnnecessary',
-                fix(fixer) {
-                  return fixer.removeRange([
-                    node.expression.range[1],
```
Comment (kirkwaiblinger) [inline packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts:299]: This is the buggy fixer

File: packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts (hunk 1 above)
Comment (kirkwaiblinger) [reply packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts:250]: (see also https://github.com/typescript-eslint/typescript-eslint/pull/8143#discussion_r1449164364)

**Review by JoshuaKGoldberg — APPROVED** [review]
💯
