### PR TITLE
fix(eslint-plugin): handle missing message IDs in eslint v5/v6

### LINKED ISSUE #2451: [no-unused-vars] TypeError: context.report() called with a messageId, but no messages were present in the rule metadata.
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```js
module.exports = {
  extends: [
    'react-app',
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
  ],
  rules: {
    '@typescript-eslint/no-unused-vars': [1, { argsIgnorePattern: '^_' }],
    '@typescript-eslint/explicit-function-return-type': 'off',
    'no-restricted-imports': [
      'error',
      {
        paths: [
          {
            name: 'styled-components',
            message: 'Please import from styled-components/macro.',
          },
        ],
        patterns: ['!styled-components/macro'],
      },
    ],
  },
};

```

```TS
// jest-styled-components.d.ts
declare namespace jest {
  interface Matchers<R> {
    toHaveStyleRule: import('jest-styled-components').jest.Matchers<
      R
    >['toHaveStyleRule'];
  }
}
```

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": ["src", "test"],
  "plugins": [
    {
      "name": "typescript-styled-plugin"
    }
  ]
}
```

**Expected Result**

No crash. The same configuration and file works fine in v3.10.1

**Actual Result**

After upgrading to v4.0.1
```
TypeError: context.report() called with a messageId, but no messages were present in the rule metadata.
Occurred while linting /Users/redacted/frontend/src/types/jest-styled-components.d.ts:1
    at /Users/redacted/frontend/node_modules/eslint/lib/linter/report-translator.js:317:23
    at Object.report (/Users/redacted/frontend/node_modules/eslint/lib/linter/linter.js:905:41)
    at TSModuleDeclaration (/Users/redacted/frontend/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars.js:124:33)
    at /Users/redacted/frontend/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/redacted/frontend/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/redacted/frontend/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/redacted/frontend/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/redacted/frontend/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/redacted/frontend/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
```

**Additional Info**

[typescript-eslint-debug.log](https://github.com/typescript-eslint/typescript-eslint/files/5152929/typescript-eslint-debug.log)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.0.1` |
| `@typescript-eslint/parser`        | `4.0.1` |
| `TypeScript`                       | `4.0.2` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.8.3` |

### PR DESCRIPTION
**Pull request by esetnik**
Fixes #2451

### CODE REVIEW

File: packages/eslint-plugin/src/rules/init-declarations.ts [hunk 1]
```diff
@@ -24,7 +24,12 @@ export default createRule<Options, MessageIds>({
       extendsBaseRule: true,
     },
     schema: baseRule.meta.schema,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      initialized:
+        "Variable '{{idName}}' should be initialized on declaration.",
+      notInitialized:
+        "Variable '{{idName}}' should not be initialized on declaration.",
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/init-declarations.ts:32]: this rule has been using message ids since 5.12.
I guess we should keep this alive until we drop v5.0.0 from the supported ranges.

File: packages/eslint-plugin/src/rules/keyword-spacing.ts [hunk 2]
```diff
@@ -17,7 +17,12 @@ export default util.createRule<Options, MessageIds>({
     },
     fixable: 'whitespace',
     schema: baseRule.meta.schema,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      expectedBefore: 'Expected space(s) before "{{value}}".',
+      expectedAfter: 'Expected space(s) after "{{value}}".',
+      unexpectedBefore: 'Unexpected space(s) before "{{value}}".',
+      unexpectedAfter: 'Unexpected space(s) after "{{value}}".',
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/keyword-spacing.ts:25]: this rule has been using message ids since 5.12.
I guess we should keep this alive until we drop v5.0.0 from the supported ranges.

File: packages/eslint-plugin/src/rules/lines-between-class-members.ts [hunk 3]
```diff
@@ -32,7 +32,10 @@ export default util.createRule<Options, MessageIds>({
     },
     fixable: 'whitespace',
     schema,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      never: 'Unexpected blank line between class members.',
+      always: 'Expected blank line between class members.',
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/lines-between-class-members.ts:38]: this rule has been using message ids since 5.12.
I guess we should keep this alive until we drop v5.0.0 from the supported ranges.

File: packages/eslint-plugin/src/rules/no-dupe-class-members.ts [hunk 4]
```diff
@@ -16,7 +16,9 @@ export default util.createRule<Options, MessageIds>({
       extendsBaseRule: true,
     },
     schema: baseRule.meta.schema,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      unexpected: "Duplicate name '{{name}}'.",
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-dupe-class-members.ts:21]: this rule has been using message ids since 4.17, so we don't need to fallback here.

File: packages/eslint-plugin/src/rules/no-empty-function.ts [hunk 5]
```diff
@@ -48,7 +48,9 @@ export default util.createRule<Options, MessageIds>({
       extendsBaseRule: true,
     },
     schema: [schema],
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      unexpected: 'Unexpected empty {{name}}.',
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-empty-function.ts:53]: this rule has been using message ids since 4.17, so we don't need to fallback here.

File: packages/eslint-plugin/src/rules/no-extra-parens.ts [hunk 6]
```diff
@@ -24,7 +24,9 @@ export default util.createRule<Options, MessageIds>({
     },
     fixable: 'code',
     schema: baseRule.meta.schema,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      unexpected: 'Unnecessary parentheses around expression.',
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-extra-parens.ts:29]: this rule has been using message ids since 4.17, so we don't need to fallback here.

File: packages/eslint-plugin/src/rules/no-extra-semi.ts [hunk 7]
```diff
@@ -16,7 +16,9 @@ export default util.createRule<Options, MessageIds>({
     },
     fixable: 'code',
     schema: baseRule.meta.schema,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      unexpected: 'Unnecessary semicolon.',
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-extra-semi.ts:21]: this rule has been using message ids since 4.17, so we don't need to fallback here.

File: packages/eslint-plugin/src/rules/no-magic-numbers.ts [hunk 8]
```diff
@@ -40,7 +40,10 @@ export default util.createRule<Options, MessageIds>({
         },
       },
     ],
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      useConst: "Number constants declarations must use 'const'.",
+      noMagic: 'No magic number: {{raw}}.',
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-magic-numbers.ts:46]: this rule has been using message ids since 5.12.
I guess we should keep this alive until we drop v5.0.0 from the supported ranges.

File: packages/eslint-plugin/src/rules/no-invalid-this.ts [hunk 9]
```diff
@@ -23,7 +23,9 @@ export default createRule<Options, MessageIds>({
       recommended: false,
       extendsBaseRule: true,
     },
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      unexpectedThis: "Unexpected 'this'.",
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-invalid-this.ts:28]: :+1: this rule has been using message ids since 7.0.

File: packages/eslint-plugin/src/rules/no-unused-expressions.ts [hunk 10]
```diff
@@ -19,7 +19,10 @@ export default util.createRule<Options, MessageIds>({
       extendsBaseRule: true,
     },
     schema: baseRule.meta.schema,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      unusedExpression:
+        'Expected an assignment or function call and instead saw an expression.',
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-unused-expressions.ts:25]: 👍 this rule has been using message ids since 7.0.

File: packages/eslint-plugin/src/rules/no-unused-vars.ts [hunk 11]
```diff
@@ -21,7 +21,9 @@ export default util.createRule<Options, MessageIds>({
       extendsBaseRule: true,
     },
     schema: baseRule.meta.schema,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      unusedVar: "'{{varName}}' is {{action}} but never used{{additional}}.",
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-unused-vars.ts:26]: 👍 this rule has been using message ids since 7.0.

File: packages/eslint-plugin/src/rules/no-useless-constructor.ts [hunk 12]
```diff
@@ -54,7 +54,9 @@ export default util.createRule<Options, MessageIds>({
       extendsBaseRule: true,
     },
     schema: baseRule.meta.schema,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      noUselessConstructor: 'Useless constructor.',
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-useless-constructor.ts:59]: 👍 this rule has been using message ids since 7.0.

File: packages/eslint-plugin/src/rules/quotes.ts [hunk 13]
```diff
@@ -20,7 +20,9 @@ export default util.createRule<Options, MessageIds>({
       extendsBaseRule: true,
     },
     fixable: 'code',
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      wrongQuotes: 'Strings must use {{description}}.',
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/quotes.ts:25]: 👍 this rule has been using message ids since 7.0.

File: packages/eslint-plugin/src/rules/semi.ts [hunk 14]
```diff
@@ -22,7 +22,10 @@ export default util.createRule<Options, MessageIds>({
     },
     fixable: 'code',
     schema: baseRule.meta.schema,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      missingSemi: 'Missing semicolon.',
+      extraSemi: 'Extra semicolon.',
+    },
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/semi.ts:28]: 👍 this rule has been using message ids since 7.0.

File: packages/eslint-plugin/src/rules/brace-style.ts [hunk 15]
```diff
@@ -20,7 +20,19 @@ export default createRule<Options, MessageIds>({
...
+      sameLineOpen:
+        'Opening curly brace appears on the same line as controlling statement.',
+      blockSameLine: 'Statement inside of curly braces should be on next line.',
+      nextLineClose:
+        'Closing curly brace does not appear on the same line as the subsequent block.',
+      singleLineClose:
+        'Closing curly brace should be on the same line as opening curly brace or on the line after the previous block.',
+      sameLineClose:
+        'Closing curly brace appears on the same line as the subsequent block.',
+    },
```
[the remark this answers is not in the document]
Comment (esetnik) [reply packages/eslint-plugin/src/rules/brace-style.ts]: reverted this change

File: packages/eslint-plugin/src/rules/dot-notation.ts [hunk 16]
```diff
@@ -43,7 +43,10 @@ export default createRule<Options, MessageIds>({
       },
     ],
     fixable: baseRule.meta.fixable,
-    messages: baseRule.meta.messages,
+    messages: baseRule.meta.messages ?? {
+      useDot: '[{{key}}] is better written in dot notation.',
+      useBrackets: '.{{key}} is a syntax error.',
+    },
```
[the remark this answers is not in the document]
Comment (esetnik) [reply packages/eslint-plugin/src/rules/dot-notation.ts]: reverted this change

**Comment by bradzacher** [comment]
missed a few of the v4 ones - the comments are (annoyingly) hidden under the fold by github

File: packages/eslint-plugin/src/rules/no-dupe-class-members.ts (hunk 4 above)
Comment (esetnik) [reply packages/eslint-plugin/src/rules/no-dupe-class-members.ts]: reverted this change

File: packages/eslint-plugin/src/rules/no-empty-function.ts (hunk 5 above)
Comment (esetnik) [reply packages/eslint-plugin/src/rules/no-empty-function.ts]: reverted this change

File: packages/eslint-plugin/src/rules/no-extra-parens.ts (hunk 6 above)
Comment (esetnik) [reply packages/eslint-plugin/src/rules/no-extra-parens.ts]: reverted this change

File: packages/eslint-plugin/src/rules/no-extra-semi.ts (hunk 7 above)
Comment (esetnik) [reply packages/eslint-plugin/src/rules/no-extra-semi.ts]: reverted this change
