### PR TITLE
fix(website): tsconfig is blank

### LINKED ISSUE #8781: Bug(website): tsconfig is blank
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

website

### Playground Link

https://typescript-eslint.io/play/#code=DYUwLgBAzgXNYCcCWA7A5gbgFBagOjAHsBVAB1JAQGEBDKEACgEoMg

### Expected Result

A TypeScript error should be reported: `Variable 's' is used before being assigned.`.

### Actual Result

No TypeScript error was reported.

### Additional Info

As first mentioned in #8659:
When arriving at the playground with _no hash_ (i.e. by clicking the `Playground` link in the header), the default `tsconfig` is `{ "compilerOptions": { "strictNullChecks": true } }`.
However, when arriving at the playground _with a hash that does not include_ the `tsconfig` parameter, the `tsconfig` is blank. This affects almost all `Open in Playground` links throughout the docs, because most of them do not include the `tsconfig` hash parameter.

### Versions

Latest live website

### PR DESCRIPTION
**Pull request by y-hsgw**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8781
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Set default values in tsconfig instead of blank.

### CODE REVIEW

File: packages/website/src/components/hooks/useHashState.ts [hunk 1]
```diff
@@ -95,7 +98,7 @@ const parseStateFromUrl = (hash: string): Partial<ConfigModel> | undefined => {
       code,
       fileType,
       eslintrc: eslintrc ?? '',
```
Comment (y-hsgw) [inline packages/website/src/components/hooks/useHashState.ts:100]: If this modification is appropriate, I was wondering if it would be okay to specify initialState for eslintrc as well?

```suggestion
      eslintrc: eslintrc ?? initialState.eslintrc,
```

Comment (JoshuaKGoldberg) [reply packages/website/src/components/hooks/useHashState.ts:100]: Yeah good call!

**Review by JoshuaKGoldberg — DISMISSED** [review]
Nicely done, what a clean change!

Both the PR tsconfig fix and the proposed eslintone look great to me. 🥳

File: packages/website/src/components/hooks/useHashState.ts (hunk 1 above)
Comment (y-hsgw) [reply packages/website/src/components/hooks/useHashState.ts]: Thank you for checking :) I've added it.
4f3b3dc

**Review by kirkwaiblinger — APPROVED** [review]
Thanks so much for doing this! This has been really annoying me for a while. 

threepio dance
