### PR TITLE
fix(eslint-plugin): [non-nullable-type-assertion-style] fix false positive when asserting to a generic type that might be nullish

### LINKED ISSUE #4512: [non-nullable-type-assertion-style] complains when casting to a type parameter that might be nullish
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/non-nullable-typer-assertion-style": "error"
  }
}
```

```TS
function first<T>(array: ArrayLike<T>): T | null {
    return array.length > 0 ? (array[0] as T) : null;
}
```

tsconfig:
```JSON
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "noUncheckedIndexedAccess": true
  },
```

**Expected Result**

typescript-eslint should not report any errors.

**Actual Result**

typescript-eslint complains about this type assertion: `array[0] as T`:

> Use a ! assertion to more succintly remove null and undefined from the type  @typescript-eslint/non-nullable-type-assertion-style

**Additional Info**

When compiling with `noUncheckedIndexedAccess`, the type assertion `array[0] as T` is required because the original type of `array[0]` is `T | undefined`.

However, non-nullable-type-assertion-style complains about the cast, suggesting that it should be `array[0]!` instead. This is not correct because the type parameter `T` might itself be nullish. `array[0]!` is equivalent to `array[0] as NonNullable<T>`, which is not the same as `array[0] as T`.

To see the issue more clearly, consider the following slightly more contrived example:

```typescript
function first<T extends string | null>(array: ArrayLike<T>): T | null {
    return array.length > 0 ? (array[0] as T) : null;
}
```

non-nullable-type-assertion-style complains about this code too, but here the problem is more obvious. Clearly the type assertion `array[0] as T` is not equivalent to `array[0]!` because the type parameter `T` has a constraint that explicitly allows the type to be `null`.

See #4509 for a fix

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.10.2` |
| `@typescript-eslint/parser`        | `5.10.2` |
| `TypeScript`                       | `4.5.5` |
| `ESLint`                           | `8.8.0` |
| `node`                             | `16.13.2` |

### PR DESCRIPTION
**Pull request by djcsdy**
## PR Checklist

-   [x] Addresses an existing issue: fixes #4512
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Consider the following code:

```typescript
function first<T>(array: ArrayLike<T>): T | null {
    return array.length > 0 ? (array[0] as T) : null;
}
```

When compiling with `noUncheckedIndexedAccess`, the type assertion `array[0] as T` is required because the original type of `array[0]` is `T | undefined`.

However, non-nullable-type-assertion-style complains about the cast, suggesting that it should be `array[0]!` instead. This is not correct because the type parameter `T` might itself be nullish. `array[0]!` is equivalent to `array[0] as NonNullable<T>`, which is not the same as `array[0] as T`.

To see the issue more clearly, consider the following slightly more contrived example:

```typescript
function first<T extends string | null>(array: ArrayLike<T>): T | null {
    return array.length > 0 ? (array[0] as T) : null;
}
```

non-nullable-type-assertion-style complains about this code too, but here the problem is more obvious. Clearly the type assertion `array[0] as T` is not equivalent to `array[0]!` because the type parameter `T` has a constraint that explicitly allows the type to be `null`.

This PR loosens non-nullable-type-assertion-style so that in addition to the type assertions it already allows, it will also allow type assertions providing both of the following conditions are true:

1. The asserted type contains a type parameter.
2. The type parameter has no constraint or, if the type parameter has a constraint, then the constraint itself includes nullish types or other type parameters that would meet these conditions.

### CODE REVIEW

File: packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ export default util.createRule({
     fixable: 'code',
     messages: {
       preferNonNullAssertion:
-        'Use a ! assertion to more succintly remove null and undefined from the type.',
+        'Use a ! assertion to more succinctly remove null and undefined from the type.',
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts:20]: Ha, whoops...

**Comment by JoshuaKGoldberg** [comment]
👋 @djcsdy thanks for finding this bug and sending a PR! Much appreciated on the initiative! ❤️ 

As hinted by the PR template you used, we ask that all PRs address an existing issue. Would you be able to file an issue for this please? I'll still give the PR a review but if we end up discussing in more depth then that should be in an issue.

For the room: this gives bug reports more visibility and lets us comment on them before someone starts work on them. We'd want to confirm an issue is valid _(this one certainly is)_ and what the right fix might be if it's not clear. Soon/eventually I/we/someone will write a GitHub bot to enforce it...

Side note: I re-opened #4010 and sent #4511 to make the PR template a little more clear.

File: packages/eslint-plugin/tests/fixtures/tsconfig.noUncheckedIndexedAccess.json [hunk 2]
```diff
@@ -0,0 +1,6 @@
+{
+  "extends": "./tsconfig.json",
+  "compilerOptions": {
+    "noUncheckedIndexedAccess": true
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/fixtures/tsconfig.noUncheckedIndexedAccess.json:4]: Really nice find here. I shudder to think what other subtle edge cases have popped up because of that 😄

File: packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts [hunk 3]
```diff
@@ -43,22 +43,42 @@ export default util.createRule({
       return tsutils.unionTypeParts(type);
     };
 
+    const couldBeNullish = (type: ts.Type): boolean => {
+      if (type.flags & ts.TypeFlags.TypeParameter) {
+        const constraint = type.getConstraint();
+        return constraint == null || couldBeNullish(constraint);
+      } else if (tsutils.isUnionType(type)) {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts:50]: Generally if you're checking individual flags in a type union, you'll want to use `tsutils.unionTypeParts`, in case the union type is a union of unions.

```ts
type AndAOne = 'a' | 'b';
type AndATwo = 'c' | 'd';
type Joined = AndAOne | AndATwo | 'e';
```

However, `tsutils.isTypeFlagSet` _should_ do the trick for you, I think.

File: packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts [hunk 4]
```diff
@@ -61,6 +61,16 @@ const x = 1 as 1;
 declare function foo<T = any>(): T;
 const bar = foo() as number;
     `,
+    `
+function first<T>(array: ArrayLike<T>): T | null {
+  return array.length > 0 ? (array[0] as T) : null;
+}
+    `,
+    `
+function first<T extends string | null>(array: ArrayLike<T>): T | null {
```
Comment (JoshuaKGoldberg) [inline packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts:70]: Just for completeness, could you also add tests for `string | undefined` and `string | null | undefined`? Nullability / flag checking can be tricky & gets busted over time a lot.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Generally looks good to me! And thank you for the detailed description; it greatly helped me -as someone who doesn't use `noUncheckedIndexedAccess` much- read what's going on. 😄

Just requesting changes on more testing coverage and deep union type checking. Filing an issue would be nice but I don't want to block this good PR on it -- if you don't have time I can.

File: packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (djcsdy) [reply packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts:50]: I think TypeScript flattens union types internally now, `tsutils.unionTypeParts` is just `return type_1.isUnionType(type) ? type.types : [type];`.

However I'm happy to change it to `tsutils.unionTypeParts` if you think that would be better style.

[the remark this answers is not in the document]
Comment (djcsdy) [reply packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts:50]: Also note that I can't use `isTypeFlagSet` for union types here, because we also need to check if components of the union are themselves type parameters. Hence the recursive call to `couldBeNullish`.

[the remark this answers is not in the document]
Comment (djcsdy) [reply packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts:50]: (I could use `isTypeFlagSet` in the `else` branch of the `if` statement though... again happy to do this if you think it's better style.)

File: packages/eslint-plugin/tests/fixtures/tsconfig.noUncheckedIndexedAccess.json (hunk 2 above)
Comment (djcsdy) [reply packages/eslint-plugin/tests/fixtures/tsconfig.noUncheckedIndexedAccess.json:4]: fwiw this issue can arise even without `noUncheckedIndexAccess`, but off the top of my head I can't think of an example that isn't totally contrived :-).

Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/tests/fixtures/tsconfig.noUncheckedIndexedAccess.json:4]: Oh? I was playing around with this for a good bit to try to find one but couldn't find anything. Is there a code snippet you have in mind?

File: packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (JoshuaKGoldberg) [reply packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts:50]: Aha, I think you understand this are a bit better than me then 😄. I had a false memory of `unionTypeParts` doing more than that. Super! Since you added the test case that showed the code still works as expected with a level of nesting, I'm totally satisfied. 🎉

**Review by JoshuaKGoldberg — APPROVED** [review]
Wonderful, thanks @djcsdy! This is great. 🔥 

I'll go ahead and merge this now because this is a good fix (and the typo hurts me, heh). But if you do have another example -even contrived- please do post back and we can work on that too!

File: packages/eslint-plugin/tests/fixtures/tsconfig.noUncheckedIndexedAccess.json (hunk 2 above)
Comment (djcsdy) [reply packages/eslint-plugin/tests/fixtures/tsconfig.noUncheckedIndexedAccess.json:4]: I couldn't find one either to be honest, but I didn't try all that hard. Maybe it really is dependent on the flag. But even if it isn't I think this fix should suffice. I'll do some experimentation.
