### PR TITLE
fix(eslint-plugin): [strict-boolean-expressions] account for truthy literals

### LINKED ISSUE #3115: [strict-boolean-expressions] False positive with union types having only one falsey value
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```javascript
module.exports = {
    "root": true,
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "tsconfigRootDir": __dirname,
        "project": ["./tsconfig.json"]
    },
    "plugins": ["@typescript-eslint"],
    "rules": {
        "@typescript-eslint/strict-boolean-expressions": ["error"]
    }
}
```

```TS
function f(arg: "Option1" | "Option2" | null) {
    if (arg)
        console.log(`Input: ${arg}`);
    else
        console.log("Null was input");
}
```

tsconfig: the default as output by `tsc --init`

**Expected Result**

I expected there to be no error, as there is exactly one possible falsey value, no ambiguity.

**Actual Result**
```
  2:9  error  Unexpected nullable string value in conditional. Please handle the nullish/empty cases explicitly  @typescript-eslint/strict-boolean-expressions
```
**Additional Info**
This is similar to the likely non-bug #2894, but in that example there are multiple falsey values.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.15.2` |
| `@typescript-eslint/parser`        | `4.15.2` |
| `TypeScript`                       | `4.1.5` |
| `ESLint`                           | `7.20.0` |
| `node`                             | `10.24.0` |

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #3115.

I hadn't seen this version of the code with phrases like `is('nullish', 'string')`. Very clever & readable! The code as-is does a _lot_ of loop iterations, but I guess that's fine because type unions are typically very small?

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Well [this](https://github.com/typescript-eslint/typescript-eslint/pull/3236/checks?check_run_id=2215426892) is an error I haven't seen in a while 😄 :

```
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/jest-haste-map/-/jest-haste-map-26.6.2.tgz: Request failed \"500 Internal Server Error\"".
```

File: packages/eslint-plugin/src/rules/strict-boolean-expressions.ts [hunk 1]
```diff
@@ -308,8 +308,13 @@ export default util.createRule<Options, MessageId>({
         return;
       }
 
+      // Known edge case: truthy primitives and nullish values are always valid boolean expressions
+      if (is('nullish', 'truthy string') || is('nullish', 'truthy number')) {
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/strict-boolean-expressions.ts:312]: I think that these two checks should probably be guarded using the `options.allowString` and `options.allowNumber` checks.

Otherwise someone could set `allowNumber: false` and find that:
```
declare const x: 1 | null;
declare const y: 1;
if (x) {} // passes linting
if (y) {} // fails linting
```
which is a weird inconsistency

**Review by bradzacher — CHANGES_REQUESTED** [review]
nice! almost there - one comment

**Review by bradzacher — APPROVED** [review]
sweet - thanks for this!
