### PR TITLE
fix(eslint-plugin): [no-unused-vars] fix false negative for type predicate parameter

### LINKED ISSUE #12003: Bug: [no-unused-vars] Type predicate parameter not reported as unused when only used in type position
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.9.2&fileType=.tsx&code=FAUwHgDg9gTgLgAgMZQHYGdEFsCeAVHCEAcQFcBDGAEwQF4EAKK8ucgLgVNQGtUoB3VAEoOzVggCW6BJhgTUAczoA%2BBAG9gCBDBBxSMVAjgxSIYAF8A3MFCRYiFBmz5CJCtQBMdRmPIeOXLwCwirqmtq6%2BobGphaWQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tidmUQAmtAG4BDaKgwBtSImjQO0SABpMUcQHNJ6%2BPEhgAvgF1w2AyANA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
// This should report `data` as unused (only used in type position) but doesn't                                  
export const myTypeGuard = (data: unknown): data is string => {                                                  
  return true                                                                                                    
};
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unused-vars": ["error"],
  },
};
```

### tsconfig

```jsonc

```

### Expected Result

I would expect `data` to be unused`

### Actual Result

no error is reported by the rule

### Additional Info

Also relevant:
```ts
// This should report `data` as unused (only used in type position) but doesn't                                  
export const myTypeGuard = (data: unknown): data is string => {                                                  
  return true                                                                                                    
};                                                                                                               
```
```ts
// This correctly reports `data2` as unused with message about type position                                     
export const myTypeGuard2 = (data2: unknown): typeof data2 => {                                                  
  return true                                                                                                    
};  
```

Discord discussion: https://discord.com/channels/1026804805894672454/1451903355440992307

### PR DESCRIPTION
**Pull request by Ju-MINJAE**
## PR Checklist

- [x] Addresses an existing open issue: fixes #12003 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Fixed a false negative in `no-unused-vars` where parameters used only in a return type predicate were incorrectly considered "used".
Updated `collectUnusedVariables` to ignore references that occur exclusively within a `TSTypePredicate` node.

😵‍💫

### CODE REVIEW

File: packages/eslint-plugin/src/rules/no-unused-vars.ts [hunk 1]
```diff
@@ -954,7 +970,14 @@ export default createRule<Options, MessageIds>({
...
       ];
       const unusedVariablesReturn: ScopeVariable[] = [];
-      for (const { used, variable } of variables) {
+      for (const variableObj of variables) {
+        const { variable } = variableObj;
+        let { used } = variableObj;
+
+        if (used && isOnlyUsedInTypePredicate(variable)) {
+          used = false;
+        }
```
Comment (bradzacher) [inline packages/eslint-plugin/src/rules/no-unused-vars.ts]: This isn't where we'd want to place our logic.
It should be located in the same places we have handling for the `typeof` case

(1) within the `collectVariables` util:
https://github.com/typescript-eslint/typescript-eslint/blob/d1ddeb0dd8c41c855274f9fced3b36aa4a594614/packages/eslint-plugin/src/util/collectUnusedVariables.ts#L795

(2) around here where we decide the `messageId`:
https://github.com/typescript-eslint/typescript-eslint/blob/3b0450abbd9d1ba18149614a0cb3b656fdf93370/packages/eslint-plugin/src/rules/no-unused-vars.ts#L1205-L1224

**Review by bradzacher — CHANGES_REQUESTED** [review]

File: packages/eslint-plugin/src/rules/no-unused-vars.ts (hunk 1 above)
Comment (Ju-MINJAE) [reply packages/eslint-plugin/src/rules/no-unused-vars.ts]: @bradzacher Understood. It definitely looks cleaner to handle it in the same places as the ` typeof` case. I will apply the changes requested

**Comment by JoshuaKGoldberg** [comment]
👋 @Ju-MINJAE did you want to re-request review on this?

**Comment by Ju-MINJAE** [comment]
@JoshuaKGoldberg yes plz

**Review by JoshuaKGoldberg — APPROVED** [review]
👍 Great, I appreciate how this mirrors the existing code. Thanks!

I'll defer to @bradzacher for review if they have time, as they already reviewed.

**Review by bradzacher — APPROVED** [review]

**Comment by bradzacher** [comment]
thanks for this! Sorry it took so long to get back and review.

**Comment by Ju-MINJAE** [comment]
@bradzacher No problem at all, thank you!
